date_start: '2024-12-01'
date_stop: '2024-12-31'
location_id:
- 1
- 2
location_name:
- Location A
- Location B
S_j_initial:
- 999
- 999
I_j_initial:
- 1
- 1
R_j_initial:
- 0
- 0
b_j:
- 0.01
- 0.02
d_j:
- 0.01
- 0.02
nu_jt:
  '1':
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  '2':
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
phi: 0.8
omega: 0.1
epsilon: 0.05
gamma: 0.2
mu: 0.01
rho: 0.9
sigma: 0.5
beta_j0_hum:
- 0.05
- 0.03
tau_i:
- 0.1
- 0.2
pi_ij:
  '1':
  - 0.8
  - 0.2
  '2':
  - 0.2
  - 0.8
alpha: 0.95
beta_j0_env:
- 0.02
- 0.04
theta_j:
- 0.6
- 0.7
psi_jt:
  '1':
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  '2':
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
zeta: 0.5
kappa: 100000.0
delta_min: 0.001
delta_max: 0.01
