#!/usr/bin/env bash
# Create ~/bin/r-mosaic-{R,Rscript} on a MOSAIC compute VM (dugong or hedgehog).
#
# This is the TRACKED, canonical generator. It supersedes the gitignored
# claude/dugong_setup/make_wrappers_dugong.sh -- keep changes here.
#
# The wrappers do two things:
#
# 1. LD_PRELOAD the venv's libstdc++ / libexpat / libssl+libcrypto ahead of the
#    system copies. Each is [ -f ]-guarded, so the SAME wrapper is correct on
#    both VMs:
#      - libstdc++   hedgehog (Ubuntu 20.04) lacks GLIBCXX_3.4.29 that the venv's
#                    compiled wheels need; harmless on dugong (24.04).
#      - libexpat    dugong: R links system libexpat 1.9.1 at startup, then
#                    reticulate imports the conda env's pyexpat (built against
#                    1.12.1) and the loader reuses the already-loaded system
#                    copy -> PSOCK workers die with
#                    `undefined symbol: XML_SetAllocTrackerActivationThreshold`.
#      - libssl/     dugong + Coiled: importing `coiled` triggers _ssl, which
#        libcrypto   needs OpenSSL 3.3.0; the system copy is 3.0.x ->
#                    `libcrypto.so.3: version 'OPENSSL_3.3.0' not found`.
#
# 2. Raise R's connection ceiling with --max-connections.
#
#    R allocates a FIXED connection table at startup: 128 slots by default, of
#    which stdin/stdout/stderr take three. Every PSOCK worker holds one slot for
#    its lifetime, so a default R build cannot put more than ~125 workers in a
#    cluster no matter how many cores the box has. On dugong (176 cores) that
#    silently cost ~28% of the machine: make_mosaic_cluster() clamped 170 -> 123,
#    and calc_model_ensemble()'s cluster threw outright.
#
#    --max-connections=N (R >= 4.4.0, max 4096) is a STARTUP option -- there is
#    no env var and no in-session way to raise it, which is exactly why it
#    belongs in the wrapper rather than in each launch command: a forgotten flag
#    does not error, it silently runs narrower.
#
#    It is placed BEFORE "$@" deliberately. R takes the LAST occurrence of the
#    flag, so a caller can still override with
#    `r-mosaic-Rscript --max-connections=1024 script.R`; and a flag placed after
#    the script filename is ignored entirely.
#
# Usage:
#   bash vm/make_wrappers.sh                    # defaults (512 connections)
#   MOSAIC_MAX_CONNECTIONS=1024 bash vm/make_wrappers.sh
#   MOSAIC_VENV=~/.virtualenvs/other bash vm/make_wrappers.sh

set -euo pipefail

MAX_CONN="${MOSAIC_MAX_CONNECTIONS:-512}"
VENV="${MOSAIC_VENV:-$HOME/.virtualenvs/r-mosaic}"

# R only accepts 128..4096; anything else is warned about and IGNORED at
# startup, which would silently put us back at 125 usable. Fail loudly instead.
if [ "$MAX_CONN" -lt 128 ] || [ "$MAX_CONN" -gt 4096 ]; then
  echo "ERROR: MOSAIC_MAX_CONNECTIONS=$MAX_CONN is outside R's accepted range [128, 4096]." >&2
  echo "       R would warn and ignore it, leaving the default 125-worker ceiling." >&2
  exit 1
fi

mkdir -p "$HOME/bin"

write_wrapper () {
  local path="$1" target="$2"
  cat > "$path" <<'EOF'
#!/usr/bin/env bash
# Generated by vm/make_wrappers.sh -- do not hand-edit (see that script for why
# each preload exists). A hand-edited copy once ended up with an INDENTED
# shebang, which made the kernel fall back to dash: `Syntax error: "(" unexpected`.
EOF
  cat >> "$path" <<EOF
VENV="\${MOSAIC_VENV:-$VENV}"
EOF
  cat >> "$path" <<'EOF'
# Modern libstdc++ (hedgehog GLIBCXX_3.4.29; harmless on dugong).
if [ -f "$VENV/lib/libstdc++.so.6" ]; then
  export LD_PRELOAD="$VENV/lib/libstdc++.so.6${LD_PRELOAD:+:$LD_PRELOAD}"
  export LD_LIBRARY_PATH="$VENV/lib${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"
fi
# venv libexpat, so R's startup system libexpat does not shadow pyexpat's.
if [ -f "$VENV/lib/libexpat.so.1" ]; then
  export LD_PRELOAD="$VENV/lib/libexpat.so.1${LD_PRELOAD:+:$LD_PRELOAD}"
fi
# venv libssl/libcrypto, needed only by the Coiled path's _ssl import.
for lib in libssl.so.3 libcrypto.so.3; do
  if [ -f "$VENV/lib/$lib" ]; then
    export LD_PRELOAD="$VENV/lib/$lib${LD_PRELOAD:+:$LD_PRELOAD}"
  fi
done
export R_LIBS_USER="$HOME/R/library"
[ -x "$VENV/bin/python" ] && export RETICULATE_PYTHON="$VENV/bin/python"
EOF
  # --max-connections BEFORE "$@" so a caller's own later flag still wins.
  echo "exec $target --max-connections=$MAX_CONN \"\$@\"" >> "$path"
  chmod +x "$path"
  head -1 "$path" | grep -q '^#!/usr/bin/env bash$' || {
    echo "ERROR: $path shebang malformed (must be #!/usr/bin/env bash at column 0)" >&2
    exit 1
  }
}

write_wrapper "$HOME/bin/r-mosaic-R"       "R"
write_wrapper "$HOME/bin/r-mosaic-Rscript" "Rscript"

if ! grep -q 'export PATH="$HOME/bin:$PATH"' "$HOME/.bashrc" 2>/dev/null; then
  echo 'export PATH="$HOME/bin:$PATH"' >> "$HOME/.bashrc"
fi

echo "Created wrappers (max-connections=$MAX_CONN, venv=$VENV):"
ls -l "$HOME/bin/r-mosaic-R" "$HOME/bin/r-mosaic-Rscript"

# Report which preloads will actually engage, so a wrong venv path is visible
# now rather than as a PSOCK worker crash later.
echo "--- preloads found in \$VENV/lib ---"
for lib in libstdc++.so.6 libexpat.so.1 libssl.so.3 libcrypto.so.3; do
  if [ -f "$VENV/lib/$lib" ]; then echo "  present: $lib"; else echo "  MISSING: $lib"; fi
done

# Verify the flag actually took effect rather than being warned-and-ignored.
echo "--- verification ---"
"$HOME/bin/r-mosaic-Rscript" -e 'cat("R", as.character(getRversion()), "| availableConnections:", parallelly::availableConnections(), "| free:", parallelly::freeConnections(), "\n")' \
  || echo "WARNING: verification call failed (is parallelly installed?)"
