#' Plot Shedding Rate as a Function of Environmental Suitability
#'
#' This function generates a plot that visualizes the suitability-dependent decay rate of environmental shedding based on climate-driven environmental suitability (\eqn{\psi_{jt}}). The function generates three models for the decay rate \eqn{\delta_{jt}}:
#' \itemize{
#'   \item \eqn{\delta_{jt} = 1 - \psi_{jt}}: A simple linear transformation of \eqn{\psi_{jt}}.
#'   \item \eqn{\delta_{jt} = 1 - \frac{1}{1 + (1 - \psi_{jt})}}: A nonlinear transformation of \eqn{\psi_{jt}}.
#'   \item \eqn{\delta_{jt} = \delta_{\min} + \psi_{jt} \cdot (\delta_{\max} - \delta_{\min})}: A linear transformation based on minimum and maximum decay rates.
#' }
#' The plot is saved as a PNG file in the directory specified by `PATHS$DOCS_FIGURES`.
#'
#' @param PATHS A list containing the paths where the plot will be saved. Typically generated by the `get_paths()` function and should include:
#' \itemize{
#'   \item \strong{DOCS_FIGURES}: Path to the directory where the plot will be saved.
#' }
#'
#' @importFrom graphics plot lines points legend text
#' @importFrom grDevices png dev.off
#' @examples
#' \dontrun{
#' # Assuming PATHS is generated from get_paths()
#' PATHS <- get_paths()
#' plot_shedding_rate(PATHS)
#' }
#' @export

plot_shedding_rate <- function(PATHS) {

     # Set seed for reproducibility
     set.seed(123)

     # Generate environmental suitability values and transformations
     psi <- runif(100, min = 0, max = 1)
     psi_transform <- 1 / (1 + (1 - psi))

     days_min <- 3
     days_max <- 90

     delta_min <- 1/days_min
     delta_max <- 1/days_max
     decay_rate <- delta_min + psi * (delta_max - delta_min)

     # Define the output file path
     output_file <- file.path(PATHS$DOCS_FIGURES, "shedding_rate.png")

     # Create the plot and save as PNG
     png(filename = output_file, width = 1800, height = 1800, units = "px", res = 300)

     # Base plot: linear transformation
     plot(psi, 1 - psi,
          xlab = expression("Climate driven environmental suitability (" * psi[jt] * ")"),
          ylab = expression("Suitability dependent decay rate (" * delta[jt] * ")"),
          pch = 19, col = "black",
          xlim = c(0, 1), ylim = c(0, 1.1),
          bty = "n")

     # Lines for different models
     lines(sort(psi), 1 - sort(psi), col = "#377EB8", lwd = 3, type = "l")  # Linear transformation
     points(psi, 1 - psi_transform, pch = 19)
     lines(sort(psi), 1 - sort(psi_transform), col = '#E41A1C', lwd = 3)  # Nonlinear transformation
     points(psi, decay_rate, pch = 19)
     lines(psi, decay_rate, col = '#4DAF4A', lwd = 3)  # Min/max transformation

     # Add legend
     legend("topright", legend = c(expression(delta[jt] == 1 - psi[jt]),
                                   expression(delta[jt] == 1 - frac(1, 1 + (1 - psi[jt]))),
                                   expression(delta[jt] == delta[min] + psi * (delta[max] - delta[min]))),
            col = c("#377EB8", "#E41A1C", "#4DAF4A"), lty = 1, pch = 19, lwd = 2, cex = 1.2, bty = "n")

     # Annotate text on the plot
     text(x = 0, y = 1.01, "0 days", pos = 4, col = "#377EB8", cex = 1)
     text(x = 0, y = 0.54, "2 days", pos = 4, col = "#E41A1C", cex = 1)
     text(x = 0, y = 0.36, labels = paste0(days_min, " days"), pos = 4, col = "#4DAF4A", cex = 1)
     text(x = 0.75, y = 0, labels = paste0(days_max, " days"), pos = 4, col = "#4DAF4A", cex = 1)

     # Close the PNG device
     dev.off()

     message(paste("Shedding rate plot saved to:", output_file))
}
