#' Compile Environmental Suitability Data for Cholera Transmission
#'
#' Compiles multiple processed data sources (climate, ENSO, cholera surveillance,
#' demographics, WASH) into a single feature-engineered training dataset for
#' environmental suitability modeling. Computes derived covariates including
#' rolling windows, anomalies, and climate / WASH interaction terms.
#'
#' As of v0.30.26 the vaccination, epidemic-memory (cases-derived), and
#' spatial-import (mobility-network) blocks are no longer computed. They were
#' already excluded from \code{est_suitability()}'s LSTM covariate list -- the
#' vaccination signal is a downstream intervention (deployed in response to
#' cholera, not in anticipation of environmental suitability), and the
#' case-derived epidemic-memory features are target leakage for a model whose
#' response is itself a case-derived binary.
#'
#' @param PATHS A list containing paths where the data is stored. Typically generated by the `get_paths()` function and should include:
#' \itemize{
#'   \item \strong{DATA_CLIMATE}: Path to the directory where processed climate data is stored.
#'   \item \strong{DATA_ENSO}: Path to the directory where ENSO data is stored.
#'   \item \strong{DATA_CHOLERA_WEEKLY}: Path to the directory containing processed combined weekly cholera cases data (WHO+JHU+SUPP sources).
#' }
#' @param cutoff Numeric threshold for case counts. Used when use_epidemic_peaks = FALSE.
#'   Weeks with cases >= cutoff are considered outbreak periods for the environmental
#'   suitability calculation. Default behavior uses this value to create the binary indicator.
#' @param use_epidemic_peaks Logical. If TRUE, uses epidemic peak periods from
#'   est_epidemic_peaks() to define environmental suitability using exact peak_start
#'   to peak_stop dates. Provides deterministic outbreak detection without any
#'   modifications or lead-up periods. Default FALSE for backwards compatibility.
#' @param date_start Start of the data window. Accepts a year (e.g. \code{2000}) or a
#'   date string (e.g. \code{"2000-01-01"}); only the year is used for filtering. Default
#'   \code{"2000-01-01"}. This caps how far back the panel extends (important when the
#'   AI source supplies pre-2000 reconstructions). Pass \code{NULL} to auto-detect the
#'   start from case data (one year prior to the earliest case observation).
#' @param date_stop End of the data window (year or date string). If NULL (default),
#'   auto-detected from the latest raw ENSO data availability.
#' @param forecast_mode Logical. If TRUE, only includes variables that can support forecasting
#'   at the specified horizon. (As of v0.30.26 the case-dependent epidemic memory and
#'   spatial-import blocks are removed entirely, so this flag now affects only the
#'   final summary-message text and the climate-anomaly leading-edge behavior.)
#'   Default TRUE.
#' @param forecast_horizon Numeric. Forecasting horizon in months. Variables dependent on
#'   surveillance data beyond this horizon are excluded in forecast mode. Default 3 months.
#' @param include_lags Logical. If TRUE, includes time-lagged climate variables with
#'   epidemiologically-informed lag periods specific to each variable. Default FALSE.
#' @param include_flood_prob Logical. If TRUE (default), imputes a continuous
#'   \code{emdat_flood_prob} column for every (iso_code, year, week) row via a
#'   binomial GAM trained on observed \code{emdat_flood_active} events
#'   (see \code{\link{impute_flood_probability}}), and adds four rolling-window
#'   aggregates (\code{emdat_flood_prob_4w_max}, \code{emdat_flood_prob_12w_max},
#'   \code{emdat_flood_prob_12w_sum}, \code{emdat_flood_prob_anom}). The
#'   probability covariates are populated in both the historical training and
#'   the forecast windows, so the downstream LSTM consumes the same feature
#'   definition in both regimes.
#'
#' @return This function processes the data and merges the climate, ENSO, and cholera cases data into a single dataset. It creates a \code{cases_binary} column indicating environmental suitability based on case patterns using sophisticated temporal logic. The processed dataset is saved as a CSV file.
#'
#' @details
#' The function performs the following key steps:
#' \itemize{
#'   \item Loads and merges climate data (temperature, precipitation, etc.) from multiple countries
#'   \item Loads ENSO and IOD climate index data
#'   \item Loads combined weekly cholera case surveillance data from WHO, JHU, and supplemental sources
#'   \item Merges all datasets by country, year, and week
#'   \item Creates environmental suitability indicator (\code{cases_binary}) using either epidemic peak-based or threshold-based methods
#'   \item Saves the complete merged dataset for use in environmental suitability modeling
#' }
#'
#' \strong{Environmental Suitability Methods:}
#' \itemize{
#'   \item \strong{Epidemic Peak-based} (use_epidemic_peaks = TRUE): Uses deterministic outbreak detection from est_epidemic_peaks() using exact peak_start to peak_stop dates without any modifications
#'   \item \strong{Threshold-based} (use_epidemic_peaks = FALSE): Uses simple case count cutoffs with temporal lead-up logic
#' }
#'
#' The epidemic peak-based method provides deterministic, epidemiologically meaningful outbreak periods
#' and is recommended for consistent environmental suitability modeling.
#'
#' @importFrom arrow read_parquet
#' @importFrom utils read.csv write.csv
#' @importFrom glue glue
#' @importFrom dplyr left_join select_if select
#' @importFrom tidyr pivot_wider
#'
#' @seealso
#' \code{\link{get_cases_binary}} for the threshold-based environmental suitability method
#' \code{\link{get_cases_binary_from_peaks}} for the epidemic peak-based method
#' \code{\link{est_epidemic_peaks}} for epidemic peak detection
#'
#' @param backfill_case_gaps Logical (default \code{TRUE}). Linearly interpolate
#'   short interior gaps in the weekly case series (e.g. holiday non-reporting)
#'   before the suitability target is built, via
#'   \code{\link{backfill_weekly_case_gaps}}, so missing weeks inside an active
#'   outbreak are not stamped as false zeros by the downstream NA->0 sanitiser.
#' @param backfill_max_weeks Integer (default \code{2L}). Maximum interior gap
#'   length (in weeks) to interpolate; longer gaps are left for the zero-fill.
#' @param backfill_method Interpolation method passed to
#'   \code{\link{backfill_weekly_case_gaps}} (default \code{"linear"}).
#'
#' @export
compile_suitability_data <- function(PATHS, cutoff, use_epidemic_peaks = FALSE,
                                    date_start = "2000-01-01", date_stop = NULL,
                                    forecast_mode = TRUE, forecast_horizon = 3, include_lags = FALSE,
                                    include_flood_prob = TRUE,
                                    backfill_case_gaps = TRUE, backfill_max_weeks = 2L,
                                    backfill_method = "linear") {

     requireNamespace('arrow')
     requireNamespace('ISOweek')
     requireNamespace('dplyr')
     requireNamespace('tidyr')
     requireNamespace('zoo')
     requireNamespace('lubridate')
     requireNamespace('rlang')
     requireNamespace('slider')

     # Load climate data for all countries (weekly)
     message("Loading climate data...")

     # List all weekly climate data files
     climate_files <- list.files(PATHS$DATA_CLIMATE, pattern = "\\.parquet$", full.names = TRUE)

     # Initialize an empty list to store climate data for each ISO code
     climate_data_list <- list()

     # Loop through each climate file and load the data
     for (climate_file in climate_files) {
          climate_data <- arrow::read_parquet(climate_file)
          climate_data_list <- append(climate_data_list, list(climate_data))
     }

     # Combine all climate data into one data frame
     combined_climate_data <- do.call(rbind, climate_data_list)
     rm(climate_data_list)

     # Load ENSO data (compiled ENSO and IOD data)
     message("Loading ENSO and IOD data...")
     enso_file <- file.path(PATHS$DATA_ENSO, "enso_weekly.csv")
     enso_data <- utils::read.csv(enso_file, stringsAsFactors = FALSE)

     # Load weekly cholera cases data (combined WHO+JHU+SUPP sources)
     message("Loading combined weekly cholera cases data (WHO+JHU+SUPP)...")
     cases_file <- file.path(PATHS$DATA_CHOLERA_WEEKLY, "cholera_surveillance_weekly_combined.csv")
     cases_data <- utils::read.csv(cases_file, stringsAsFactors = FALSE)

     # Determine date range based on case data and ENSO data (or use provided dates)
     message("Determining optimal date range...")
     
     if (is.null(date_start)) {
          # Find earliest case observation (excluding zeros and NAs)
          cases_with_dates <- cases_data[!is.na(cases_data$cases) & cases_data$cases > 0, ]
          if (nrow(cases_with_dates) > 0) {
               earliest_case_year <- min(cases_with_dates$year, na.rm = TRUE)
               start_year <- earliest_case_year - 1  # Start one year prior
               message(sprintf("  - Earliest case observation: %d", earliest_case_year))
          } else {
               earliest_case_year <- NA
               start_year <- 2000  # Fallback if no case data found
               message("  - No case observations found, using fallback start year")
          }
     } else {
          # Accept either a year (e.g. 2000) or a date string (e.g. "2000-01-01").
          start_year <- suppressWarnings(as.integer(substr(as.character(date_start), 1, 4)))
          if (is.na(start_year)) {
               stop("date_start must be a year (e.g. 2000) or a date string like '2000-01-01'.")
          }
          message(sprintf("  - Using start year: %d (from date_start = %s)",
                          start_year, as.character(date_start)))
     }

     if (is.null(date_stop)) {
          # Find the actual end date of raw ENSO data (not interpolated/forecasted)
          end_year <- max(enso_data$year, na.rm = TRUE)
          message(sprintf("  - Latest ENSO data: %d (using max date from raw ENSO dataset)", end_year))
     } else {
          end_year <- suppressWarnings(as.integer(substr(as.character(date_stop), 1, 4)))
          if (is.na(end_year)) {
               stop("date_stop must be a year (e.g. 2026) or a date string like '2026-12-31'.")
          }
          message(sprintf("  - Using end year: %d (from date_stop = %s)",
                          end_year, as.character(date_stop)))
     }
     
     message(sprintf("  - Final date range: %d-%d", start_year, end_year))

     # Filter all datasets to this date range and MOSAIC countries only
     message("Filtering datasets to optimal date range and MOSAIC countries...")
     
     # Filter by date range
     combined_climate_data <- combined_climate_data[combined_climate_data$year >= start_year & 
                                                   combined_climate_data$year <= end_year, ]
     enso_data <- enso_data[enso_data$year >= start_year & enso_data$year <= end_year, ]
     cases_data <- cases_data[cases_data$year >= start_year & cases_data$year <= end_year, ]
     
     # Filter by MOSAIC countries only
     combined_climate_data <- combined_climate_data[combined_climate_data$iso_code %in% iso_codes_mosaic, ]
     cases_data <- cases_data[cases_data$iso_code %in% iso_codes_mosaic, ]
     
     message(sprintf("  - Filtered to %d MOSAIC countries: %s", 
                    length(iso_codes_mosaic), 
                    paste(head(sort(iso_codes_mosaic), 8), collapse = ", ")))
     if (length(iso_codes_mosaic) > 8) {
          message(sprintf("    ... and %d more countries", length(iso_codes_mosaic) - 8))
     }

     message("Merging datasets...")
     # Convert the climate data to wide format, with variable names as new columns.
     # values_fn = mean defends against the (rare but real) case where the
     # upstream parquet contains duplicate (iso_code, year, week, variable_name)
     # rows -- without it pivot_wider silently produces list-columns and every
     # downstream merge fails with a cryptic error.
     combined_climate_data_wide <- tidyr::pivot_wider(
          combined_climate_data,
          names_from = variable_name,
          values_from = value,
          values_fn = mean
     )

     combined_climate_data_wide <- combined_climate_data_wide %>%
          dplyr::select(-date_start, -date_stop)

     # Drop data_source before pivoting — different variables transition between
     # historical/observed/forecast at different weeks, which creates duplicate rows
     # in pivot_wider and silently loses IOD data after the ENSO34 filter at line 210
     enso_data$data_source <- NULL

     # Convert ENSO data to wide format (IOD, ENSO3, ENSO34, ENSO4 as new
     # columns). values_fn = mean: same defensive pattern as the climate
     # pivot above -- protects against any residual duplicate (year, week,
     # variable) rows that survive the data_source drop.
     enso_data_wide <- tidyr::pivot_wider(
          enso_data,
          names_from = variable,
          values_from = value,
          values_fn = mean
     )

     enso_data_wide <- enso_data_wide %>%
          dplyr::select(-date_start, -date_stop)

     # Merge datasets: Merge cases data with wide climate data and ENSO data
     combined_climate_data_wide <- merge(combined_climate_data_wide, enso_data_wide, by = c("year", "week"), all.x = TRUE)
     d <- merge(cases_data, combined_climate_data_wide, by = c("iso_code", "year", "week"), all.y = TRUE)

     message(sprintf("After merge: %d observations, columns: %s",
                     nrow(d), paste(head(names(d), 10), collapse = ", ")))


     # Restrict the panel to ISO weeks 1-52.
     #
     # WHY THIS IS NOT JUST `week %in% 1:52`:
     # A handful of ISO years (2004, 2009, 2015, 2020, 2026, ...) genuinely
     # have 53 ISO weeks, so dropping W53 removes ~80 legitimate country-week
     # rows from training years 2015 and 2020 (out of ~37k). The cost is a
     # small calendar-span bias in year-end rolling windows for those two
     # years (a 12-row precip_sum_12w near January 2016 / 2021 covers
     # 13 calendar weeks because the W53 row is missing).
     #
     # WHY WE DROP THEM ANYWAY:
     # The upstream climate processor (process_open_meteo_data) labels W53
     # rows by *calendar* year rather than ISO year, so it emits spurious
     # (year=N+1, week=53) rows for the 1-2 January days that fall in
     # ISO W53 of year N. Keeping W53 would pull those partial-week
     # artifacts into the panel. Dropping all W53 is the simplest robust
     # choice until the upstream processor is fixed; see notes/TODOs in
     # process_open_meteo_data for the structural fix.
     # The 2026 forecast horizon ends well before W53 of 2026, so this
     # filter does not affect production forecasts today.
     d <- d %>%
          dplyr::filter(week >= 1 & week <= 52)

     # Create ISO week strings
     d$iso_week <- paste0(d$year, "-W", sprintf("%02d", d$week))

     # Convert ISO week to center date (Thursday - middle of week)
     d$date <- ISOweek::ISOweek2date(paste0(d$iso_week, "-4"))

     # Remove the temporary iso_week column
     d$iso_week <- NULL

     # Ensure month column has integer month values
     d$month <- as.integer(format(d$date, "%m"))

     # Remove columns that are entirely NA or NaN
     d <- dplyr::select_if(d, ~!all(is.na(.) | is.nan(.)))
     
     # Filter to only include time periods with ENSO data (since ENSO is the limiting factor for forecasting)
     d <- d %>% dplyr::filter(!is.na(ENSO34))  # Use ENSO34 as the reference since it's always present
     
     message(sprintf("  - Filtered to ENSO data availability: %d observations retained", nrow(d)))

     # ---- Backfill short reporting gaps (e.g. holiday non-reporting) ---------
     # Genuinely-missing interior weeks bounded by reported weeks (most often the
     # Christmas/New-Year reporting lapse) are linearly interpolated here -- BEFORE
     # cases_binary / transmission_intensity are built and before the
     # est_suitability NA->0 sanitiser -- so a missing holiday week inside an
     # active outbreak is not stamped as a false zero-incidence week. Gaps longer
     # than `backfill_max_weeks` (major missing months/years) and the series ends
     # are left NA for the downstream zero-fill. The canonical surveillance files
     # are untouched; this only shapes the suitability panel, and a
     # `cases_interpolated` flag marks the filled weeks.
     if (isTRUE(backfill_case_gaps)) {
          d <- backfill_weekly_case_gaps(d, max_interp_weeks = backfill_max_weeks,
                                         method = backfill_method, verbose = TRUE)
     }

     if ("rain_sum" %in% colnames(d)) d <- d[,-which(colnames(d) == 'rain_sum')]

     # ============================================================================
     # ENHANCED COVARIATES INTEGRATION
     # ============================================================================

     message("Adding enhanced covariates for count-based modeling...")

     # 1. Demographics (annual data, interpolated to weekly)
     message("  - Adding demographic variables...")
     # Daily-interpolated UN file (smooth across year boundaries) replaces the
     # annual file, which produced a ~1-2% stairstep discontinuity in
     # total_population at each Dec 31 -> Jan 1. Joined on (iso_code, date).
     demog_path <- file.path(PATHS$DATA_PROCESSED, "demographics", "UN_world_population_prospects_daily.csv")
     if (file.exists(demog_path)) {
          demog_data <- utils::read.csv(demog_path, stringsAsFactors = FALSE)
          demog_data$date <- as.Date(demog_data$date)
          demog_data <- demog_data[, c("iso_code", "date", "total_population",
                                       "births_per_1000", "deaths_per_1000")]
          # Filter to MOSAIC countries only
          demog_data <- demog_data[demog_data$iso_code %in% iso_codes_mosaic, ]
          d$date <- as.Date(d$date)
          d <- merge(d, demog_data, by = c("iso_code", "date"), all.x = TRUE)
     }

     # ========================================================================
     # Per-capita rate + candidate response variables
     # ------------------------------------------------------------------------
     # Placed immediately after the demographics merge so total_population is in
     # scope (and benefits from the smooth daily values). No row filtering occurs
     # after this point, so the full-window p99 anchors below are computed over
     # the same row set that is written to the final CSV.
     #
     # Leakage note: the global/per-country p99 anchors are full-window
     # statistics. For retrospective rolling-CV validation this is leakage; for
     # real-time forecasting there is no future to leak from. User has explicitly
     # accepted this trade-off (see plan_data_pipeline_part_a.md).
     # ========================================================================
     message("  - Adding per-capita rate and candidate response variables...")

     # Negative case counts are an upstream data error; clamp to 0 (with a warning)
     # so the log1p targets and `rate` cannot produce NaN/-Inf. Mirrors the guard in
     # est_suitability().
     n_neg <- sum(d$cases < 0, na.rm = TRUE)
     if (n_neg > 0) {
          warning(sprintf(
               "compile_suitability_data: %d row(s) had negative case counts; clamping to 0. Investigate the upstream surveillance merge.",
               n_neg))
          d$cases[!is.na(d$cases) & d$cases < 0] <- 0
     }

     # Per-capita weekly case rate, cases per 100k.
     # NA when cases is NA (no observation that week) OR population is bad.
     d$rate <- d$cases / d$total_population * 1e5
     bad_pop <- is.na(d$total_population) | d$total_population <= 0 | !is.finite(d$total_population)
     d$rate[bad_pop] <- NA_real_
     d$rate[is.na(d$cases) & !bad_pop] <- NA_real_
     # d$rate is now NA iff cases is NA OR population is bad; otherwise the rate.

     # ANCHOR INVARIANCE: every normalization anchor below is computed over TRUSTED
     # direct-source rows only (WHO/JHU/SUPP), excluding AI gap-fill rows. This makes
     # the anchors — and therefore the target values for trusted rows — INVARIANT to
     # whether AI rows are present (include_ai). AI rows still receive target values,
     # scored on the trusted-source scale. `source` is NA only for empty grid cells.
     is_ai <- if ("source" %in% names(d)) (!is.na(d$source) & d$source == "AI") else rep(FALSE, nrow(d))

     # ---- transmission_intensity: reproduction of est_suitability() ----
     # est_suitability() sets NA cases to 0 and negatives to 0, then normalizes by
     # log1p of the 99th percentile of cases over MOSAIC countries. Reproduced here
     # over TRUSTED MOSAIC rows so the column is invariant to include_ai AND remains
     # bit-identical to production when include_ai = FALSE (all rows trusted).
     # est_suitability()/the LSTM sandbox recompute their own target from `cases`, so
     # this column is a diagnostic/back-compat alias and does NOT propagate NA.
     ti_cases <- d$cases
     ti_cases[is.na(ti_cases)] <- 0
     ti_cases[ti_cases < 0]    <- 0
     ti_anchor_mask <- (d$iso_code %in% iso_codes_mosaic) & !is_ai
     ti_p99 <- stats::quantile(ti_cases[ti_anchor_mask], 0.99, na.rm = TRUE)
     if (!is.finite(ti_p99) || ti_p99 <= 0) ti_p99 <- 1
     d$transmission_intensity <- pmin(1.0, log1p(ti_cases) / log1p(ti_p99))

     # ---- Candidate response variables (A/B/C/D/F) ----
     # These propagate NA where cases (or rate) is NA, so downstream consumers can
     # drop unobserved weeks during training. Anchors use trusted rows only.

     # Global anchors (trusted rows, full-window).
     global_p99_count <- stats::quantile(d$cases[!is_ai], 0.99, na.rm = TRUE)
     if (!is.finite(global_p99_count) || global_p99_count <= 0) global_p99_count <- 1
     global_p99_rate <- stats::quantile(d$rate[!is_ai], 0.99, na.rm = TRUE)
     if (!is.finite(global_p99_rate) || global_p99_rate <= 0) global_p99_rate <- 1e-3

     # A: count, global p99
     d$target_A_count_global <- pmin(1, log1p(d$cases) / log1p(global_p99_count))
     # C: per-capita rate, global p99
     d$target_C_rate_global <- pmin(1, log1p(d$rate) / log1p(global_p99_rate))

     # B, D, F: per-country variants
     d$target_B_count_per_country        <- NA_real_
     d$target_D_rate_per_country_floored <- NA_real_
     d$target_F_rank_per_country         <- NA_real_

     for (iso in unique(d$iso_code)) {
          mask         <- d$iso_code == iso
          trusted_mask <- mask & !is_ai          # trusted (non-AI) rows for this country
          country_cases <- d$cases[mask]
          country_rate  <- d$rate[mask]
          # Anchors from trusted rows only (invariant to AI volume). Population is
          # source-independent; use trusted rows for the same invariance.
          anchor_cases <- d$cases[trusted_mask]
          anchor_rate  <- d$rate[trusted_mask]
          country_pop  <- stats::median(d$total_population[trusted_mask], na.rm = TRUE)

          # cp99c: per-country case p99, floored at 1 (avoids div-by-zero for
          # non-endemic countries).
          cp99c <- max(stats::quantile(anchor_cases, 0.99, na.rm = TRUE), 1)
          if (!is.finite(cp99c) || cp99c <= 0) cp99c <- 1

          # cp99r: per-country rate p99, floored at the "5 cases/wk equivalent
          # rate" (population-scaled). Keeps full per-country dynamic range even
          # for low-incidence countries (e.g. TGO) without re-creating the
          # flat-prediction problem a fixed 0.19/100k floor caused.
          cases_eq_5 <- if (is.finite(country_pop) && country_pop > 0) {
               5 / country_pop * 1e5
          } else {
               1e-3  # fallback if pop is bad — small floor to avoid log(0)
          }
          cp99r <- max(stats::quantile(anchor_rate, 0.99, na.rm = TRUE), cases_eq_5, na.rm = TRUE)
          if (!is.finite(cp99r) || cp99r <= 0) cp99r <- cases_eq_5

          # B/D applied to ALL rows in the country (incl AI), scored on the trusted anchor.
          d$target_B_count_per_country[mask] <-
               pmin(1, log1p(country_cases) / log1p(cp99c))
          d$target_D_rate_per_country_floored[mask] <-
               pmin(1, log1p(country_rate) / log1p(cp99r))

          # F: per-country rank over ALL observed weeks (trusted AND AI), so AI
          # observations receive a rank value like targets A-D. na.last="keep" leaves
          # empty grid cells NA; divide by (n_obs + 1) so the max is < 1 (keeps
          # qlogis() finite for any logit-domain consumer).
          # NOTE: unlike A-D (which anchor on trusted rows and are therefore invariant
          # to include_ai), F co-ranks the AI rows, so its values reflect the AI weeks
          # present in the build.
          n_obs_iso <- sum(!is.na(country_cases))
          d$target_F_rank_per_country[mask] <-
               rank(country_cases, ties.method = "average", na.last = "keep") /
                    (n_obs_iso + 1)
     }

     # 2. World Bank socioeconomic indicators (annual, forward-fill for future years)
     message("  - Adding socioeconomic indicators...")

     # GDP
     gdp_path <- file.path(PATHS$DATA_PROCESSED, "world_bank", "GDP_data_world_bank.csv")
     if (file.exists(gdp_path)) {
          gdp_data <- utils::read.csv(gdp_path, stringsAsFactors = FALSE)
          gdp_data <- gdp_data[, c("iso_code", "year", "GDP")]
          # Filter to MOSAIC countries only
          gdp_data <- gdp_data[gdp_data$iso_code %in% iso_codes_mosaic, ]
          d <- merge(d, gdp_data, by = c("iso_code", "year"), all.x = TRUE)
          # Forward-fill for future years
          d <- d %>%
               dplyr::group_by(iso_code) %>%
               dplyr::mutate(GDP = zoo::na.locf(GDP, na.rm = FALSE)) %>%
               dplyr::ungroup()
     }

     # Population density
     pop_density_path <- file.path(PATHS$DATA_PROCESSED, "world_bank", "population_density_data_world_bank.csv")
     if (file.exists(pop_density_path)) {
          pop_density_data <- utils::read.csv(pop_density_path, stringsAsFactors = FALSE)
          pop_density_data <- pop_density_data %>%
               dplyr::select(iso_code, year, pop_density) %>%
               dplyr::rename(population_density = pop_density)
          # Filter to MOSAIC countries only
          pop_density_data <- pop_density_data[pop_density_data$iso_code %in% iso_codes_mosaic, ]
          d <- merge(d, pop_density_data, by = c("iso_code", "year"), all.x = TRUE)
          d <- d %>%
               dplyr::group_by(iso_code) %>%
               dplyr::mutate(population_density = zoo::na.locf(population_density, na.rm = FALSE)) %>%
               dplyr::ungroup()
     }

     # Urban population
     urban_path <- file.path(PATHS$DATA_PROCESSED, "world_bank", "world_bank_urban_population_data.csv")
     if (file.exists(urban_path)) {
          urban_data <- utils::read.csv(urban_path, stringsAsFactors = FALSE)
          urban_data <- urban_data %>%
               dplyr::select(iso_code, year, urban_pop_prop) %>%
               dplyr::rename(urban_population_pct = urban_pop_prop)
          # Filter to MOSAIC countries only
          urban_data <- urban_data[urban_data$iso_code %in% iso_codes_mosaic, ]
          d <- merge(d, urban_data, by = c("iso_code", "year"), all.x = TRUE)
          d <- d %>%
               dplyr::group_by(iso_code) %>%
               dplyr::mutate(urban_population_pct = zoo::na.locf(urban_population_pct, na.rm = FALSE)) %>%
               dplyr::ungroup()
     }

     # Poverty ratio
     poverty_path <- file.path(PATHS$DATA_PROCESSED, "world_bank", "world_bank_poverty_ratio_data.csv")
     if (file.exists(poverty_path)) {
          poverty_data <- utils::read.csv(poverty_path, stringsAsFactors = FALSE)
          poverty_data <- poverty_data[, c("iso_code", "year", "poverty_ratio")]
          # Filter to MOSAIC countries only
          poverty_data <- poverty_data[poverty_data$iso_code %in% iso_codes_mosaic, ]
          d <- merge(d, poverty_data, by = c("iso_code", "year"), all.x = TRUE)
          d <- d %>%
               dplyr::group_by(iso_code) %>%
               dplyr::mutate(poverty_ratio = zoo::na.locf(poverty_ratio, na.rm = FALSE)) %>%
               dplyr::ungroup()
     }

     # 3. Vaccination block intentionally removed in v0.30.26: vaccination
     # is a downstream intervention (vaccines are deployed in response to
     # cholera, not in anticipation of environmental suitability), so it
     # is non-causal as a suitability predictor. The columns were also
     # already excluded from `est_suitability()`'s LSTM covariate list.
     # Computing and persisting them in the suitability dataframe was
     # wasted IO; removed for cleanliness.

     # 3b. EM-DAT flood occurrence (weekly, country-level)
     message("  - Adding EM-DAT flood occurrence indicators...")
     emdat_path <- file.path(PATHS$DATA_EMDAT, "floods_country_weekly.csv")
     if (file.exists(emdat_path)) {
          emdat_data <- utils::read.csv(emdat_path, stringsAsFactors = FALSE)
          emdat_cols <- c("emdat_flood_active", "emdat_flood_new",
                          "emdat_flood_affected", "emdat_flood_deaths")
          emdat_data <- emdat_data[emdat_data$iso_code %in% iso_codes_mosaic,
                                    c("iso_code", "year", "week", emdat_cols)]
          d <- merge(d, emdat_data, by = c("iso_code", "year", "week"), all.x = TRUE)
          # Weeks inside the EM-DAT panel are already zero-filled at the panel
          # source; weeks beyond it (the LSTM forecast window) intentionally
          # carry NA so impute_flood_probability() can replace them with a
          # GAM-imputed continuous probability rather than a degenerate zero.
     } else {
          message("    - EM-DAT flood file not found at: ", emdat_path)
     }

     # 4. WASH indicators (static, country-level)
     message("  - Adding WASH indicators...")
     wash_path <- file.path(PATHS$DATA_PROCESSED, "WASH", "WASH_data_Sikder_2023.csv")
     if (file.exists(wash_path)) {
          wash_data <- utils::read.csv(wash_path, stringsAsFactors = FALSE)
          wash_data <- wash_data[, c("iso_code", "Piped_Water", "Other_Improved_Water",
                                    "Septic_or_Sewer_Sanitation", "Other_Improved_Sanitation",
                                    "Unimproved_Water", "Surface_Water",
                                    "Unimproved_Sanitation", "Open_Defecation")]
          # Filter to MOSAIC countries only
          wash_data <- wash_data[wash_data$iso_code %in% iso_codes_mosaic, ]
          d <- merge(d, wash_data, by = "iso_code", all.x = TRUE)

          # Fill NA values with mean of all countries for each WASH variable
          wash_vars <- c("Piped_Water", "Other_Improved_Water", "Septic_or_Sewer_Sanitation",
                        "Other_Improved_Sanitation", "Unimproved_Water", "Surface_Water",
                        "Unimproved_Sanitation", "Open_Defecation")
          for (var in wash_vars) {
               if (var %in% names(d)) {
                    na_count <- sum(is.na(d[[var]]))
                    if (na_count > 0) {
                         mean_val <- mean(d[[var]], na.rm = TRUE)
                         d[[var]][is.na(d[[var]])] <- mean_val
                         message(sprintf("    - Filled %d NA values in %s with mean: %.2f",
                                       na_count, var, mean_val))
                    }
               }
          }
     }

     # 5. Calculate derived climate indices
     message("  - Calculating derived climate indices...")

     # Vapor Pressure Deficit (VPD)
     if (all(c("temperature_2m_mean", "relative_humidity_2m_mean") %in% names(d))) {
          # Saturation vapor pressure (kPa)
          es <- 0.6108 * exp(17.27 * d$temperature_2m_mean / (d$temperature_2m_mean + 237.3))
          # Actual vapor pressure
          ea <- es * (d$relative_humidity_2m_mean / 100)
          # VPD
          d$vpd <- es - ea
     }

     # Moisture Deficit Index
     if (all(c("et0_fao_evapotranspiration_sum", "precipitation_sum") %in% names(d))) {
          d$moisture_deficit <- d$et0_fao_evapotranspiration_sum - d$precipitation_sum
     }

     # Aridity Index
     if (all(c("precipitation_sum", "et0_fao_evapotranspiration_sum") %in% names(d))) {
          d$aridity_index <- ifelse(d$et0_fao_evapotranspiration_sum > 0,
                                    d$precipitation_sum / d$et0_fao_evapotranspiration_sum,
                                    NA)
     }

     # SPEI approximation (standardized by country)
     if (all(c("precipitation_sum", "et0_fao_evapotranspiration_sum") %in% names(d))) {
          d <- d %>%
               dplyr::group_by(iso_code) %>%
               dplyr::mutate(spei_approx = scale(precipitation_sum - et0_fao_evapotranspiration_sum)[,1]) %>%
               dplyr::ungroup()
     }

     # Growing Degree Days (V. cholerae optimal > 15°C)
     if ("temperature_2m_mean" %in% names(d)) {
          d$gdd_cholera <- pmax(0, d$temperature_2m_mean - 15)
     }

     # Diurnal Temperature Range
     if (all(c("temperature_2m_max", "temperature_2m_min") %in% names(d))) {
          d$diurnal_temp_range <- d$temperature_2m_max - d$temperature_2m_min
     }

     # Heat Index (simplified formula)
     if (all(c("temperature_2m_mean", "relative_humidity_2m_mean") %in% names(d))) {
          d$heat_index <- d$temperature_2m_mean +
                        0.348 * d$relative_humidity_2m_mean -
                        0.7 * sqrt(d$relative_humidity_2m_mean) * (d$temperature_2m_mean - 14.4) -
                        2.4
     }

     # 6. Add temporal features
     message("  - Adding temporal features...")

     # Cyclical patterns
     d$sin_annual <- sin(2 * pi * d$week / 52.18)
     d$cos_annual <- cos(2 * pi * d$week / 52.18)
     d$sin_biannual <- sin(4 * pi * d$week / 52.18)
     d$cos_biannual <- cos(4 * pi * d$week / 52.18)
     d$sin_quarterly <- sin(8 * pi * d$week / 52.18)
     d$cos_quarterly <- cos(8 * pi * d$week / 52.18)
     
     # Monthly cyclical patterns
     d$sin_monthly <- sin(2 * pi * d$month / 12)
     d$cos_monthly <- cos(2 * pi * d$month / 12)

     # Temporal trends
     d$time_linear <- scale(as.numeric(d$date))[,1]
     d$years_since_2000 <- pmax(0, d$year - 2000)
     d$years_since_2020 <- pmax(0, d$year - 2020)

     # 7. Add climate interaction terms
     message("  - Adding interaction terms...")

     if (all(c("temperature_2m_mean", "precipitation_sum") %in% names(d))) {
          d$temp_precip_interaction <- d$temperature_2m_mean * d$precipitation_sum
     }

     if (all(c("relative_humidity_2m_mean", "temperature_2m_mean") %in% names(d))) {
          d$humidity_temp_interaction <- d$relative_humidity_2m_mean * d$temperature_2m_mean
     }

     if (all(c("ENSO34", "precipitation_sum") %in% names(d))) {
          d$enso_precip_interaction <- d$ENSO34 * d$precipitation_sum
     }

     if (all(c("IOD", "temperature_2m_mean") %in% names(d))) {
          d$iod_temp_interaction <- d$IOD * d$temperature_2m_mean
     }

     # Add geographic data (elevation, lat/lon, region)
     message("  - Adding geographic variables...")
     elevation_path <- file.path(PATHS$DATA_ELEVATION, "country_elevation_mean.csv")
     if (file.exists(elevation_path)) {
          elevation_data <- utils::read.csv(elevation_path, stringsAsFactors = FALSE)
          # Filter to MOSAIC countries only
          elevation_data <- elevation_data[elevation_data$iso_code %in% iso_codes_mosaic, ]
          d <- merge(d, elevation_data[c("iso_code", "elevation")], by = "iso_code", all.x = TRUE)
     }
     
     # Add latitude and longitude (country centroids)
     country_coords_path <- file.path(PATHS$DATA_PROCESSED, "geography", "country_centroids.csv")
     if (file.exists(country_coords_path)) {
          coords_data <- utils::read.csv(country_coords_path, stringsAsFactors = FALSE)
          coords_data <- coords_data[, c("iso_code", "latitude", "longitude")]
          # Filter to MOSAIC countries only
          coords_data <- coords_data[coords_data$iso_code %in% iso_codes_mosaic, ]
          d <- merge(d, coords_data, by = "iso_code", all.x = TRUE)
     }
     
     # Add regional classifications (if available)
     region_path <- file.path(PATHS$DATA_PROCESSED, "geography", "country_regions.csv")
     if (file.exists(region_path)) {
          region_data <- utils::read.csv(region_path, stringsAsFactors = FALSE)
          region_data <- region_data[, c("iso_code", "region")]
          # Filter to MOSAIC countries only
          region_data <- region_data[region_data$iso_code %in% iso_codes_mosaic, ]
          d <- merge(d, region_data, by = "iso_code", all.x = TRUE)
     } else {
          # Fallback: create basic regional classification based on ISO codes if file doesn't exist
          message("    - Regional classification file not found, creating basic regions based on WHO regions")
          d$region <- MOSAIC::get_who_region(d$iso_code)
     }

     if (all(c("elevation", "temperature_2m_mean") %in% names(d))) {
          d$elevation_temp_interaction <- d$elevation * d$temperature_2m_mean
     }

     if (all(c("moisture_deficit", "temperature_2m_mean") %in% names(d))) {
          d$moisture_temp_interaction <- d$moisture_deficit * d$temperature_2m_mean
     }

     message(sprintf("Enhanced covariates added. Total columns: %d", ncol(d)))

     # ============================================================================
     # HANDLE REMAINING NA VALUES
     # ============================================================================

     message("Handling NA values in all covariates...")

     # List all numeric columns that might have NAs (exclude identifiers and dates)
     exclude_cols <- c("iso_code", "year", "week", "month", "date", "source",
                      "cases", "deaths", "cases_binary",
                      # Surveillance quality/provenance + response variables: these
                      # are TARGET-side, not features. Their NAs are meaningful
                      # ("no observation that week") and MUST NOT be mean-imputed —
                      # imputing them would fabricate confidence/rate/target values
                      # for unobserved cells and defeat their NA-propagation contract.
                      "confidence_weight", "disaggregation_method", "rate",
                      "transmission_intensity",
                      "target_A_count_global", "target_B_count_per_country",
                      "target_C_rate_global", "target_D_rate_per_country_floored",
                      "target_F_rank_per_country",
                      # Keep EM-DAT columns NA-aware: forecast-window rows must
                      # stay NA so impute_flood_probability() can replace them
                      # downstream with a GAM-imputed continuous probability.
                      "emdat_flood_active", "emdat_flood_new",
                      "emdat_flood_affected", "emdat_flood_deaths")
     numeric_cols <- names(d)[sapply(d, is.numeric)]
     numeric_cols <- setdiff(numeric_cols, exclude_cols)

     # Separate time series variables from static variables
     timeseries_vars <- c("IOD", "ENSO3", "ENSO34", "ENSO4",
                         "temperature_2m_mean", "temperature_2m_max", "temperature_2m_min",
                         "precipitation_sum", "relative_humidity_2m_mean",
                         "wind_speed_10m_mean", "cloud_cover_mean",
                         "et0_fao_evapotranspiration_sum", "soil_moisture_0_to_10cm_mean",
                         "vpd", "moisture_deficit", "aridity_index", "spei_approx",
                         "gdd_cholera", "diurnal_temp_range", "heat_index",
                         "temp_precip_interaction", "humidity_temp_interaction",
                         "enso_precip_interaction", "iod_temp_interaction",
                         "elevation_temp_interaction", "moisture_temp_interaction")

     static_vars <- setdiff(numeric_cols, timeseries_vars)

     na_summary <- data.frame(variable = character(), na_count = integer(),
                             method = character(), stringsAsFactors = FALSE)

     # 1. Handle time series variables with interpolation/forward-fill
     message("  - Handling time series variables...")
     for (var in timeseries_vars) {
          if (var %in% names(d)) {
               na_count <- sum(is.na(d[[var]]))
               if (na_count > 0) {
                    # Use last observation carried forward (LOCF) for time series
                    d <- d %>%
                         dplyr::arrange(iso_code, year, week) %>%
                         dplyr::group_by(iso_code) %>%
                         dplyr::mutate(!!var := zoo::na.locf(!!rlang::sym(var), na.rm = FALSE)) %>%
                         dplyr::ungroup()

                    # For any remaining NAs (at the beginning), use next observation carried backward
                    d <- d %>%
                         dplyr::group_by(iso_code) %>%
                         dplyr::mutate(!!var := zoo::na.locf(!!rlang::sym(var), fromLast = TRUE, na.rm = FALSE)) %>%
                         dplyr::ungroup()

                    # If still NAs (entire country missing), use global mean
                    remaining_nas <- sum(is.na(d[[var]]))
                    if (remaining_nas > 0) {
                         mean_val <- mean(d[[var]], na.rm = TRUE)
                         d[[var]][is.na(d[[var]])] <- mean_val
                         na_summary <- rbind(na_summary,
                                           data.frame(variable = var, na_count = na_count,
                                                    method = "interpolate+mean", stringsAsFactors = FALSE))
                    } else {
                         na_summary <- rbind(na_summary,
                                           data.frame(variable = var, na_count = na_count,
                                                    method = "interpolate", stringsAsFactors = FALSE))
                    }
               }
          }
     }

     # 2. Handle static variables with mean imputation
     message("  - Handling static/slow-changing variables...")
     for (col in static_vars) {
          na_count <- sum(is.na(d[[col]]))
          if (na_count > 0) {
               mean_val <- mean(d[[col]], na.rm = TRUE)
               if (!is.na(mean_val)) {
                    d[[col]][is.na(d[[col]])] <- mean_val
                    na_summary <- rbind(na_summary,
                                      data.frame(variable = col, na_count = na_count,
                                               method = "mean", stringsAsFactors = FALSE))
               }
          }
     }

     if (nrow(na_summary) > 0) {
          message(sprintf("  - Handled NA values in %d variables", nrow(na_summary)))
          # Show summary for variables with most NAs
          na_summary <- na_summary[order(na_summary$na_count, decreasing = TRUE), ]
          top_na <- head(na_summary, 5)
          for (i in 1:nrow(top_na)) {
               message(sprintf("    - %s: %d NAs filled using %s",
                             top_na$variable[i], top_na$na_count[i], top_na$method[i]))
          }
          if (nrow(na_summary) > 5) {
               message(sprintf("    - ... and %d more variables", nrow(na_summary) - 5))
          }
     } else {
          message("  - No NA values found in numeric covariates")
     }

     # Final check for any remaining NAs
     total_nas <- sum(is.na(d[, numeric_cols]))
     if (total_nas > 0) {
          warning(sprintf("Warning: %d NA values remain after imputation", total_nas))
     } else {
          message("  - All NA values successfully imputed")
     }

     # Create binary environmental suitability indicator from case data
     message("Creating environmental suitability indicator (cases_binary)...")
     if (use_epidemic_peaks) {
          message("  - Using epidemic peak-based method (deterministic)")
          message("    * Loading epidemic peaks from est_epidemic_peaks() analysis...")
          message("    * Creating deterministic outbreak-based suitability periods...")
          message("    * Using exact peak_start to peak_stop dates without modifications...")
          peak_function <- MOSAIC::get_cases_binary_from_peaks(PATHS)
          d <- peak_function(d)
          message("    * Epidemic peak-based environmental suitability indicator completed!")
     } else {
          message(sprintf("  - Using case threshold method (cutoff = %d)", cutoff))
          d <- MOSAIC::get_cases_binary(d, cutoff = cutoff)
     }

     # ============================================================================
     # ENHANCED TIME SERIES COVARIATES
     # ============================================================================

     message("Creating enhanced time series covariates...")
     
     # Calculate forecast weeks and memory lag for consistent use
     if (forecast_mode) {
          forecast_weeks <- ceiling(forecast_horizon * 4.33)  # Convert months to weeks
          memory_lag <- forecast_weeks + 4  # Add 4-week buffer for forecast safety
          message(sprintf("  - Forecast mode enabled: %d month horizon (%d weeks)", 
                         forecast_horizon, forecast_weeks))
          message(sprintf("  - Using %d-week lag for epidemic memory variables", memory_lag))
          
          # Warning for very long forecast horizons
          if (forecast_horizon > 12) {
               warning(sprintf("Very long forecast horizon (%d months) may reduce reliability of epidemic memory variables", 
                             forecast_horizon))
          }
     } else {
          forecast_weeks <- 0
          memory_lag <- 0  # No additional lag for historical analysis
     }

     # 1. Rolling windows (2, 4, 8, 12 weeks)
     message("  - Adding rolling window variables...")
     d <- d %>%
          dplyr::group_by(iso_code) %>%
          dplyr::arrange(date, .by_group = TRUE) %>%
          dplyr::mutate(
               # Precipitation rolling windows
               precip_sum_2w = slider::slide_dbl(precipitation_sum, sum, .before = 1, .complete = TRUE),
               precip_sum_4w = slider::slide_dbl(precipitation_sum, sum, .before = 3, .complete = TRUE),
               precip_sum_8w = slider::slide_dbl(precipitation_sum, sum, .before = 7, .complete = TRUE),
               precip_sum_12w = slider::slide_dbl(precipitation_sum, sum, .before = 11, .complete = TRUE),
               
               # Temperature rolling windows
               temp_mean_2w = slider::slide_dbl(temperature_2m_mean, mean, .before = 1, .complete = TRUE),
               temp_mean_4w = slider::slide_dbl(temperature_2m_mean, mean, .before = 3, .complete = TRUE),
               temp_mean_8w = slider::slide_dbl(temperature_2m_mean, mean, .before = 7, .complete = TRUE),
               temp_mean_12w = slider::slide_dbl(temperature_2m_mean, mean, .before = 11, .complete = TRUE),
               
               # Relative humidity rolling windows
               rh_mean_2w = slider::slide_dbl(relative_humidity_2m_mean, mean, .before = 1, .complete = TRUE),
               rh_mean_4w = slider::slide_dbl(relative_humidity_2m_mean, mean, .before = 3, .complete = TRUE),
               rh_mean_8w = slider::slide_dbl(relative_humidity_2m_mean, mean, .before = 7, .complete = TRUE),
               rh_mean_12w = slider::slide_dbl(relative_humidity_2m_mean, mean, .before = 11, .complete = TRUE)
          ) %>%
          dplyr::ungroup()

     # 2. Standardized anomalies vs local climatology (by location × week-of-year)
     message("  - Calculating standardized anomalies...")
     d <- d %>%
          dplyr::group_by(iso_code, week) %>%
          dplyr::mutate(
               # Precipitation anomalies
               precip_clim_mean = mean(precipitation_sum, na.rm = TRUE),
               precip_clim_sd = sd(precipitation_sum, na.rm = TRUE),
               precip_anom = (precipitation_sum - precip_clim_mean) / ifelse(precip_clim_sd > 0, precip_clim_sd, 1),
               
               # Temperature anomalies
               temp_clim_mean = mean(temperature_2m_mean, na.rm = TRUE),
               temp_clim_sd = sd(temperature_2m_mean, na.rm = TRUE),
               temp_anom = (temperature_2m_mean - temp_clim_mean) / ifelse(temp_clim_sd > 0, temp_clim_sd, 1),
               
               # VPD anomalies (if available)
               vpd_clim_mean = ifelse("vpd" %in% names(.), mean(vpd, na.rm = TRUE), NA),
               vpd_clim_sd = ifelse("vpd" %in% names(.), sd(vpd, na.rm = TRUE), NA),
               vpd_anom = ifelse("vpd" %in% names(.), 
                               (vpd - vpd_clim_mean) / ifelse(vpd_clim_sd > 0, vpd_clim_sd, 1), 
                               NA),
               
               # Soil moisture anomalies
               soilm_clim_mean = mean(soil_moisture_0_to_10cm_mean, na.rm = TRUE),
               soilm_clim_sd = sd(soil_moisture_0_to_10cm_mean, na.rm = TRUE),
               soil_moisture_anom = (soil_moisture_0_to_10cm_mean - soilm_clim_mean) /
                                  ifelse(soilm_clim_sd > 0, soilm_clim_sd, 1),

               # Teleconnection anomalies (week-of-year deseasonalization)
               # The raw ENSO/IOD indices are anomalies vs a 30-year climatology
               # baseline but retain a residual annual cycle that produces
               # spurious 30-78w correlations with cholera (seasonal aliasing).
               # Subtracting the week-of-year climatology removes that cycle and
               # isolates the non-seasonal teleconnection deviation.
               IOD_clim_mean = mean(IOD, na.rm = TRUE),
               IOD_clim_sd = sd(IOD, na.rm = TRUE),
               IOD_anom = (IOD - IOD_clim_mean) /
                          ifelse(IOD_clim_sd > 0, IOD_clim_sd, 1),

               ENSO3_clim_mean = mean(ENSO3, na.rm = TRUE),
               ENSO3_clim_sd = sd(ENSO3, na.rm = TRUE),
               ENSO3_anom = (ENSO3 - ENSO3_clim_mean) /
                            ifelse(ENSO3_clim_sd > 0, ENSO3_clim_sd, 1),

               ENSO34_clim_mean = mean(ENSO34, na.rm = TRUE),
               ENSO34_clim_sd = sd(ENSO34, na.rm = TRUE),
               ENSO34_anom = (ENSO34 - ENSO34_clim_mean) /
                             ifelse(ENSO34_clim_sd > 0, ENSO34_clim_sd, 1),

               ENSO4_clim_mean = mean(ENSO4, na.rm = TRUE),
               ENSO4_clim_sd = sd(ENSO4, na.rm = TRUE),
               ENSO4_anom = (ENSO4 - ENSO4_clim_mean) /
                            ifelse(ENSO4_clim_sd > 0, ENSO4_clim_sd, 1)
          ) %>%
          # Remove intermediate climatology columns
          dplyr::select(-precip_clim_mean, -precip_clim_sd, -temp_clim_mean, -temp_clim_sd,
                       -vpd_clim_mean, -vpd_clim_sd, -soilm_clim_mean, -soilm_clim_sd,
                       -IOD_clim_mean, -IOD_clim_sd,
                       -ENSO3_clim_mean, -ENSO3_clim_sd,
                       -ENSO34_clim_mean, -ENSO34_clim_sd,
                       -ENSO4_clim_mean, -ENSO4_clim_sd) %>%
          dplyr::ungroup()

     # 3. Climate extremes and spell indicators
     message("  - Adding climate extremes indicators...")
     d <- d %>%
          dplyr::group_by(iso_code) %>%
          dplyr::arrange(date, .by_group = TRUE) %>%
          dplyr::mutate(
               # Precipitation extremes (using 90th percentile threshold)
               precip_p90_threshold = quantile(precipitation_sum, 0.9, na.rm = TRUE),
               precip_extreme_p90_count = as.numeric(precipitation_sum >= precip_p90_threshold),
               
               # Temperature extremes (heatwave proxy - above 95th percentile)
               temp_p95_threshold = quantile(temperature_2m_mean, 0.95, na.rm = TRUE),
               heatwave_days = as.numeric(temperature_2m_mean >= temp_p95_threshold),
               
               # Dry spell length (consecutive weeks with precip < 1mm)
               dry_week = precipitation_sum < 1.0,
               dry_spell_len = slider::slide_dbl(dry_week, ~ sum(.x), .before = 6, .complete = TRUE)
          ) %>%
          dplyr::select(-precip_p90_threshold, -temp_p95_threshold, -dry_week) %>%
          dplyr::ungroup()

     # 4. Epidemic memory block intentionally removed in v0.30.26:
     # `r_t`, `cum_cases_4w/8w/12w/52w`, `nonzero_ratio_52w`,
     # `weeks_since_major_outbreak`, `peak_cases_52w`, and
     # `seasonal_outbreak_risk` are all derived from observed cholera
     # cases. Predicting cases_binary (the LSTM target) using any
     # function of cases is target leakage -- even with the
     # forecast-safe `memory_lag`, the predictor still carries case
     # information that the model would otherwise have to infer from
     # climate alone. The columns were already excluded from
     # `est_suitability()`'s covariate list; computing and persisting
     # them in the suitability dataframe was wasted IO and a foot-gun.

     # 5. Spatial-import block intentionally removed in v0.30.26.
     # The mobility-derived network covariates -- import_vulnerability,
     # export_potential, weighted_import_connectivity, connectivity_degree,
     # betweenness_centrality, eigenvector_centrality, import_export_balance --
     # were already excluded from est_suitability()'s LSTM covariate list
     # and not used by the imputation GAM. Computing and persisting them
     # in the suitability dataframe was wasted IO.

     # 6. Enhanced interaction terms (WASH × extremes, Urban × climate, nonlinear transforms)
     message("  - Adding enhanced interaction terms...")
     
     # WASH × extreme precipitation
     if (all(c("precip_extreme_p90_count", "Unimproved_Sanitation") %in% names(d))) {
          d$wash_precip_extreme_interaction <- d$precip_extreme_p90_count * d$Unimproved_Sanitation
     }
     
     # Urban × precipitation anomaly
     if (all(c("urban_population_pct", "precip_anom") %in% names(d))) {
          d$urban_precip_anom_interaction <- d$urban_population_pct * d$precip_anom
     }

     # WASH × climate / Vibrio-growth / drought-break interactions
     # (added 2026-06; mechanism categories from cholera-environmental-suitability
     # literature; included as engineered features because each product encodes a
     # multiplicative AND-gate over slow/fast variables that the LSTM has limited
     # capacity to discover from raw inputs alone.)
     #
     # Tier 1 — direct fecal-oral transmission (extreme rain / flood × poor sanitation):
     if (all(c("Open_Defecation", "precip_extreme_p90_count") %in% names(d))) {
          d$od_x_precip_extreme <- d$Open_Defecation * d$precip_extreme_p90_count
     }
     # NOTE: od_x_flood_4w and surface_water_x_flood_12w are computed LATER —
     # after impute_flood_probability() materializes the emdat_flood_prob_*
     # rolling aggregates further below in this function.
     if (all(c("Open_Defecation", "soil_moisture_anom") %in% names(d))) {
          d$od_x_soil_moisture_anom <- d$Open_Defecation * d$soil_moisture_anom
     }
     if (all(c("Piped_Water", "precip_extreme_p90_count") %in% names(d))) {
          d$nonpiped_x_precip_extreme <- (1 - d$Piped_Water) * d$precip_extreme_p90_count
     }

     # Tier 2 — V. cholerae environmental growth niche (warm AND wet AND-gate):
     if (all(c("soil_moisture_anom", "temperature_2m_mean") %in% names(d))) {
          d$sm_anom_x_temp <- d$soil_moisture_anom * d$temperature_2m_mean
     }
     if (all(c("Surface_Water", "temperature_2m_mean") %in% names(d))) {
          d$surface_water_x_temp <- d$Surface_Water * d$temperature_2m_mean
     }
     if (all(c("precip_anom", "temperature_2m_mean") %in% names(d))) {
          d$precip_anom_x_temp <- d$precip_anom * d$temperature_2m_mean
     }

     # Tier 3 — drought-break / regime-transition flush events:
     if (all(c("dry_spell_len", "precip_sum_2w") %in% names(d))) {
          d$dryspell_x_precip_2w <- d$dry_spell_len * d$precip_sum_2w
     }
     if (all(c("spei_approx", "precip_anom") %in% names(d))) {
          d$spei_x_precip_anom <- d$spei_approx * d$precip_anom
     }

     # Nonlinear transforms for key variables
     if ("precip_anom" %in% names(d)) {
          d$precip_anom_sq <- d$precip_anom^2
     }

     if ("temp_anom" %in% names(d)) {
          d$temp_anom_sq <- d$temp_anom^2
     }
     
     # 7. Time-lagged climate variables (epidemiologically-informed lags)
     if (include_lags) {
          message("  - Adding time-lagged climate variables...")
          
          d <- d %>%
               dplyr::group_by(iso_code) %>%
               dplyr::arrange(date, .by_group = TRUE) %>%
               dplyr::mutate(
                    # ---- Climate raw: extended grid to lag 24w ------------
                    # Precipitation: 1-8w short-window + 12,16,20,24w (ENSO-mediated rainfall response)
                    precipitation_sum_lag1 = dplyr::lag(precipitation_sum, 1),
                    precipitation_sum_lag2 = dplyr::lag(precipitation_sum, 2),
                    precipitation_sum_lag4 = dplyr::lag(precipitation_sum, 4),
                    precipitation_sum_lag6 = dplyr::lag(precipitation_sum, 6),
                    precipitation_sum_lag8 = dplyr::lag(precipitation_sum, 8),
                    precipitation_sum_lag12 = dplyr::lag(precipitation_sum, 12),
                    precipitation_sum_lag16 = dplyr::lag(precipitation_sum, 16),
                    precipitation_sum_lag20 = dplyr::lag(precipitation_sum, 20),
                    precipitation_sum_lag24 = dplyr::lag(precipitation_sum, 24),

                    # Temperature mean: 2-8w + extended 12,16,20,24w
                    temperature_2m_mean_lag2 = dplyr::lag(temperature_2m_mean, 2),
                    temperature_2m_mean_lag4 = dplyr::lag(temperature_2m_mean, 4),
                    temperature_2m_mean_lag8 = dplyr::lag(temperature_2m_mean, 8),
                    temperature_2m_mean_lag12 = dplyr::lag(temperature_2m_mean, 12),
                    temperature_2m_mean_lag16 = dplyr::lag(temperature_2m_mean, 16),
                    temperature_2m_mean_lag20 = dplyr::lag(temperature_2m_mean, 20),
                    temperature_2m_mean_lag24 = dplyr::lag(temperature_2m_mean, 24),

                    # Temperature max: 2-8w + 12,16w
                    temperature_2m_max_lag2 = dplyr::lag(temperature_2m_max, 2),
                    temperature_2m_max_lag4 = dplyr::lag(temperature_2m_max, 4),
                    temperature_2m_max_lag6 = dplyr::lag(temperature_2m_max, 6),
                    temperature_2m_max_lag8 = dplyr::lag(temperature_2m_max, 8),
                    temperature_2m_max_lag12 = dplyr::lag(temperature_2m_max, 12),
                    temperature_2m_max_lag16 = dplyr::lag(temperature_2m_max, 16),

                    # Relative humidity: 1-4w + extended 8,12,16w
                    relative_humidity_2m_mean_lag1 = dplyr::lag(relative_humidity_2m_mean, 1),
                    relative_humidity_2m_mean_lag2 = dplyr::lag(relative_humidity_2m_mean, 2),
                    relative_humidity_2m_mean_lag4 = dplyr::lag(relative_humidity_2m_mean, 4),
                    relative_humidity_2m_mean_lag8 = dplyr::lag(relative_humidity_2m_mean, 8),
                    relative_humidity_2m_mean_lag12 = dplyr::lag(relative_humidity_2m_mean, 12),
                    relative_humidity_2m_mean_lag16 = dplyr::lag(relative_humidity_2m_mean, 16),

                    # VPD: 1-8w + 12,16w
                    vpd_lag1 = if("vpd" %in% names(.) && !all(is.na(vpd))) dplyr::lag(vpd, 1) else NA_real_,
                    vpd_lag4 = if("vpd" %in% names(.) && !all(is.na(vpd))) dplyr::lag(vpd, 4) else NA_real_,
                    vpd_lag8 = if("vpd" %in% names(.) && !all(is.na(vpd))) dplyr::lag(vpd, 8) else NA_real_,
                    vpd_lag12 = if("vpd" %in% names(.) && !all(is.na(vpd))) dplyr::lag(vpd, 12) else NA_real_,
                    vpd_lag16 = if("vpd" %in% names(.) && !all(is.na(vpd))) dplyr::lag(vpd, 16) else NA_real_,

                    # Soil moisture: 1-8w + 12,16w
                    soil_moisture_0_to_10cm_mean_lag1 = dplyr::lag(soil_moisture_0_to_10cm_mean, 1),
                    soil_moisture_0_to_10cm_mean_lag2 = dplyr::lag(soil_moisture_0_to_10cm_mean, 2),
                    soil_moisture_0_to_10cm_mean_lag4 = dplyr::lag(soil_moisture_0_to_10cm_mean, 4),
                    soil_moisture_0_to_10cm_mean_lag6 = dplyr::lag(soil_moisture_0_to_10cm_mean, 6),
                    soil_moisture_0_to_10cm_mean_lag8 = dplyr::lag(soil_moisture_0_to_10cm_mean, 8),
                    soil_moisture_0_to_10cm_mean_lag12 = dplyr::lag(soil_moisture_0_to_10cm_mean, 12),
                    soil_moisture_0_to_10cm_mean_lag16 = dplyr::lag(soil_moisture_0_to_10cm_mean, 16),

                    # SPEI (integrated hydro-climate balance): 4-24w
                    spei_approx_lag4 = if("spei_approx" %in% names(.) && !all(is.na(spei_approx))) dplyr::lag(spei_approx, 4) else NA_real_,
                    spei_approx_lag8 = if("spei_approx" %in% names(.) && !all(is.na(spei_approx))) dplyr::lag(spei_approx, 8) else NA_real_,
                    spei_approx_lag12 = if("spei_approx" %in% names(.) && !all(is.na(spei_approx))) dplyr::lag(spei_approx, 12) else NA_real_,
                    spei_approx_lag16 = if("spei_approx" %in% names(.) && !all(is.na(spei_approx))) dplyr::lag(spei_approx, 16) else NA_real_,
                    spei_approx_lag20 = if("spei_approx" %in% names(.) && !all(is.na(spei_approx))) dplyr::lag(spei_approx, 20) else NA_real_,
                    spei_approx_lag24 = if("spei_approx" %in% names(.) && !all(is.na(spei_approx))) dplyr::lag(spei_approx, 24) else NA_real_,

                    # Evapotranspiration: 1-8w + 12,16w
                    et0_fao_evapotranspiration_sum_lag1 = dplyr::lag(et0_fao_evapotranspiration_sum, 1),
                    et0_fao_evapotranspiration_sum_lag4 = dplyr::lag(et0_fao_evapotranspiration_sum, 4),
                    et0_fao_evapotranspiration_sum_lag8 = dplyr::lag(et0_fao_evapotranspiration_sum, 8),
                    et0_fao_evapotranspiration_sum_lag12 = dplyr::lag(et0_fao_evapotranspiration_sum, 12),
                    et0_fao_evapotranspiration_sum_lag16 = dplyr::lag(et0_fao_evapotranspiration_sum, 16),

                    # Diurnal temperature range: 2,4 + 8w
                    diurnal_temp_range_lag2 = if("diurnal_temp_range" %in% names(.) && !all(is.na(diurnal_temp_range)))
                                                    dplyr::lag(diurnal_temp_range, 2) else NA_real_,
                    diurnal_temp_range_lag4 = if("diurnal_temp_range" %in% names(.) && !all(is.na(diurnal_temp_range)))
                                                    dplyr::lag(diurnal_temp_range, 4) else NA_real_,
                    diurnal_temp_range_lag8 = if("diurnal_temp_range" %in% names(.) && !all(is.na(diurnal_temp_range)))
                                                    dplyr::lag(diurnal_temp_range, 8) else NA_real_,

                    # Heat index: 2-8w + 12,16w
                    heat_index_lag2 = if("heat_index" %in% names(.) && !all(is.na(heat_index))) dplyr::lag(heat_index, 2) else NA_real_,
                    heat_index_lag4 = if("heat_index" %in% names(.) && !all(is.na(heat_index))) dplyr::lag(heat_index, 4) else NA_real_,
                    heat_index_lag8 = if("heat_index" %in% names(.) && !all(is.na(heat_index))) dplyr::lag(heat_index, 8) else NA_real_,
                    heat_index_lag12 = if("heat_index" %in% names(.) && !all(is.na(heat_index))) dplyr::lag(heat_index, 12) else NA_real_,
                    heat_index_lag16 = if("heat_index" %in% names(.) && !all(is.na(heat_index))) dplyr::lag(heat_index, 16) else NA_real_,

                    # Cloud cover: 1,4 + 8w
                    cloud_cover_mean_lag1 = dplyr::lag(cloud_cover_mean, 1),
                    cloud_cover_mean_lag4 = dplyr::lag(cloud_cover_mean, 4),
                    cloud_cover_mean_lag8 = dplyr::lag(cloud_cover_mean, 8),

                    # Wind speed: 1,2 + 4,8w
                    wind_speed_10m_mean_lag1 = dplyr::lag(wind_speed_10m_mean, 1),
                    wind_speed_10m_mean_lag2 = dplyr::lag(wind_speed_10m_mean, 2),
                    wind_speed_10m_mean_lag4 = dplyr::lag(wind_speed_10m_mean, 4),
                    wind_speed_10m_mean_lag8 = dplyr::lag(wind_speed_10m_mean, 8),

                    # ---- Anomaly lags (mechanistically distinct from raw) ----
                    # precip_anom: 4-20w
                    precip_anom_lag4 = if("precip_anom" %in% names(.) && !all(is.na(precip_anom))) dplyr::lag(precip_anom, 4) else NA_real_,
                    precip_anom_lag8 = if("precip_anom" %in% names(.) && !all(is.na(precip_anom))) dplyr::lag(precip_anom, 8) else NA_real_,
                    precip_anom_lag12 = if("precip_anom" %in% names(.) && !all(is.na(precip_anom))) dplyr::lag(precip_anom, 12) else NA_real_,
                    precip_anom_lag16 = if("precip_anom" %in% names(.) && !all(is.na(precip_anom))) dplyr::lag(precip_anom, 16) else NA_real_,
                    precip_anom_lag20 = if("precip_anom" %in% names(.) && !all(is.na(precip_anom))) dplyr::lag(precip_anom, 20) else NA_real_,

                    # temp_anom: 4-16w
                    temp_anom_lag4 = if("temp_anom" %in% names(.) && !all(is.na(temp_anom))) dplyr::lag(temp_anom, 4) else NA_real_,
                    temp_anom_lag8 = if("temp_anom" %in% names(.) && !all(is.na(temp_anom))) dplyr::lag(temp_anom, 8) else NA_real_,
                    temp_anom_lag12 = if("temp_anom" %in% names(.) && !all(is.na(temp_anom))) dplyr::lag(temp_anom, 12) else NA_real_,
                    temp_anom_lag16 = if("temp_anom" %in% names(.) && !all(is.na(temp_anom))) dplyr::lag(temp_anom, 16) else NA_real_,

                    # soil_moisture_anom: 4-20w
                    soil_moisture_anom_lag4 = if("soil_moisture_anom" %in% names(.) && !all(is.na(soil_moisture_anom))) dplyr::lag(soil_moisture_anom, 4) else NA_real_,
                    soil_moisture_anom_lag8 = if("soil_moisture_anom" %in% names(.) && !all(is.na(soil_moisture_anom))) dplyr::lag(soil_moisture_anom, 8) else NA_real_,
                    soil_moisture_anom_lag12 = if("soil_moisture_anom" %in% names(.) && !all(is.na(soil_moisture_anom))) dplyr::lag(soil_moisture_anom, 12) else NA_real_,
                    soil_moisture_anom_lag16 = if("soil_moisture_anom" %in% names(.) && !all(is.na(soil_moisture_anom))) dplyr::lag(soil_moisture_anom, 16) else NA_real_,
                    soil_moisture_anom_lag20 = if("soil_moisture_anom" %in% names(.) && !all(is.na(soil_moisture_anom))) dplyr::lag(soil_moisture_anom, 20) else NA_real_,

                    # vpd_anom: 4-16w
                    vpd_anom_lag4 = if("vpd_anom" %in% names(.) && !all(is.na(vpd_anom))) dplyr::lag(vpd_anom, 4) else NA_real_,
                    vpd_anom_lag8 = if("vpd_anom" %in% names(.) && !all(is.na(vpd_anom))) dplyr::lag(vpd_anom, 8) else NA_real_,
                    vpd_anom_lag12 = if("vpd_anom" %in% names(.) && !all(is.na(vpd_anom))) dplyr::lag(vpd_anom, 12) else NA_real_,
                    vpd_anom_lag16 = if("vpd_anom" %in% names(.) && !all(is.na(vpd_anom))) dplyr::lag(vpd_anom, 16) else NA_real_,

                    # Teleconnection anomaly lags 4-24w
                    # (deseasonalized — these should give cleaner long-lead
                    # signal than raw ENSO/IOD lags, which retain annual-cycle
                    # aliasing.)
                    IOD_anom_lag4 = dplyr::lag(IOD_anom, 4),
                    IOD_anom_lag8 = dplyr::lag(IOD_anom, 8),
                    IOD_anom_lag12 = dplyr::lag(IOD_anom, 12),
                    IOD_anom_lag16 = dplyr::lag(IOD_anom, 16),
                    IOD_anom_lag20 = dplyr::lag(IOD_anom, 20),
                    IOD_anom_lag24 = dplyr::lag(IOD_anom, 24),

                    ENSO3_anom_lag4 = dplyr::lag(ENSO3_anom, 4),
                    ENSO3_anom_lag8 = dplyr::lag(ENSO3_anom, 8),
                    ENSO3_anom_lag12 = dplyr::lag(ENSO3_anom, 12),
                    ENSO3_anom_lag16 = dplyr::lag(ENSO3_anom, 16),
                    ENSO3_anom_lag20 = dplyr::lag(ENSO3_anom, 20),
                    ENSO3_anom_lag24 = dplyr::lag(ENSO3_anom, 24),

                    ENSO34_anom_lag4 = dplyr::lag(ENSO34_anom, 4),
                    ENSO34_anom_lag8 = dplyr::lag(ENSO34_anom, 8),
                    ENSO34_anom_lag12 = dplyr::lag(ENSO34_anom, 12),
                    ENSO34_anom_lag16 = dplyr::lag(ENSO34_anom, 16),
                    ENSO34_anom_lag20 = dplyr::lag(ENSO34_anom, 20),
                    ENSO34_anom_lag24 = dplyr::lag(ENSO34_anom, 24),

                    ENSO4_anom_lag4 = dplyr::lag(ENSO4_anom, 4),
                    ENSO4_anom_lag8 = dplyr::lag(ENSO4_anom, 8),
                    ENSO4_anom_lag12 = dplyr::lag(ENSO4_anom, 12),
                    ENSO4_anom_lag16 = dplyr::lag(ENSO4_anom, 16),
                    ENSO4_anom_lag20 = dplyr::lag(ENSO4_anom, 20),
                    ENSO4_anom_lag24 = dplyr::lag(ENSO4_anom, 24),

                    # ---- ENSO/IOD: COMPLETE GRID 4-48w across all four indices ----
                    # ENSO3 (Eastern Pacific)
                    ENSO3_lag4  = dplyr::lag(ENSO3, 4),
                    ENSO3_lag8  = dplyr::lag(ENSO3, 8),
                    ENSO3_lag12 = dplyr::lag(ENSO3, 12),
                    ENSO3_lag16 = dplyr::lag(ENSO3, 16),
                    ENSO3_lag20 = dplyr::lag(ENSO3, 20),
                    ENSO3_lag24 = dplyr::lag(ENSO3, 24),
                    ENSO3_lag28 = dplyr::lag(ENSO3, 28),
                    ENSO3_lag32 = dplyr::lag(ENSO3, 32),
                    ENSO3_lag36 = dplyr::lag(ENSO3, 36),
                    ENSO3_lag40 = dplyr::lag(ENSO3, 40),
                    ENSO3_lag44 = dplyr::lag(ENSO3, 44),

                    # ENSO34 (Central Pacific)
                    ENSO34_lag4  = dplyr::lag(ENSO34, 4),
                    ENSO34_lag8  = dplyr::lag(ENSO34, 8),
                    ENSO34_lag12 = dplyr::lag(ENSO34, 12),
                    ENSO34_lag16 = dplyr::lag(ENSO34, 16),
                    ENSO34_lag20 = dplyr::lag(ENSO34, 20),
                    ENSO34_lag24 = dplyr::lag(ENSO34, 24),
                    ENSO34_lag28 = dplyr::lag(ENSO34, 28),
                    ENSO34_lag32 = dplyr::lag(ENSO34, 32),
                    ENSO34_lag36 = dplyr::lag(ENSO34, 36),
                    ENSO34_lag40 = dplyr::lag(ENSO34, 40),
                    ENSO34_lag44 = dplyr::lag(ENSO34, 44),
                    ENSO34_lag48 = dplyr::lag(ENSO34, 48),

                    # ENSO4 (Western Pacific) — was only lag40/lag44; fill short+medium
                    ENSO4_lag4  = dplyr::lag(ENSO4, 4),
                    ENSO4_lag8  = dplyr::lag(ENSO4, 8),
                    ENSO4_lag12 = dplyr::lag(ENSO4, 12),
                    ENSO4_lag16 = dplyr::lag(ENSO4, 16),
                    ENSO4_lag20 = dplyr::lag(ENSO4, 20),
                    ENSO4_lag24 = dplyr::lag(ENSO4, 24),
                    ENSO4_lag28 = dplyr::lag(ENSO4, 28),
                    ENSO4_lag32 = dplyr::lag(ENSO4, 32),
                    ENSO4_lag36 = dplyr::lag(ENSO4, 36),
                    ENSO4_lag40 = dplyr::lag(ENSO4, 40),
                    ENSO4_lag44 = dplyr::lag(ENSO4, 44),

                    # IOD (Indian Ocean Dipole) — complete grid 0-44w
                    IOD_lag0  = IOD,
                    IOD_lag4  = dplyr::lag(IOD, 4),
                    IOD_lag8  = dplyr::lag(IOD, 8),
                    IOD_lag12 = dplyr::lag(IOD, 12),
                    IOD_lag16 = dplyr::lag(IOD, 16),
                    IOD_lag20 = dplyr::lag(IOD, 20),
                    IOD_lag24 = dplyr::lag(IOD, 24),
                    IOD_lag28 = dplyr::lag(IOD, 28),
                    IOD_lag32 = dplyr::lag(IOD, 32),
                    IOD_lag36 = dplyr::lag(IOD, 36),
                    IOD_lag40 = dplyr::lag(IOD, 40),
                    IOD_lag44 = dplyr::lag(IOD, 44)
               ) %>%
               dplyr::ungroup()

          message("    - Added climate/anomaly/ENSO/IOD time-lagged variables (extended grid)")

          # Remove any lag columns that are entirely NA (failed conditional creation)
          lag_columns <- names(d)[grepl("_lag\\d+$", names(d))]
          all_na_lags <- sapply(d[lag_columns], function(x) all(is.na(x)))
          if (any(all_na_lags)) {
               removed_lags <- names(all_na_lags)[all_na_lags]
               d <- d[, !names(d) %in% removed_lags]
               message(sprintf("    - Removed %d all-NA lag columns: %s",
                              length(removed_lags),
                              paste(head(removed_lags, 5), collapse = ", ")))
          }
     } else {
          message("  - Skipping time-lagged climate variables")
     }

     message(sprintf("Enhanced covariates added. Total columns: %d", ncol(d)))

     # ============================================================================
     # FLOOD PROBABILITY IMPUTATION (binomial GAM)
     # ============================================================================
     # Runs here, AFTER climate anomalies and rolling windows are fully
     # populated, so the GAM has its full predictor set. EM-DAT columns were
     # excluded from the upstream NA-imputation block so forecast-window rows
     # still carry NA for emdat_flood_active and impute_flood_probability()
     # replaces them with a continuous imputed probability.
     # Source the required-column list from the imputation function itself
     # so the gate cannot drift out of sync with the GAM contract as the
     # formula evolves.
     gam_required <- MOSAIC:::.impute_flood_probability_required()
     gam_missing  <- setdiff(gam_required, names(d))
     if (isTRUE(include_flood_prob) && length(gam_missing) == 0) {

          message("Imputing flood probability with binomial GAM...")
          diag_dir <- if (!is.null(PATHS$DOCS_FIGURES)) {
               file.path(PATHS$DOCS_FIGURES, "flood_imputation")
          } else NULL
          d <- MOSAIC::impute_flood_probability(
               d,
               output_col  = "emdat_flood_prob",
               diagnostics = TRUE,
               diag_dir    = diag_dir,
               verbose     = TRUE
          )

          # Country-grouped rolling-window aggregates of the imputed probability.
          # The anomaly baseline subtracts the per-country mean restricted to
          # historical rows (emdat_flood_active observed), so the GAM's
          # forecast-window extrapolations don't contaminate the anomaly
          # reference for the training period.
          d <- d %>%
               dplyr::group_by(iso_code) %>%
               dplyr::arrange(date, .by_group = TRUE) %>%
               dplyr::mutate(
                    emdat_flood_prob_4w_max  = slider::slide_dbl(emdat_flood_prob, max,
                                                                  .before = 3,  .complete = TRUE),
                    emdat_flood_prob_12w_max = slider::slide_dbl(emdat_flood_prob, max,
                                                                  .before = 11, .complete = TRUE),
                    emdat_flood_prob_12w_sum = slider::slide_dbl(emdat_flood_prob, sum,
                                                                  .before = 11, .complete = TRUE),
                    emdat_flood_prob_anom    = emdat_flood_prob -
                         mean(emdat_flood_prob[!is.na(emdat_flood_active)], na.rm = TRUE)
               ) %>%
               dplyr::ungroup()

          # Flood × WASH interactions — must happen AFTER impute_flood_probability
          # materializes emdat_flood_prob_4w_max and emdat_flood_prob_12w_max.
          if (all(c("Open_Defecation", "emdat_flood_prob_4w_max") %in% names(d))) {
               d$od_x_flood_4w <- d$Open_Defecation * d$emdat_flood_prob_4w_max
          }
          if (all(c("Surface_Water", "emdat_flood_prob_12w_max") %in% names(d))) {
               d$surface_water_x_flood_12w <-
                    d$Surface_Water * d$emdat_flood_prob_12w_max
          }

          # Flood probability anomaly lags (4-20w window). These require
          # emdat_flood_prob_anom which is materialized just above. Only
          # compute when include_lags = TRUE (matches the gating logic for
          # all other lag columns).
          if (isTRUE(include_lags) && "emdat_flood_prob_anom" %in% names(d)) {
               d <- d %>%
                    dplyr::group_by(iso_code) %>%
                    dplyr::arrange(date, .by_group = TRUE) %>%
                    dplyr::mutate(
                         emdat_flood_prob_anom_lag4  = dplyr::lag(emdat_flood_prob_anom, 4),
                         emdat_flood_prob_anom_lag8  = dplyr::lag(emdat_flood_prob_anom, 8),
                         emdat_flood_prob_anom_lag12 = dplyr::lag(emdat_flood_prob_anom, 12),
                         emdat_flood_prob_anom_lag16 = dplyr::lag(emdat_flood_prob_anom, 16),
                         emdat_flood_prob_anom_lag20 = dplyr::lag(emdat_flood_prob_anom, 20)
                    ) %>%
                    dplyr::ungroup()
          }
     } else if (isTRUE(include_flood_prob)) {
          message("Skipping flood probability imputation; missing column(s): ",
                  paste(gam_missing, collapse = ", "))
     }

     # The `source` column is intentionally retained in the suitability CSV
     # (previously dropped here). Useful for diagnostics — which weeks have WHO
     # vs JHU vs SUPP backing — and a prerequisite for PART B's confidence_weight
     # propagation. It flows through column reordering below via remaining_cols.

     # Reorder columns thematically (matching the order of data assembly)
     # 1. Location/Time/Cases/Deaths
     base_cols <- c("iso_code", "year", "month", "week", "date", "cases", "cases_binary", "deaths")

     # 1b. Surveillance provenance / quality metadata (carried from the combined
     # surveillance CSV). Listed explicitly so the confidence_weight column is
     # preserved by design rather than only incidentally via remaining_cols.
     # Absent columns are dropped by the final `%in% names(d)` filter, so this is
     # a no-op when a column is not present.
     surveillance_meta_cols <- c("source", "confidence_weight", "disaggregation_method")

     # 2. Temporal variables
     temporal_cols <- c("sin_annual", "cos_annual", "sin_biannual", "cos_biannual",
                       "sin_quarterly", "cos_quarterly", "sin_monthly", "cos_monthly",
                       "time_linear", "years_since_2000", "years_since_2020")
     
     # 3. Demographics and socioeconomic (moved before ENSO)
     demo_cols <- c("total_population", "births_per_1000", "deaths_per_1000",
                   "GDP", "population_density", "urban_population_pct", "poverty_ratio")
     
     # 4. Vaccination and other health (moved before ENSO)
     health_cols <- character(0)
     
     # 5. WASH indicators (moved before ENSO)
     wash_cols <- c("Piped_Water", "Other_Improved_Water", "Septic_or_Sewer_Sanitation",
                   "Other_Improved_Sanitation", "Unimproved_Water", "Surface_Water",
                   "Unimproved_Sanitation", "Open_Defecation")
     
     # 6. ENSO/Climate indices
     enso_cols <- c("IOD", "ENSO3", "ENSO34", "ENSO4")
     
     # 7. Basic climate variables
     basic_climate_cols <- c("temperature_2m_mean", "temperature_2m_max", "temperature_2m_min",
                            "precipitation_sum", "relative_humidity_2m_mean", "wind_speed_10m_mean",
                            "cloud_cover_mean", "et0_fao_evapotranspiration_sum", 
                            "soil_moisture_0_to_10cm_mean")
     
     # 8. Rolling window variables
     rolling_cols <- c("precip_sum_2w", "precip_sum_4w", "precip_sum_8w", "precip_sum_12w",
                      "temp_mean_2w", "temp_mean_4w", "temp_mean_8w", "temp_mean_12w", 
                      "rh_mean_2w", "rh_mean_4w", "rh_mean_8w", "rh_mean_12w")
     
     # 9. Standardized anomalies
     anomaly_cols <- c("precip_anom", "temp_anom", "vpd_anom", "soil_moisture_anom")
     
     # 10. Climate extremes and spells  
     extremes_cols <- c("precip_extreme_p90_count", "heatwave_days", "dry_spell_len")
     
     # 11. Epidemic memory variables removed in v0.30.26 (case-derived,
     # target-leakage risk). Empty placeholder kept so the column-order
     # array stays valid.
     memory_cols <- character(0)

     # 12. Spatial-import variables removed in v0.30.26. Empty placeholder
     # kept so the column-order array stays valid.
     spatial_cols <- character(0)

     # 13. Climate interaction terms (original)
     interaction_cols <- c("temp_precip_interaction", "humidity_temp_interaction",
                          "enso_precip_interaction", "iod_temp_interaction",
                          "elevation_temp_interaction", "moisture_temp_interaction")
     
     # 14. Enhanced interaction terms (WASH × extremes, Urban × climate)
     # Tier 1 (direct fecal-oral): od_x_*, surface_water_x_flood_12w, nonpiped_x_precip_extreme
     # Tier 2 (Vc growth):         sm_anom_x_temp, surface_water_x_temp, precip_anom_x_temp
     # Tier 3 (drought-break):     dryspell_x_precip_2w, spei_x_precip_anom
     enhanced_interaction_cols <- c(
          "wash_precip_extreme_interaction", "urban_precip_anom_interaction",
          "od_x_precip_extreme", "od_x_flood_4w", "od_x_soil_moisture_anom",
          "surface_water_x_flood_12w", "nonpiped_x_precip_extreme",
          "sm_anom_x_temp", "surface_water_x_temp", "precip_anom_x_temp",
          "dryspell_x_precip_2w", "spei_x_precip_anom"
     )
     
     # 15. Nonlinear transforms
     nonlinear_cols <- c("precip_anom_sq", "temp_anom_sq")
     
     # 16. Time-lagged climate variables (if included). Extended grid to give
     # the LSTM and downstream correlation analyses wide coverage of mechanism-
     # plausible lag windows: short-window climate (1-8w), medium-window climate
     # (12-24w), anomalies (4-20w), full ENSO/IOD grid (4-44/48w).
     if (include_lags) {
          lag_cols <- c(
               # Precipitation (1-24w)
               "precipitation_sum_lag1", "precipitation_sum_lag2", "precipitation_sum_lag4",
               "precipitation_sum_lag6", "precipitation_sum_lag8",
               "precipitation_sum_lag12", "precipitation_sum_lag16",
               "precipitation_sum_lag20", "precipitation_sum_lag24",
               # Temperature mean (2-24w)
               "temperature_2m_mean_lag2", "temperature_2m_mean_lag4",
               "temperature_2m_mean_lag8", "temperature_2m_mean_lag12",
               "temperature_2m_mean_lag16", "temperature_2m_mean_lag20",
               "temperature_2m_mean_lag24",
               # Temperature max (2-16w)
               "temperature_2m_max_lag2", "temperature_2m_max_lag4",
               "temperature_2m_max_lag6", "temperature_2m_max_lag8",
               "temperature_2m_max_lag12", "temperature_2m_max_lag16",
               # Relative humidity (1-16w)
               "relative_humidity_2m_mean_lag1", "relative_humidity_2m_mean_lag2",
               "relative_humidity_2m_mean_lag4", "relative_humidity_2m_mean_lag8",
               "relative_humidity_2m_mean_lag12", "relative_humidity_2m_mean_lag16",
               # VPD (1-16w)
               "vpd_lag1", "vpd_lag4", "vpd_lag8", "vpd_lag12", "vpd_lag16",
               # Soil moisture (1-16w)
               "soil_moisture_0_to_10cm_mean_lag1", "soil_moisture_0_to_10cm_mean_lag2",
               "soil_moisture_0_to_10cm_mean_lag4", "soil_moisture_0_to_10cm_mean_lag6",
               "soil_moisture_0_to_10cm_mean_lag8", "soil_moisture_0_to_10cm_mean_lag12",
               "soil_moisture_0_to_10cm_mean_lag16",
               # SPEI (4-24w)
               "spei_approx_lag4", "spei_approx_lag8", "spei_approx_lag12",
               "spei_approx_lag16", "spei_approx_lag20", "spei_approx_lag24",
               # ET (1-16w)
               "et0_fao_evapotranspiration_sum_lag1", "et0_fao_evapotranspiration_sum_lag4",
               "et0_fao_evapotranspiration_sum_lag8", "et0_fao_evapotranspiration_sum_lag12",
               "et0_fao_evapotranspiration_sum_lag16",
               # Diurnal temp range (2-8w)
               "diurnal_temp_range_lag2", "diurnal_temp_range_lag4", "diurnal_temp_range_lag8",
               # Heat index (2-16w)
               "heat_index_lag2", "heat_index_lag4", "heat_index_lag8",
               "heat_index_lag12", "heat_index_lag16",
               # Cloud cover (1-8w)
               "cloud_cover_mean_lag1", "cloud_cover_mean_lag4", "cloud_cover_mean_lag8",
               # Wind speed (1-8w)
               "wind_speed_10m_mean_lag1", "wind_speed_10m_mean_lag2",
               "wind_speed_10m_mean_lag4", "wind_speed_10m_mean_lag8",
               # Anomaly lags (4-20w) — mechanistically distinct from raw
               "precip_anom_lag4", "precip_anom_lag8", "precip_anom_lag12",
               "precip_anom_lag16", "precip_anom_lag20",
               "temp_anom_lag4", "temp_anom_lag8", "temp_anom_lag12", "temp_anom_lag16",
               "soil_moisture_anom_lag4", "soil_moisture_anom_lag8",
               "soil_moisture_anom_lag12", "soil_moisture_anom_lag16",
               "soil_moisture_anom_lag20",
               "vpd_anom_lag4", "vpd_anom_lag8", "vpd_anom_lag12", "vpd_anom_lag16",
               # Teleconnection anomaly lags (4-24w; week-of-year deseasonalized)
               "IOD_anom_lag4", "IOD_anom_lag8", "IOD_anom_lag12",
               "IOD_anom_lag16", "IOD_anom_lag20", "IOD_anom_lag24",
               "ENSO3_anom_lag4", "ENSO3_anom_lag8", "ENSO3_anom_lag12",
               "ENSO3_anom_lag16", "ENSO3_anom_lag20", "ENSO3_anom_lag24",
               "ENSO34_anom_lag4", "ENSO34_anom_lag8", "ENSO34_anom_lag12",
               "ENSO34_anom_lag16", "ENSO34_anom_lag20", "ENSO34_anom_lag24",
               "ENSO4_anom_lag4", "ENSO4_anom_lag8", "ENSO4_anom_lag12",
               "ENSO4_anom_lag16", "ENSO4_anom_lag20", "ENSO4_anom_lag24",
               # ENSO3 (4-44w)
               "ENSO3_lag4", "ENSO3_lag8", "ENSO3_lag12", "ENSO3_lag16",
               "ENSO3_lag20", "ENSO3_lag24", "ENSO3_lag28", "ENSO3_lag32",
               "ENSO3_lag36", "ENSO3_lag40", "ENSO3_lag44",
               # ENSO34 (4-48w)
               "ENSO34_lag4", "ENSO34_lag8", "ENSO34_lag12", "ENSO34_lag16",
               "ENSO34_lag20", "ENSO34_lag24", "ENSO34_lag28", "ENSO34_lag32",
               "ENSO34_lag36", "ENSO34_lag40", "ENSO34_lag44", "ENSO34_lag48",
               # ENSO4 (4-44w)
               "ENSO4_lag4", "ENSO4_lag8", "ENSO4_lag12", "ENSO4_lag16",
               "ENSO4_lag20", "ENSO4_lag24", "ENSO4_lag28", "ENSO4_lag32",
               "ENSO4_lag36", "ENSO4_lag40", "ENSO4_lag44",
               # IOD (0-44w)
               "IOD_lag0", "IOD_lag4", "IOD_lag8", "IOD_lag12", "IOD_lag16",
               "IOD_lag20", "IOD_lag24", "IOD_lag28", "IOD_lag32",
               "IOD_lag36", "IOD_lag40", "IOD_lag44",
               # Flood probability anomaly (4-20w; populated after impute block below)
               "emdat_flood_prob_anom_lag4", "emdat_flood_prob_anom_lag8",
               "emdat_flood_prob_anom_lag12", "emdat_flood_prob_anom_lag16",
               "emdat_flood_prob_anom_lag20"
          )
     } else {
          lag_cols <- c()
     }
     
     # 17. Derived climate indices
     indices_cols <- c("vpd", "moisture_deficit", "aridity_index", "spei_approx",
                      "gdd_cholera", "diurnal_temp_range", "heat_index")
     
     # 18. Geographic
     geo_cols <- c("elevation", "latitude", "longitude", "region")
     
     # Combine all organized columns
     organized_cols <- c(base_cols, surveillance_meta_cols, temporal_cols, demo_cols,
                        health_cols, wash_cols,
                        enso_cols, basic_climate_cols, rolling_cols, anomaly_cols,
                        extremes_cols, memory_cols, spatial_cols, interaction_cols,
                        enhanced_interaction_cols, nonlinear_cols, lag_cols, indices_cols, geo_cols)
     
     # Get any remaining columns not explicitly categorized
     remaining_cols <- setdiff(names(d), organized_cols)
     
     # Final column order
     final_cols <- c(organized_cols, remaining_cols)
     
     # Only keep columns that actually exist in the data
     final_cols <- final_cols[final_cols %in% names(d)]
     
     d <- d[, final_cols]
     
     # Final validation message for forecast mode (vaccination,
     # epidemic-memory, and spatial-import blocks removed in v0.30.26)
     if (forecast_mode) {
          message(sprintf("  - Forecast mode validated: dataset ready for %d-month forecasting", forecast_horizon))
     }

     # Remove unnecessary objects from memory
     rm(cases_data, combined_climate_data, combined_climate_data_wide, enso_data, enso_data_wide)

     if (53 %in% d$week) stop("week index is out of bounds")

     # Generate comprehensive dataset statistics
     message("=== DATASET SUMMARY ===")
     
     # Basic dimensions
     n_countries <- length(unique(d$iso_code))
     n_observations <- nrow(d)
     n_covariates <- ncol(d) - 8  # Subtract base columns (iso_code, year, month, week, date, cases, cases_binary, deaths)
     
     # Date ranges
     # Overall dataset (covariates)
     covariate_date_start <- min(d$date, na.rm = TRUE)
     covariate_date_end <- max(d$date, na.rm = TRUE)
     covariate_span_years <- round(as.numeric(difftime(covariate_date_end, covariate_date_start, units = "days")) / 365.25, 1)
     
     # Observed case data (non-NA, non-zero cases only)
     case_data_dates <- d$date[!is.na(d$cases) & d$cases > 0]
     if (length(case_data_dates) > 0) {
          case_date_start <- min(case_data_dates)
          case_date_end <- max(case_data_dates)
          case_span_years <- round(as.numeric(difftime(case_date_end, case_date_start, units = "days")) / 365.25, 1)
     } else {
          case_date_start <- NA
          case_date_end <- NA
          case_span_years <- 0
     }
     
     # Countries list (abbreviated if many)
     countries_list <- sort(unique(d$iso_code))
     if (length(countries_list) <= 10) {
          countries_str <- paste(countries_list, collapse = ", ")
     } else {
          countries_str <- paste(paste(countries_list[1:8], collapse = ", "), 
                               sprintf("... and %d more", length(countries_list) - 8))
     }
     
     # Case statistics
     total_cases <- sum(d$cases, na.rm = TRUE)
     total_deaths <- sum(d$deaths, na.rm = TRUE)
     case_weeks <- sum(d$cases > 0, na.rm = TRUE)
     case_proportion <- round(case_weeks / n_observations * 100, 1)
     
     # Missing data assessment
     na_counts <- sapply(d, function(x) sum(is.na(x)))
     high_na_vars <- names(na_counts[na_counts > (nrow(d) * 0.1)])  # >10% missing
     high_na_count <- length(high_na_vars)
     
     # Variable categories count
     temporal_count <- length(temporal_cols)
     climate_count <- length(basic_climate_cols) + length(rolling_cols) + length(anomaly_cols) + 
                     length(extremes_cols) + length(indices_cols) + 
                     if(include_lags) length(lag_cols) else 0
     interaction_count <- length(interaction_cols) + length(enhanced_interaction_cols)
     
     # Print summary
     message(sprintf("Countries: %d (%s)", n_countries, countries_str))
     message(sprintf("Covariate period: %s to %s (%.1f years)", 
                    format(covariate_date_start, "%Y-%m-%d"), 
                    format(covariate_date_end, "%Y-%m-%d"), 
                    covariate_span_years))
     if (!is.na(case_date_start) && !is.na(case_date_end)) {
          message(sprintf("Observed case period: %s to %s (%.1f years)", 
                         format(case_date_start, "%Y-%m-%d"), 
                         format(case_date_end, "%Y-%m-%d"), 
                         case_span_years))
     } else {
          message("Observed case period: No non-zero cases found")
     }
     message(sprintf("Observations: %s total", format(n_observations, big.mark = ",")))
     message(sprintf("Cases: %s total cases, %s deaths", 
                    format(total_cases, big.mark = ","), 
                    format(total_deaths, big.mark = ",")))
     message(sprintf("Case weeks: %s (%.1f%% of observations)", 
                    format(case_weeks, big.mark = ","), case_proportion))
     message(sprintf("Covariates: %d total", n_covariates))
     message(sprintf("  - Temporal: %d", temporal_count))
     message(sprintf("  - Climate: %d", climate_count))
     message(sprintf("  - Demographics/Health: %d", length(demo_cols) + length(health_cols)))
     message(sprintf("  - WASH: %d", length(wash_cols)))
     message(sprintf("  - ENSO: %d", length(enso_cols)))
     message(sprintf("  - Interactions: %d", interaction_count))
     message(sprintf("  - Time lags: %d", if(include_lags) length(lag_cols) else 0))
     message(sprintf("  - Geographic: %d", length(geo_cols)))
     
     if (high_na_count > 0) {
          message(sprintf("Variables with >10%% missing data: %d", high_na_count))
     }
     
     # Mode-specific messages
     if (forecast_mode) {
          message(sprintf("MODE: Forecast (%d-month horizon)", forecast_horizon))
     } else {
          message("MODE: Historical analysis")
     }
     
     if (include_lags) {
          message("LAGS: Time-lagged climate variables included (1-36 week lags)")
     } else {
          message("LAGS: No time-lagged variables")
     }
     
     message("=======================")

     # Save the merged dataset to a CSV file
     path <- file.path(PATHS$DATA_CHOLERA_WEEKLY, 'cholera_country_weekly_suitability_data.csv')
     write.csv(d, file = path, row.names = FALSE)
     message("Processed suitability data saved here: ", path)
}
