#' Endemic Simulation Configuration
#'
#' A **multi-year endemic** parameter set that sustains low-level transmission
#' and produces recurring seasonal + quadrennial waves via environmental
#' persistence.
#' The object is generated by `make_simulation_endemic_config_files.R
#' (sim_endemic)` and saved in the package as **`config_simulation_endemic`**.
#'
#' @format A named **list** with the same structure as
#'   [config_default] but spanning five years of daily timesteps.
#'
#' @details
#' | Aspect | Setting |
#' | ------ | ------- |
#' | **Time span** | 1 Jan 2020 – 31 Dec 2024 (≈ 1 826 days). |
#' | **Locations** | “FOO” (8 k), “BAR” (12 k), “BAZ” (20 k). |
#' | **Initial mix** | 10 % susceptible, 30 % first-dose vaccinated, ~60 % recovered, ~0.1 % infectious (≥ 1 exposed and ≥ 1 infectious each site). |
#' | **Transmission** | Site-specific human-to-human β: **0.18**, **0.30**, **0.24**, plus environmental β of half those values, with a first-harmonic seasonal forcing of amplitude 0.2 and a random phase per site. |
#' | **Environment** | Suitability ψ<sub>jt</sub> = 0.45 + annual 0.25 sin (2π t/365 + φ<sub>j</sub>) + quadrennial 0.15 sin (2π t/1 460 + φ<sub>j</sub>/2), with a random phase φ<sub>j</sub> per site; values clipped to \[0,1\] (shipped range ≈ 0.06–0.85). `psi_star_*` are the identity. |
#' | **Environmental half-life** | `decay_days_long = 365` days (~1 year); `decay_days_short = 1`. |
#' | **Immunity waning** | ω₁ ≈ 1/180 d (0.0056), ω₂ ≈ 1/300 d (0.0033). |
#' | **Mobility** | τ<sub>i</sub> = 0.005, 0.002, 0.006 per day. |
#' | **Observed data** | `reported_cases` / `reported_deaths` hold one simulated realisation of the model itself (`run_simulation()` on this config), not real surveillance. |
#' | **Seed** | `set.seed(999999999)` for full reproducibility. |
#'
#' Together, the longer environmental survival and waning immunity allow
#' susceptibles to replenish, generating periodic endemic outbreaks without the
#' explosive dynamics of the epidemic toy set.
#'
#' @usage
#' config_simulation_endemic
#'
#' @seealso
#'   * [config_simulation_epidemic] – one-year outbreak scenario.
#'   * [config_default] – comprehensive default configuration.
#'   * `make_simulation_endemic_config_files.R (sim_endemic)` – generator script.
#'
#' @keywords datasets
"config_simulation_endemic"
