#' Download 1km DEM Raster for Multiple Countries and Save to Files
#'
#' This function downloads 1km resolution DEM (Digital Elevation Model) raster data for a given vector of ISO3 country codes, and writes each raster to a GeoTIFF file.
#'
#' @param PATHS A list containing paths where DEM data will be saved. Typically generated by the `get_paths()` function and should include:
#' \itemize{
#'   \item \strong{DATA_DEM}: Path to the directory where DEM rasters will be saved.
#' }
#' @param iso_codes A character vector of ISO3 country codes for which DEM data should be downloaded.
#' @param zoom_level An integer representing the zoom level for the DEM data. Zoom levels 6-8 are recommended for 1km resolution (default = 6).
#' @param overwrite If \code{FALSE} (default), a country whose DEM file already exists is skipped; \code{TRUE} re-downloads and replaces it.
#'
#' @return Invisibly, the paths of the DEM files that exist after the call. Each is written atomically (temporary file, then rename), so a failed or interrupted download never replaces a good raster.
#'
#' @details Terrain does not change between refreshes, and \code{PATHS$DATA_DEM} lives under
#' \code{MOSAIC-data/raw/}, so existing rasters are never rewritten unless \code{overwrite = TRUE}.
#'
#' @importFrom elevatr get_elev_raster
#' @importFrom sf st_bbox
#' @importFrom rnaturalearth ne_countries
#' @importFrom raster writeRaster
#' @importFrom glue glue
#' @examples
#' \dontrun{
#' # Define the ISO3 country codes
#' iso_codes <- c("ZAF", "KEN", "NGA")
#'
#' # Get paths for data storage
#' PATHS <- get_paths()
#'
#' # Download DEM rasters for the countries
#' download_country_DEM(PATHS, iso_codes)
#' }
#' @export

download_country_DEM <- function(PATHS, iso_codes, zoom_level = 6, overwrite = FALSE) {

     requireNamespace('sf')
     requireNamespace('raster')

     # Ensure the output directory exists
     if (!dir.exists(PATHS$DATA_DEM)) dir.create(PATHS$DATA_DEM, recursive = TRUE)


     out <- character(0)

     # Loop through each ISO3 country code
     for (i in seq_along(iso_codes)) {

          dem_filename <- file.path(PATHS$DATA_DEM, glue::glue("{iso_codes[i]}_1km_DEM.tif"))

          if (file.exists(dem_filename) && !overwrite) {
               message(glue::glue("DEM for {iso_codes[i]} already exists; skipping."))
               out <- c(out, dem_filename)
               next
          }

          # Construct the path to the shapefile for each country
          shapefile_path <- file.path(PATHS$DATA_SHAPEFILES, paste0(iso_codes[i], "_ADM0.shp"))

          # Check if the shapefile exists
          if (!file.exists(shapefile_path)) {
               message(paste("Shapefile for", iso_codes[i], "not found. Skipping."))
               next
          }

          # Load the country shapefile
          country_shapefile <- sf::st_read(shapefile_path, quiet = TRUE)

          if (is.null(country_shapefile) || nrow(country_shapefile) == 0) {
               message(glue::glue("Skipping {iso_codes[i]}: shapefile not found."))
               next
          }

          message(glue::glue("Downloading DEM for {iso_codes[i]}..."))

          # Download the DEM data for the country's bounding box
          dem_raster <- elevatr::get_elev_raster(locations = country_shapefile, z = zoom_level, clip = "bbox")

          # Save atomically so an interrupted write cannot leave a truncated GeoTIFF
          .write_file_atomic(dem_filename, function(tmp) {
               raster::writeRaster(dem_raster, filename = tmp, format = "GTiff", overwrite = TRUE)
          })

          message(glue::glue("DEM for {iso_codes[i]} saved to {dem_filename}."))
          out <- c(out, dem_filename)
     }

     message(glue::glue("DEM data saved for all countries in {PATHS$DATA_DEM}."))
     invisible(out)
}
