#' Download 1km DEM Raster for Multiple Countries and Save to Files
#'
#' This function downloads 1km resolution DEM (Digital Elevation Model) raster data for a given vector of ISO3 country codes, and writes each raster to a GeoTIFF file.
#'
#' @param PATHS A list containing paths where DEM data will be saved. Typically generated by the `get_paths()` function and should include:
#' \itemize{
#'   \item \strong{DATA_DEM}: Path to the directory where DEM rasters will be saved.
#' }
#' @param iso_codes A character vector of ISO3 country codes for which DEM data should be downloaded.
#' @param zoom_level An integer representing the zoom level for the DEM data. Zoom levels 6-8 are recommended for 1km resolution (default = 6).
#'
#' @return The function does not return a value. It downloads the DEM data for each country and saves the results as GeoTIFF files in the specified directory.
#'
#' @importFrom elevatr get_elev_raster
#' @importFrom sf st_bbox
#' @importFrom rnaturalearth ne_countries
#' @importFrom raster writeRaster
#' @importFrom glue glue
#' @examples
#' \dontrun{
#' # Define the ISO3 country codes
#' iso_codes <- c("ZAF", "KEN", "NGA")
#'
#' # Get paths for data storage
#' PATHS <- get_paths()
#'
#' # Download DEM rasters for the countries
#' download_country_DEM(iso_codes, PATHS)
#' }
#' @export

download_country_DEM <- function(PATHS, iso_codes, zoom_level = 6) {

     requireNamespace('sf')
     requireNamespace('raster')

     # Ensure the output directory exists
     if (!dir.exists(PATHS$DATA_DEM)) dir.create(PATHS$DATA_DEM, recursive = TRUE)


     # Loop through each ISO3 country code
     for (i in 1:length(iso_codes)) {

          message(glue::glue("Downloading DEM for {iso_codes[i]}..."))

          # Construct the path to the shapefile for each country
          shapefile_path <- file.path(PATHS$DATA_SHAPEFILES, paste0(iso_codes[i], "_ADM0.shp"))

          # Check if the shapefile exists
          if (!file.exists(shapefile_path)) {
               message(paste("Shapefile for", iso_codes[i], "not found. Skipping."))
               next
          }

          # Load the country shapefile
          country_shapefile <- sf::st_read(shapefile_path, quiet = TRUE)


          if (is.null(country_shapefile) || nrow(country_shapefile) == 0) {
               message(glue::glue("Skipping {iso_codes[i]}: shapefile not found."))
               next
          }

          # Download the DEM data for the country's bounding box
          dem_raster <- elevatr::get_elev_raster(locations = country_shapefile, z = zoom_level, clip = "bbox")

          # Create a filename for the DEM file
          dem_filename <- file.path(PATHS$DATA_DEM, glue::glue("{iso_codes[i]}_1km_DEM.tif"))

          # Save the DEM raster as a GeoTIFF file
          raster::writeRaster(dem_raster, filename = dem_filename, format = "GTiff", overwrite = TRUE)

          message(glue::glue("DEM for {iso_codes[i]} saved to {dem_filename}."))

     }

     message(glue::glue("DEM data saved for all countries in {PATHS$DATA_DEM}."))
}
