#' Estimate Vaccine Effectiveness Decay Model
#'
#' This function fits a proportional decay model to vaccine effectiveness data and estimates the parameters of the model, saving the results to CSV files. The model assumes that vaccine effectiveness decays over time according to a proportional decay function. Additionally, it fits a beta distribution to the initial vaccine effectiveness to capture the uncertainty in the estimate.
#'
#' @param PATHS A list containing the paths where the parameter data and predictions will be saved. Typically generated by the `get_paths()` function and should include:
#' \itemize{
#'   \item \strong{MODEL_INPUT}: Path to the directory where the parameter estimates and predictions will be saved.
#'   \item \strong{DATA_VACCINE_EFFECTIVENESS}: Path to the directory where vaccine effectiveness data is located.
#' }
#'
#' @details
#' The function uses a non-linear least squares (NLS) approach, specifically the Levenberg-Marquardt algorithm from the `nls.lm` function in the `minpack.lm` package, to fit the vaccine effectiveness decay model. The model is defined by two parameters:
#' \itemize{
#'   \item \strong{\eqn{\phi}}: Initial vaccine effectiveness at time zero.
#'   \item \strong{\eqn{\omega}}: Decay rate of vaccine effectiveness over time.
#' }
#'
#' The standard errors for the parameter estimates are extracted from the covariance matrix of the fitted model. Confidence intervals for the initial vaccine effectiveness are used to fit a beta distribution to capture uncertainty in the estimate.
#'
#' After fitting the model, the function generates a prediction of vaccine effectiveness over time and saves the predictions, along with the parameter estimates and beta distribution parameters, to CSV files in the specified `MODEL_INPUT` directory.
#'
#' @return The function does not return any values but saves the following CSV files:
#' \itemize{
#'   \item `param_vaccine_effectiveness.csv`: Parameter estimates for the initial vaccine effectiveness and decay rate, including beta distribution parameters for uncertainty.
#'   \item `pred_vaccine_effectiveness.csv`: Predicted vaccine effectiveness over time (days after vaccination).
#' }
#'
#' @examples
#' \dontrun{
#' # Assuming PATHS is generated from get_paths()
#' PATHS <- get_paths()
#'
#' # Estimate vaccine effectiveness and save results
#' est_vaccine_effectiveness(PATHS)
#' }
#'
#' @importFrom minpack.lm nls.lm
#' @importFrom utils read.csv write.csv
#' @importFrom stats vcov quantile rbeta
#' @export


est_vaccine_effectiveness <- function(PATHS) {

     requireNamespace("minpack.lm")

     # Load vaccine effectiveness data
     df <- read.csv(file.path(PATHS$DATA_VACCINE_EFFECTIVENESS, "vaccine_effectiveness_data.csv"), stringsAsFactors = FALSE)

     proportional_decay_function <- function(par, x) {
          a <- par[1]
          b <- par[2]
          a * (1 - b) ^ x
     }

     objective_function <- function(par) {
          residuals <- df$effectiveness - proportional_decay_function(par, df$day)
          residuals
     }


     starting_values <- c(a = 0.7, b = 0.001)  # a is the initial immune proportion, b is the decay rate

     fit <- minpack.lm::nls.lm(par = starting_values,
                               fn = objective_function,
                               upper = c(1, 1),
                               lower = c(0, 0),
                               control = nls.lm.control(maxiter = 1000)  # Increase max iterations to 10000
     )

     cov_matrix <- vcov(fit)
     se <- sqrt(diag(cov_matrix))

     fitted_parameters <- fit$par
     fitted_parameters_hi <- c(fit$par[1]+1.96*se[1], fit$par[2])
     fitted_parameters_lo <- c(fit$par[1]-1.96*se[1], fit$par[2])
     print(fitted_parameters)



     # Get beta distribution for vaccine effectiveness
     quants <- c(0.02775, 0.5, 0.974)
     probs <- c(fitted_parameters_lo[1], fitted_parameters[1], fitted_parameters_hi[1])
     prm <- get_beta_params(quantiles=quants, probs=probs)
     samps <- rbeta(1000, shape1 = prm$shape1, shape2 = prm$shape2)
     ci <- quantile(samps, probs = c(0.025, 0.975))


     param_df_omega <- make_param_df(
          variable_name = "omega",
          variable_description = "Waning rate of vaccine derived immunity",
          parameter_distribution = "point",
          parameter_name = "mean",
          parameter_value = fitted_parameters['b']
     )

     path <- file.path(PATHS$MODEL_INPUT, "param_omega_vaccine_effectiveness.csv")
     write.csv(param_df_omega, path, row.names = FALSE)
     message(paste("Parameter data frame for vaccine derived immune decay (omega) saved to:", path))


     param_df_phi <- make_param_df(
          variable_name = "phi",
          variable_description = "Initial vaccine effectiveness",
          parameter_distribution = "point",
          parameter_name = "mean",
          parameter_value = fitted_parameters['a']
     )

     param_df_phi_stoch <- make_param_df(
          variable_name = "phi",
          variable_description = "Initial vaccine effectiveness",
          parameter_distribution = "beta",
          parameter_name = c("shape1", "shape2"),
          parameter_value = c(prm$shape1, prm$shape2)
     )


     param_df <- rbind(param_df_phi, param_df_phi_stoch)

     path <- file.path(PATHS$MODEL_INPUT, "param_phi_vaccine_effectiveness.csv")
     write.csv(param_df, path, row.names = FALSE)
     message(paste("Parameter data frame for vaccine effectiveness (phi) saved to:", path))


     # Produce predicted decay function across all days after infection

     prediction <- data.frame(day = seq(0, 365*10, by = 1))
     prediction$predicted <- proportional_decay_function(fitted_parameters, prediction$day)
     prediction$predicted_lo <- proportional_decay_function(fitted_parameters_lo, prediction$day)
     prediction$predicted_hi <- proportional_decay_function(fitted_parameters_hi, prediction$day)
     head(prediction)


     path <- file.path(PATHS$MODEL_INPUT, "pred_vaccine_effectiveness.csv")
     write.csv(prediction, path, row.names = FALSE)
     message(paste("Predicted vaccine effectiveness (days after infection) saved to:", path))


}
