#' Estimate Vaccine Immune Decay
#'
#' This function estimates oral cholera vaccine (OCV) immune decay by fitting exponential decay models
#' to meta-regression effectiveness data from Xu et al (2024). It estimates decay parameters (omega) and
#' initial effectiveness (phi) for both one-dose and two-dose regimens, and generates plots for predicted
#' vaccine effectiveness over time.
#'
#' @param PATHS A list containing the paths where data and figures are saved. Typically generated by the `get_paths()` function and should include:
#' \itemize{
#'   \item \strong{MODEL_INPUT}: Path to the directory where parameter files will be saved.
#'   \item \strong{DOCS_FIGURES}: Path to the directory where the plots will be saved.
#' }
#'
#' @references Xu et al. (2024). Effectiveness of Oral Cholera Vaccines: A Systematic Review and Meta-Analysis.
#' medRxiv. https://doi.org/10.1101/2024.08.13.24311930v2
#'
#' @importFrom minpack.lm nls.lm nls.lm.control
#' @importFrom ggplot2 ggplot aes geom_ribbon geom_line geom_point geom_errorbar annotate labs theme_classic scale_y_continuous scale_x_continuous scale_color_manual
#' @importFrom cowplot plot_grid
#' @examples
#' \dontrun{
#' # Assuming PATHS is generated from get_paths()
#' PATHS <- get_paths()
#' est_vaccine_immune_decay(PATHS)
#' }
#' @export

est_immune_decay_vaccine <- function(PATHS) {

     # Create vaccine effectiveness data from Xu et al (2024) meta-regression
     # Two-dose OCV effectiveness
     two_dose_data <- data.frame(
          months = c(12, 24, 36, 48),
          days = c(12, 24, 36, 48) * 30.5,
          effectiveness = c(0.68, 0.60, 0.53, 0.47),
          effectiveness_lo = c(0.58, 0.40, 0.24, 0.09),
          effectiveness_hi = c(0.78, 0.73, 0.71, 0.70),
          dose_regimen = "Two-dose OCV",
          source = "Xu et al (2024)"
     )

     # One-dose OCV effectiveness
     one_dose_data <- data.frame(
          months = c(6, 12, 18, 24, 30),
          days = c(6, 12, 18, 24, 30) * 30.5,
          effectiveness = c(0.70, 0.60, 0.53, 0.47, 0.42),
          effectiveness_lo = c(0.60, 0.51, 0.42, 0.34, 0.26),
          effectiveness_hi = c(0.77, 0.68, 0.62, 0.58, 0.55),
          dose_regimen = "One-dose OCV",
          source = "Xu et al (2024)"
     )

     # Define exponential decay function for vaccine effectiveness
     # VE(t) = phi * exp(-omega * t) where t is days since vaccination
     exponential_decay_function <- function(par, x) {
          phi <- par[1]    # Initial effectiveness
          omega <- par[2]  # Decay rate per day
          phi * exp(-omega * x)
     }

     # Function to fit exponential decay model with constraints
     fit_vaccine_decay <- function(data, dose_name) {

          # Starting values for model parameters
          start_values <- c(phi = 0.80, omega = 0.0005)

          # Objective function to minimize residuals
          objective_function <- function(par, x, y) {
               predicted <- exponential_decay_function(par, x)
               residuals <- y - predicted
               residuals
          }

          # Fit model for mean effectiveness
          fit_mean <- nls.lm(par = start_values,
                            fn = objective_function,
                            x = data$days,
                            y = data$effectiveness,
                            control = nls.lm.control(maxiter = 10000))

          # Fit model for upper CI
          # Constrain phi to [0, 1], leave omega unconstrained (use large bounds)
          fit_hi <- nls.lm(par = start_values,
                          fn = objective_function,
                          x = data$days,
                          y = data$effectiveness_hi,
                          upper = c(1.0, Inf),  # phi <= 1, omega unconstrained
                          lower = c(fit_mean$par[1], 0),     # phi >= 0, omega >= 0
                          control = nls.lm.control(maxiter = 10000))

          # Fit model for lower CI
          fit_lo <- nls.lm(par = start_values,
                          fn = objective_function,
                          x = data$days,
                          y = data$effectiveness_lo,
                          upper = c(fit_mean$par[1] - (fit_hi$par[1] - fit_mean$par[1]), Inf),  # phi <= 1, omega unconstrained
                          lower = c(0.0, 0),     # phi >= 0, omega >= 0
                          control = nls.lm.control(maxiter = 10000))



          # Return fitted parameters directly without constraints
          return(list(
               mean = fit_mean$par,
               lo = fit_lo$par,
               hi = fit_hi$par,
               dose = dose_name
          ))
     }

     # Fit models for both dose regimens
     fit_one_dose <- fit_vaccine_decay(one_dose_data, "one_dose")
     fit_two_dose <- fit_vaccine_decay(two_dose_data, "two_dose")

     # Create prediction data frames for both dose regimens
     days_predict <- seq(0, 365*5, by = 1)  # Predict up to 5 years

     # One-dose predictions
     prediction_one_dose <- data.frame(
          day = days_predict,
          predicted = exponential_decay_function(fit_one_dose$mean, days_predict),
          predicted_lo = exponential_decay_function(fit_one_dose$lo, days_predict),
          predicted_hi = exponential_decay_function(fit_one_dose$hi, days_predict),
          dose_regimen = "One-dose OCV"
     )

     # Two-dose predictions
     prediction_two_dose <- data.frame(
          day = days_predict,
          predicted = exponential_decay_function(fit_two_dose$mean, days_predict),
          predicted_lo = exponential_decay_function(fit_two_dose$lo, days_predict),
          predicted_hi = exponential_decay_function(fit_two_dose$hi, days_predict),
          dose_regimen = "Two-dose OCV"
     )

     # Calculate gamma distribution parameters for omega_1 and omega_2
     # Based on our analysis: mode = (shape - 1) / rate

     # omega_1 (one-dose waning rate)
     omega_1_mode <- fit_one_dose$mean[2]  # Use fitted omega as mode
     omega_1_shape <- 5.26  # From our prior analysis
     omega_1_rate <- (omega_1_shape - 1) / omega_1_mode

     # omega_2 (two-dose waning rate)
     omega_2_mode <- fit_two_dose$mean[2]  # Use fitted omega as mode
     omega_2_shape <- 2.5  # From our prior analysis
     omega_2_rate <- (omega_2_shape - 1) / omega_2_mode

     # Create parameter data frames
     # One-dose parameters
     param_df_omega_1 <- make_param_df(
          variable_name = 'omega_1',
          variable_description = 'Vaccine waning rate (one dose)',
          parameter_distribution = c('point', 'point', 'point', 'gamma', 'gamma'),
          parameter_name = c('low', 'mean', 'high', 'shape', 'rate'),
          parameter_value = c(fit_one_dose$lo[2], fit_one_dose$mean[2], fit_one_dose$hi[2],
                            omega_1_shape, omega_1_rate)
     )

     param_df_phi_1 <- make_param_df(
          variable_name = 'phi_1',
          variable_description = 'Initial vaccine effectiveness (one dose)',
          parameter_distribution = c('point', 'point', 'point'),
          parameter_name = c('low', 'mean', 'high'),
          parameter_value = c(fit_one_dose$lo[1], fit_one_dose$mean[1], fit_one_dose$hi[1])
     )

     # Two-dose parameters
     param_df_omega_2 <- make_param_df(
          variable_name = 'omega_2',
          variable_description = 'Vaccine waning rate (two dose)',
          parameter_distribution = c('point', 'point', 'point', 'gamma', 'gamma'),
          parameter_name = c('low', 'mean', 'high', 'shape', 'rate'),
          parameter_value = c(fit_two_dose$lo[2], fit_two_dose$mean[2], fit_two_dose$hi[2],
                            omega_2_shape, omega_2_rate)
     )

     param_df_phi_2 <- make_param_df(
          variable_name = 'phi_2',
          variable_description = 'Initial vaccine effectiveness (two dose)',
          parameter_distribution = c('point', 'point', 'point'),
          parameter_name = c('low', 'mean', 'high'),
          parameter_value = c(fit_two_dose$lo[1], fit_two_dose$mean[1], fit_two_dose$hi[1])
     )

     param_df <- rbind(param_df_omega_1, param_df_phi_1, param_df_omega_2, param_df_phi_2)

     # Save parameter files
     path <- file.path(PATHS$MODEL_INPUT, "param_vaccine_effectiveness.csv")
     #write.csv(param_df, path, row.names = FALSE)
     message(paste("Vaccine effectiveness parameters (omega_1, omega_2, phi_1, phi_2) saved to:", path))

     # Combine predictions and save
     prediction_combined <- rbind(prediction_one_dose, prediction_two_dose)
     path <- file.path(PATHS$MODEL_INPUT, "pred_vaccine_effectiveness.csv")
     #write.csv(prediction_combined, path, row.names = FALSE)
     message(paste("Predicted vaccine effectiveness over time saved to:", path))

     # Print summary statistics
     cat("\n=== FITTED VACCINE PARAMETERS ===\n")
     cat("One-dose OCV:\n")
     cat(sprintf("  phi_1 (initial effectiveness): %.3f [%.3f, %.3f]\n",
                 fit_one_dose$mean[1], fit_one_dose$lo[1], fit_one_dose$hi[1]))
     cat(sprintf("  omega_1 (waning rate/day): %.6f [%.6f, %.6f]\n",
                 fit_one_dose$mean[2], fit_one_dose$lo[2], fit_one_dose$hi[2]))
     cat(sprintf("  Half-life: %.1f days\n", log(2)/fit_one_dose$mean[2]))

     cat("\nTwo-dose OCV:\n")
     cat(sprintf("  phi_2 (initial effectiveness): %.3f [%.3f, %.3f]\n",
                 fit_two_dose$mean[1], fit_two_dose$lo[1], fit_two_dose$hi[1]))
     cat(sprintf("  omega_2 (waning rate/day): %.6f [%.6f, %.6f]\n",
                 fit_two_dose$mean[2], fit_two_dose$lo[2], fit_two_dose$hi[2]))
     cat(sprintf("  Half-life: %.1f days\n", log(2)/fit_two_dose$mean[2]))
     cat("\n")



     # Define modern colors
     green_fill <- "#90EE90"  # Light green for ribbon
     green_line <- "#228B22"  # Forest green for lines
     blue_fill <- "#87CEEB"   # Sky blue for ribbon
     blue_line <- "#4169E1"   # Royal blue for lines

     # Plot 1: One-dose OCV effectiveness over time
     p1 <-
          ggplot() +
          geom_ribbon(data = prediction_one_dose,
                     aes(x = day, ymin = predicted_lo, ymax = predicted_hi),
                     fill = green_fill, alpha = 0.4) +
          geom_line(data = prediction_one_dose,
                   aes(x = day, y = predicted),
                   color = green_line, linewidth = 1.5) +
          geom_line(data = prediction_one_dose,
                   aes(x = day, y = predicted_lo),
                   color = green_line, linewidth = 0.75, linetype='dashed', alpha = 0.7) +
          geom_line(data = prediction_one_dose,
                   aes(x = day, y = predicted_hi),
                   color = green_line, linewidth = 0.75, linetype='dashed', alpha = 0.7) +
          # Data points with error bars in black
          geom_errorbar(data = one_dose_data,
                       aes(x = days, ymin = effectiveness_lo, ymax = effectiveness_hi),
                       width = 0, color = "black", alpha = 0.8) +
          geom_point(data = one_dose_data,
                    aes(x = days, y = effectiveness),
                    color = "black", size = 3) +
          # Annotations
          annotate("text", x = 365 * 4, y = 0.15,
                  label = sprintf("One-dose OCV\nphi = %.3f\nomega = %.5f\nHalf-life = %.0f days",
                                  fit_one_dose$mean[1], fit_one_dose$mean[2],
                                  log(2)/fit_one_dose$mean[2]),
                  color = green_line, size = 4.5, hjust = 0, fontface = "bold") +
          labs(x = "Years after vaccination",
               y = "Vaccine effectiveness",
               title = "One-dose OCV") +
          theme_classic(base_size = 16) +
          theme(panel.grid.minor = element_blank(),
                panel.grid.major.y = element_line(color = "gray90", linetype = "dotted"),
                axis.title.x = element_text(margin = margin(t = 10)),
                axis.title.y = element_text(margin = margin(r = 10)),
                plot.title = element_text(size = 18, face = "bold", hjust = 0.5)) +
          scale_y_continuous(limits = c(0, 1), expand = c(0, 0),
                           breaks = seq(0, 1, 0.2)) +
          scale_x_continuous(limits = c(0, 365*5),
                           labels = 0:5,
                           breaks = 365 * (0:5),
                           expand = c(0, 0))

     # Plot 2: Two-dose OCV effectiveness over time
     p2 <-
          ggplot() +
          geom_ribbon(data = prediction_two_dose,
                     aes(x = day, ymin = predicted_lo, ymax = predicted_hi),
                     fill = blue_fill, alpha = 0.4) +
          geom_line(data = prediction_two_dose,
                   aes(x = day, y = predicted),
                   color = blue_line, linewidth = 1.5) +
          geom_line(data = prediction_two_dose,
                   aes(x = day, y = predicted_lo),
                   color = blue_line, linewidth = 0.75, linetype='dashed', alpha = 0.7) +
          geom_line(data = prediction_two_dose,
                   aes(x = day, y = predicted_hi),
                   color = blue_line, linewidth = 0.75, linetype='dashed', alpha = 0.7) +
          # Data points with error bars in black
          geom_errorbar(data = two_dose_data,
                       aes(x = days, ymin = effectiveness_lo, ymax = effectiveness_hi),
                       width = 0, color = "black", alpha = 0.8) +
          geom_point(data = two_dose_data,
                    aes(x = days, y = effectiveness),
                    color = "black", size = 3) +
          # Annotations
          annotate("text", x = 365 * 4, y = 0.15,
                  label = sprintf("Two-dose OCV\nphi = %.3f\nomega = %.5f\nHalf-life = %.0f days",
                                  fit_two_dose$mean[1], fit_two_dose$mean[2],
                                  log(2)/fit_two_dose$mean[2]),
                  color = blue_line, size = 4.5, hjust = 0, fontface = "bold") +
          labs(x = "Years after vaccination",
               y = "Vaccine effectiveness",
               title = "Two-dose OCV") +
          theme_classic(base_size = 16) +
          theme(panel.grid.minor = element_blank(),
                panel.grid.major.y = element_line(color = "gray90", linetype = "dotted"),
                axis.title.x = element_text(margin = margin(t = 10)),
                axis.title.y = element_text(margin = margin(r = 10)),
                plot.title = element_text(size = 18, face = "bold", hjust = 0.5)) +
          scale_y_continuous(limits = c(0, 1), expand = c(0, 0),
                           breaks = seq(0, 1, 0.2)) +
          scale_x_continuous(limits = c(0, 365*5),
                           labels = 0:5,
                           breaks = 365 * (0:5),
                           expand = c(0, 0))



     # Removed plots 3 and 4 as requested

     # Combine the plots in 2 rows
     combo <- cowplot::plot_grid(p1, p2,
                                 nrow = 2, ncol = 1,
                                 align = "v",
                                 rel_heights = c(1, 1))

     print(combo)

     # Save the combined plot
     plot_output_path <- file.path(PATHS$DOCS_FIGURES, "vaccine_effectiveness_decay.png")
     ggplot2::ggsave(plot_output_path, plot = combo, width = 3000, height = 2400, units = "px", dpi = 300)

     message(paste("Vaccine effectiveness decay plot saved to:", plot_output_path))

}
