#' Estimate Prior Distribution for Asymptomatic Shedding Rate (zeta_2)
#'
#' Compiles a meta-analysis of published *Vibrio cholerae* asymptomatic
#' shedding anchors (stool concentration x normal daily stool mass) and fits
#' a lognormal prior on the per-person-per-day asymptomatic shedding rate
#' used in the MOSAIC environmental reservoir update:
#' \deqn{W(t+1) \mathrel{+}= (1 - \theta_j) \cdot \mathrm{Poisson}(\zeta_2 \cdot I_{\mathrm{asym}})}
#' so \eqn{\zeta_2} is the expected total *V. cholerae* cells shed per
#' asymptomatic infected person per day during the shedding phase.
#'
#' The function assembles a small literature table of per-person-per-day
#' asymptomatic shedding anchors. The evidence base is thin: Nelson 2009
#' gives the only verbatim primary-source anchor
#' ("approximately 10^3 vibrios per gram of stool") and Kaper 1995 provides
#' an expert-review range (10^3 to 10^5 cells per gram). Given this single
#' primary source, the fit applies a hard floor `sdlog >= 2.0` to honestly
#' reflect that \eqn{n_{\mathrm{independent}} = 1}.
#'
#' @param PATHS A list of paths generated by `get_paths()`. Must include:
#' \itemize{
#'   \item \strong{MODEL_INPUT}: directory where parameter CSVs are saved.
#'   \item \strong{DOCS_FIGURES}: directory where the summary figure is saved.
#' }
#'
#' @return Invisibly returns a list with elements:
#' \itemize{
#'   \item \code{data}: the source meta-analysis table.
#'   \item \code{fit}: fitted lognormal parameters (\code{meanlog}, \code{sdlog},
#'         \code{median}, \code{mode}, \code{mean}, \code{ci_lower},
#'         \code{ci_upper}, \code{n_sources}, \code{mu_log10}, \code{sd_log10}).
#'   \item \code{param_df}: long-format parameter data frame (as saved to disk).
#'   \item \code{prediction}: density grid on linear and log10-x scales.
#'   \item \code{sensitivity}: a `leave_nelson_out` sub-fit that uses only
#'         the Kaper review rows (`n_primary_sources = 0`, published as a
#'         warning).
#' }
#'
#' @details
#' \strong{Assembly equation.} Each entry contributes
#' \eqn{\zeta_{2,i} = c_i \times V_i} with `V = 150 g/day` taken from
#' normal adult physiology (100-250 g/day); no cholera-specific
#' asymptomatic stool-volume measurement exists.
#'
#' \strong{Single-source caveat and sdlog floor.} The central anchor rests
#' on a single primary source (Nelson 2009). The fit applies a hard floor
#' `sdlog >= 2.0` (raised from 1.5 in rev 1 per modeller review). The floor
#' preserves the lognormal median (meanlog is unchanged); the mode shifts
#' left as a consequence. With the median at ~1.5e5 and sdlog = 2.0 the
#' 95 percent CI spans roughly 3e3 to 7.6e6 - factor ~50 on each side - which
#' is the correct spread to cover a +/- 1 order-of-magnitude error in the
#' single primary source.
#'
#' \strong{King 2008 caveat (documentation only).} King, Ionides, Pascual &
#' Bouma (2008) describe "a negligible quantity of vibrio" shed by
#' asymptomatic hosts in their natural-vaccination model. This is
#' qualitative and directionally supports a small `zeta_2` / large
#' `zeta_ratio`, but it does not give a quantitative value. It is therefore
#' NOT included as a fitted row - treating a qualitative claim as
#' quantitative data would masquerade ignorance as evidence. See
#' `claude/zeta_priors_update/zeta_sources/12_King_2008_Nature_inapparent.md`.
#'
#' \strong{Leave-Nelson-out sensitivity.} `$sensitivity$leave_nelson_out`
#' returns the fit using only the Kaper review rows. This fit has effective
#' `n_primary_sources = 0` (Kaper is a review that cites Nelson-era primary
#' data) and is published as a warning, not a usable prior.
#'
#' \strong{n_sources caveat.} The returned `$fit$n_sources` equals
#' `nrow(fit_df)` = 3 (Nelson, Kaper-lower, Kaper-upper). The effective
#' number of *independent primary sources* is 1 (Nelson 2009); Kaper 1995
#' is a review that does not contribute independent primary data. The
#' sdlog-floor mechanism encodes this single-source risk regardless of
#' the `n_sources` count.
#'
#' \strong{Per-day vs per-infection.} `zeta_2` is a per-day shedding rate
#' during asymptomatic infection; \eqn{\gamma_2^{-1}} (~2 d) governs the
#' duration. Nelson's verbatim claim is that asymptomatic shedding lasts
#' "only one day" -- close to the current `gamma_2` prior. Cumulative
#' cells per asymptomatic infection is `zeta_2 / gamma_2`.
#'
#' \strong{Relation to documented priors.} Earlier MOSAIC-docs narrative
#' states `zeta_2 ~ Uniform(0.01, 10^3)`. That range derives from the
#' Frame-B calibration rescaling and is superseded by this lognormal
#' literature-derived prior, whose 95\% CI extends to ~10^7.
#'
#' @references
#' \itemize{
#'   \item Nelson EJ, Harris JB, Morris JG, Calderwood SB, Camilli A (2009).
#'         Cholera transmission: the host, pathogen and bacteriophage dynamic.
#'         *Nat Rev Microbiol* 7(10):693-702. *("Asymptomatic patients typically
#'         shed vibrios for only one day at approximately 10^3 vibrios per
#'         gram of stool.")*
#'   \item Kaper JB, Morris JG, Levine MM (1995). Cholera. *Clin Microbiol Rev*
#'         8(1):48-86. *(expert review range 10^3 to 10^5 cells per gram)*
#'   \item King AA, Ionides EL, Pascual M, Bouma MJ (2008). Inapparent
#'         infections and cholera dynamics. *Nature* 454(7206):877-80.
#'         *(qualitative only; not a fitted row)*
#' }
#'
#' @examples
#' \dontrun{
#' PATHS <- get_paths()
#' est_zeta_2_prior(PATHS)
#' }
#'
#' @importFrom stats dlnorm qlnorm weighted.mean dnorm
#' @importFrom utils write.csv
#' @importFrom ggplot2 ggplot aes geom_point geom_errorbar geom_vline geom_line
#'             geom_ribbon geom_hline geom_rug scale_x_log10 scale_y_continuous
#'             scale_color_manual scale_fill_manual scale_size_continuous
#'             scale_alpha_manual labs theme_classic theme element_text
#'             element_line element_blank annotation_logticks annotate margin
#' @importFrom cowplot plot_grid
#' @importFrom grDevices png dev.off
#' @export

est_zeta_2_prior <- function(PATHS) {

     requireNamespace("ggplot2")
     requireNamespace("cowplot")

     #--------------------------------------------------------------------------
     # 1. Literature meta-analysis table
     #
     # V = 150 g/day normal stool mass from general physiology (100-250 g/day);
     # no cholera-specific asymptomatic volume data.
     #--------------------------------------------------------------------------

     data_df <- data.frame(
          source         = c("Nelson 2009 (primary)",
                             "Kaper 1995 (asymp range low)",
                             "Kaper 1995 (asymp range high)",
                             "Levine & Robins-Browne 2012"),
          author_year    = c("Nelson et al. 2009",
                             "Kaper, Morris & Levine 1995",
                             "Kaper, Morris & Levine 1995",
                             "Levine & Robins-Browne 2012"),
          # Stool concentration (cells per gram)
          c              = c(1e3, 1e3, 1e5, NA),
          # Stool mass (g per day)
          V              = c(150, 150, 150, NA),
          # Point estimate of zeta_2 (cells per person per day)
          zeta_2         = c(1.5e5, 1.5e5, 1.5e7, NA),
          zeta_2_lo      = c(1.5e3, 1e4, 1e6, NA),
          zeta_2_hi      = c(1.5e7, 1e6, 1e8, NA),
          weight         = c(1.00, 0.25, 0.25, 0.00),
          study_type     = c("Expert review", "Expert review",
                             "Expert review", "Expert review"),
          notes          = c("Only primary anchor; verbatim 'approximately 10^3 vibrios per gram of stool'",
                             "Review; overlaps Nelson primary - weight 0.25 avoids double-counting",
                             "Review range upper bound",
                             "Mechanism review; no cholera-specific CFU data (Excluded)"),
          stringsAsFactors = FALSE
     )

     #--------------------------------------------------------------------------
     # 2. Weighted lognormal fit on log10 scale
     #--------------------------------------------------------------------------

     fit_df <- data_df[data_df$weight > 0, ]
     stopifnot("All literature rows have weight 0" = sum(fit_df$weight) > 0)

     log10_zeta <- log10(fit_df$zeta_2)
     w          <- fit_df$weight

     mu_log10    <- stats::weighted.mean(log10_zeta, w)
     var_log10   <- sum(w * (log10_zeta - mu_log10)^2) / sum(w)
     sigma_log10 <- sqrt(var_log10)

     if (!is.finite(sigma_log10) || sigma_log10 <= 0) {
          message("est_zeta_2_prior: weighted variance is zero; ",
                  "using sigma_log10 = 0.5 fallback (will be raised by sdlog floor).")
          sigma_log10 <- 0.5
     }

     meanlog <- mu_log10    * log(10)
     sdlog   <- sigma_log10 * log(10)

     # Hard sdlog floor for single-primary-source risk. The floor preserves
     # the lognormal median; the mode shifts left as a consequence.
     sdlog_floor <- 2.0
     if (sdlog < sdlog_floor) {
          message("est_zeta_2_prior: sdlog raised from ",
                  round(sdlog, 3), " to floor ", sdlog_floor,
                  " due to single-primary-source risk (Nelson 2009).")
          sdlog       <- sdlog_floor
          sigma_log10 <- sdlog / log(10)
     }

     lognormal_median <- exp(meanlog)
     lognormal_mode   <- exp(meanlog - sdlog^2)
     lognormal_mean   <- exp(meanlog + sdlog^2 / 2)
     ci_lower         <- stats::qlnorm(0.025, meanlog = meanlog, sdlog = sdlog)
     ci_upper         <- stats::qlnorm(0.975, meanlog = meanlog, sdlog = sdlog)

     fit <- list(
          meanlog    = meanlog,
          sdlog      = sdlog,
          median     = lognormal_median,
          mode       = lognormal_mode,
          mean       = lognormal_mean,
          ci_lower   = ci_lower,
          ci_upper   = ci_upper,
          n_sources  = nrow(fit_df),
          mu_log10   = mu_log10,
          sd_log10   = sigma_log10
     )

     #--------------------------------------------------------------------------
     # 2b. Sensitivity: leave-Nelson-out (Kaper rows only)
     #--------------------------------------------------------------------------

     .refit <- function(sub_df, apply_floor = TRUE) {
          if (nrow(sub_df) == 0 || sum(sub_df$weight) <= 0) {
               return(list(meanlog = NA_real_, sdlog = NA_real_,
                           median = NA_real_))
          }
          sub_log10 <- log10(sub_df$zeta_2)
          sub_w     <- sub_df$weight
          sub_mu    <- stats::weighted.mean(sub_log10, sub_w)
          sub_var   <- sum(sub_w * (sub_log10 - sub_mu)^2) / sum(sub_w)
          sub_sigma <- sqrt(sub_var)
          if (!is.finite(sub_sigma) || sub_sigma <= 0) sub_sigma <- 0.5
          sub_ml    <- sub_mu * log(10)
          sub_sl    <- sub_sigma * log(10)
          if (apply_floor && sub_sl < sdlog_floor) sub_sl <- sdlog_floor
          list(meanlog = sub_ml, sdlog = sub_sl,
               median  = exp(sub_ml))
     }

     leave_nelson_fit <- .refit(fit_df[fit_df$source != "Nelson 2009 (primary)", ])

     sensitivity <- list(
          leave_nelson_out = leave_nelson_fit
     )

     #--------------------------------------------------------------------------
     # 3. Prediction grid and parameter data frame
     #--------------------------------------------------------------------------

     x_vals <- 10 ^ seq(1, 10, length.out = 1000)
     pred_df <- data.frame(
          zeta_2          = x_vals,
          log10_zeta_2    = log10(x_vals),
          density         = stats::dlnorm(x_vals, meanlog = meanlog, sdlog = sdlog),
          density_log10   = stats::dnorm(log10(x_vals),
                                         mean = mu_log10, sd = sigma_log10)
     )

     param_df <- make_param_df(
          variable_name          = "zeta_2",
          variable_description   = "Asymptomatic shedding rate (V. cholerae cells per infected person per day)",
          parameter_distribution = c("point", "point", "point", "point",
                                     "lognormal", "lognormal"),
          parameter_name         = c("low", "median", "mode", "high",
                                     "meanlog", "sdlog"),
          parameter_value        = c(ci_lower, lognormal_median, lognormal_mode, ci_upper,
                                     meanlog, sdlog)
     )

     #--------------------------------------------------------------------------
     # 4. Save data, predictions, and parameter priors to MODEL_INPUT
     #--------------------------------------------------------------------------

     dir.create(PATHS$MODEL_INPUT, recursive = TRUE, showWarnings = FALSE)
     dir.create(PATHS$DOCS_FIGURES, recursive = TRUE, showWarnings = FALSE)

     path_data <- file.path(PATHS$MODEL_INPUT, "data_zeta_2_prior.csv")
     utils::write.csv(data_df, path_data, row.names = FALSE)
     message("zeta_2 literature meta-analysis saved to: ", path_data)

     path_pred <- file.path(PATHS$MODEL_INPUT, "pred_zeta_2_prior.csv")
     utils::write.csv(pred_df, path_pred, row.names = FALSE)
     message("zeta_2 prior density grid saved to: ", path_pred)

     path_param <- file.path(PATHS$MODEL_INPUT, "param_zeta_2_prior.csv")
     utils::write.csv(param_df, path_param, row.names = FALSE)
     message("zeta_2 prior parameters saved to: ", path_param)

     #--------------------------------------------------------------------------
     # 5. Print summary
     #--------------------------------------------------------------------------

     cat("\n=== FITTED PRIOR: zeta_2 (Asymptomatic shedding rate, cells/person/day) ===\n")
     cat(sprintf("  Sources included  : %d (of %d)\n",
                 nrow(fit_df), nrow(data_df)))
     cat("  NOTE: single primary source (Nelson 2009); sdlog hard floor of 2.0 applied.\n")
     cat(sprintf("  Weighted log10 mean : %.3f  (10^%.2f = %.2e cells/person/day)\n",
                 mu_log10, mu_log10, 10^mu_log10))
     cat(sprintf("  Weighted log10 SD   : %.3f  (post-floor; %.1f-fold 1-sigma spread)\n",
                 sigma_log10, 10^sigma_log10))
     cat(sprintf("  Lognormal meanlog   : %.4f\n", meanlog))
     cat(sprintf("  Lognormal sdlog     : %.4f (floored to >=2.0)\n", sdlog))
     cat(sprintf("  Median              : %.2e cells/person/day\n", lognormal_median))
     cat(sprintf("  Mode                : %.2e cells/person/day\n", lognormal_mode))
     cat(sprintf("  95%% CI              : [%.2e, %.2e] cells/person/day\n",
                 ci_lower, ci_upper))
     cat("  Sensitivity (leave_nelson_out, Kaper rows only; n_primary = 0):\n")
     cat(sprintf("    median=%.2e, sdlog=%.3f  [published as warning, not a usable prior]\n",
                 leave_nelson_fit$median, leave_nelson_fit$sdlog))
     cat("\n")

     #--------------------------------------------------------------------------
     # 6. Paper-quality figure: sources forest + fitted density
     #--------------------------------------------------------------------------

     study_pal <- c("Volunteer challenge"     = "#1B4F72",
                    "QMRA synthesis"          = "#117A65",
                    "Expert review"           = "#B9770E",
                    "Model convention"        = "#7D3C98",
                    "Severity-weighted pool"  = "#512E5F")

     plot_df <- data_df
     plot_df$study_type <- factor(plot_df$study_type,
                                  levels = names(study_pal))
     plot_df$source <- factor(plot_df$source,
                              levels = rev(data_df$source))
     plot_df$weight_label <- ifelse(plot_df$weight == 0, "Excluded", "Included")

     p_sources <-
          ggplot2::ggplot(plot_df,
                          ggplot2::aes(y = source, x = zeta_2, colour = study_type)) +
          ggplot2::annotate("rect",
                            xmin  = ci_lower, xmax = ci_upper,
                            ymin  = -Inf,     ymax = Inf,
                            fill  = "grey85", alpha = 0.35) +
          ggplot2::geom_vline(xintercept = lognormal_median,
                              linetype = "solid", colour = "grey30", linewidth = 0.6) +
          ggplot2::geom_vline(xintercept = c(ci_lower, ci_upper),
                              linetype = "dashed", colour = "grey40", linewidth = 0.4) +
          ggplot2::geom_errorbar(ggplot2::aes(xmin = zeta_2_lo, xmax = zeta_2_hi,
                                              alpha = weight_label),
                                 orientation = "y", width = 0, linewidth = 0.6,
                                 na.rm = TRUE) +
          ggplot2::geom_point(ggplot2::aes(size = weight, alpha = weight_label),
                              na.rm = TRUE) +
          ggplot2::scale_x_log10(limits = c(1e1, 1e10),
                                 breaks = 10 ^ seq(1, 10, by = 1),
                                 labels = c(expression(10^1), expression(10^2),
                                            expression(10^3), expression(10^4),
                                            expression(10^5), expression(10^6),
                                            expression(10^7), expression(10^8),
                                            expression(10^9), expression(10^10))) +
          ggplot2::scale_color_manual(values = study_pal, name = "Study type") +
          ggplot2::scale_size_continuous(range = c(2, 4.5), guide = "none") +
          ggplot2::scale_alpha_manual(values = c("Included" = 1, "Excluded" = 0.35),
                                      name = "") +
          ggplot2::annotation_logticks(sides = "b", short = ggplot2::unit(0.05, "cm"),
                                       mid = ggplot2::unit(0.1, "cm"),
                                       long = ggplot2::unit(0.15, "cm")) +
          ggplot2::labs(title = expression("A. Published anchors for " * italic(V.~cholerae) * " asymptomatic shedding rate " * zeta[2]),
                        x = expression(zeta[2] ~ "  (cells " %.% "person"^{-1} %.% "day"^{-1} * ", log scale)"),
                        y = NULL) +
          ggplot2::theme_classic(base_size = 13) +
          ggplot2::theme(
               legend.position   = "right",
               legend.key.height = ggplot2::unit(0.5, "cm"),
               legend.title      = ggplot2::element_text(size = 11, face = "bold"),
               panel.grid.major.x = ggplot2::element_line(colour = "grey92",
                                                          linewidth = 0.3),
               panel.grid.minor  = ggplot2::element_blank(),
               axis.title.x      = ggplot2::element_text(margin = ggplot2::margin(t = 8)),
               axis.text.y       = ggplot2::element_text(size = 10),
               plot.title        = ggplot2::element_text(face = "bold", size = 14,
                                                         margin = ggplot2::margin(b = 8))
          )

     rug_df <- fit_df[, c("zeta_2", "study_type", "weight")]
     rug_df$study_type <- factor(rug_df$study_type, levels = names(study_pal))

     peak_density <- max(pred_df$density_log10)

     p_density <-
          ggplot2::ggplot() +
          ggplot2::geom_ribbon(data = pred_df,
                               ggplot2::aes(x = zeta_2, ymin = 0, ymax = density_log10),
                               fill = "#B9770E", alpha = 0.25) +
          ggplot2::geom_line(data = pred_df,
                             ggplot2::aes(x = zeta_2, y = density_log10),
                             colour = "#B9770E", linewidth = 1) +
          ggplot2::geom_vline(xintercept = lognormal_median,
                              linetype = "solid", colour = "grey20", linewidth = 0.6) +
          ggplot2::geom_vline(xintercept = c(ci_lower, ci_upper),
                              linetype = "dashed", colour = "grey40", linewidth = 0.4) +
          ggplot2::geom_rug(data = rug_df,
                            ggplot2::aes(x = zeta_2, colour = study_type),
                            sides = "b", length = ggplot2::unit(0.04, "npc"),
                            linewidth = 0.8, alpha = 0.9) +
          ggplot2::scale_x_log10(limits = c(1e1, 1e10),
                                 breaks = 10 ^ seq(1, 10, by = 1),
                                 labels = c(expression(10^1), expression(10^2),
                                            expression(10^3), expression(10^4),
                                            expression(10^5), expression(10^6),
                                            expression(10^7), expression(10^8),
                                            expression(10^9), expression(10^10))) +
          ggplot2::scale_y_continuous(limits = c(0, peak_density * 1.35),
                                      expand = c(0, 0)) +
          ggplot2::scale_color_manual(values = study_pal, name = "Study type",
                                      guide = "none") +
          ggplot2::annotation_logticks(sides = "b", short = ggplot2::unit(0.05, "cm"),
                                       mid = ggplot2::unit(0.1, "cm"),
                                       long = ggplot2::unit(0.15, "cm")) +
          ggplot2::annotate("text",
                            x = lognormal_median, y = peak_density * 1.08,
                            label = sprintf("median\n%.1e", lognormal_median),
                            hjust = 0.5, vjust = 0, size = 3.4, colour = "grey20",
                            lineheight = 0.9) +
          ggplot2::annotate("text",
                            x = ci_lower, y = peak_density * 0.55,
                            label = sprintf("2.5%%\n%.1e", ci_lower),
                            hjust = 1.15, vjust = 0.5, size = 3.1, colour = "grey40",
                            lineheight = 0.9) +
          ggplot2::annotate("text",
                            x = ci_upper, y = peak_density * 0.55,
                            label = sprintf("97.5%%\n%.1e", ci_upper),
                            hjust = -0.15, vjust = 0.5, size = 3.1, colour = "grey40",
                            lineheight = 0.9) +
          ggplot2::annotate("text",
                            x = 10^1.3, y = peak_density * 1.25,
                            hjust = 0, vjust = 0.5, size = 3.6, colour = "#B9770E",
                            label = sprintf("Lognormal(meanlog = %.2f, sdlog = %.2f) [sdlog floored to 2.0]",
                                            meanlog, sdlog)) +
          ggplot2::labs(title = "B. Fitted prior (single-primary-source; sdlog floored to 2.0)",
                        x = expression(zeta[2] ~ "  (cells " %.% "person"^{-1} %.% "day"^{-1} * ", log scale)"),
                        y = expression("Density (per log"[10] ~ zeta[2] * ")")) +
          ggplot2::theme_classic(base_size = 13) +
          ggplot2::theme(
               panel.grid.major.x = ggplot2::element_line(colour = "grey92",
                                                          linewidth = 0.3),
               panel.grid.minor   = ggplot2::element_blank(),
               axis.title.x       = ggplot2::element_text(margin = ggplot2::margin(t = 8)),
               axis.title.y       = ggplot2::element_text(margin = ggplot2::margin(r = 8)),
               plot.title         = ggplot2::element_text(face = "bold", size = 14,
                                                          margin = ggplot2::margin(b = 8))
          )

     combo <- cowplot::plot_grid(p_sources, p_density,
                                 ncol = 1, align = "v", rel_heights = c(1.0, 1))

     figure_path <- file.path(PATHS$DOCS_FIGURES, "zeta_2_prior.png")
     grDevices::png(filename = figure_path, width = 2800, height = 2800,
                    units = "px", res = 300)
     print(combo)
     grDevices::dev.off()
     message("zeta_2 prior figure saved to: ", figure_path)

     invisible(list(data        = data_df,
                    fit         = fit,
                    param_df    = param_df,
                    prediction  = pred_df,
                    sensitivity = sensitivity))
}
