#' Fit Mobility Model Using Flight Data and Distance Matrices
#'
#' This function estimates the departure probability (tau_i) and diffusion model (pi_ij) using flight data, distance matrices, and population sizes. It processes flight data, builds mobility and distance matrices, fits the mobility model, and saves the results in CSV format.
#'
#' @note This function requires the optional \code{mobility} package from GitHub.
#'   Install with: \code{remotes::install_github("COVID-19-Mobility-Data-Network/mobility")}
#'
#'   The \code{mobility} package requires JAGS (>= 4.3.0) to be installed on your system.
#'   Most users will not need to regenerate mobility data, as pre-computed files are
#'   included in the package.
#'
#' @param PATHS A list containing paths where data, models, and figures are stored. Typically generated by the `get_paths()` function and should include:
#' \itemize{
#'   \item \strong{DATA_OAG}: Path to the directory containing flight data (OAG).
#'   \item \strong{DATA_SHAPEFILES}: Path to the directory containing shapefiles for African countries.
#'   \item \strong{DATA_DEMOGRAPHICS}: Path to the directory containing demographic data.
#'   \item \strong{MODEL_INPUT}: Path to the directory where the model input files will be saved.
#'   \item \strong{DOCS_FIGURES}: Path to the directory where figures will be saved.
#' }
#'
#' @return The function saves mobility matrices (M, D, N), travel probabilities (tau_j), and diffusion matrices (pi_ij) as CSV files in the specified directory. It also generates and saves visualizations as PNG files.
#'
#' @importFrom ggplot2 ggplot aes geom_tile xlab ylab theme_bw element_text margin scale_fill_gradient guides guide_colorbar geom_segment geom_sf geom_point geom_text scale_size_continuous theme_void
#' @importFrom reshape2 melt
#' @importFrom sf st_read st_coordinates st_centroid
#' @importFrom dplyr left_join rename
#' @importFrom glue glue
#' @importFrom cowplot plot_grid
#' @importFrom utils read.csv write.csv
#' @param od_source Which origin-destination matrix drives the DIFFUSION fit.
#'   \describe{
#'     \item{\code{"air"}}{(default) OAG flight counts -- the historical
#'       behaviour, byte-identical to previous runs.}
#'     \item{\code{"fused"}}{The four-source overland structure from
#'       \code{\link{process_mobility_od_data}} (UN DESA stock + Abel-Cohen
#'       flows + Meta SCI + contiguity). Row-normalised and unit-free, so
#'       \code{tau_i} is still fit on the air matrix.}
#'     \item{\code{"blend"}}{\strong{Recommended.} The additive sum of the
#'       air flight matrix and the raked overland matrix, both daily person
#'       flows. Yields additive \code{tau_i} and a single gamma/omega pair
#'       describing the combined kernel -- the only form \code{config_default}
#'       can represent. Retains the long-range air links that pure overland
#'       replacement destroys.}
#'     \item{\code{"fused_raked"}}{The fused structure IPF-raked to
#'       evidence-based daily departure margins by
#'       \code{\link{rake_mobility_od_to_tau}}. Carries amplitude, so
#'       \code{tau_i} is fit on it.}
#'   }
#' @param distance_metric Distance units for the gravity kernel.
#'   \describe{
#'     \item{\code{"great_circle"}}{(default) Centroid-to-centroid great-circle
#'       distance. \strong{Note the stored units are not kilometres}:
#'       \code{get_distance_matrix()} already returns km (spherical, R = 6371)
#'       and the historical code then multiplies by 111.35, the planar
#'       degrees-to-km factor. \code{mobility_D.csv} is therefore km x 111.35.
#'       Harmless for the fit -- the constant cancels in the row-normalised
#'       \code{pi} and \code{gamma} is scale-free in a power model -- but the
#'       artifact's units are wrong and it is retained only for continuity
#'       with the shipped \code{gamma}.}
#'     \item{\code{"travel_time"}}{Overland least-cost travel time in HOURS
#'       from \code{\link{get_travel_time_matrix}} (MAP motorized friction
#'       surface). This is what the MOSAIC-OCV E3 work fit gamma on.}
#'   }
#'   \strong{gamma is not comparable across metrics} -- it is a decay exponent
#'   on whatever units D carries, so a travel-time gamma cannot be read against
#'   a kilometre gamma. Compare only within a metric.
#' @param fused_count_scale Integer scale applied to the row-normalised fused
#'   structure so \code{mobility::mobility()} receives counts. Default 1e5.
#'   The absolute scale does not move gamma/omega (verified in the MOSAIC-OCV
#'   E3 Route-2 work); it only affects the kernel-mix term.
#' @param suffix Filename suffix for outputs. Defaults to \code{"_fused"} when
#'   \code{od_source = "fused"} and/or \code{"_tt"} for travel-time, and
#'   \code{""} otherwise, so a non-default run cannot silently overwrite the
#'   production air/great-circle connectivity.
#'
#' @section Structure vs amplitude (important):
#' Under \code{od_source = "fused"} the departure process \code{tau_i} is
#' \strong{still fit on the OAG flight matrix}, not on the fused structure.
#' This is deliberate. The fused matrix is row-normalised and unit-free, and
#' its dominant input (UN DESA) is a decades-accumulated migrant \emph{stock};
#' dividing such a matrix by population does not yield a departure rate. The
#' MOSAIC-OCV E3 investigation measured a ~700x inflation from exactly that
#' error. So the fused pathway supplies kernel \strong{structure}
#' (gamma, omega, pi) only; \strong{amplitude} continues to come from real
#' flow counts. A defensible overland amplitude needs separate evidence
#' (border throughput / IOM DTM), which this function does not attempt.
#'
#' @export

est_mobility <- function(PATHS,
                         od_source         = c("air", "fused", "fused_raked", "blend"),
                         distance_metric   = c("great_circle", "travel_time"),
                         fused_count_scale = 1e5,
                         suffix            = NULL) {

     od_source       <- match.arg(od_source)
     distance_metric <- match.arg(distance_metric)
     if (is.null(suffix)) {
          suffix <- paste0(switch(od_source, air = "", fused = "_fused",
                                  fused_raked = "_fused_raked", blend = "_blend"),
                           if (distance_metric == "travel_time") "_tt" else "")
     }
     .mosaic_check_suffix(suffix,
                          is_default = identical(od_source, "air") &&
                                       identical(distance_metric, "great_circle"))

     .out <- function(f) .mosaic_suffix_path(file.path(PATHS$MODEL_INPUT, f), suffix)


     # Check for optional mobility package
     if (!requireNamespace("mobility", quietly = TRUE)) {
          stop(
               "The 'mobility' package is required but not installed.\n",
               "Install with: remotes::install_github('COVID-19-Mobility-Data-Network/mobility')\n\n",
               "Note: The mobility package requires JAGS (>= 4.3.0) to be installed.\n",
               "Most users do not need to regenerate mobility data, as pre-computed files\n",
               "are included in model/input/.",
               call. = FALSE
          )
     }

     requireNamespace('ggplot2')
     requireNamespace('reshape2')
     requireNamespace('sf')
     requireNamespace('dplyr')
     requireNamespace('tidyr')
     requireNamespace('glue')


     #--------------------------------------------------------------------------
     # Load flight data and build mobility matrix (M)
     #--------------------------------------------------------------------------

     message("Getting mean DAILY OAG flight data from 2017")
     data_flights <- utils::read.csv(file.path(PATHS$DATA_OAG, "oag_africa_2017_mean_daily.csv"), stringsAsFactors = FALSE)
     data_flights <- data_flights[data_flights$origin_iso3 %in% MOSAIC::iso_codes_mosaic,]
     data_flights <- data_flights[data_flights$destination_iso3 %in% MOSAIC::iso_codes_mosaic,]

     M_air <- mobility::get_mob_matrix(orig=data_flights$origin_iso3,
                                       dest=data_flights$destination_iso3,
                                       value=data_flights$count)

     # M_air always drives the DEPARTURE fit (real flow counts). Only the
     # DIFFUSION fit switches source -- see the "Structure vs amplitude"
     # section in the roxygen above.
     if (identical(od_source, "blend")) {

          f_raked <- file.path(PATHS$DATA_PROCESSED, "mobility", "M_fused_raked.csv")
          if (!file.exists(f_raked)) {
               stop("Raked OD matrix not found: ", f_raked,
                    "\n  Build it with rake_mobility_od_to_tau(PATHS).", call. = FALSE)
          }
          message("Using ADDITIVE BLEND: air flights + raked overland")
          Mr <- as.matrix(utils::read.csv(f_raked, row.names = 1, check.names = FALSE))
          colnames(Mr) <- gsub("^X", "", colnames(Mr))
          keep  <- intersect(rownames(M_air), rownames(Mr))
          M_air <- M_air[keep, keep, drop = FALSE]
          Mr    <- Mr[keep, keep, drop = FALSE]

          # Both sides are DAILY person-flows -- OAG is a mean-daily count and
          # the rake targets tau_daily * N -- so they add directly, no scaling
          # constant. This makes tau additive by construction (the row sums
          # are air + overland departures) and gives a SINGLE gamma/omega pair
          # describing the mixture, which is all config_default can carry.
          # Keeping the air channel matters: it carries the long-range,
          # non-adjacent links that are the only route by which a distant
          # country can be seeded.
          M <- M_air + Mr
          storage.mode(M) <- "double"
          M <- round(M); storage.mode(M) <- "integer"
          names(dimnames(M)) <- c("origin", "destination")

     } else if (identical(od_source, "fused_raked")) {

          f_raked <- file.path(PATHS$DATA_PROCESSED, "mobility", "M_fused_raked.csv")
          if (!file.exists(f_raked)) {
               stop("Raked OD matrix not found: ", f_raked,
                    "\n  Build it with rake_mobility_od_to_tau(PATHS).", call. = FALSE)
          }
          message("Using IPF-RAKED fused OD (carries evidence-based amplitude)")
          Mr <- as.matrix(utils::read.csv(f_raked, row.names = 1, check.names = FALSE))
          colnames(Mr) <- gsub("^X", "", colnames(Mr))
          keep <- intersect(rownames(M_air), rownames(Mr))
          Mr <- Mr[keep, keep, drop = FALSE]
          # raked cells are daily person-flows; mobility() wants counts
          M <- round(Mr)
          storage.mode(M) <- "integer"
          names(dimnames(M)) <- c("origin", "destination")
          M_air <- M_air[keep, keep, drop = FALSE]

     } else if (identical(od_source, "fused")) {
          f_fused <- file.path(PATHS$DATA_PROCESSED, "mobility", "M_structure_fused.csv")
          if (!file.exists(f_fused)) {
               stop("Fused OD structure not found: ", f_fused,
                    "\n  Build it with:  download_mobility_od_sources(PATHS)",
                    "\n              then  process_mobility_od_data(PATHS)", call. = FALSE)
          }
          message("Using FUSED overland OD structure for the diffusion fit")
          Mf <- as.matrix(utils::read.csv(f_fused, row.names = 1, check.names = FALSE))
          colnames(Mf) <- gsub("^X", "", colnames(Mf))

          keep <- intersect(rownames(M_air), rownames(Mf))
          if (length(keep) < 2L) stop("Fused structure shares <2 ISO codes with the air matrix.",
                                      call. = FALSE)
          if (length(keep) < nrow(M_air)) {
               warning("Fused structure covers ", length(keep), " of ", nrow(M_air),
                       " air-matrix countries; restricting to the intersection.",
                       call. = FALSE)
          }
          Mf <- Mf[keep, keep, drop = FALSE]
          # mobility::mobility() expects counts
          M <- round(Mf * fused_count_scale)
          storage.mode(M) <- "integer"
          names(dimnames(M)) <- c("origin", "destination")
          M_air <- M_air[keep, keep, drop = FALSE]
     } else {
          M <- M_air
     }



     #--------------------------------------------------------------------------
     # Get distance matrix (D)
     #--------------------------------------------------------------------------

     message("Making distance matrix")
     shapefiles <- list.files(PATHS$DATA_SHAPEFILES, pattern = "\\.shp$", full.names = TRUE)
     data_centroids <- do.call(rbind, lapply(shapefiles, MOSAIC::get_centroid))

     if (!(all(data_flights$origin_iso3 %in% data_centroids$iso3))) stop("Some iso3 codes are missing in data_centriods")
     data_centroids <- data_centroids[data_centroids$iso3 %in% MOSAIC::iso_codes_mosaic,]
     row.names(data_centroids) <- NULL
     head(data_centroids)

     if (identical(distance_metric, "travel_time")) {

          message("Using OVERLAND LEAST-COST TRAVEL TIME (hours) as distance")
          D <- MOSAIC::get_travel_time_matrix(PATHS,
                                              iso_codes = data_centroids$iso3,
                                              verbose   = TRUE)
          D <- D[data_centroids$iso3, data_centroids$iso3, drop = FALSE]

          # gamma is estimated on whatever distance units D carries. An
          # unreachable pair (island / disconnected landmass) is Inf, which the
          # gravity likelihood cannot consume; substitute a finite upper bound
          # so those pairs are merely very distant rather than fatal.
          if (any(!is.finite(D))) {
               cap <- max(D[is.finite(D)], na.rm = TRUE) * 1.5
               n_cap <- sum(!is.finite(D))
               warning(n_cap, " unreachable pair(s) capped at ", round(cap, 1),
                       " h (1.5x the largest finite travel time).", call. = FALSE)
               D[!is.finite(D)] <- cap
          }
          names(dimnames(D)) <- c("origin", "destination")

     } else {

          D <- get_distance_matrix(x=data_centroids$lon,
                                   y=data_centroids$lat,
                                   id=data_centroids$iso3)
          D <- D*111.35  # Convert decimal degrees to kilometers
     }


     #--------------------------------------------------------------------------
     # Get Population size vector (N)
     #--------------------------------------------------------------------------

     message("Getting population sizes (2017 to match OAG data)")
     data_demographics <- utils::read.csv(file.path(PATHS$DATA_DEMOGRAPHICS, "demographics_africa_2000_2023.csv"), stringsAsFactors = FALSE)
     data_demographics <- data_demographics[data_demographics$year == 2017 & data_demographics$iso_code %in% MOSAIC::iso_codes_mosaic,]
     data_demographics <- data_demographics[order(data_demographics$iso_code),]
     N <- as.integer(data_demographics$population)
     names(N) <- data_demographics$iso_code


     #--------------------------------------------------------------------------
     # Check that dimensions match
     #--------------------------------------------------------------------------

     check <- c(
          dim(M)[1] == dim(M)[2],
          dim(M)[1] == length(N),
          dim(M)[2] == length(N),
          dimnames(M)$origin == names(N),
          dimnames(M)$destination == names(N),
          dim(M)[1] == dim(D)[1],
          dim(M)[2] == dim(D)[2],
          dimnames(M)$origin == dimnames(D)$origin,
          dimnames(M)$destination == dimnames(D)$destination
     )

     if (!all(check)) {
          stop("Dimension mismatch in M, D, or N.")
     } else {
          message("Mobility matrices dimensions match")
     }

     #--------------------------------------------------------------------------
     # Fit probability of travel, departure (tau_i)
     #--------------------------------------------------------------------------

     message("Fitting departure process: travel probability (tau_j)")
     # ALWAYS the air matrix: a row-normalised structure has no departure
     # amplitude, and DESA stock / population is not a rate.
     # "fused_raked" carries evidence-based daily person-flows, so tau is fit
     # on it. Bare "fused" is unit-free, so tau stays on the air matrix.
     M_tau <- if (od_source %in% c("fused_raked", "blend")) M else M_air
     diagonal <- diag(M_tau)
     diagonal[is.na(diagonal)] <- 0

     trips_total <- apply(M_tau, 1, function(x) sum(x, na.rm = TRUE))
     y <- as.integer(trips_total - diagonal)
     names(y) <- names(diag(M_tau))

     y <- y[match(names(N), names(y))]

     mod_travel_prob <- mobility::fit_prob_travel(travel = y,
                                                  total = N,
                                                  n_chain = 5,
                                                  n_burn = 1000,
                                                  n_samp = 1000,
                                                  n_thin = 5)

     mod_travel_prob_summary <- mobility::summary(mod_travel_prob)
     mod_travel_prob_summary <- data.frame(iso3 = names(N), mod_travel_prob_summary)

     beta_params <- propvacc::get_beta_params(mu = mod_travel_prob_summary$mean, mod_travel_prob_summary$sd^2)

     df_travel_prob <- data.frame(
          country = convert_iso_to_country(names(y)),
          iso_code = names(y),
          mean = mod_travel_prob_summary$mean,
          sd = mod_travel_prob_summary$sd,
          ci_lo = mod_travel_prob_summary$Q2.5,
          ci_hi = mod_travel_prob_summary$Q97.5,
          shape1 = beta_params$shape1,
          shape2 = beta_params$shape2
     )

     df_travel_prob <- merge(df_travel_prob, data.frame(iso_code = names(N), population = N), by='iso_code')

     tau_vec <- as.vector(df_travel_prob$mean)
     names(tau_vec) <- df_travel_prob$iso_code


     #--------------------------------------------------------------------------
     # Fit probability of travel from origin to destination, diffusion (pi_i)
     #--------------------------------------------------------------------------

     message("Fitting diffusion process: gravity power model for pi_ij")
     mobility_matrices <- list(M=M, D=D, N=N)
     mod_mobility <- mobility::mobility(data=mobility_matrices,
                                        model='departure-diffusion',
                                        type='power',
                                        hierarchical = F,
                                        n_chain = 5,
                                        n_burn = 1000,
                                        n_samp = 1000,
                                        n_thin = 5)
     mod_mobility_summary <- mobility::summary(mod_mobility, probs=c(0.025, 0.975), ac_lags=10)
     mod_mobility_summary <- data.frame(parameter = row.names(mod_mobility_summary), mod_mobility_summary)
     mobility::check(mod_mobility)

     pi_mat <- MOSAIC::calc_diffusion_matrix_pi(D = D,
                                                N = N,
                                                gamma = mod_mobility_summary['gamma', 'mean'],
                                                omega = mod_mobility_summary['omega', 'mean'])


     #--------------------------------------------------------------------------
     # Save matrices and parameters to file
     #--------------------------------------------------------------------------

     message("Writing mobility model matrices to file: M, D, N, tau, pi")
     utils::write.csv(data_centroids, .out("mobility_lon_lat.csv"), row.names = FALSE)
     utils::write.csv(M, .out("mobility_M.csv"), row.names = TRUE)
     utils::write.csv(D, .out("mobility_D.csv"), row.names = TRUE)
     utils::write.csv(N, .out("mobility_N.csv"), row.names = TRUE)
     utils::write.csv(mod_travel_prob_summary, .out("mobility_travel_prob_params.csv"), row.names = TRUE)
     utils::write.csv(mod_mobility_summary, .out("mobility_gravity_params.csv"), row.names = TRUE)
     utils::write.csv(tau_vec, .out("mobility_tau.csv"), row.names = TRUE)
     utils::write.csv(pi_mat, .out("mobility_pi.csv"), row.names = TRUE)


     message("Writing standard format parameter data frames")
     param_df_point <- make_param_df(
          variable_name = "tau",
          variable_description = "Country-level travel probabilities",
          parameter_distribution = "point",
          i = df_travel_prob$iso_code,
          parameter_name = "mean",
          parameter_value = df_travel_prob$mean
     )

     param_df_stoch <- make_param_df(
          variable_name = "tau",  # Assuming 'tau' represents travel probabilities
          variable_description = "Country-level travel probabilities",
          parameter_distribution = "beta",
          i = df_travel_prob$iso_code,
          parameter_name = c(rep("shape1", nrow(df_travel_prob)), rep("shape2", nrow(df_travel_prob))),
          parameter_value = c(df_travel_prob$shape1, df_travel_prob$shape2)
     )

     param_df <- rbind(param_df_point, param_df_stoch)
     param_df <- param_df[order(param_df$i),]

     utils::write.csv(param_df, .out("param_tau_departure.csv"), row.names = FALSE)

     tmp <- melt(pi_mat)

     param_df <- make_param_df(
          variable_name = "pi",  # Assuming 'tau' represents travel probabilities
          variable_description = "Probability of travel from i to j",
          parameter_distribution = "point",
          i = tmp$origin,
          j = tmp$destination,
          parameter_name = 'mean',
          parameter_value = tmp$value
     )

     utils::write.csv(param_df, .out("param_pi_diffusion.csv"), row.names = FALSE)


     param_df <- rbind(
          make_param_df(
               variable_name = "mobility_gamma",
               variable_description = "Distance parameter in mobility model",
               parameter_distribution = "point",
               parameter_name = 'mean',
               parameter_value = mod_mobility_summary['gamma', 'mean']
          ),
          make_param_df(
               variable_name = "mobility_omega",
               variable_description = "Population parameter in mobility model",
               parameter_distribution = "point",
               parameter_name = 'mean',
               parameter_value = mod_mobility_summary['omega', 'mean']
          )
     )

     utils::write.csv(param_df, .out("param_gravity_model.csv"), row.names = FALSE)

     message("Matrices and parameter estimates saved here:")
     message(PATHS$MODEL_INPUT)

}
