#' Estimate Vaccine Effectiveness Decay Parameters
#'
#' This function estimates oral cholera vaccine (OCV) effectiveness decay by fitting exponential decay models
#' to meta-regression effectiveness data from Xu et al (2024). It estimates decay parameters (omega) and
#' initial effectiveness (phi) for both one-dose and two-dose regimens using non-linear least squares
#' with the Levenberg-Marquardt algorithm.
#'
#' @param PATHS A list containing the paths where data and parameters are saved. Typically generated by the `get_paths()` function and should include:
#' \itemize{
#'   \item \strong{MODEL_INPUT}: Path to the directory where parameter files, data, and predictions will be saved.
#' }
#'
#' @details The function performs the following steps:
#' \enumerate{
#'   \item Creates vaccine effectiveness data from Xu et al (2024) meta-regression results
#'   \item Fits exponential decay models VE(t) = phi * exp(-omega * t) separately for one-dose and two-dose regimens
#'   \item Estimates parameters for mean effectiveness and confidence intervals using constrained optimization
#'   \item Infers beta distributions for initial effectiveness (phi) and gamma distributions for decay rates (omega)
#'   \item Saves data points, predictions, and parameter distributions to CSV files
#' }
#'
#' The model parameters are:
#' \itemize{
#'   \item \strong{phi_1, phi_2}: Initial vaccine effectiveness for one-dose and two-dose regimens
#'   \item \strong{omega_1, omega_2}: Daily decay rates for one-dose and two-dose regimens
#' }
#'
#' @return The function does not return values but saves three CSV files:
#' \itemize{
#'   \item \code{data_vaccine_effectiveness.csv}: Original meta-regression data points from Xu et al
#'   \item \code{pred_vaccine_effectiveness.csv}: Predicted effectiveness over 10 years with confidence intervals
#'   \item \code{param_vaccine_effectiveness.csv}: Parameter estimates with distributional parameters for uncertainty
#' }
#'
#' @references Xu et al. (2024). Effectiveness of Oral Cholera Vaccines: A Systematic Review and Meta-Analysis.
#' medRxiv. https://doi.org/10.1101/2024.08.13.24311930v2
#'
#' @importFrom minpack.lm nls.lm nls.lm.control
#' @examples
#' \dontrun{
#' # Assuming PATHS is generated from get_paths()
#' PATHS <- get_paths()
#' est_vaccine_effectiveness(PATHS)
#' }
#' @export

est_vaccine_effectiveness <- function(PATHS) {


     #--------------------------------------------------------------------------
     # Create vaccine effectiveness data from Xu et al (2024) meta-regression
     #--------------------------------------------------------------------------

     # One-dose OCV effectiveness
     one_dose_data <- data.frame(
          months = c(6, 12, 18, 24, 30),
          days = c(6, 12, 18, 24, 30) * 30.5,
          effectiveness = c(0.70, 0.60, 0.53, 0.47, 0.42),
          effectiveness_lo = c(0.60, 0.51, 0.42, 0.34, 0.26),
          effectiveness_hi = c(0.77, 0.68, 0.62, 0.58, 0.55),
          dose_regimen = "One-dose OCV",
          source = "Xu et al (2024)"
     )

     # Two-dose OCV effectiveness
     two_dose_data <- data.frame(
          months = c(12, 24, 36, 48),
          days = c(12, 24, 36, 48) * 30.5,
          effectiveness = c(0.68, 0.60, 0.53, 0.47),
          effectiveness_lo = c(0.58, 0.40, 0.24, 0.09),
          effectiveness_hi = c(0.78, 0.73, 0.71, 0.70),
          dose_regimen = "Two-dose OCV",
          source = "Xu et al (2024)"
     )

     data_df <- rbind(one_dose_data, two_dose_data)



     #--------------------------------------------------------------------------
     # Estimate exponential decay for vaccine effectiveness
     #--------------------------------------------------------------------------

     # VE(t) = phi * exp(-omega * t) where t is days since vaccination
     exponential_decay_function <- function(par, x) {
          phi <- par[1]    # Initial effectiveness
          omega <- par[2]  # Decay rate per day
          phi * exp(-omega * x)
     }

     # Function to fit exponential decay model with constraints
     fit_vaccine_decay <- function(data, dose_name) {

          # Starting values for model parameters
          start_values <- c(phi = 0.80, omega = 0.0005)

          # Objective function to minimize residuals
          objective_function <- function(par, x, y) {
               predicted <- exponential_decay_function(par, x)
               residuals <- y - predicted
               residuals
          }

          # Fit model for mean effectiveness
          fit_mean <- nls.lm(par = start_values,
                             fn = objective_function,
                             x = data$days,
                             y = data$effectiveness,
                             control = nls.lm.control(maxiter = 10000))

          # Fit model for upper CI
          # Constrain phi to [0, 1], leave omega unconstrained (use large bounds)
          fit_hi <- nls.lm(par = start_values,
                           fn = objective_function,
                           x = data$days,
                           y = data$effectiveness_hi,
                           upper = c(1.0, Inf),  # phi <= 1, omega unconstrained
                           lower = c(fit_mean$par[1], 0),     # phi >= 0, omega >= 0
                           control = nls.lm.control(maxiter = 10000))

          # Fit model for lower CI
          fit_lo <- nls.lm(par = start_values,
                           fn = objective_function,
                           x = data$days,
                           y = data$effectiveness_lo,
                           upper = c(fit_mean$par[1] - (fit_hi$par[1] - fit_mean$par[1]), Inf),  # phi <= 1, omega unconstrained
                           lower = c(0.0, 0),     # phi >= 0, omega >= 0
                           control = nls.lm.control(maxiter = 10000))

          # Return fitted parameters directly without constraints
          return(list(
               mean = fit_mean$par,
               lo = fit_lo$par,
               hi = fit_hi$par,
               dose = dose_name
          ))
     }

     # Fit models for both dose regimens
     fit_one_dose <- fit_vaccine_decay(one_dose_data, "one_dose")
     fit_two_dose <- fit_vaccine_decay(two_dose_data, "two_dose")

     # Create prediction data frames for both dose regimens
     days_predict <- seq(0, 365*10, by = 1)  # Predict up to 5 years

     # One-dose predictions
     prediction_one_dose <- data.frame(
          day = days_predict,
          predicted = exponential_decay_function(fit_one_dose$mean, days_predict),
          predicted_lo = exponential_decay_function(fit_one_dose$lo, days_predict),
          predicted_hi = exponential_decay_function(fit_one_dose$hi, days_predict),
          dose_regimen = "One-dose OCV"
     )

     # Two-dose predictions
     prediction_two_dose <- data.frame(
          day = days_predict,
          predicted = exponential_decay_function(fit_two_dose$mean, days_predict),
          predicted_lo = exponential_decay_function(fit_two_dose$lo, days_predict),
          predicted_hi = exponential_decay_function(fit_two_dose$hi, days_predict),
          dose_regimen = "Two-dose OCV"
     )

     prediction_df <- rbind(prediction_one_dose, prediction_two_dose)



     #--------------------------------------------------------------------------
     # Infer prior distributions for phi_* and omega_*
     #--------------------------------------------------------------------------

     phi_1_fit <- fit_beta_from_ci(
          mode_val = fit_one_dose$mean['phi'],
          ci_lower = fit_one_dose$lo['phi'],
          ci_upper = fit_one_dose$hi['phi'],
          method = "moment_matching",
          verbose = FALSE
     )

     phi_2_fit <- fit_beta_from_ci(
          mode_val = fit_two_dose$mean['phi'],
          ci_lower = fit_two_dose$lo['phi'],
          ci_upper = fit_two_dose$hi['phi'],
          method = "moment_matching",
          verbose = FALSE
     )

     param_df_phi_1 <- make_param_df(
          variable_name = 'phi_1',
          variable_description = 'Initial vaccine effectiveness (one dose)',
          parameter_distribution = c('point', 'point', 'point',
                                     'beta', 'beta'),
          parameter_name = c('low', 'mean', 'high',
                             'shape1', 'shape2'),
          parameter_value = c(fit_one_dose$lo[1], fit_one_dose$mean[1], fit_one_dose$hi[1],
                              phi_1_fit$shape1, phi_1_fit$shape2)
     )

     param_df_phi_2 <- make_param_df(
          variable_name = 'phi_2',
          variable_description = 'Initial vaccine effectiveness (two dose)',
          parameter_distribution = c('point', 'point', 'point',
                                     'beta', 'beta'),
          parameter_name = c('low', 'mean', 'high',
                             'shape1', 'shape2'),
          parameter_value = c(fit_two_dose$lo[1], fit_two_dose$mean[1], fit_two_dose$hi[1],
                              phi_2_fit$shape1, phi_2_fit$shape2)
     )


     # Calculate gamma distribution parameters for omega_1 and omega_2

     # Note: omega is inversely related to effectiveness
     # High effectiveness (hi) → Low omega (slower decay)
     # Low effectiveness (lo) → High omega (faster decay)
     # So we need to swap the CI bounds for omega
     omega_1_fit <- fit_gamma_from_ci(
          mode_val = fit_one_dose$mean['omega'],
          ci_lower = fit_one_dose$hi['omega'],  # hi effectiveness = low omega
          ci_upper = fit_one_dose$lo['omega'],  # lo effectiveness = high omega
          method = "moment_matching",
          verbose = FALSE
     )

     omega_2_fit <- fit_gamma_from_ci(
          mode_val = fit_two_dose$mean['omega'],
          ci_lower = fit_two_dose$hi['omega'],  # hi effectiveness = low omega
          ci_upper = fit_two_dose$lo['omega'],  # lo effectiveness = high omega
          method = "moment_matching",
          verbose = FALSE
     )

     param_df_omega_1 <- make_param_df(
          variable_name = 'omega_1',
          variable_description = 'Vaccine waning rate (one dose)',
          parameter_distribution = c('point', 'point', 'point',
                                     'gamma', 'gamma'),
          parameter_name = c('low', 'mean', 'high',
                             'shape', 'rate'),
          # Note: omega CI is inverted relative to effectiveness
          parameter_value = c(fit_one_dose$hi[2], fit_one_dose$mean[2], fit_one_dose$lo[2],
                              omega_1_fit$shape, omega_1_fit$rate)
     )

     param_df_omega_2 <- make_param_df(
          variable_name = 'omega_2',
          variable_description = 'Vaccine waning rate (two dose)',
          parameter_distribution = c('point', 'point', 'point',
                                     'gamma', 'gamma'),
          parameter_name = c('low', 'mean', 'high',
                             'shape', 'rate'),
          # Note: omega CI is inverted relative to effectiveness
          parameter_value = c(fit_two_dose$hi[2], fit_two_dose$mean[2], fit_two_dose$lo[2],
                              omega_2_fit$shape, omega_2_fit$rate)
     )



     param_df <- rbind(param_df_omega_1, param_df_phi_1, param_df_omega_2, param_df_phi_2)



     #--------------------------------------------------------------------------
     # Save data, predictions, and parameter priors to file
     #--------------------------------------------------------------------------

     # Save Xu et al meta-regression data points
     path <- file.path(PATHS$MODEL_INPUT, "data_vaccine_effectiveness.csv")
     write.csv(data_df, path, row.names = FALSE)
     message(paste("Predicted vaccine effectiveness over time saved to:", path))

     # Save predicted vaccine effectiveness decay functions
     path <- file.path(PATHS$MODEL_INPUT, "pred_vaccine_effectiveness.csv")
     write.csv(prediction_df, path, row.names = FALSE)
     message(paste("Predicted vaccine effectiveness over time saved to:", path))


     # Save parameter files
     path <- file.path(PATHS$MODEL_INPUT, "param_vaccine_effectiveness.csv")
     write.csv(param_df, path, row.names = FALSE)
     message(paste("Vaccine effectiveness parameters (omega_1, omega_2, phi_1, phi_2) saved to:", path))



     #--------------------------------------------------------------------------
     # Print summary statistics
     #--------------------------------------------------------------------------

     cat("\n=== FITTED VACCINE PARAMETERS ===\n")
     cat("One-dose OCV:\n")
     cat(sprintf("  phi_1 (initial effectiveness): %.3f [%.3f, %.3f]\n",
                 fit_one_dose$mean[1], fit_one_dose$lo[1], fit_one_dose$hi[1]))
     cat(sprintf("  omega_1 (waning rate/day): %.6f [%.6f, %.6f]\n",
                 fit_one_dose$mean[2], fit_one_dose$lo[2], fit_one_dose$hi[2]))
     cat(sprintf("  Half-life: %.1f days\n", log(2)/fit_one_dose$mean[2]))

     cat("\nTwo-dose OCV:\n")
     cat(sprintf("  phi_2 (initial effectiveness): %.3f [%.3f, %.3f]\n",
                 fit_two_dose$mean[1], fit_two_dose$lo[1], fit_two_dose$hi[1]))
     cat(sprintf("  omega_2 (waning rate/day): %.6f [%.6f, %.6f]\n",
                 fit_two_dose$mean[2], fit_two_dose$lo[2], fit_two_dose$hi[2]))
     cat(sprintf("  Half-life: %.1f days\n", log(2)/fit_two_dose$mean[2]))
     cat("\n")


}
