#' Estimate Prior Distribution for Environmental Half-Saturation Constant (kappa)
#'
#' This function compiles a meta-analysis of published *Vibrio cholerae* infectious
#' dose (ID50) estimates and fits a lognormal prior distribution for the
#' environmental dose-response half-saturation constant \eqn{\kappa} used in the
#' MOSAIC environmental force-of-infection term:
#' \deqn{\lambda_W \propto W / (\kappa + W)}
#' where \eqn{W} is the environmental bacterial concentration and \eqn{\kappa}
#' is the concentration (CFU) at which the probability of infection is 50\%.
#'
#' The function assembles a literature table of ID50 estimates spanning direct
#' human-volunteer challenge studies (Hornick 1971, Cash 1974, Levine 1981/1988,
#' Tacket 1999), QMRA Beta-Poisson fits (Haas, Rose & Gerba 1999), expert-review
#' summaries (Nelson et al. 2009, Kaper et al. 1995), and values adopted by
#' convention in the cholera modelling literature (Codeco 2001, Hartley et al.
#' 2006). Each source is weighted by its relevance to the endemic / buffered
#' exposure context most relevant to sub-Saharan African transmission settings.
#' A lognormal is then fit by weighted maximum-likelihood on the log10 scale.
#'
#' @param PATHS A list of paths generated by `get_paths()`. Must include:
#' \itemize{
#'   \item \strong{MODEL_INPUT}: directory where parameter CSVs are saved.
#'   \item \strong{DOCS_FIGURES}: directory where the summary figure is saved.
#' }
#'
#' @return Invisibly returns a list with elements:
#' \itemize{
#'   \item \code{data}: the source meta-analysis table.
#'   \item \code{fit}: fitted lognormal parameters (\code{meanlog}, \code{sdlog},
#'         \code{median}, \code{mode}, \code{ci_lower}, \code{ci_upper}).
#'   \item \code{param_df}: long-format parameter data frame (as saved to disk).
#' }
#'
#' @details
#' The MOSAIC dose-response follows Codeco (2001) and Hartley et al. (2006):
#' the infection hazard is a saturating Michaelis-Menten function of
#' environmental concentration with half-saturation \eqn{\kappa}. Historical
#' cholera models have fixed \eqn{\kappa = 10^6} cells, a value traceable to
#' Sack (1971) and Hornick et al. (1971) under unbuffered water-only exposure
#' in healthy adults. Modern re-analyses of buffered-exposure volunteer studies
#' (NaHCO3 neutralisation, representative of typical endemic exposure through
#' food or contaminated drinking water) consistently support a lower central
#' estimate of \eqn{\sim 10^5} CFU, with substantial between-study heterogeneity.
#'
#' Fitting: each source contributes a point estimate \eqn{\log_{10} \kappa_i}
#' with weight \eqn{w_i} reflecting its evidentiary quality. Weighted mean and
#' standard deviation on the log10 scale are converted to lognormal
#' \code{meanlog} and \code{sdlog}. The resulting prior is reconciled with
#' \code{fit_lognormal_from_ci()} so that \code{meanlog} is consistent with the
#' weighted mode and the 2.5th / 97.5th percentiles match the empirical spread.
#'
#' @references
#' \itemize{
#'   \item Hornick RB, et al. (1971). The Broad Street pump revisited: response
#'         of volunteers to ingested cholera vibrios. *Bull N Y Acad Med* 47(10):1181-91.
#'   \item Cash RA, et al. (1974). Response of man to infection with *Vibrio cholerae*.
#'         I. Clinical, serologic, and bacteriologic responses to a known inoculum.
#'         *J Infect Dis* 129(1):45-52.
#'   \item Levine MM, et al. (1981). Volunteer studies in development of vaccines
#'         against cholera and enterotoxigenic *Escherichia coli*: a review.
#'         In: Holme T, et al., eds. *Acute Enteric Infections in Children*.
#'   \item Levine MM, et al. (1988). Safety, immunogenicity, and efficacy of
#'         recombinant live oral cholera vaccines, CVD 103 and CVD 103-HgR.
#'         *Lancet* 2(8609):467-70.
#'   \item Tacket CO, et al. (1999). Initial clinical studies of CVD 112 *V.cholerae*
#'         O139 live oral vaccine. *Infect Immun* 67(12):6346-49.
#'   \item Haas CN, Rose JB, Gerba CP (1999). *Quantitative Microbial Risk
#'         Assessment*. Wiley, New York.
#'   \item Codeco CT (2001). Endemic and epidemic dynamics of cholera: the role
#'         of the aquatic reservoir. *BMC Infect Dis* 1:1.
#'   \item Hartley DM, Morris JG, Smith DL (2006). Hyperinfectivity: a critical
#'         element in the ability of *V. cholerae* to cause epidemics? *PLoS Med*
#'         3(1):e7.
#'   \item Kaper JB, Morris JG, Levine MM (1995). Cholera. *Clin Microbiol Rev*
#'         8(1):48-86.
#'   \item Nelson EJ, Harris JB, Morris JG, Calderwood SB, Camilli A (2009).
#'         Cholera transmission: the host, pathogen and bacteriophage dynamic.
#'         *Nat Rev Microbiol* 7(10):693-702.
#'   \item QMRA Wiki: *Vibrio cholerae* dose-response models.
#'         https://qmrawiki.org/experiments/vibrio-cholerae
#' }
#'
#' @examples
#' \dontrun{
#' PATHS <- get_paths()
#' est_kappa_prior(PATHS)
#' }
#'
#' @importFrom stats dlnorm qlnorm weighted.mean
#' @importFrom utils write.csv
#' @importFrom ggplot2 ggplot aes geom_point geom_errorbar geom_vline geom_line
#'             geom_ribbon geom_hline geom_rug scale_x_log10 scale_y_continuous
#'             scale_color_manual scale_fill_manual scale_size_continuous
#'             scale_alpha_manual labs theme_classic theme element_text
#'             element_line element_blank annotation_logticks annotate margin
#' @importFrom cowplot plot_grid
#' @importFrom grDevices png dev.off
#' @export

est_kappa_prior <- function(PATHS) {

     requireNamespace("ggplot2")
     requireNamespace("cowplot")

     #--------------------------------------------------------------------------
     # 1. Literature meta-analysis table
     #
     # Each row is one published estimate of the V. cholerae ID50 (or a value
     # adopted by convention for kappa in a cholera model). Columns:
     #   id50        : point estimate of ID50 in CFU
     #   id50_lo/hi  : approximate 95% uncertainty bounds
     #   weight      : evidentiary weight used in the weighted lognormal fit.
     #                 Weights reflect how directly the source informs the
     #                 environmental half-saturation kappa under typical
     #                 endemic exposure (buffered via food or water). Model-
     #                 convention values and the hyperinfectious extreme are
     #                 shown for context (weight 0) but excluded from the fit,
     #                 as they are either derived from the same primary data
     #                 (circularity) or represent a transient sub-population.
     #   endpoint    : clinical definition of infection in the source
     #--------------------------------------------------------------------------

     data_df <- data.frame(
          source         = c("Hornick 1971 (buffered)",
                             "Hornick 1971 (water only)",
                             "Cash 1974",
                             "Levine 1981",
                             "Levine 1988",
                             "Tacket 1999",
                             "Haas/QMRA 1999 (disease)",
                             "Nelson 2009 (water)",
                             "Nelson 2009 (with food)",
                             "Kaper 1995 review",
                             "Codeco 2001 (model)",
                             "Hartley 2006 (non-HI)",
                             "Hartley 2006 (HI)"),
          author_year    = c("Hornick et al. 1971",
                             "Hornick et al. 1971",
                             "Cash et al. 1974",
                             "Levine et al. 1981",
                             "Levine et al. 1988",
                             "Tacket et al. 1999",
                             "Haas, Rose & Gerba 1999",
                             "Nelson et al. 2009",
                             "Nelson et al. 2009",
                             "Kaper, Morris & Levine 1995",
                             "Codeco 2001",
                             "Hartley, Morris & Smith 2006",
                             "Hartley, Morris & Smith 2006"),
          strain         = c("O1 Classical Inaba 569B",
                             "O1 Classical Inaba 569B",
                             "O1 El Tor N16961",
                             "O1 Classical",
                             "O1 El Tor CVD 103-HgR challenge",
                             "O139",
                             "O1 Classical (Hornick data)",
                             "O1 (review)",
                             "O1 (review)",
                             "O1 (review)",
                             "generic (model kappa)",
                             "O1 non-hyperinfectious (model)",
                             "O1 hyperinfectious (model)"),
          exposure       = c("NaHCO3 buffered",
                             "unbuffered water",
                             "NaHCO3 buffered",
                             "NaHCO3 buffered",
                             "NaHCO3 buffered",
                             "NaHCO3 buffered",
                             "NaHCO3 buffered",
                             "water, healthy adults",
                             "food vehicle",
                             "mixed",
                             "environmental reservoir",
                             "environmental reservoir",
                             "freshly shed / hyperinfectious"),
          endpoint       = c("clinical cholera (diarrhoea)",
                             "clinical cholera (diarrhoea)",
                             "clinical cholera",
                             "diarrhoeal illness",
                             "diarrhoeal illness",
                             "moderate/severe diarrhoea",
                             "Beta-Poisson disease endpoint",
                             "clinical review",
                             "clinical review",
                             "clinical review",
                             "50% infection probability",
                             "50% infection probability",
                             "50% infection probability"),
          n_volunteers   = c(30, 4, 6, 8, 12, 15, NA, NA, NA, NA, NA, NA, NA),
          # Point estimates of ID50 (CFU)
          id50           = c(1e6, 1e11, 5e5, 1e4, 1e5, 1e5,
                             1e6, 1e5, 1e3, 1e5, 1e6, 1e6, 1e3),
          # Approximate 95% bounds from reported dose-response spread
          id50_lo        = c(1e5, 1e10, 1e5, 1e3, 1e4, 1e4,
                             1e5, 1e3, 1e2, 1e4, 1e5, 1e5, 1e2),
          id50_hi        = c(1e8, 1e12, 1e6, 1e5, 1e6, 1e6,
                             1e8, 1e8, 1e4, 1e6, 1e7, 1e7, 1e4),
          # Evidentiary weight. The fit is anchored on buffered human-
          # volunteer-challenge studies (weight 1.0). The QMRA Beta-Poisson
          # synthesis (Haas 1999) is a re-fit of Hornick's primary data and
          # is therefore down-weighted to 0.5 to avoid double-counting.
          # Expert-review summaries of buffered conditions get weight 0.5.
          # Unbuffered water-only exposure (Hornick water, Nelson water
          # range) is atypical of endemic transmission and enters the plot
          # only as context (weight 0). Food-vehicle entry (Nelson) is kept
          # at 0.25 as a low-end anchor. Model-convention values and the
          # hyperinfectious state are shown for context (weight 0) — they
          # are either downstream of the same primary data or represent a
          # transient sub-population, not kappa.
          weight         = c(1.00, 0.00, 1.00, 1.00, 1.00, 1.00,
                             0.50, 0.00, 0.25, 0.50, 0.00, 0.00, 0.00),
          study_type     = c("Volunteer challenge",
                             "Volunteer challenge",
                             "Volunteer challenge",
                             "Volunteer challenge",
                             "Volunteer challenge",
                             "Volunteer challenge",
                             "QMRA synthesis",
                             "Expert review",
                             "Expert review",
                             "Expert review",
                             "Model convention",
                             "Model convention",
                             "Model convention"),
          stringsAsFactors = FALSE
     )



     #--------------------------------------------------------------------------
     # 2. Weighted lognormal fit on log10 scale
     #--------------------------------------------------------------------------

     fit_df <- data_df[data_df$weight > 0, ]
     log10_id50 <- log10(fit_df$id50)
     w          <- fit_df$weight

     # Weighted geometric mean and SD on log10 scale
     mu_log10    <- stats::weighted.mean(log10_id50, w)
     var_log10   <- sum(w * (log10_id50 - mu_log10)^2) / sum(w)
     sigma_log10 <- sqrt(var_log10)

     # Convert log10 moments to natural-log (lognormal) parameters
     meanlog <- mu_log10    * log(10)
     sdlog   <- sigma_log10 * log(10)

     # Lognormal summary statistics
     lognormal_median <- exp(meanlog)
     lognormal_mode   <- exp(meanlog - sdlog^2)
     lognormal_mean   <- exp(meanlog + sdlog^2 / 2)
     ci_lower         <- stats::qlnorm(0.025, meanlog = meanlog, sdlog = sdlog)
     ci_upper         <- stats::qlnorm(0.975, meanlog = meanlog, sdlog = sdlog)

     fit <- list(
          meanlog    = meanlog,
          sdlog      = sdlog,
          median     = lognormal_median,
          mode       = lognormal_mode,
          mean       = lognormal_mean,
          ci_lower   = ci_lower,
          ci_upper   = ci_upper,
          n_sources  = nrow(fit_df),
          mu_log10   = mu_log10,
          sd_log10   = sigma_log10
     )



     #--------------------------------------------------------------------------
     # 3. Prediction grid (lognormal density) and parameter data frame
     #--------------------------------------------------------------------------

     x_vals <- 10 ^ seq(1, 13, length.out = 1000)
     # Density on the natural-value scale (dlnorm) AND on the log10-x scale
     # (Gaussian in log10 kappa). The log10-scale density is what produces a
     # symmetric bell curve on a log-x plot and is better for visualisation.
     pred_df <- data.frame(
          kappa           = x_vals,
          log10_kappa     = log10(x_vals),
          density         = stats::dlnorm(x_vals, meanlog = meanlog, sdlog = sdlog),
          density_log10   = stats::dnorm(log10(x_vals),
                                         mean = mu_log10, sd = sigma_log10)
     )

     param_df <- make_param_df(
          variable_name          = "kappa",
          variable_description   = "V. cholerae environmental dose-response half-saturation constant (CFU); concentration giving 50% infection probability",
          parameter_distribution = c("point", "point", "point", "point",
                                     "lognormal", "lognormal"),
          parameter_name         = c("low", "median", "mode", "high",
                                     "meanlog", "sdlog"),
          parameter_value        = c(ci_lower, lognormal_median, lognormal_mode, ci_upper,
                                     meanlog, sdlog)
     )



     #--------------------------------------------------------------------------
     # 4. Save data, predictions, and parameter priors to MODEL_INPUT
     #--------------------------------------------------------------------------

     dir.create(PATHS$MODEL_INPUT, recursive = TRUE, showWarnings = FALSE)
     dir.create(PATHS$DOCS_FIGURES, recursive = TRUE, showWarnings = FALSE)

     path_data <- file.path(PATHS$MODEL_INPUT, "data_kappa_prior.csv")
     utils::write.csv(data_df, path_data, row.names = FALSE)
     message("Kappa literature meta-analysis saved to: ", path_data)

     path_pred <- file.path(PATHS$MODEL_INPUT, "pred_kappa_prior.csv")
     utils::write.csv(pred_df, path_pred, row.names = FALSE)
     message("Kappa prior density grid saved to: ", path_pred)

     path_param <- file.path(PATHS$MODEL_INPUT, "param_kappa_prior.csv")
     utils::write.csv(param_df, path_param, row.names = FALSE)
     message("Kappa prior parameters saved to: ", path_param)



     #--------------------------------------------------------------------------
     # 5. Print summary
     #--------------------------------------------------------------------------

     cat("\n=== FITTED PRIOR: kappa (V. cholerae ID50, CFU) ===\n")
     cat(sprintf("  Sources included  : %d (of %d; hyperinfectious excluded)\n",
                 nrow(fit_df), nrow(data_df)))
     cat(sprintf("  Weighted log10 mean : %.3f  (10^%.2f = %.2e CFU)\n",
                 mu_log10, mu_log10, 10^mu_log10))
     cat(sprintf("  Weighted log10 SD   : %.3f  (%.1f-fold 1-sigma spread)\n",
                 sigma_log10, 10^sigma_log10))
     cat(sprintf("  Lognormal meanlog   : %.4f\n", meanlog))
     cat(sprintf("  Lognormal sdlog     : %.4f\n", sdlog))
     cat(sprintf("  Median (CFU)        : %.2e\n", lognormal_median))
     cat(sprintf("  Mode   (CFU)        : %.2e\n", lognormal_mode))
     cat(sprintf("  95%% CI (CFU)        : [%.2e, %.2e]\n", ci_lower, ci_upper))
     cat("\n")



     #--------------------------------------------------------------------------
     # 6. Paper-quality figure: sources forest + fitted density
     #--------------------------------------------------------------------------

     study_pal <- c("Volunteer challenge" = "#1B4F72",
                    "QMRA synthesis"      = "#117A65",
                    "Expert review"       = "#B9770E",
                    "Model convention"    = "#7D3C98")

     plot_df <- data_df
     plot_df$study_type <- factor(plot_df$study_type,
                                  levels = names(study_pal))
     # Preserve table order on y-axis but reverse so first row appears at top
     plot_df$source <- factor(plot_df$source,
                              levels = rev(data_df$source))
     # Indicate zero-weight (hyperinfectious) sources visually
     plot_df$weight_label <- ifelse(plot_df$weight == 0, "Excluded", "Included")



     # Panel A: forest-style plot of sources with uncertainty bars
     p_sources <-
          ggplot2::ggplot(plot_df,
                          ggplot2::aes(y = source, x = id50, colour = study_type)) +
          ggplot2::annotate("rect",
                            xmin  = ci_lower, xmax = ci_upper,
                            ymin  = -Inf,     ymax = Inf,
                            fill  = "grey85", alpha = 0.35) +
          ggplot2::geom_vline(xintercept = lognormal_median,
                              linetype = "solid", colour = "grey30", linewidth = 0.6) +
          ggplot2::geom_vline(xintercept = c(ci_lower, ci_upper),
                              linetype = "dashed", colour = "grey40", linewidth = 0.4) +
          ggplot2::geom_errorbar(ggplot2::aes(xmin = id50_lo, xmax = id50_hi,
                                              alpha = weight_label),
                                 orientation = "y", width = 0, linewidth = 0.6) +
          ggplot2::geom_point(ggplot2::aes(size = weight, alpha = weight_label)) +
          ggplot2::scale_x_log10(limits = c(1e1, 1e13),
                                 breaks = 10 ^ seq(1, 13, by = 2),
                                 labels = c(expression(10^1), expression(10^3),
                                            expression(10^5), expression(10^7),
                                            expression(10^9), expression(10^11),
                                            expression(10^13))) +
          ggplot2::scale_color_manual(values = study_pal, name = "Study type") +
          ggplot2::scale_size_continuous(range = c(2, 4.5), guide = "none") +
          ggplot2::scale_alpha_manual(values = c("Included" = 1, "Excluded" = 0.35),
                                      name = "") +
          ggplot2::annotation_logticks(sides = "b", short = ggplot2::unit(0.05, "cm"),
                                       mid = ggplot2::unit(0.1, "cm"),
                                       long = ggplot2::unit(0.15, "cm")) +
          ggplot2::labs(title = expression("A. Published estimates of " * italic(V.~cholerae) * " ID"[50]),
                        x = expression(kappa ~ "  (CFU, log scale)"),
                        y = NULL) +
          ggplot2::theme_classic(base_size = 13) +
          ggplot2::theme(
               legend.position   = "right",
               legend.key.height = ggplot2::unit(0.5, "cm"),
               legend.title      = ggplot2::element_text(size = 11, face = "bold"),
               panel.grid.major.x = ggplot2::element_line(colour = "grey92",
                                                          linewidth = 0.3),
               panel.grid.minor  = ggplot2::element_blank(),
               axis.title.x      = ggplot2::element_text(margin = ggplot2::margin(t = 8)),
               axis.text.y       = ggplot2::element_text(size = 10),
               plot.title        = ggplot2::element_text(face = "bold", size = 14,
                                                         margin = ggplot2::margin(b = 8))
          )



     # Panel B: fitted lognormal density with source positions as rug
     rug_df <- fit_df[, c("id50", "study_type", "weight")]
     rug_df$study_type <- factor(rug_df$study_type, levels = names(study_pal))

     peak_density <- max(pred_df$density_log10)

     p_density <-
          ggplot2::ggplot() +
          ggplot2::geom_ribbon(data = pred_df,
                               ggplot2::aes(x = kappa, ymin = 0, ymax = density_log10),
                               fill = "#1B4F72", alpha = 0.25) +
          ggplot2::geom_line(data = pred_df,
                             ggplot2::aes(x = kappa, y = density_log10),
                             colour = "#1B4F72", linewidth = 1) +
          ggplot2::geom_vline(xintercept = lognormal_median,
                              linetype = "solid", colour = "grey20", linewidth = 0.6) +
          ggplot2::geom_vline(xintercept = c(ci_lower, ci_upper),
                              linetype = "dashed", colour = "grey40", linewidth = 0.4) +
          ggplot2::geom_rug(data = rug_df,
                            ggplot2::aes(x = id50, colour = study_type),
                            sides = "b", length = ggplot2::unit(0.04, "npc"),
                            linewidth = 0.8, alpha = 0.9) +
          ggplot2::scale_x_log10(limits = c(1e1, 1e13),
                                 breaks = 10 ^ seq(1, 13, by = 2),
                                 labels = c(expression(10^1), expression(10^3),
                                            expression(10^5), expression(10^7),
                                            expression(10^9), expression(10^11),
                                            expression(10^13))) +
          ggplot2::scale_y_continuous(limits = c(0, peak_density * 1.35),
                                      expand = c(0, 0)) +
          ggplot2::scale_color_manual(values = study_pal, name = "Study type",
                                      guide = "none") +
          ggplot2::annotation_logticks(sides = "b", short = ggplot2::unit(0.05, "cm"),
                                       mid = ggplot2::unit(0.1, "cm"),
                                       long = ggplot2::unit(0.15, "cm")) +
          ggplot2::annotate("text",
                            x = lognormal_median, y = peak_density * 1.08,
                            label = sprintf("median\n%.1e", lognormal_median),
                            hjust = 0.5, vjust = 0, size = 3.4, colour = "grey20",
                            lineheight = 0.9) +
          ggplot2::annotate("text",
                            x = ci_lower, y = peak_density * 0.55,
                            label = sprintf("2.5%%\n%.1e", ci_lower),
                            hjust = 1.15, vjust = 0.5, size = 3.1, colour = "grey40",
                            lineheight = 0.9) +
          ggplot2::annotate("text",
                            x = ci_upper, y = peak_density * 0.55,
                            label = sprintf("97.5%%\n%.1e", ci_upper),
                            hjust = -0.15, vjust = 0.5, size = 3.1, colour = "grey40",
                            lineheight = 0.9) +
          ggplot2::annotate("text",
                            x = 10^1.3, y = peak_density * 1.25,
                            hjust = 0, vjust = 0.5, size = 3.6, colour = "#1B4F72",
                            label = sprintf("Lognormal(meanlog = %.2f, sdlog = %.2f)",
                                            meanlog, sdlog)) +
          ggplot2::labs(title = "B. Fitted prior",
                        x = expression(kappa ~ "  (CFU, log scale)"),
                        y = expression("Density (per log"[10] ~ kappa * ")")) +
          ggplot2::theme_classic(base_size = 13) +
          ggplot2::theme(
               panel.grid.major.x = ggplot2::element_line(colour = "grey92",
                                                          linewidth = 0.3),
               panel.grid.minor   = ggplot2::element_blank(),
               axis.title.x       = ggplot2::element_text(margin = ggplot2::margin(t = 8)),
               axis.title.y       = ggplot2::element_text(margin = ggplot2::margin(r = 8)),
               plot.title         = ggplot2::element_text(face = "bold", size = 14,
                                                          margin = ggplot2::margin(b = 8))
          )



     combo <- cowplot::plot_grid(p_sources, p_density,
                                 ncol = 1, align = "v", rel_heights = c(1.35, 1))

     figure_path <- file.path(PATHS$DOCS_FIGURES, "kappa_prior.png")
     grDevices::png(filename = figure_path, width = 2800, height = 2800,
                    units = "px", res = 300)
     print(combo)
     grDevices::dev.off()
     message("Kappa prior figure saved to: ", figure_path)

     invisible(list(data = data_df, fit = fit, param_df = param_df,
                    prediction = pred_df))
}
