#' Get Seasonal Dynamics Data for Cholera and Precipitation
#'
#' This function retrieves historical precipitation data, processes cholera case data, fits seasonal dynamics models using Fourier series,
#' and saves the results to a CSV file.
#'
#' @param PATHS A list containing paths where raw and processed data are stored. Typically generated by the `get_paths()` function.
#'
#' @return The function saves the parameter estimates, fitted values, and processed data as CSV files.
#'
#' @importFrom dplyr select mutate group_by summarize filter bind_rows
#' @importFrom tidyr spread
#' @importFrom lubridate week year
#' @importFrom sf st_read st_coordinates
#' @importFrom utils write.csv read.csv
#' @importFrom glue glue
#' @importFrom ggplot2 ggplot geom_sf labs theme_minimal
#' @importFrom minpack.lm nlsLM
#' @export

est_seasonal_dynamics <- function(PATHS) {

     iso_codes <- MOSAIC::iso_codes_mosaic

     # Load cholera cases data
     cholera_data <- utils::read.csv(file.path(PATHS$DATA_WHO_WEEKLY, "cholera_country_weekly_processed.csv"), stringsAsFactors = FALSE)

     iso_codes_with_data <- sort(unique(cholera_data$iso_code))
     iso_codes_no_data <- setdiff(iso_codes, unique(cholera_data$iso_code))

     all_precip_data <- list()
     all_fitted_values <- list()
     all_param_values <- list()

     for (country_iso_code in iso_codes) {

          message(glue::glue("Processing country: {country_iso_code}"))


          # instead load climate data

          country_shp <- sf::st_read(file.path(PATHS$DATA_SHAPEFILES, paste0(country_iso_code, "_ADM0.shp")), quiet = TRUE)
          grid_points <- MOSAIC::generate_country_grid_n(country_shp, n_points = 10)
          coords <- sf::st_coordinates(grid_points)
          coords <- as.data.frame(coords)

          precipitation_data_list <- list()

          for (i in seq_len(nrow(coords))) {
               lat <- coords$Y[i]
               lon <- coords$X[i]

               precip_data <- get_historical_precip(lat, lon, as.Date("2014-09-01"), as.Date("2024-09-01"), api_key = "your_api_key_here")
               precip_data$year <- lubridate::year(precip_data$date)
               precip_data$week <- lubridate::week(precip_data$date)

               weekly_precip <- precip_data %>%
                    dplyr::group_by(year, week) %>%
                    dplyr::summarize(weekly_precipitation_sum = sum(daily_precipitation_sum, na.rm = TRUE))

               weekly_precip$iso_code <- country_iso_code
               precipitation_data_list[[i]] <- weekly_precip
          }

          precip_data <- do.call(rbind, precipitation_data_list)
          precip_data <- merge(precip_data, cholera_data, by = c("week", "iso_code"), all.x = TRUE)

          # Scale precipitation and cholera data
          precip_data <- precip_data %>%
               dplyr::mutate(precip_scaled = scale(weekly_precipitation_sum),
                             cases_scaled = scale(cases))

          # Fit Fourier series model for precipitation
          fit_precip <- minpack.lm::nlsLM(
               precip_scaled ~ generalized_fourier(week, beta0, a1, b1, a2, b2, p = 52),
               data = precip_data,
               start = list(beta0 = 0, a1 = 1, b1 = 1, a2 = 0.5, b2 = 0.5)
          )

          param_precip <- coef(summary(fit_precip))
          param_values_precip <- data.frame(
               country_iso_code = country_iso_code,
               response = "precipitation",
               parameter = rownames(param_precip),
               mean = param_precip[,"Estimate"],
               se = param_precip[,"Std. Error"],
               ci_lo = param_precip[,"Estimate"] - param_precip[,"Std. Error"] * 1.96,
               ci_hi = param_precip[,"Estimate"] + param_precip[,"Std. Error"] * 1.96
          )

          all_param_values[[country_iso_code]] <- param_values_precip
          all_precip_data[[country_iso_code]] <- precip_data
     }

     combined_param_values <- do.call(rbind, all_param_values)
     utils::write.csv(combined_param_values, file = file.path(PATHS$MODEL_INPUT, "combined_param_values.csv"), row.names = FALSE)
     message("Parameter values saved.")
}
