#' Estimate Prior Distribution for the Shedding Ratio (zeta_ratio = zeta_1 / zeta_2)
#'
#' Fits a lognormal prior for the per-person-per-day symptomatic-to-
#' asymptomatic shedding ratio \eqn{\zeta_{\mathrm{ratio}} = \zeta_1 / \zeta_2}
#' used in `sample_parameters()` to derive \eqn{\zeta_2 = \zeta_1 / \zeta_{\mathrm{ratio}}}
#' at sampling time (which guarantees \eqn{\zeta_1 > \zeta_2} algebraically).
#'
#' The function produces THREE candidate lognormal fits and writes the
#' precision-weighted combined prior:
#' \itemize{
#'   \item \strong{(A) Direct channel}: weighted-MLE lognormal on literature
#'         ratio anchors (Smith 2026 medRxiv, Nelson 2009 paired, Kaper 1995,
#'         Harris 2012, Chao 2011, Finger 2018, Righetto 2012, Sugimoto 2014,
#'         MOSAIC calibration).
#'   \item \strong{(B) Derived channel}: paired Monte-Carlo lognormal from
#'         the fitted \eqn{\zeta_1} / \eqn{\zeta_2} marginals, with a
#'         paired-bootstrap step on the shared Nelson 2009 anchor.
#'   \item \strong{(C) Combined}: precision-weighted (inverse-variance)
#'         lognormal combination of (A) and (B). This is what is written
#'         into `priors_default$parameters_global$zeta_ratio`.
#' }
#'
#' @param PATHS A list of paths generated by `get_paths()`. Must include:
#' \itemize{
#'   \item \strong{MODEL_INPUT}: directory where parameter CSVs are saved.
#'   \item \strong{DOCS_FIGURES}: directory where the summary figure is saved.
#' }
#' @param zeta_1_fit Either `NULL`, the full list returned by
#'   `est_zeta_1_prior()`, or the `$fit` sublist with at least `meanlog`
#'   and `sdlog`. If `NULL`, `est_zeta_1_prior(PATHS)` is called internally.
#' @param zeta_2_fit Same contract as `zeta_1_fit`; calls `est_zeta_2_prior(PATHS)`
#'   if `NULL`.
#' @param n_sim Integer. Monte-Carlo sample size for the derived channel.
#'   Default `100000L`.
#' @param seed Integer. Random-number seed for reproducible paired-bootstrap
#'   MC. Default `1L`. Byte-equality of the written `priors_default.json`
#'   across builds requires an identical seed.
#' @param diagnostic_candidate_fits Logical. If `TRUE`, attempt skew-normal /
#'   Student-t / generalised-normal diagnostic fits via `fitdistrplus`.
#'   Default `FALSE`. Requires the optional `fitdistrplus` package; if the
#'   package is not installed a message is emitted and `$diagnostics$candidate_fits`
#'   remains `NULL`.
#'
#' @return Invisibly returns a list with elements:
#' \itemize{
#'   \item \code{data}: direct-literature anchor table (Table 7.A).
#'   \item \code{fit}: combined (C) lognormal parameters (`meanlog`, `sdlog`,
#'         `median`, `mode`, `mean`, `ci_lower`, `ci_upper`).
#'   \item \code{param_df}: long-format parameter data frame (as saved to disk).
#'   \item \code{prediction}: density grid for the direct, derived and
#'         combined channels (tagged via the `channel` column).
#'   \item \code{diagnostics}: a list with `fit_direct`, `fit_derived`,
#'         `fit_combined`, `ratio_sample` (paired-bootstrap MC draws on the
#'         log10 scale), `analytic_check` (independent-lognormal closed form,
#'         cross-check only), and `candidate_fits`.
#' }
#'
#' @details
#' \strong{Direct channel (A).} Weighted MLE on log10 of the literature
#' ratio anchors in the direct-ratio table. The anchors span ~1.6x
#' (Smith 2026 household per-person-day) to ~10^5 (Nelson 2009 paired
#' stool concentrations). This spread reflects genuinely different
#' quantities (household transmission probability vs stool concentration
#' ratio) and is preserved in the fit's `sdlog`.
#'
#' \strong{Derived channel (B).} If \eqn{\zeta_1 \sim \mathrm{LN}(\mu_1, \sigma_1^2)}
#' and \eqn{\zeta_2 \sim \mathrm{LN}(\mu_2, \sigma_2^2)} are independent,
#' their ratio is exactly \eqn{\mathrm{LN}(\mu_1 - \mu_2, \sigma_1^2 + \sigma_2^2)}.
#' The derived channel uses this analytic closed form directly. Nelson 2009
#' is a shared primary source for both marginals, which would in principle
#' induce positive correlation and reduce the ratio's variance, but
#' correctly propagating that requires decomposing each marginal's variance
#' into a Nelson-attributable component and a residual independent
#' component -- a subjective attribution that is not well-supported by the
#' available literature. The closed-form variance
#' \eqn{\sigma_1^2 + \sigma_2^2} is therefore a conservative upper bound on
#' the true derived-channel spread. A 100,000-draw Monte Carlo sample of the
#' ratio distribution is generated for the diagnostic figure and returned
#' in \code{$diagnostics$ratio_sample}; it does not enter the fit
#' statistics.
#'
#' \strong{Combined channel (C).} Given direct and derived fits
#' \eqn{\mathrm{LN}(\mu_A, \sigma_A^2)} and \eqn{\mathrm{LN}(\mu_B, \sigma_B^2)},
#' the precision-weighted mean on the log scale is
#' \deqn{\mu_C = \frac{\mu_A / \sigma_A^2 + \mu_B / \sigma_B^2}{1/\sigma_A^2 + 1/\sigma_B^2}, \quad \sigma_C = \left(1/\sigma_A^2 + 1/\sigma_B^2\right)^{-1/2}}
#' This is the Bayesian posterior for the log-ratio under flat priors
#' when both channels are treated as independent normal likelihoods.
#'
#' \strong{Smith 2026 dose-response note.} Smith et al. 2026
#' (medRxiv) report an odds ratio of 0.60 (95 percent CI 0.11-3.23) for
#' household transmission with asymptomatic vs symptomatic index cases,
#' giving an inverse transmission ratio of ~1.6. Under a near-linear Hill
#' dose-response regime and equal contact patterns this is compatible with
#' a low per-person-per-day `zeta_ratio`. The value is included at
#' weight 0.5 alongside Nelson's 10^5 stool-concentration ratio so the
#' reader can see the tension.
#'
#' \strong{fitdistrplus dependency.} This function does NOT import
#' `fitdistrplus`. If `diagnostic_candidate_fits = TRUE` the package is
#' loaded via `requireNamespace()` with a graceful fallback; this follows
#' the pattern at `R/est_initial_R.R:704-710`.
#'
#' @references
#' \itemize{
#'   \item Smith CP, Lessler J, Hegde ST, et al. (2026). Estimating the
#'         transmission potential of symptomatic and asymptomatic cholera
#'         cases from household microbiological and clinical data. *medRxiv*.
#'   \item Nelson EJ, et al. (2009). *Nat Rev Microbiol* 7(10):693-702.
#'   \item Chao DL, Halloran ME, Longini IM (2011). Vaccination strategies
#'         for epidemic cholera in Haiti. *PNAS* 108(17):7081-85.
#'   \item Finger F, Bertuzzo E, Luquero FJ, et al. (2018). The potential
#'         impact of case-area targeted interventions in response to cholera
#'         outbreaks. *PLoS Med* 15(2):e1002509.
#'   \item Righetto L, Casagrandi R, Bertuzzo E, et al. (2012). The role of
#'         aquatic reservoir fluctuations in long-term cholera patterns.
#'         *Epidemics* 4(1):33-42.
#'   \item Sugimoto JD, Koepke AA, Kenah E, et al. (2014). Household
#'         transmission of V. cholerae in Bangladesh. *PLoS NTD* 8(11):e3314.
#'   \item Kaper JB, Morris JG, Levine MM (1995). Cholera. *Clin Microbiol Rev*
#'         8(1):48-86.
#'   \item Harris JB, et al. (2012). Cholera. *Lancet* 379(9835):2466-76.
#' }
#'
#' @examples
#' \dontrun{
#' PATHS <- get_paths()
#' z1 <- est_zeta_1_prior(PATHS)
#' z2 <- est_zeta_2_prior(PATHS)
#' est_zeta_ratio_prior(PATHS, zeta_1_fit = z1, zeta_2_fit = z2)
#' }
#'
#' @importFrom stats dlnorm qlnorm weighted.mean rlnorm rnorm dnorm sd
#' @importFrom utils write.csv
#' @importFrom ggplot2 ggplot aes geom_point geom_errorbar geom_vline geom_line
#'             geom_ribbon geom_hline geom_rug scale_x_log10 scale_y_continuous
#'             scale_color_manual scale_fill_manual scale_size_continuous
#'             scale_alpha_manual scale_linetype_manual
#'             labs theme_classic theme element_text
#'             element_line element_blank annotation_logticks annotate margin
#' @importFrom cowplot plot_grid
#' @importFrom grDevices png dev.off
#' @export

est_zeta_ratio_prior <- function(PATHS,
                                 zeta_1_fit = NULL,
                                 zeta_2_fit = NULL,
                                 n_sim      = 100000L,
                                 seed       = 1L,
                                 diagnostic_candidate_fits = FALSE) {

     requireNamespace("ggplot2")
     requireNamespace("cowplot")

     # Validate n_sim / seed
     if (!is.numeric(n_sim) || length(n_sim) != 1 || n_sim < 100) {
          stop("`n_sim` must be a single positive integer >= 100.", call. = FALSE)
     }
     n_sim <- as.integer(n_sim)
     if (!is.numeric(seed) || length(seed) != 1) {
          stop("`seed` must be a single integer.", call. = FALSE)
     }
     seed <- as.integer(seed)

     # Validate / unwrap fit inputs (accepts full return list or $fit sublist)
     .extract_fit <- function(x, arg_name) {
          if (is.null(x)) return(NULL)
          if (!is.null(x$fit)) x <- x$fit
          required <- c("meanlog", "sdlog")
          missing  <- setdiff(required, names(x))
          if (length(missing) > 0) {
               stop(sprintf("`%s` is missing required field(s): %s",
                            arg_name, paste(missing, collapse = ", ")),
                    call. = FALSE)
          }
          x
     }

     z1 <- .extract_fit(zeta_1_fit, "zeta_1_fit")
     z2 <- .extract_fit(zeta_2_fit, "zeta_2_fit")

     if (is.null(z1)) {
          message("est_zeta_ratio_prior: zeta_1_fit not supplied; ",
                  "calling est_zeta_1_prior() internally.")
          z1_res <- est_zeta_1_prior(PATHS)
          z1     <- z1_res$fit
     }
     if (is.null(z2)) {
          message("est_zeta_ratio_prior: zeta_2_fit not supplied; ",
                  "calling est_zeta_2_prior() internally.")
          z2_res <- est_zeta_2_prior(PATHS)
          z2     <- z2_res$fit
     }

     #--------------------------------------------------------------------------
     # 1. Direct-literature anchor table (Table 7.A)
     #--------------------------------------------------------------------------

     data_df <- data.frame(
          source         = c("Smith 2026 (household per-person-day)",
                             "Nelson 2009 paired severe/asymp",
                             "Kaper 1995 paired ranges",
                             "Harris 2012 paired severe/asymp",
                             "Chao 2011 modelling",
                             "Finger 2018 modelling",
                             "Righetto 2012 modelling",
                             "Sugimoto 2014 household",
                             "MOSAIC single-stage calibration posterior"),
          author_year    = c("Smith et al. 2026",
                             "Nelson et al. 2009",
                             "Kaper, Morris & Levine 1995",
                             "Harris et al. 2012",
                             "Chao, Halloran & Longini 2011",
                             "Finger et al. 2018",
                             "Righetto et al. 2012",
                             "Sugimoto et al. 2014",
                             "MOSAIC MOZ single-stage"),
          ratio          = c(1.6, 1e5, 1e3, 1e5, 10, 10, 1, 3, 400),
          ratio_lo       = c(0.3, 1e4, 1e2, 1e4, 3, 3, 0.5, 1, 200),
          ratio_hi       = c(9.1, 1e6, 1e5, 1e6, 30, 30, 3, 10, 580),
          # v0.29.1 bias-correction:
          #   - Nelson 2009 paired (row 2):  1.00 -> 0.30
          #     (value 10^5 is a stool-CONCENTRATION ratio, not a per-day
          #     RATE ratio; correcting for stool-volume asymmetry would push
          #     it higher, but it is not the same quantity as zeta_ratio)
          #   - Kaper 1995 paired (row 3):   0.25 -> 0.10 (review overlaps Nelson)
          #   - Harris 2012 paired (row 4):  0.25 -> 0.10 (review overlaps Nelson)
          weight         = c(0.50, 0.30, 0.10, 0.10, 0.10, 0.10, 0.10, 0.25, 0.25),
          study_type     = c("Household cohort",
                             "Primary clinical",
                             "Expert review",
                             "Expert review",
                             "Model convention",
                             "Model convention",
                             "Model convention",
                             "Household cohort",
                             "Calibration posterior"),
          notes          = c("Direct primary-data per-person-per-day household transmission ratio; OR 0.60 (0.11-3.23) asymp-vs-symp inverted",
                             "Biological stool-concentration ratio (10^8/10^3); primary source for both ends",
                             "Expert review; overlaps Nelson paired",
                             "Modern clinical seminar",
                             "Modelling convention (symptomatic shed 10x more)",
                             "Same convention as Chao 2011",
                             "Framework paper; parameter p defined but not quantified",
                             "Household SAR-based indirect ratio (same regime as Smith 2026)",
                             "Empirical posterior on current zeta_ratio (scale-caveat applies)"),
          stringsAsFactors = FALSE
     )

     #--------------------------------------------------------------------------
     # 2. Direct-channel fit (A): weighted MLE on log10(ratio)
     #--------------------------------------------------------------------------

     fit_df_A <- data_df[data_df$weight > 0, ]
     stopifnot("All direct-literature rows have weight 0" = sum(fit_df_A$weight) > 0)

     log10_r  <- log10(fit_df_A$ratio)
     w_A      <- fit_df_A$weight

     mu_log10_A    <- stats::weighted.mean(log10_r, w_A)
     var_log10_A   <- sum(w_A * (log10_r - mu_log10_A)^2) / sum(w_A)
     sigma_log10_A <- sqrt(var_log10_A)
     if (!is.finite(sigma_log10_A) || sigma_log10_A <= 0) sigma_log10_A <- 0.5
     meanlog_A <- mu_log10_A    * log(10)
     sdlog_A   <- sigma_log10_A * log(10)

     ci_lower_A <- stats::qlnorm(0.025, meanlog = meanlog_A, sdlog = sdlog_A)
     ci_upper_A <- stats::qlnorm(0.975, meanlog = meanlog_A, sdlog = sdlog_A)

     fit_direct <- list(
          meanlog   = meanlog_A,
          sdlog     = sdlog_A,
          median    = exp(meanlog_A),
          ci_lower  = ci_lower_A,
          ci_upper  = ci_upper_A,
          n_sources = nrow(fit_df_A)
     )

     #--------------------------------------------------------------------------
     # 3. Derived-channel fit (B): independent-lognormal analytic ratio
     #
     # Ratio of two independent lognormals is exactly lognormal:
     #   zeta_1 / zeta_2 ~ LN(mu_1 - mu_2, sqrt(sigma_1^2 + sigma_2^2))
     #
     # A paired-bootstrap that attempts to narrow variance by injecting a
     # shared Nelson-perturbation into BOTH marginals' meanlogs does not
     # actually work: the shared term cancels exactly in the log-ratio,
     # leaving the residual variance equal to sigma_1^2 + sigma_2^2 -- the
     # independent closed form. Properly handling the shared-source
     # correlation would require decomposing each marginal's variance into
     # "Nelson-attributable" and "residual" components (a subjective
     # attribution we do not attempt here). See plan_zeta_priors_
     # implementation.md revision history for the methodological note.
     #
     # We therefore use the analytic closed form as the derived channel.
     # A Monte Carlo sample is still drawn for the diagnostic figure and
     # for the sample artefact, but it does not enter the fit statistics.
     #--------------------------------------------------------------------------

     meanlog_B <- z1$meanlog - z2$meanlog
     sdlog_B   <- sqrt(z1$sdlog^2 + z2$sdlog^2)
     mu_log10_B    <- meanlog_B / log(10)
     sigma_log10_B <- sdlog_B   / log(10)

     ci_lower_B <- stats::qlnorm(0.025, meanlog = meanlog_B, sdlog = sdlog_B)
     ci_upper_B <- stats::qlnorm(0.975, meanlog = meanlog_B, sdlog = sdlog_B)

     fit_derived <- list(
          meanlog  = meanlog_B,
          sdlog    = sdlog_B,
          median   = exp(meanlog_B),
          ci_lower = ci_lower_B,
          ci_upper = ci_upper_B
     )

     # Monte Carlo sample of the derived-channel ratio distribution,
     # produced only for the diagnostic figure and the saved sample
     # artefact. Independent draws from the two marginals (no shared
     # perturbation) because the derived channel IS the independent-
     # lognormal ratio.
     set.seed(seed)
     zeta_1_s <- stats::rlnorm(n_sim, meanlog = z1$meanlog, sdlog = z1$sdlog)
     zeta_2_s <- stats::rlnorm(n_sim, meanlog = z2$meanlog, sdlog = z2$sdlog)
     ratio_s  <- zeta_1_s / zeta_2_s
     log10_ratio_s <- log10(ratio_s)
     log10_ratio_s <- log10_ratio_s[is.finite(log10_ratio_s)]

     # analytic_check retained for backward compatibility and to give the
     # reader a single named handle onto the derived formula.
     analytic_check <- list(meanlog = meanlog_B, sdlog = sdlog_B)

     #--------------------------------------------------------------------------
     # 4. Combined fit (C): precision-weighted lognormal
     #--------------------------------------------------------------------------

     prec_A <- 1 / sdlog_A^2
     prec_B <- 1 / sdlog_B^2
     meanlog_C <- (prec_A * meanlog_A + prec_B * meanlog_B) / (prec_A + prec_B)
     sdlog_C   <- sqrt(1 / (prec_A + prec_B))
     mu_log10_C    <- meanlog_C    / log(10)
     sigma_log10_C <- sdlog_C      / log(10)

     lognormal_median <- exp(meanlog_C)
     lognormal_mode   <- exp(meanlog_C - sdlog_C^2)
     lognormal_mean   <- exp(meanlog_C + sdlog_C^2 / 2)
     ci_lower         <- stats::qlnorm(0.025, meanlog = meanlog_C, sdlog = sdlog_C)
     ci_upper         <- stats::qlnorm(0.975, meanlog = meanlog_C, sdlog = sdlog_C)

     fit <- list(
          meanlog  = meanlog_C,
          sdlog    = sdlog_C,
          median   = lognormal_median,
          mode     = lognormal_mode,
          mean     = lognormal_mean,
          ci_lower = ci_lower,
          ci_upper = ci_upper
     )

     fit_combined <- list(
          meanlog  = meanlog_C,
          sdlog    = sdlog_C,
          median   = lognormal_median,
          ci_lower = ci_lower,
          ci_upper = ci_upper
     )

     #--------------------------------------------------------------------------
     # 4b. Optional candidate-family diagnostics (gated)
     #--------------------------------------------------------------------------

     candidate_fits <- NULL
     if (isTRUE(diagnostic_candidate_fits)) {
          if (!requireNamespace("fitdistrplus", quietly = TRUE)) {
               message("Install 'fitdistrplus' to get candidate-family diagnostics; ",
                       "returning NULL for `$candidate_fits`.")
          } else {
               # Normal on log10 scale is equivalent to lognormal on linear
               # scale, so we just record the MLE normal fit as a baseline.
               fit_norm <- tryCatch(
                    fitdistrplus::fitdist(log10_ratio_s, "norm"),
                    error = function(e) {
                         message("fitdist(norm) failed: ", e$message); NULL
                    }
               )
               candidate_fits <- list(
                    norm_log10 = if (!is.null(fit_norm))
                                      list(mean = unname(fit_norm$estimate["mean"]),
                                           sd   = unname(fit_norm$estimate["sd"]),
                                           loglik = fit_norm$loglik,
                                           aic    = fit_norm$aic)
                                 else NULL
               )
          }
     }

     #--------------------------------------------------------------------------
     # 5. Prediction grid - three overlaid density curves
     #--------------------------------------------------------------------------

     x_vals <- 10 ^ seq(-1, 12, length.out = 1000)

     pred_A <- data.frame(
          zeta_ratio       = x_vals,
          log10_zeta_ratio = log10(x_vals),
          density          = stats::dlnorm(x_vals, meanlog = meanlog_A, sdlog = sdlog_A),
          density_log10    = stats::dnorm(log10(x_vals), mean = mu_log10_A, sd = sigma_log10_A),
          channel          = "direct",
          stringsAsFactors = FALSE
     )
     pred_B <- data.frame(
          zeta_ratio       = x_vals,
          log10_zeta_ratio = log10(x_vals),
          density          = stats::dlnorm(x_vals, meanlog = meanlog_B, sdlog = sdlog_B),
          density_log10    = stats::dnorm(log10(x_vals), mean = mu_log10_B, sd = sigma_log10_B),
          channel          = "derived",
          stringsAsFactors = FALSE
     )
     pred_C <- data.frame(
          zeta_ratio       = x_vals,
          log10_zeta_ratio = log10(x_vals),
          density          = stats::dlnorm(x_vals, meanlog = meanlog_C, sdlog = sdlog_C),
          density_log10    = stats::dnorm(log10(x_vals), mean = mu_log10_C, sd = sigma_log10_C),
          channel          = "combined",
          stringsAsFactors = FALSE
     )
     pred_df <- rbind(pred_A, pred_B, pred_C)

     param_df <- make_param_df(
          variable_name          = "zeta_ratio",
          variable_description   = "Symptomatic-to-asymptomatic shedding ratio (zeta_1 / zeta_2); combined (C) lognormal",
          parameter_distribution = c("point", "point", "point", "point",
                                     "lognormal", "lognormal"),
          parameter_name         = c("low", "median", "mode", "high",
                                     "meanlog", "sdlog"),
          parameter_value        = c(ci_lower, lognormal_median, lognormal_mode, ci_upper,
                                     meanlog_C, sdlog_C)
     )

     #--------------------------------------------------------------------------
     # 6. Save data, predictions, and parameter priors to MODEL_INPUT
     #--------------------------------------------------------------------------

     dir.create(PATHS$MODEL_INPUT, recursive = TRUE, showWarnings = FALSE)
     dir.create(PATHS$DOCS_FIGURES, recursive = TRUE, showWarnings = FALSE)

     path_data <- file.path(PATHS$MODEL_INPUT, "data_zeta_ratio_prior.csv")
     utils::write.csv(data_df, path_data, row.names = FALSE)
     message("zeta_ratio direct-literature anchors saved to: ", path_data)

     path_pred <- file.path(PATHS$MODEL_INPUT, "pred_zeta_ratio_prior.csv")
     utils::write.csv(pred_df, path_pred, row.names = FALSE)
     message("zeta_ratio prior density grid saved to: ", path_pred)

     path_param <- file.path(PATHS$MODEL_INPUT, "param_zeta_ratio_prior.csv")
     utils::write.csv(param_df, path_param, row.names = FALSE)
     message("zeta_ratio prior parameters saved to: ", path_param)

     #--------------------------------------------------------------------------
     # 7. Print summary
     #--------------------------------------------------------------------------

     cat("\n=== FITTED PRIOR: zeta_ratio (zeta_1 / zeta_2, dimensionless) ===\n")
     cat(sprintf("  Direct (A)   : meanlog=%.3f, sdlog=%.3f, median=%.2e, n=%d\n",
                 meanlog_A, sdlog_A, exp(meanlog_A), fit_direct$n_sources))
     cat(sprintf("  Derived (B)  : meanlog=%.3f, sdlog=%.3f, median=%.2e  [analytic closed form; MC sample n=%d for diagnostics only]\n",
                 meanlog_B, sdlog_B, exp(meanlog_B), n_sim))
     cat(sprintf("  Analytic     : meanlog=%.3f, sdlog=%.3f (independent-lognormal cross-check; identical to derived by construction)\n",
                 analytic_check$meanlog, analytic_check$sdlog))
     cat(sprintf("  Combined (C) : meanlog=%.3f, sdlog=%.3f, median=%.2e\n",
                 meanlog_C, sdlog_C, lognormal_median))
     cat(sprintf("  95%% CI (C)   : [%.2e, %.2e]\n", ci_lower, ci_upper))
     cat("\n")

     #--------------------------------------------------------------------------
     # 8. Figure: forest + three overlaid density curves
     #--------------------------------------------------------------------------

     study_pal <- c("Primary clinical"        = "#1B4F72",
                    "Household cohort"        = "#117A65",
                    "Expert review"           = "#B9770E",
                    "Model convention"        = "#7D3C98",
                    "Calibration posterior"   = "#C0392B")

     plot_df <- data_df
     plot_df$study_type <- factor(plot_df$study_type,
                                  levels = names(study_pal))
     plot_df$source <- factor(plot_df$source,
                              levels = rev(data_df$source))
     plot_df$weight_label <- ifelse(plot_df$weight == 0, "Excluded", "Included")

     p_sources <-
          ggplot2::ggplot(plot_df,
                          ggplot2::aes(y = source, x = ratio, colour = study_type)) +
          ggplot2::annotate("rect",
                            xmin  = ci_lower, xmax = ci_upper,
                            ymin  = -Inf,     ymax = Inf,
                            fill  = "grey85", alpha = 0.35) +
          ggplot2::geom_vline(xintercept = lognormal_median,
                              linetype = "solid", colour = "grey30", linewidth = 0.6) +
          ggplot2::geom_vline(xintercept = c(ci_lower, ci_upper),
                              linetype = "dashed", colour = "grey40", linewidth = 0.4) +
          ggplot2::geom_errorbar(ggplot2::aes(xmin = ratio_lo, xmax = ratio_hi,
                                              alpha = weight_label),
                                 orientation = "y", width = 0, linewidth = 0.6) +
          ggplot2::geom_point(ggplot2::aes(size = weight, alpha = weight_label)) +
          ggplot2::scale_x_log10(limits = c(1e-1, 1e12),
                                 breaks = 10 ^ seq(-1, 12, by = 2),
                                 labels = c(expression(10^-1), expression(10^1),
                                            expression(10^3), expression(10^5),
                                            expression(10^7), expression(10^9),
                                            expression(10^11))) +
          ggplot2::scale_color_manual(values = study_pal, name = "Study type") +
          ggplot2::scale_size_continuous(range = c(2, 4.5), guide = "none") +
          ggplot2::scale_alpha_manual(values = c("Included" = 1, "Excluded" = 0.35),
                                      name = "") +
          ggplot2::annotation_logticks(sides = "b", short = ggplot2::unit(0.05, "cm"),
                                       mid = ggplot2::unit(0.1, "cm"),
                                       long = ggplot2::unit(0.15, "cm")) +
          ggplot2::labs(title = expression("A. Direct-literature anchors for " * zeta[ratio] * " = " * zeta[1] / zeta[2]),
                        x = expression(zeta[ratio] ~ "  (log scale)"),
                        y = NULL) +
          ggplot2::theme_classic(base_size = 13) +
          ggplot2::theme(
               legend.position   = "right",
               legend.key.height = ggplot2::unit(0.5, "cm"),
               legend.title      = ggplot2::element_text(size = 11, face = "bold"),
               panel.grid.major.x = ggplot2::element_line(colour = "grey92",
                                                          linewidth = 0.3),
               panel.grid.minor  = ggplot2::element_blank(),
               axis.title.x      = ggplot2::element_text(margin = ggplot2::margin(t = 8)),
               axis.text.y       = ggplot2::element_text(size = 10),
               plot.title        = ggplot2::element_text(face = "bold", size = 14,
                                                         margin = ggplot2::margin(b = 8))
          )

     # Rug of direct-literature anchors on the density panel
     rug_df <- fit_df_A[, c("ratio", "study_type", "weight")]
     rug_df$study_type <- factor(rug_df$study_type, levels = names(study_pal))

     # Channel colour and linetype aesthetics for the overlay
     channel_colours <- c(direct   = "#117A65",
                          derived  = "#C0392B",
                          combined = "#1B4F72")
     channel_linetypes <- c(direct   = "dashed",
                            derived  = "dotted",
                            combined = "solid")
     pred_df$channel <- factor(pred_df$channel,
                               levels = c("direct", "derived", "combined"))

     peak_density <- max(pred_df$density_log10)

     p_density <-
          ggplot2::ggplot() +
          ggplot2::geom_line(data = pred_df,
                             ggplot2::aes(x = zeta_ratio, y = density_log10,
                                          colour   = channel,
                                          linetype = channel),
                             linewidth = 1) +
          ggplot2::geom_vline(xintercept = lognormal_median,
                              linetype = "solid", colour = "grey20", linewidth = 0.6) +
          ggplot2::geom_vline(xintercept = c(ci_lower, ci_upper),
                              linetype = "dashed", colour = "grey40", linewidth = 0.4) +
          ggplot2::geom_rug(data = rug_df,
                            ggplot2::aes(x = ratio),
                            sides = "b", length = ggplot2::unit(0.04, "npc"),
                            linewidth = 0.8, alpha = 0.9, colour = "grey30",
                            inherit.aes = FALSE) +
          ggplot2::scale_x_log10(limits = c(1e-1, 1e12),
                                 breaks = 10 ^ seq(-1, 12, by = 2),
                                 labels = c(expression(10^-1), expression(10^1),
                                            expression(10^3), expression(10^5),
                                            expression(10^7), expression(10^9),
                                            expression(10^11))) +
          ggplot2::scale_y_continuous(limits = c(0, peak_density * 1.35),
                                      expand = c(0, 0)) +
          ggplot2::scale_color_manual(values = channel_colours, name = "Channel") +
          ggplot2::scale_linetype_manual(values = channel_linetypes, name = "Channel") +
          ggplot2::annotation_logticks(sides = "b", short = ggplot2::unit(0.05, "cm"),
                                       mid = ggplot2::unit(0.1, "cm"),
                                       long = ggplot2::unit(0.15, "cm")) +
          ggplot2::annotate("text",
                            x = lognormal_median, y = peak_density * 1.08,
                            label = sprintf("combined median\n%.1e", lognormal_median),
                            hjust = 0.5, vjust = 0, size = 3.4, colour = "grey20",
                            lineheight = 0.9) +
          ggplot2::annotate("text",
                            x = 10^-0.8, y = peak_density * 1.25,
                            hjust = 0, vjust = 0.5, size = 3.6, colour = "#1B4F72",
                            label = sprintf("Combined(meanlog = %.2f, sdlog = %.2f)",
                                            meanlog_C, sdlog_C)) +
          ggplot2::labs(title = "B. Direct, derived, and combined lognormal densities (rug = direct-literature anchors)",
                        x = expression(zeta[ratio] ~ "  (log scale)"),
                        y = expression("Density (per log"[10] ~ zeta[ratio] * ")")) +
          ggplot2::theme_classic(base_size = 13) +
          ggplot2::theme(
               legend.position    = "right",
               panel.grid.major.x = ggplot2::element_line(colour = "grey92",
                                                          linewidth = 0.3),
               panel.grid.minor   = ggplot2::element_blank(),
               axis.title.x       = ggplot2::element_text(margin = ggplot2::margin(t = 8)),
               axis.title.y       = ggplot2::element_text(margin = ggplot2::margin(r = 8)),
               plot.title         = ggplot2::element_text(face = "bold", size = 14,
                                                          margin = ggplot2::margin(b = 8))
          )

     combo <- cowplot::plot_grid(p_sources, p_density,
                                 ncol = 1, align = "v", rel_heights = c(1.15, 1))

     figure_path <- file.path(PATHS$DOCS_FIGURES, "zeta_ratio_prior.png")
     grDevices::png(filename = figure_path, width = 2800, height = 2800,
                    units = "px", res = 300)
     print(combo)
     grDevices::dev.off()
     message("zeta_ratio prior figure saved to: ", figure_path)

     diagnostics <- list(
          fit_direct     = fit_direct,
          fit_derived    = fit_derived,
          fit_combined   = fit_combined,
          ratio_sample   = log10_ratio_s,
          analytic_check = analytic_check,
          candidate_fits = candidate_fits
     )

     invisible(list(data        = data_df,
                    fit         = fit,
                    param_df    = param_df,
                    prediction  = pred_df,
                    diagnostics = diagnostics))
}
