#' Plot Vaccine Immune Decay
#'
#' Draws the documentation figure of oral cholera vaccine (OCV) effectiveness
#' over time for the one- and two-dose regimens: the Xu et al. (2024)
#' meta-regression points and the exponential-decay fits
#' \eqn{VE_k(t) = \phi_k e^{-\omega_k t}} produced by
#' \code{\link{est_vaccine_effectiveness}}.
#'
#' This function does not fit anything. Before v0.100.0 it re-implemented the
#' \code{est_vaccine_effectiveness()} fit (without its \eqn{\phi_2 \ge \phi_1}
#' bound and with hard-coded omega shapes), announced parameter files it did not
#' write, and so plotted a fit that differed from the one behind the priors. It
#' now reads the files that \code{est_vaccine_effectiveness()} writes, so the
#' figure always shows the fit the priors use; run that function first.
#'
#' @param PATHS A list containing the paths where data and figures are saved. Typically generated by the `get_paths()` function and should include:
#' \itemize{
#'   \item \strong{MODEL_INPUT}: Directory holding \code{data_vaccine_effectiveness.csv}, \code{pred_vaccine_effectiveness.csv} and \code{param_vaccine_effectiveness.csv} from \code{est_vaccine_effectiveness()}.
#'   \item \strong{DOCS_FIGURES}: Directory where \code{vaccine_effectiveness_decay.png} is saved.
#' }
#'
#' @return Invisibly, the combined plot object; the figure is written to \code{DOCS_FIGURES}.
#'
#' @references Xu et al. (2024). Effectiveness of Oral Cholera Vaccines: A Systematic Review and Meta-Analysis.
#' medRxiv. https://doi.org/10.1101/2024.08.13.24311930v2
#'
#' @importFrom ggplot2 ggplot aes geom_ribbon geom_line geom_point geom_errorbar annotate labs theme_classic scale_y_continuous scale_x_continuous scale_color_manual
#' @importFrom cowplot plot_grid
#' @examples
#' \dontrun{
#' PATHS <- get_paths()
#' est_vaccine_effectiveness(PATHS)
#' est_immune_decay_vaccine(PATHS)
#' }
#' @export

est_immune_decay_vaccine <- function(PATHS) {

     read_input <- function(file) {
          path <- file.path(PATHS$MODEL_INPUT, file)
          if (!file.exists(path)) {
               stop(file, " not found in PATHS$MODEL_INPUT; run est_vaccine_effectiveness(PATHS) first.")
          }
          utils::read.csv(path, stringsAsFactors = FALSE)
     }
     data_df  <- read_input("data_vaccine_effectiveness.csv")
     pred_df  <- read_input("pred_vaccine_effectiveness.csv")
     param_df <- read_input("param_vaccine_effectiveness.csv")

     one_dose_data <- data_df[data_df$dose_regimen == "One-dose OCV", ]
     two_dose_data <- data_df[data_df$dose_regimen == "Two-dose OCV", ]
     days_max <- 365 * 5
     prediction_one_dose <- pred_df[pred_df$dose_regimen == "One-dose OCV" & pred_df$day <= days_max, ]
     prediction_two_dose <- pred_df[pred_df$dose_regimen == "Two-dose OCV" & pred_df$day <= days_max, ]

     point_value <- function(variable, name) {
          v <- param_df$parameter_value[param_df$variable_name == variable &
                                           param_df$parameter_distribution == "point" &
                                           param_df$parameter_name == name]
          if (length(v) != 1L) stop("param_vaccine_effectiveness.csv has no single point '", name,
                                    "' for ", variable)
          v
     }
     fit_one_dose <- list(mean = c(point_value("phi_1", "mean"), point_value("omega_1", "mean")))
     fit_two_dose <- list(mean = c(point_value("phi_2", "mean"), point_value("omega_2", "mean")))

     # Define modern colors
     green_fill <- "#90EE90"  # Light green for ribbon
     green_line <- "#228B22"  # Forest green for lines
     blue_fill <- "#87CEEB"   # Sky blue for ribbon
     blue_line <- "#4169E1"   # Royal blue for lines

     # Plot 1: One-dose OCV effectiveness over time
     p1 <-
          ggplot2::ggplot() +
          ggplot2::geom_ribbon(data = prediction_one_dose,
                     ggplot2::aes(x = day, ymin = predicted_lo, ymax = predicted_hi),
                     fill = green_fill, alpha = 0.4) +
          ggplot2::geom_line(data = prediction_one_dose,
                   ggplot2::aes(x = day, y = predicted),
                   color = green_line, linewidth = 1.5) +
          ggplot2::geom_line(data = prediction_one_dose,
                   ggplot2::aes(x = day, y = predicted_lo),
                   color = green_line, linewidth = 0.75, linetype='dashed', alpha = 0.7) +
          ggplot2::geom_line(data = prediction_one_dose,
                   ggplot2::aes(x = day, y = predicted_hi),
                   color = green_line, linewidth = 0.75, linetype='dashed', alpha = 0.7) +
          ggplot2::geom_errorbar(data = one_dose_data,
                       ggplot2::aes(x = days, ymin = effectiveness_lo, ymax = effectiveness_hi),
                       width = 0, color = "black", alpha = 0.8) +
          ggplot2::geom_point(data = one_dose_data,
                    ggplot2::aes(x = days, y = effectiveness),
                    color = "black", size = 3) +
          ggplot2::annotate("text", x = 365 * 4, y = 0.15,
                  label = sprintf("One-dose OCV\nphi = %.3f\nomega = %.5f\nHalf-life = %.0f days",
                                  fit_one_dose$mean[1], fit_one_dose$mean[2],
                                  log(2)/fit_one_dose$mean[2]),
                  color = green_line, size = 4.5, hjust = 0, fontface = "bold") +
          ggplot2::labs(x = "Years after vaccination",
               y = "Vaccine effectiveness",
               title = "One-dose OCV") +
          ggplot2::theme_classic(base_size = 16) +
          ggplot2::theme(panel.grid.minor = ggplot2::element_blank(),
                panel.grid.major.y = ggplot2::element_line(color = "gray90", linetype = "dotted"),
                axis.title.x = ggplot2::element_text(margin = ggplot2::margin(t = 10)),
                axis.title.y = ggplot2::element_text(margin = ggplot2::margin(r = 10)),
                plot.title = ggplot2::element_text(size = 18, face = "bold", hjust = 0.5)) +
          ggplot2::scale_y_continuous(limits = c(0, 1), expand = c(0, 0),
                           breaks = seq(0, 1, 0.2)) +
          ggplot2::scale_x_continuous(limits = c(0, 365*5),
                           labels = 0:5,
                           breaks = 365 * (0:5),
                           expand = c(0, 0))

     # Plot 2: Two-dose OCV effectiveness over time
     p2 <-
          ggplot2::ggplot() +
          ggplot2::geom_ribbon(data = prediction_two_dose,
                     ggplot2::aes(x = day, ymin = predicted_lo, ymax = predicted_hi),
                     fill = blue_fill, alpha = 0.4) +
          ggplot2::geom_line(data = prediction_two_dose,
                   ggplot2::aes(x = day, y = predicted),
                   color = blue_line, linewidth = 1.5) +
          ggplot2::geom_line(data = prediction_two_dose,
                   ggplot2::aes(x = day, y = predicted_lo),
                   color = blue_line, linewidth = 0.75, linetype='dashed', alpha = 0.7) +
          ggplot2::geom_line(data = prediction_two_dose,
                   ggplot2::aes(x = day, y = predicted_hi),
                   color = blue_line, linewidth = 0.75, linetype='dashed', alpha = 0.7) +
          ggplot2::geom_errorbar(data = two_dose_data,
                       ggplot2::aes(x = days, ymin = effectiveness_lo, ymax = effectiveness_hi),
                       width = 0, color = "black", alpha = 0.8) +
          ggplot2::geom_point(data = two_dose_data,
                    ggplot2::aes(x = days, y = effectiveness),
                    color = "black", size = 3) +
          ggplot2::annotate("text", x = 365 * 4, y = 0.15,
                  label = sprintf("Two-dose OCV\nphi = %.3f\nomega = %.5f\nHalf-life = %.0f days",
                                  fit_two_dose$mean[1], fit_two_dose$mean[2],
                                  log(2)/fit_two_dose$mean[2]),
                  color = blue_line, size = 4.5, hjust = 0, fontface = "bold") +
          ggplot2::labs(x = "Years after vaccination",
               y = "Vaccine effectiveness",
               title = "Two-dose OCV") +
          ggplot2::theme_classic(base_size = 16) +
          ggplot2::theme(panel.grid.minor = ggplot2::element_blank(),
                panel.grid.major.y = ggplot2::element_line(color = "gray90", linetype = "dotted"),
                axis.title.x = ggplot2::element_text(margin = ggplot2::margin(t = 10)),
                axis.title.y = ggplot2::element_text(margin = ggplot2::margin(r = 10)),
                plot.title = ggplot2::element_text(size = 18, face = "bold", hjust = 0.5)) +
          ggplot2::scale_y_continuous(limits = c(0, 1), expand = c(0, 0),
                           breaks = seq(0, 1, 0.2)) +
          ggplot2::scale_x_continuous(limits = c(0, 365*5),
                           labels = 0:5,
                           breaks = 365 * (0:5),
                           expand = c(0, 0))



     # Combine the plots in 2 rows
     combo <- cowplot::plot_grid(p1, p2,
                                 nrow = 2, ncol = 1,
                                 align = "v",
                                 rel_heights = c(1, 1))

     # Save the combined plot
     plot_output_path <- file.path(PATHS$DOCS_FIGURES, "vaccine_effectiveness_decay.png")
     ggplot2::ggsave(plot_output_path, plot = combo, width = 3000, height = 2400, units = "px", dpi = 300)

     message(paste("Vaccine effectiveness decay plot saved to:", plot_output_path))

     invisible(combo)
}
