#' Estimate Prior Distribution for Symptomatic Shedding Rate (zeta_1)
#'
#' Compiles a meta-analysis of published *Vibrio cholerae* shedding anchors
#' (stool concentration x time-averaged daily stool volume) for symptomatic
#' infections and fits a lognormal prior on the per-person-per-day shedding
#' rate used in the MOSAIC environmental reservoir update:
#' \deqn{W(t+1) \mathrel{+}= (1 - \theta_j) \cdot \mathrm{Poisson}(\zeta_1 \cdot I_{\mathrm{sym}})}
#' so \eqn{\zeta_1} is the expected total *V. cholerae* cells shed per
#' symptomatic infected person per day during the shedding phase. The
#' \eqn{\gamma_1} parameter handles the shedding-phase duration; \eqn{\zeta_1}
#' is a daily rate, not a total-per-infection.
#'
#' The function assembles a literature table of per-person-per-day shedding
#' anchors constructed as stool concentration (\eqn{c}, cells per mL) times
#' time-averaged daily stool volume (\eqn{V}, mL per day) for defined
#' severity classes (severe, moderate, mild). A severity-weighted pool is
#' also constructed using the `severity_mix` argument. A weighted lognormal
#' is then fit by maximum-likelihood on the log10 scale.
#'
#' @param PATHS A list of paths generated by `get_paths()`. Must include:
#' \itemize{
#'   \item \strong{MODEL_INPUT}: directory where parameter CSVs are saved.
#'   \item \strong{DOCS_FIGURES}: directory where the summary figure is saved.
#' }
#' @param severity_mix Named numeric vector with entries `severe`, `moderate`,
#'   and `mild` that sum to 1. Used to compute the severity-weighted pool
#'   anchor. Defaults to `c(severe = 0.2, moderate = 0.4, mild = 0.4)` (endemic
#'   mix). The severe fraction (0.2) is informed by Harris 2012's narrative
#'   that approximately 20 percent of symptomatic cholera cases are severe;
#'   the moderate/mild split is an expert estimate exposed here as a
#'   sensitivity argument.
#'
#' @return Invisibly returns a list with elements:
#' \itemize{
#'   \item \code{data}: the source meta-analysis table.
#'   \item \code{fit}: fitted lognormal parameters (\code{meanlog}, \code{sdlog},
#'         \code{median}, \code{mode}, \code{mean}, \code{ci_lower},
#'         \code{ci_upper}, \code{n_sources}, \code{mu_log10}, \code{sd_log10}).
#'   \item \code{param_df}: long-format parameter data frame (as saved to disk).
#'   \item \code{prediction}: density grid on linear and log10-x scales.
#'   \item \code{sensitivity}: leave-one-anchor-out sub-fits
#'         (\code{include_calib}, \code{volume_peak}, \code{volume_low}).
#' }
#'
#' @details
#' \strong{Assembly equation.} Each literature entry contributes
#' \eqn{\zeta_{1,i} = c_i \times V_i} with lower and upper bounds taken from
#' the spread of the concentration and volume anchors for that severity class.
#' Time-averaged stool volumes are used (`V_sev` = 8, `V_mod` = 4,
#' `V_mild` = 0.5 L/day) because the LASER Poisson update multiplies the rate
#' by the current `I_sym` compartment, which already integrates the shedding
#' course via \eqn{\gamma_1}. Peak purging rates (~1 L/h, ~14-24 L/day) are
#' treated as upper-bound sensitivity rows, not the central anchor.
#'
#' \strong{Severity-weighted pool caveat.} At the default severity mix
#' (0.2 / 0.4 / 0.4) the severe class dominates ~94 percent of the arithmetic
#' because \eqn{c_{\mathrm{sev}} = 10^8} is 100x larger than \eqn{c_{\mathrm{mild}} = 10^6}.
#' This is acceptable: surveillance observes severe cases disproportionately,
#' so the effective \eqn{\zeta_1} the data constrains is close to the severe
#' value anyway. The `severity_mix` argument is exposed so callers can run
#' sensitivity analyses (e.g. the outbreak mix 0.35 / 0.40 / 0.25).
#'
#' \strong{Weighted MLE on log10 scale.} Weighted mean and SD on the log10
#' scale are converted to lognormal `meanlog` and `sdlog`:
#' \deqn{\mu_{\log_{10}} = \frac{\sum w_i \log_{10}(\zeta_{1,i})}{\sum w_i}, \quad
#'       \sigma^2_{\log_{10}} = \frac{\sum w_i (\log_{10}(\zeta_{1,i}) - \mu_{\log_{10}})^2}{\sum w_i}}
#' then `meanlog = mu_log10 * ln(10)` and `sdlog = sigma_log10 * ln(10)`.
#'
#' \strong{Sensitivity returns.} The `$sensitivity` list contains three
#' alternative fits: `include_calib` (refits WITH the MOSAIC calibration
#' posterior row at weight 0.25, producing a much wider sdlog because the
#' Frame-B-calibrated value is 7 OOM below biological-units literature
#' anchors), `volume_peak` (rescales all severe-class V=8 L/day rows to
#' V=12 L/day), and `volume_low` (rescales to V=6 L/day).
#'
#' \strong{Per-day vs per-infection.} `zeta_1` is a per-day shedding rate
#' during the symptomatic infectious period; \eqn{\gamma_1^{-1}} (~10 d)
#' governs the duration. The cumulative cells shed per symptomatic
#' infection is therefore approximately `zeta_1 / gamma_1`, and the
#' per-infection contribution ratio vs asymptomatic is
#' `zeta_ratio * (gamma_2 / gamma_1)` (~5x the per-day ratio under current
#' gamma priors). When comparing this prior to literature that quotes
#' cumulative stool output per infection, apply the duration multiplier.
#'
#' \strong{Relation to documented priors.} Earlier MOSAIC-docs narrative
#' states `zeta_1 ~ Uniform(10^4, 10^8)`. That range derives from the
#' Frame-B calibration rescaling and is superseded by this lognormal
#' literature-derived prior. The new prior's 95\% CI extends to ~10^13,
#' well above the stale Uniform upper bound.
#'
#' Primary source notes are stored in
#' `claude/zeta_priors_update/zeta_sources/` (14 PDFs + 32 source notes).
#' See `claude/zeta_priors_update/plan_zeta_priors_implementation.md` for
#' the full provenance.
#'
#' @references
#' \itemize{
#'   \item Nelson EJ, Harris JB, Morris JG, Calderwood SB, Camilli A (2009).
#'         Cholera transmission: the host, pathogen and bacteriophage dynamic.
#'         *Nat Rev Microbiol* 7(10):693-702.
#'   \item Merrell DS, Butler SM, Qadri F, et al. (2002). Host-induced epidemic
#'         spread of the cholera bacterium. *Nature* 417(6889):642-45.
#'   \item Harris JB, LaRocque RC, Qadri F, Ryan ET, Calderwood SB (2012).
#'         Cholera. *Lancet* 379(9835):2466-76.
#'   \item Nelson EJ, Grembi JA, Chao DL, et al. (2020). Gold standard cholera
#'         diagnostics are tarnished by lytic bacteriophage and antibiotics.
#'         *J Clin Microbiol* 58(9).
#'   \item Kaper JB, Morris JG, Levine MM (1995). Cholera. *Clin Microbiol Rev*
#'         8(1):48-86.
#'   \item Codeco CT (2001). Endemic and epidemic dynamics of cholera: the role
#'         of the aquatic reservoir. *BMC Infect Dis* 1:1.
#'   \item Nelson EJ, Chowdhury A, Flynn J, et al. (2008). Transmission of
#'         *V. cholerae* is antagonized by lytic phage and entry into the
#'         aquatic environment. *PLoS Pathog* 4(10):e1000187.
#'   \item Fung IC (2014). Cholera transmission dynamic models for public
#'         health practitioners. *Emerg Themes Epidemiol* 11:1.
#'   \item Kirpich A, Weppelmann TA, Yang Y, et al. (2015). Cholera
#'         transmission in Ouest Department of Haiti. *PLoS NTD*.
#' }
#'
#' @examples
#' \dontrun{
#' PATHS <- get_paths()
#' est_zeta_1_prior(PATHS)
#' }
#'
#' @importFrom stats dlnorm qlnorm weighted.mean dnorm
#' @importFrom utils write.csv
#' @importFrom ggplot2 ggplot aes geom_point geom_errorbar geom_vline geom_line
#'             geom_ribbon geom_hline geom_rug scale_x_log10 scale_y_continuous
#'             scale_color_manual scale_fill_manual scale_size_continuous
#'             scale_alpha_manual labs theme_classic theme element_text
#'             element_line element_blank annotation_logticks annotate margin
#' @importFrom cowplot plot_grid
#' @importFrom grDevices png dev.off
#' @export

est_zeta_1_prior <- function(PATHS,
                             severity_mix = c(severe = 0.2,
                                              moderate = 0.4,
                                              mild = 0.4)) {

     requireNamespace("ggplot2")
     requireNamespace("cowplot")

     # Validate severity_mix
     required_names <- c("severe", "moderate", "mild")
     if (is.null(names(severity_mix)) ||
         !all(required_names %in% names(severity_mix))) {
          stop("`severity_mix` must be a named numeric vector with entries ",
               "'severe', 'moderate', and 'mild'.", call. = FALSE)
     }
     sm_total <- sum(severity_mix[required_names])
     if (!isTRUE(all.equal(sm_total, 1, tolerance = 1e-8))) {
          stop(sprintf("`severity_mix` entries must sum to 1 (got %.6f).",
                       sm_total), call. = FALSE)
     }
     if (any(severity_mix[required_names] < 0)) {
          stop("`severity_mix` entries must all be non-negative.", call. = FALSE)
     }

     #--------------------------------------------------------------------------
     # 1. Literature meta-analysis table
     #
     # Each row is one per-person-per-day shedding anchor constructed as
     # stool concentration * time-averaged daily stool volume. Central
     # working volumes: V_sev = 8, V_mod = 4, V_mild = 0.5 L/day
     # (see plan_zeta_priors_implementation.md Section 4.3 for clinical
     # sources - Harris 2012, Fung 2014, WHO guidelines).
     #--------------------------------------------------------------------------

     # Severity-weighted pool (row 9) computed from severity_mix argument.
     # v0.29.1 bias-corrected values (per plan_zeta_priors_implementation.md
     # §4.3 revision):
     #   - V_sev lowered from 8 L/day to 4 L/day (time-averaged over the
     #     1-2 week clinical course rather than first-24-h peak rate)
     #   - V_mod lowered from 4 L/day to 2 L/day (same rationale)
     #   - V_mild lowered from 500 to 300 mL/day
     #   - Mild concentration lowered from 10^6 to 10^5 cells/mL
     #     (non-rice-water stool has substantially lower bacterial load)
     # Per-class central point estimates (cells per person per day):
     #   severe:   10^8 cells/mL * 4000 mL/day = 4e11
     #   moderate: 10^7 cells/mL * 2000 mL/day = 2e10
     #   mild:     10^5 cells/mL *  300 mL/day = 3e7
     # Note: rows 9 and 10 (pool rows) are kept in the table for the forest
     # plot but excluded from the fit (weight 0) — they are derived quantities
     # of rows 1, 4, 5 and including them was triple-counting the severe class.
     zeta_sev_pt  <- 1e8 * 4000
     zeta_mod_pt  <- 1e7 * 2000
     zeta_mild_pt <- 1e5 * 300
     pool_endemic_pt <- severity_mix["severe"]   * zeta_sev_pt +
                       severity_mix["moderate"] * zeta_mod_pt +
                       severity_mix["mild"]     * zeta_mild_pt

     # Fixed outbreak pool (sensitivity row 10) uses the author-estimate
     # outbreak mix 0.35 / 0.40 / 0.25 regardless of the severity_mix
     # function argument (which is applied only to the endemic pool).
     pool_outbreak_pt <- 0.35 * zeta_sev_pt +
                        0.40 * zeta_mod_pt +
                        0.25 * zeta_mild_pt

     data_df <- data.frame(
          source         = c("Nelson 2009 + Harris 2012 (severe)",
                             "Merrell 2002 (severe)",
                             "Nelson 2020 (severe reference)",
                             "Nelson 2009 (moderate)",
                             "Nelson 2009 (mild)",
                             "Kaper 1995 (severe range)",
                             "Harris 2012 (clinical seminar)",
                             "Codeco 2001 (range)",
                             "Endemic severity-weighted pool",
                             "Outbreak severity-weighted pool",
                             "Nelson 2008 (Bangladesh acute)",
                             "Kirpich 2015 (Haiti)",
                             "Fung 2014 (population model)",
                             "V_sev high sensitivity (10 L/day)",
                             "V_sev low sensitivity (1.5 L/day)",
                             "MOSAIC calibration posterior (Frame B)"),
          author_year    = c("Nelson et al. 2009; Harris et al. 2012",
                             "Merrell et al. 2002",
                             "Nelson et al. 2020",
                             "Nelson et al. 2009",
                             "Nelson et al. 2009",
                             "Kaper, Morris & Levine 1995",
                             "Harris et al. 2012",
                             "Codeco 2001",
                             "Severity-weighted pool (endemic mix)",
                             "Severity-weighted pool (outbreak mix)",
                             "Nelson et al. 2008",
                             "Kirpich et al. 2015",
                             "Fung 2014",
                             "Harris et al. 2012 (peak purging)",
                             "Harris et al. 2012 (low-volume)",
                             "MOSAIC MOZ bfrs_balanced_binned"),
          severity_class = c("Severe", "Severe", "Severe",
                             "Moderate", "Mild",
                             "Severe", "Severe", "Severe",
                             "Mixed", "Mixed",
                             "Severe", "Severe",
                             "Population",
                             "Severe", "Severe",
                             "Empirical"),
          # Stool concentration (cells per mL); NA for pool and posterior rows
          c              = c(1e8, 1e8, 3e8,
                             1e7, 1e5,
                             1e8, 1e8, 10^7.5,
                             NA, NA,
                             1e8, 1e8,
                             NA,
                             1e8, 1e8,
                             NA),
          # Time-averaged stool volume (mL per day) — averaged over the full
          # 1-2 week clinical course, not first-24-h peak rate
          V              = c(4e3, 4e3, 4e3,
                             2e3, 3e2,
                             4e3, 4e3, 4e3,
                             NA, NA,
                             4e3, 4e3,
                             NA,
                             1.0e4, 1.5e3,
                             NA),
          # Point estimate of zeta_1 (cells per person per day) = c * V
          zeta_1         = c(4e11, 4e11, 1.2e12,
                             2e10, 3e7,
                             4e11, 4e11, 1.26e11,
                             pool_endemic_pt, pool_outbreak_pt,
                             4e11, 4e11,
                             1e9,
                             1e12, 1.5e11,
                             5e4),
          zeta_1_lo      = c(4e10, 4e10, 3e11,
                             1e9, 1e6,
                             1e10, 4e10, 1e10,
                             1e10, 1e10,
                             4e10, 4e10,
                             1e8,
                             1e11, 1e10,
                             2.7e4),
          zeta_1_hi      = c(4e12, 4e12, 1.2e13,
                             1e11, 1e9,
                             1e13, 4e12, 1e12,
                             1e13, 1e13,
                             4e12, 4e12,
                             1e11,
                             5e12, 1e12,
                             8.7e4),
          # v0.29.1 bias-corrected weights:
          #   - Nelson 2020 (row 3): 0.50 -> 0.10 (community-consensus reference, not primary)
          #   - Kaper 1995 (row 6):  0.50 -> 0.10 (review overlaps Nelson primary)
          #   - Harris 2012 (row 7): 0.50 -> 0.10 (review overlaps Nelson primary)
          #   - Pool rows 9, 10:     -> 0.00 (derived from rows 1/4/5 — avoid double-counting)
          weight         = c(1.00, 1.00, 0.10,
                             0.50, 0.25,
                             0.10, 0.10, 0.25,
                             0.00, 0.00,
                             0.25, 0.25,
                             0.10,
                             0.25, 0.25,
                             0.00),                  # row 16: scale incomparable — see @details
          study_type     = c("Primary clinical", "Primary clinical",
                             "Expert review",
                             "Expert review", "Expert review",
                             "Expert review", "Expert review",
                             "Model convention",
                             "Severity-weighted pool",
                             "Severity-weighted pool",
                             "Primary clinical", "Primary clinical",
                             "Model convention",
                             "Severity-weighted pool",
                             "Severity-weighted pool",
                             "Calibration posterior"),
          notes          = c("Primary anchor: severe rice-water stool with time-averaged volume",
                             "Independent primary measurement (N=3, ICDDR)",
                             "Community-consensus reference stool concentration",
                             "Moderate class from Nelson review range",
                             "Mild class; Nelson '10^8' treated as upper bound",
                             "Expert review; overlaps Nelson sources",
                             "Modern clinical seminar",
                             "Modelling review of primary data",
                             "Severity-weighted pool (endemic mix); operationally relevant zeta_1 for I_symptomatic",
                             "Severity-weighted pool (outbreak mix 0.35/0.40/0.25); sensitivity row",
                             "Bangladesh primary shedding data; partial overlap with Nelson 2009",
                             "Haiti clinical primary",
                             "Modelling review; context only",
                             "Peak-volume upper-bound sensitivity (V_sev=12 L/day)",
                             "Low-volume lower-bound sensitivity (V_sev=6 L/day)",
                             "Frame-B calibration posterior; scale not directly comparable to biological-units literature anchors. Excluded from main fit (weight 0); appears in the forest plot for context and is published as `$sensitivity$include_calib` for comparison"),
          stringsAsFactors = FALSE
     )

     #--------------------------------------------------------------------------
     # 2. Weighted lognormal fit on log10 scale
     #--------------------------------------------------------------------------

     fit_df <- data_df[data_df$weight > 0, ]
     stopifnot("All literature rows have weight 0" = sum(fit_df$weight) > 0)

     log10_zeta <- log10(fit_df$zeta_1)
     w          <- fit_df$weight

     mu_log10    <- stats::weighted.mean(log10_zeta, w)
     var_log10   <- sum(w * (log10_zeta - mu_log10)^2) / sum(w)
     sigma_log10 <- sqrt(var_log10)

     # Degenerate-fit fallback: if every weighted log10 value is identical
     # the variance is exactly zero and the lognormal collapses to a spike.
     if (!is.finite(sigma_log10) || sigma_log10 <= 0) {
          message("est_zeta_1_prior: weighted variance is zero; ",
                  "using sigma_log10 = 0.5 fallback.")
          sigma_log10 <- 0.5
     }

     meanlog <- mu_log10    * log(10)
     sdlog   <- sigma_log10 * log(10)

     lognormal_median <- exp(meanlog)
     lognormal_mode   <- exp(meanlog - sdlog^2)
     lognormal_mean   <- exp(meanlog + sdlog^2 / 2)
     ci_lower         <- stats::qlnorm(0.025, meanlog = meanlog, sdlog = sdlog)
     ci_upper         <- stats::qlnorm(0.975, meanlog = meanlog, sdlog = sdlog)

     fit <- list(
          meanlog    = meanlog,
          sdlog      = sdlog,
          median     = lognormal_median,
          mode       = lognormal_mode,
          mean       = lognormal_mean,
          ci_lower   = ci_lower,
          ci_upper   = ci_upper,
          n_sources  = nrow(fit_df),
          mu_log10   = mu_log10,
          sd_log10   = sigma_log10
     )

     #--------------------------------------------------------------------------
     # 2b. Sensitivity sub-fits
     #--------------------------------------------------------------------------

     .refit <- function(sub_df) {
          if (sum(sub_df$weight) <= 0) {
               return(list(meanlog = NA_real_, sdlog = NA_real_,
                           median = NA_real_))
          }
          sub_log10 <- log10(sub_df$zeta_1)
          sub_w     <- sub_df$weight
          sub_mu    <- stats::weighted.mean(sub_log10, sub_w)
          sub_var   <- sum(sub_w * (sub_log10 - sub_mu)^2) / sum(sub_w)
          sub_sigma <- sqrt(sub_var)
          if (!is.finite(sub_sigma) || sub_sigma <= 0) sub_sigma <- 0.5
          sub_ml    <- sub_mu * log(10)
          sub_sl    <- sub_sigma * log(10)
          list(meanlog = sub_ml, sdlog = sub_sl,
               median  = exp(sub_ml))
     }

     # Include-calibration-posterior sensitivity: the MOSAIC empirical row is
     # excluded from the main fit (weight 0, row 16) because its Frame-B scale
     # is not directly comparable to biological-units literature anchors.
     # This sensitivity fit includes it at weight 0.25 so the reader can see
     # what the fit WOULD be if the calibration posterior were treated as an
     # anchor — almost always a much larger sdlog.
     include_calib_df            <- data_df
     include_calib_df$weight[include_calib_df$source ==
          "MOSAIC calibration posterior (Frame B)"] <- 0.25
     include_calib_df            <- include_calib_df[include_calib_df$weight > 0, ]
     include_calib_fit           <- .refit(include_calib_df)

     # Volume-peak sensitivity: replace V_sev central (8 L/day) anchors with
     # peak-volume (12 L/day) anchors. We swap rows 1-2 and 6-7 zeta_1 values
     # by the 1.5x factor (12/8) and refit with the original weights.
     peak_df          <- fit_df
     # Scale ALL severe-class rows that use the central V_sev = 4000 anchor
     # (Nelson 2009 + Harris, Merrell 2002, Nelson 2020, Kaper 1995 severe,
     # Harris 2012, Codeco 2001, Nelson 2008, Kirpich 2015). Rows that use a
     # different V by construction (the V_sev sensitivity rows 14/15) are
     # intentionally not rescaled.
     peak_sev_mask    <- peak_df$severity_class == "Severe" &
                         abs(peak_df$V - 4000) < 1e-6
     peak_df$zeta_1[peak_sev_mask] <- peak_df$zeta_1[peak_sev_mask] * (10 / 4)
     volume_peak_fit  <- .refit(peak_df)

     # Volume-low sensitivity: apply 6/8 = 0.75 factor to the same severe rows.
     low_df           <- fit_df
     low_df$zeta_1[peak_sev_mask] <- low_df$zeta_1[peak_sev_mask] * (1.5 / 4)
     volume_low_fit   <- .refit(low_df)

     sensitivity <- list(
          include_calib = include_calib_fit,
          volume_peak   = volume_peak_fit,
          volume_low    = volume_low_fit
     )

     #--------------------------------------------------------------------------
     # 3. Prediction grid (lognormal density) and parameter data frame
     #--------------------------------------------------------------------------

     x_vals <- 10 ^ seq(6, 15, length.out = 1000)
     pred_df <- data.frame(
          zeta_1          = x_vals,
          log10_zeta_1    = log10(x_vals),
          density         = stats::dlnorm(x_vals, meanlog = meanlog, sdlog = sdlog),
          density_log10   = stats::dnorm(log10(x_vals),
                                         mean = mu_log10, sd = sigma_log10)
     )

     param_df <- make_param_df(
          variable_name          = "zeta_1",
          variable_description   = "Symptomatic shedding rate (V. cholerae cells per infected person per day)",
          parameter_distribution = c("point", "point", "point", "point",
                                     "lognormal", "lognormal"),
          parameter_name         = c("low", "median", "mode", "high",
                                     "meanlog", "sdlog"),
          parameter_value        = c(ci_lower, lognormal_median, lognormal_mode, ci_upper,
                                     meanlog, sdlog)
     )

     #--------------------------------------------------------------------------
     # 4. Save data, predictions, and parameter priors to MODEL_INPUT
     #--------------------------------------------------------------------------

     dir.create(PATHS$MODEL_INPUT, recursive = TRUE, showWarnings = FALSE)
     dir.create(PATHS$DOCS_FIGURES, recursive = TRUE, showWarnings = FALSE)

     path_data <- file.path(PATHS$MODEL_INPUT, "data_zeta_1_prior.csv")
     utils::write.csv(data_df, path_data, row.names = FALSE)
     message("zeta_1 literature meta-analysis saved to: ", path_data)

     path_pred <- file.path(PATHS$MODEL_INPUT, "pred_zeta_1_prior.csv")
     utils::write.csv(pred_df, path_pred, row.names = FALSE)
     message("zeta_1 prior density grid saved to: ", path_pred)

     path_param <- file.path(PATHS$MODEL_INPUT, "param_zeta_1_prior.csv")
     utils::write.csv(param_df, path_param, row.names = FALSE)
     message("zeta_1 prior parameters saved to: ", path_param)

     #--------------------------------------------------------------------------
     # 5. Print summary
     #--------------------------------------------------------------------------

     cat("\n=== FITTED PRIOR: zeta_1 (Symptomatic shedding rate, cells/person/day) ===\n")
     cat(sprintf("  Sources included  : %d (of %d)\n",
                 nrow(fit_df), nrow(data_df)))
     cat(sprintf("  Severity mix      : severe=%.2f, moderate=%.2f, mild=%.2f\n",
                 severity_mix["severe"], severity_mix["moderate"],
                 severity_mix["mild"]))
     cat(sprintf("  Weighted log10 mean : %.3f  (10^%.2f = %.2e cells/person/day)\n",
                 mu_log10, mu_log10, 10^mu_log10))
     cat(sprintf("  Weighted log10 SD   : %.3f  (%.1f-fold 1-sigma spread)\n",
                 sigma_log10, 10^sigma_log10))
     cat(sprintf("  Lognormal meanlog   : %.4f\n", meanlog))
     cat(sprintf("  Lognormal sdlog     : %.4f\n", sdlog))
     cat(sprintf("  Median              : %.2e cells/person/day\n", lognormal_median))
     cat(sprintf("  Mode                : %.2e cells/person/day\n", lognormal_mode))
     cat(sprintf("  95%% CI              : [%.2e, %.2e] cells/person/day\n",
                 ci_lower, ci_upper))
     cat("  Sensitivity fits:\n")
     cat(sprintf("    include_calib   : median=%.2e, sdlog=%.3f\n",
                 include_calib_fit$median, include_calib_fit$sdlog))
     cat(sprintf("    volume_peak     : median=%.2e, sdlog=%.3f\n",
                 volume_peak_fit$median, volume_peak_fit$sdlog))
     cat(sprintf("    volume_low      : median=%.2e, sdlog=%.3f\n",
                 volume_low_fit$median, volume_low_fit$sdlog))
     cat("\n")

     #--------------------------------------------------------------------------
     # 6. Paper-quality figure: sources forest + fitted density
     #--------------------------------------------------------------------------

     study_pal <- c("Primary clinical"        = "#1B4F72",
                    "Expert review"           = "#B9770E",
                    "Model convention"        = "#7D3C98",
                    "Severity-weighted pool"  = "#512E5F",
                    "Calibration posterior"   = "#C0392B")

     plot_df <- data_df
     plot_df$study_type <- factor(plot_df$study_type,
                                  levels = names(study_pal))
     plot_df$source <- factor(plot_df$source,
                              levels = rev(data_df$source))
     plot_df$weight_label <- ifelse(plot_df$weight == 0, "Excluded", "Included")

     p_sources <-
          ggplot2::ggplot(plot_df,
                          ggplot2::aes(y = source, x = zeta_1, colour = study_type)) +
          ggplot2::annotate("rect",
                            xmin  = ci_lower, xmax = ci_upper,
                            ymin  = -Inf,     ymax = Inf,
                            fill  = "grey85", alpha = 0.35) +
          ggplot2::geom_vline(xintercept = lognormal_median,
                              linetype = "solid", colour = "grey30", linewidth = 0.6) +
          ggplot2::geom_vline(xintercept = c(ci_lower, ci_upper),
                              linetype = "dashed", colour = "grey40", linewidth = 0.4) +
          ggplot2::geom_errorbar(ggplot2::aes(xmin = zeta_1_lo, xmax = zeta_1_hi,
                                              alpha = weight_label),
                                 orientation = "y", width = 0, linewidth = 0.6) +
          ggplot2::geom_point(ggplot2::aes(size = weight, alpha = weight_label)) +
          ggplot2::scale_x_log10(limits = c(1e3, 1e15),
                                 breaks = 10 ^ seq(3, 15, by = 2),
                                 labels = c(expression(10^3), expression(10^5),
                                            expression(10^7), expression(10^9),
                                            expression(10^11), expression(10^13),
                                            expression(10^15))) +
          ggplot2::scale_color_manual(values = study_pal, name = "Study type") +
          ggplot2::scale_size_continuous(range = c(2, 4.5), guide = "none") +
          ggplot2::scale_alpha_manual(values = c("Included" = 1, "Excluded" = 0.35),
                                      name = "") +
          ggplot2::annotation_logticks(sides = "b", short = ggplot2::unit(0.05, "cm"),
                                       mid = ggplot2::unit(0.1, "cm"),
                                       long = ggplot2::unit(0.15, "cm")) +
          ggplot2::labs(title = expression("A. Published anchors for " * italic(V.~cholerae) * " shedding rate " * zeta[1]),
                        x = expression(zeta[1] ~ "  (cells " %.% "person"^{-1} %.% "day"^{-1} * ", log scale)"),
                        y = NULL) +
          ggplot2::theme_classic(base_size = 13) +
          ggplot2::theme(
               legend.position   = "right",
               legend.key.height = ggplot2::unit(0.5, "cm"),
               legend.title      = ggplot2::element_text(size = 11, face = "bold"),
               panel.grid.major.x = ggplot2::element_line(colour = "grey92",
                                                          linewidth = 0.3),
               panel.grid.minor  = ggplot2::element_blank(),
               axis.title.x      = ggplot2::element_text(margin = ggplot2::margin(t = 8)),
               axis.text.y       = ggplot2::element_text(size = 10),
               plot.title        = ggplot2::element_text(face = "bold", size = 14,
                                                         margin = ggplot2::margin(b = 8))
          )

     rug_df <- fit_df[, c("zeta_1", "study_type", "weight")]
     rug_df$study_type <- factor(rug_df$study_type, levels = names(study_pal))

     peak_density <- max(pred_df$density_log10)

     p_density <-
          ggplot2::ggplot() +
          ggplot2::geom_ribbon(data = pred_df,
                               ggplot2::aes(x = zeta_1, ymin = 0, ymax = density_log10),
                               fill = "#1B4F72", alpha = 0.25) +
          ggplot2::geom_line(data = pred_df,
                             ggplot2::aes(x = zeta_1, y = density_log10),
                             colour = "#1B4F72", linewidth = 1) +
          ggplot2::geom_vline(xintercept = lognormal_median,
                              linetype = "solid", colour = "grey20", linewidth = 0.6) +
          ggplot2::geom_vline(xintercept = c(ci_lower, ci_upper),
                              linetype = "dashed", colour = "grey40", linewidth = 0.4) +
          ggplot2::geom_rug(data = rug_df,
                            ggplot2::aes(x = zeta_1, colour = study_type),
                            sides = "b", length = ggplot2::unit(0.04, "npc"),
                            linewidth = 0.8, alpha = 0.9) +
          ggplot2::scale_x_log10(limits = c(1e3, 1e15),
                                 breaks = 10 ^ seq(3, 15, by = 2),
                                 labels = c(expression(10^3), expression(10^5),
                                            expression(10^7), expression(10^9),
                                            expression(10^11), expression(10^13),
                                            expression(10^15))) +
          ggplot2::scale_y_continuous(limits = c(0, peak_density * 1.35),
                                      expand = c(0, 0)) +
          ggplot2::scale_color_manual(values = study_pal, name = "Study type",
                                      guide = "none") +
          ggplot2::annotation_logticks(sides = "b", short = ggplot2::unit(0.05, "cm"),
                                       mid = ggplot2::unit(0.1, "cm"),
                                       long = ggplot2::unit(0.15, "cm")) +
          ggplot2::annotate("text",
                            x = lognormal_median, y = peak_density * 1.08,
                            label = sprintf("median\n%.1e", lognormal_median),
                            hjust = 0.5, vjust = 0, size = 3.4, colour = "grey20",
                            lineheight = 0.9) +
          ggplot2::annotate("text",
                            x = ci_lower, y = peak_density * 0.55,
                            label = sprintf("2.5%%\n%.1e", ci_lower),
                            hjust = 1.15, vjust = 0.5, size = 3.1, colour = "grey40",
                            lineheight = 0.9) +
          ggplot2::annotate("text",
                            x = ci_upper, y = peak_density * 0.55,
                            label = sprintf("97.5%%\n%.1e", ci_upper),
                            hjust = -0.15, vjust = 0.5, size = 3.1, colour = "grey40",
                            lineheight = 0.9) +
          ggplot2::annotate("text",
                            x = 10^3.3, y = peak_density * 1.25,
                            hjust = 0, vjust = 0.5, size = 3.6, colour = "#1B4F72",
                            label = sprintf("Lognormal(meanlog = %.2f, sdlog = %.2f)",
                                            meanlog, sdlog)) +
          ggplot2::labs(title = "B. Fitted prior",
                        x = expression(zeta[1] ~ "  (cells " %.% "person"^{-1} %.% "day"^{-1} * ", log scale)"),
                        y = expression("Density (per log"[10] ~ zeta[1] * ")")) +
          ggplot2::theme_classic(base_size = 13) +
          ggplot2::theme(
               panel.grid.major.x = ggplot2::element_line(colour = "grey92",
                                                          linewidth = 0.3),
               panel.grid.minor   = ggplot2::element_blank(),
               axis.title.x       = ggplot2::element_text(margin = ggplot2::margin(t = 8)),
               axis.title.y       = ggplot2::element_text(margin = ggplot2::margin(r = 8)),
               plot.title         = ggplot2::element_text(face = "bold", size = 14,
                                                          margin = ggplot2::margin(b = 8))
          )

     combo <- cowplot::plot_grid(p_sources, p_density,
                                 ncol = 1, align = "v", rel_heights = c(1.35, 1))

     figure_path <- file.path(PATHS$DOCS_FIGURES, "zeta_1_prior.png")
     grDevices::png(filename = figure_path, width = 2800, height = 2800,
                    units = "px", res = 300)
     print(combo)
     grDevices::dev.off()
     message("zeta_1 prior figure saved to: ", figure_path)

     invisible(list(data        = data_df,
                    fit         = fit,
                    param_df    = param_df,
                    prediction  = pred_df,
                    sensitivity = sensitivity))
}
