#' Estimate Immune Decay
#'
#' This function estimates immune durability by fitting a proportional decay model to the data.
#' It uses nonlinear least squares fitting (NLS) to estimate decay parameters and generates plots
#' for predicted immune durability and decay rate distributions.
#'
#' @param PATHS A list containing the paths where data and figures are saved. Typically generated by the `get_paths()` function and should include:
#' \itemize{
#'   \item \strong{DATA_IMMUNE_DURABILITY}: Path to the directory containing the immune durability data.
#'   \item \strong{DOCS_FIGURES}: Path to the directory where the plots will be saved.
#' }
#'
#' @importFrom minpack.lm nls.lm nls.lm.control
#' @importFrom ggplot2 ggplot aes geom_ribbon geom_line geom_point geom_segment annotate labs theme_classic scale_y_continuous scale_x_continuous scale_color_manual
#' @importFrom cowplot plot_grid
#' @importFrom truncnorm dtruncnorm
#' @examples
#' \dontrun{
#' # Assuming PATHS is generated from get_paths()
#' PATHS <- get_paths()
#' est_immune_decay(PATHS)
#' }
#' @export

est_immune_decay <- function(PATHS) {

     immune_data <- read.csv(file.path(PATHS$DATA_IMMUNITY, "immune_decay_data.csv"), stringsAsFactors = FALSE)

     # Define proportional decay function
     proportional_decay_function <- function(par, x) {
          a <- par[1]
          b <- par[2]
          a * (1 - b) ^ x
     }

     # Starting values for model parameters
     start_values <- c(a = 0.95, b = 0.00025)

     # Objective function to minimize residuals
     objective_function <- function(par, y) {
          residuals <- y - proportional_decay_function(par, immune_data$day)
          residuals
     }

     # Fit model for best fit, upper, and lower bounds
     fit <- nls.lm(par = start_values, fn = objective_function, y = immune_data$effectiveness,
                   upper = c(0.99, 1), lower = c(0.99, 0), control = nls.lm.control(maxiter = 1000))

     fit_hi <- nls.lm(par = start_values, fn = objective_function, y = immune_data$effectiveness_hi,
                      upper = c(0.99, 1), lower = c(0.99, 0), control = nls.lm.control(maxiter = 1000))

     fit_lo <- nls.lm(par = start_values, fn = objective_function, y = immune_data$effectiveness_lo,
                      upper = c(0.99, 1), lower = c(0.99, 0), control = nls.lm.control(maxiter = 1000))

     # Extract fitted parameters
     fitted_parameters <- fit$par
     fitted_parameters_hi <- fit_hi$par
     fitted_parameters_lo <- fit_lo$par

     # Create prediction data frame
     prediction <- data.frame(day = seq(0, 365*15, by = 1))
     prediction$predicted <- proportional_decay_function(fitted_parameters, prediction$day)
     prediction$predicted_lo <- proportional_decay_function(fitted_parameters_lo, prediction$day)
     prediction$predicted_hi <- proportional_decay_function(fitted_parameters_hi, prediction$day)

     # Generate the decay rate distribution
     sd_epsilon <- (fitted_parameters_lo[2] - fitted_parameters_hi[2]) / (2 * 1.96)
     mean_epsilon <- fitted_parameters[2]
     x_vals <- seq(fitted_parameters_hi[2], fitted_parameters_lo[2], length.out = 1000)
     y_vals <- dlnorm(x_vals, meanlog = log(mean_epsilon + (sd_epsilon^2)/2), sdlog = 0.25)





     param_df_point <- make_param_df(variable_name = 'epsilon',
                                     variable_description = 'Immunity decay rate',
                                     parameter_distribution = rep('point', 3),
                                     parameter_name = c('low', 'mean', 'high'),
                                     parameter_value = c(fitted_parameters_lo['b'], fitted_parameters['b'], fitted_parameters_hi['b']))


     param_df_stoch <- make_param_df(variable_name = 'epsilon',
                                     variable_description = 'Immunity decay rate',
                                     parameter_distribution = 'lognormal',
                                     parameter_name = c('mean', 'sd'),
                                     parameter_value = c(mean_epsilon, sd_epsilon))

     param_df <- rbind(param_df_point, param_df_stoch)

     path <- file.path(PATHS$MODEL_INPUT, "param_epsilon_immune_decay.csv")
     write.csv(param_df, path, row.names = FALSE)
     message(paste("Parameter data frame for immune decay (epsilon) saved to:", path))

     path <- file.path(PATHS$MODEL_INPUT, "pred_immune_decay.csv")
     write.csv(prediction, path, row.names = FALSE)
     message(paste("Predicted immune decay (days after infection) saved to:", path))



     p1 <-
          ggplot() +
          geom_ribbon(data = prediction, aes(x = day, ymin = predicted_lo, ymax = predicted_hi), fill = "grey", alpha = 0.2) +  # Shaded ribbon for confidence intervals
          geom_line(data = prediction, aes(x = day, y = predicted), color = 'black', size = 1.25) +
          geom_line(data = prediction, aes(x = day, y = predicted_lo), color = '#DAA520', size = 0.75, linetype='dashed') +
          geom_line(data = prediction, aes(x = day, y = predicted_hi), color = '#6A5ACD', size = 0.75, linetype='dashed') +
          geom_point(data = immune_data[1,], aes(x = day, y = effectiveness, color = source), fill='white', pch=21, size = 5) +  # Points for original data
          geom_point(data = immune_data[2,], aes(x = day, y = effectiveness, color = source), size = 5) +  # Points for original data
          geom_point(data = immune_data[3,], aes(x = day, y = effectiveness, color = source), size = 5) +
          geom_segment(data = immune_data[2,], aes(x = day, y = effectiveness_lo, yend = effectiveness_hi, color = source), size=1.25) +  # Horizontal error bars
          geom_segment(data = immune_data[3,], aes(x = day, y = effectiveness_lo, yend = effectiveness_hi, color = source), size=1.25) +  # Horizontal error bars
          annotate("text", x = 365 * 12.25, y = 0.75, label = bquote(epsilon == .(sprintf("%.5f", fitted_parameters_hi[2]))), color = "#6A5ACD", size = 5) +
          annotate("text", x = 365 * 12.25, y = 0.7, label = bquote(epsilon == .(sprintf("%.5f", fitted_parameters[2]))), color = "black", size = 5) +
          annotate("text", x = 365 * 12.25, y = 0.65, label = bquote(epsilon == .(sprintf("%.5f", fitted_parameters_lo[2]))), color = "#DAA520", size = 5) +
          labs(x = "Years after infection", y = "Proportion immune") +
          ggtitle("A") +
          theme_classic(base_size = 18) +
          theme(panel.grid.minor = element_blank(),  # Remove minor gridlines
                panel.grid.major.y = element_blank(),
                axis.title.x = element_text(margin = margin(t = 15)),  # Increase space between x-axis and x-axis label
                axis.title.y = element_text(margin = margin(r = 15)),
                legend.position = c(0.99, 0.975),  # Place legend inside the plot (top-right corner)
                legend.justification = c("right", "top"),  # Align the legend to the right-top
                legend.title = element_blank(),  # Remove the legend title
                legend.text = element_text(size = 11),
                legend.background = element_blank()) +
          scale_y_continuous(limits = c(0, 1), expand = c(0, 0)) +
          scale_x_continuous(limits = c(0, 365*15), labels = 1:15, breaks = 365 * (1:15), expand = c(0, 0)) +  # Yearly labels and breaks
          scale_color_manual(values = c('Ali et al (2011)' = "#FF6347",
                                        'Clemens et al (1991)' = "#008B8B",
                                        'Assumption' = 'black'))



     p2 <-
          ggplot(data.frame(x = x_vals, y = y_vals), aes(x = x, y = y)) +
          geom_area(fill = "grey", alpha = 0.2) +  # Fill the area under the curve
          geom_line(color = "grey50", size = 1) +
          geom_vline(xintercept = mean_epsilon, linetype = "solid", color = "black", size = 1.25) +
          geom_vline(xintercept = fitted_parameters_hi[2], linetype = "dashed", color = "#6A5ACD", size = 0.75) +  # Dashed grey line at x = 0
          geom_vline(xintercept = fitted_parameters_lo[2], linetype = "dashed", color = "#DAA520", size = 0.75) +  # Dashed grey line at x = 0
          labs(x = stringr::str_wrap(expression("Decay rate in immunity from natural infection (\u03B5)"), , width = 20)) +  # Only label the x-axis
          ggtitle("B") +
          scale_y_continuous(limits = c(0, max(y_vals) * 1.1), expand = c(0, 0)) +  # Yearly labels and breaks
          theme_classic(base_size = 18) +
          theme(
               axis.title.y = element_blank(),  # Remove the y-axis label
               axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1),  # Rotate x-axis labels
               axis.title.x = element_text(margin = margin(t = 30), hjust = 0.5),  # Increase space between x-axis title and labels
               plot.margin = unit(c(1.75, 0.1, 0.75, 0.1), "inches")  # Adjust margins
          )

     # Combine the plots
     combo <- cowplot::plot_grid(p1, p2, nrow = 1, rel_widths = c(2.25, 1))

     print(combo)

     # Save the combined plot
     plot_output_path <- file.path(PATHS$DOCS_FIGURES, "immune_decay.png")
     ggplot2::ggsave(plot_output_path, plot = combo, width = 3000, height = 2000, units = "px", dpi = 300)

     message(paste("Immune durability plot saved to:", plot_output_path))

}
