#' Estimate and Visualize Symptomatic Proportion Data
#'
#' This function reads the symptomatic proportion data, fits a Beta distribution to simulate the proportion of infections that are symptomatic, and generates visualizations comparing estimates from previous studies.
#'
#' @param PATHS A list containing paths where the symptomatic proportion data and figures should be saved. Typically generated by the `get_paths()` function and should include:
#' \itemize{
#'   \item \strong{DATA_PROCESSED}: Path to the symptomatic proportion data.
#'   \item \strong{DOCS_FIGURES}: Path to save the generated plots.
#' }
#'
#' @return The function does not return a value but generates and saves plots to a PNG file.
#'
#' @examples
#' \dontrun{
#' # Estimate and visualize symptomatic proportion data
#' PATHS <- get_paths()
#' est_symptomatic_prop(PATHS)
#' }
#'
#' @importFrom ggplot2 ggplot geom_histogram stat_function geom_vline geom_text scale_x_continuous scale_y_continuous theme_minimal labs annotate geom_line
#' @importFrom utils read.csv write.csv
#' @importFrom stats rbeta quantile dbeta
#' @export

est_symptomatic_prop <- function(PATHS) {

     # Read the symptomatic proportion data
     df <- utils::read.csv(file.path(PATHS$DATA_SYMPTOMATIC, "summary_symptomatic_cases.csv"))

     # Simulate sigma (proportion of infections that are symptomatic) using a Beta distribution
     quantiles <- c(0.0001, 0.0275, 0.25, 0.5, 0.75, 0.975, 0.9999)
     probs <- c(min(df$ci_lo, na.rm = TRUE),
                quantile(df$ci_lo, probs = 0.0275, na.rm = TRUE),
                quantile(df$ci_lo, probs = 0.25, na.rm = TRUE),
                mean(df$mean, na.rm = TRUE),
                quantile(df$ci_hi, probs = 0.75, na.rm = TRUE),
                quantile(df$ci_hi, probs = 0.975, na.rm = TRUE),
                max(df$ci_hi, na.rm = TRUE))

     prm <- propvacc::get_beta_params(quantiles = quantiles, probs = probs)
     samps <- stats::rbeta(1000, shape1 = prm$shape1, shape2 = prm$shape2)
     ci <- stats::quantile(samps, probs = c(0.025, 0.5, 0.975))

     param_df <- MOSAIC::make_param_df(
          variable_name = 'sigma',
          variable_description = 'proportion symptomatic',
          parameter_distribution = 'beta',
          parameter_name = names(prm),
          parameter_value = unlist(prm)
     )

     path <- file.path(PATHS$MODEL_INPUT, "param_sigma_prop_symptomatic.csv")
     write.csv(param_df, path, row.names = FALSE)
     message(paste("Parameter data frame for symptomatic proportion (theta) saved to:", path))

     # Create Beta distribution plot
     df_samples <- data.frame(x = samps)
     x_vals <- seq(0, 1, length.out = 1000)
     y_vals <- stats::dbeta(x_vals, prm$shape1, prm$shape2)
     df_beta <- data.frame(x = x_vals, y = y_vals)

     p1 <- ggplot2::ggplot(df_samples, ggplot2::aes(x = x)) +
          ggplot2::geom_histogram(ggplot2::aes(y = ..density..), bins = 35, fill = "#1B4F72", color = 'white', alpha = 0.5) +
          ggplot2::geom_line(data = df_beta, ggplot2::aes(x = x, y = y), color = "black", size = 1) +
          ggplot2::geom_vline(xintercept = ci[c(1, 3)], linetype = "dashed", color = "grey20", size = 0.25) +
          ggplot2::geom_vline(xintercept = ci[2], linetype = "dashed", color = "grey20", size = 0.25) +
          ggplot2::labs(title = "A", x = "", y = "") +
          ggplot2::scale_x_continuous(limits = c(-0.02, 1.25), breaks = seq(0, 1, 0.25), expand = c(0, 0)) +
          ggplot2::scale_y_continuous(expand = c(0.005, 0.005)) +
          ggplot2::theme_minimal(base_size = 14)

     # Comparison with previous studies
     pal <- c("#274001", "#828a00", "#D35400", "#7D3C98", "#1B4F72", "#a62f03", "#400d01", "#4d8584")

     p2 <- ggplot2::ggplot(df, ggplot2::aes(x = source, y = mean, color = source)) +
          ggplot2::geom_hline(yintercept = ci[c(1, 3)], linetype = "dashed", color = "grey20", size = 0.25) +
          ggplot2::geom_hline(yintercept = ci[2], linetype = "dashed", color = "grey20", size = 0.25) +
          ggplot2::geom_rect(ggplot2::aes(xmin = as.numeric(factor(source)) - 0.2,
                                          xmax = as.numeric(factor(source)) + 0.2,
                                          ymin = ci_lo, ymax = ci_hi, fill = source), alpha = 0.3, color = NA) +
          ggplot2::geom_rect(ggplot2::aes(xmin = as.numeric(factor(source)) - 0.2,
                                          xmax = as.numeric(factor(source)) + 0.2,
                                          ymin = mean - 0.0025, ymax = mean + 0.0025, fill = source)) +
          ggplot2::labs(title = "B", x = "", y = "Proportion of infections that are symptomatic") +
          ggplot2::scale_fill_manual(values = pal) +
          ggplot2::scale_color_manual(values = pal) +
          ggplot2::theme_minimal(base_size = 14) +
          ggplot2::coord_flip()

     # Combine and save plot
     combo <- cowplot::plot_grid(p1, p2, ncol = 1, rel_heights = c(1, 1.5), align = 'vh')

     figure_path <- file.path(PATHS$DOCS_FIGURES, "proportion_symptomatic.png")

     grDevices::png(filename = figure_path, width = 2400, height = 2400, units = "px", res = 300)
     print(combo)
     grDevices::dev.off()

     message(paste("Symptomatic proportion plot saved to:", figure_path))


}
