#' Estimate Seasonal Dynamics for Cholera and Precipitation Using Fourier Series
#'
#' This function retrieves historical precipitation data, processes cholera case data, and fits seasonal dynamics models using a double Fourier series. The results are saved to a CSV file, including parameter estimates, fitted values, and processed data.
#'
#' @param PATHS A list containing paths where raw and processed data are stored. Typically generated by the `get_paths()` function and should include:
#' \itemize{
#'   \item \strong{DATA_CLIMATE}: Path to the directory where climate data is stored.
#'   \item \strong{DATA_SHAPEFILES}: Path to the directory containing country shapefiles.
#'   \item \strong{DATA_WHO_WEEKLY}: Path to the directory containing cholera data.
#'   \item \strong{MODEL_INPUT}: Path to the directory where model input files will be saved.
#' }
#'
#' @return The function saves the parameter estimates, fitted values, and processed data to a CSV file.
#'
#' @importFrom dplyr mutate group_by summarize bind_rows
#' @importFrom tidyr spread
#' @importFrom lubridate week year
#' @importFrom sf st_read st_coordinates
#' @importFrom utils write.csv read.csv
#' @importFrom glue glue
#' @importFrom ggplot2 ggplot geom_sf labs theme_minimal
#' @importFrom minpack.lm nlsLM
#' @export
est_seasonal_dynamics <- function(PATHS) {


     requireNamespace('minpack.lm')
     requireNamespace('FNN')
     requireNamespace('sf')


     # Load necessary country data
     iso_codes <- MOSAIC::iso_codes_mosaic

     # Load cholera cases data
     cholera_data <- utils::read.csv(file.path(PATHS$DATA_WHO_WEEKLY, "cholera_country_weekly_processed.csv"), stringsAsFactors = FALSE)

     iso_codes_with_data <- sort(unique(cholera_data$iso_code))
     iso_codes_no_data <- setdiff(iso_codes, unique(cholera_data$iso_code))

     ################################################################################
     # Model seasonal dynamics of cases and precipitation using Fourier series
     ################################################################################

     all_precip_data <- list()
     all_fitted_values <- list()
     all_param_values <- list()

     for (country_iso_code in iso_codes) {

          message(glue::glue("Processing country: {country_iso_code}"))

          country_name <- MOSAIC::convert_iso_to_country(country_iso_code)

          # Load climate data for the country
          precip_file <- file.path(PATHS$DATA_CLIMATE, glue::glue("climate_data_MRI_AGCM3_2_S_precipitation_sum_1970-01-01_2030-12-31_{country_iso_code}.parquet"))

          # Check if the precipitation file exists
          if (file.exists(precip_file)) {
               message(glue::glue("Loading precipitation data from file for {country_iso_code}"))
               precip_data <- arrow::read_parquet(file = precip_file)
          } else {
               stop(glue::glue("Precipitation data not found for {country_iso_code}."))
          }

          precip_data <- precip_data[precip_data$date >= '2014-09-01' & precip_data$date < '2024-09-01',]

          # Aggregate weekly precipitation data
          precip_data <- precip_data %>%
               mutate(week = lubridate::week(date), year = lubridate::year(date)) %>%
               group_by(year, week) %>%
               summarize(weekly_precipitation_sum = sum(value, na.rm = TRUE), .groups = 'drop')

          # Merge with cholera data by week and ISO code
          precip_data$iso_code <- country_iso_code
          precip_data <- merge(precip_data, cholera_data, by = c("week", "iso_code"), all.x = TRUE)

          # Create a sequence of weeks for the fitted curve
          week_seq <- seq(min(precip_data$week), max(precip_data$week), length.out = 100)

          # Scale the precipitation and cholera data
          precip_data$precip_scaled <- scale(precip_data$weekly_precipitation_sum, center = TRUE, scale = TRUE)
          precip_data$cases_scaled <- scale(precip_data$cases, center = TRUE, scale = TRUE)

          # Fit the Generalized Fourier Series model to precipitation data using MOSAIC::fourier_series_double
          fit_fourier_precip <- minpack.lm::nlsLM(
               precip_scaled ~ MOSAIC::fourier_series_double(week, a1, b1, a2, b2, p = 52, beta0 = 0),
               data = precip_data,
               start = list(a1 = 1, b1 = 1, a2 = 0.5, b2 = 0.5)
          )

          # Extract coefficients and standard errors
          coefs_precip <- coef(fit_fourier_precip)
          se_precip <- sqrt(diag(vcov(fit_fourier_precip)))

          param_values_precip <- data.frame(
               country_name = country_name,
               country_iso_code = country_iso_code,
               response = "precipitation",
               parameter = names(coefs_precip),
               mean = coefs_precip,
               se = se_precip,
               ci_lo = coefs_precip - 1.96 * se_precip,
               ci_hi = coefs_precip + 1.96 * se_precip
          )

          # Use MOSAIC::fourier_series_double to calculate fitted values for precipitation
          fitted_values_precip <- MOSAIC::fourier_series_double(week_seq, coefs_precip["a1"], coefs_precip["b1"], coefs_precip["a2"], coefs_precip["b2"], p = 52, beta0 = 0)

          # Fit the Fourier series model to cholera cases if data is available
          if (country_iso_code %in% iso_codes_with_data) {
               fit_fourier_cases <- minpack.lm::nlsLM(
                    cases_scaled ~ MOSAIC::fourier_series_double(week, a1, b1, a2, b2, p = 52, beta0 = 0),
                    data = precip_data,
                    start = list(
                         a1 = coefs_precip["a1"],
                         b1 = coefs_precip["b1"],
                         a2 = coefs_precip["a2"],
                         b2 = coefs_precip["b2"]
                    )
               )

               coefs_cases <- coef(fit_fourier_cases)
               se_cases <- sqrt(diag(vcov(fit_fourier_cases)))

               param_values_cases <- data.frame(
                    country_name = country_name,
                    country_iso_code = country_iso_code,
                    response = "cases",
                    parameter = names(coefs_cases),
                    mean = coefs_cases,
                    se = se_cases,
                    ci_lo = coefs_cases - 1.96 * se_cases,
                    ci_hi = coefs_cases + 1.96 * se_cases
               )

               # Use MOSAIC::fourier_series_double to calculate fitted values for cholera cases
               fitted_values_cases <- MOSAIC::fourier_series_double(week_seq, coefs_cases["a1"], coefs_cases["b1"], coefs_cases["a2"], coefs_cases["b2"], p = 52, beta0 = 0)
          } else {
               fitted_values_cases <- rep(NA, length(week_seq))

               param_values_cases <- data.frame(
                    country_name = country_name,
                    country_iso_code = country_iso_code,
                    response = "cases",
                    parameter = names(coefs_precip),
                    mean = NA,
                    se = NA,
                    ci_lo = NA,
                    ci_hi = NA
               )
          }

          # Store fitted values
          fitted_values <- data.frame(
               week = week_seq,
               iso_code = country_iso_code,
               fitted_values_fourier_precip = fitted_values_precip,
               fitted_values_fourier_cases = fitted_values_cases
          )

          # Store results for each country
          precip_data$Country <- country_name
          fitted_values$Country <- country_name
          param_values <- rbind(param_values_precip, param_values_cases)

          all_precip_data[[country_iso_code]] <- precip_data
          all_fitted_values[[country_iso_code]] <- fitted_values
          all_param_values[[country_iso_code]] <- param_values

     }

     # Combine all results into a single dataframe
     combined_precip_data <- do.call(rbind, all_precip_data)
     combined_fitted_values <- do.call(rbind, all_fitted_values)
     combined_param_values <- do.call(rbind, all_param_values)

     # Remove beta0 and p parameters
     combined_param_values <- combined_param_values[!(combined_param_values$parameter %in% c("beta0", "p")),]

     path <- file.path(PATHS$MODEL_INPUT, "param_fourier_series.csv")
     utils::write.csv(combined_param_values, file = path, row.names = FALSE)
     message("Parameter values saved to:")
     message(path)









}
