#' Fit Mobility Model Using Flight Data and Distance Matrices
#'
#' This function estimates the departure probability (tau_i) and diffusion model (pi_ij) using flight data, distance matrices, and population sizes. It processes flight data, builds mobility and distance matrices, fits the mobility model, and saves the results in CSV format.
#'
#' @note This function requires the optional \code{mobility} package from GitHub.
#'   Install with: \code{remotes::install_github("COVID-19-Mobility-Data-Network/mobility")}
#'
#'   The \code{mobility} package requires JAGS (>= 4.3.0) to be installed on your system.
#'   Most users will not need to regenerate mobility data, as pre-computed files are
#'   included in the package.
#'
#' @param PATHS A list containing paths where data, models, and figures are stored. Typically generated by the `get_paths()` function and should include:
#' \itemize{
#'   \item \strong{DATA_OAG}: Path to the directory containing flight data (OAG).
#'   \item \strong{DATA_SHAPEFILES}: Path to the directory containing shapefiles for African countries.
#'   \item \strong{DATA_DEMOGRAPHICS}: Path to the directory containing demographic data.
#'   \item \strong{MODEL_INPUT}: Path to the directory where the model input files will be saved.
#'   \item \strong{DOCS_FIGURES}: Path to the directory where figures will be saved.
#' }
#'
#' @return The function saves mobility matrices (M, D, N), travel probabilities (tau_j), and diffusion matrices (pi_ij) as CSV files in the specified directory. It also generates and saves visualizations as PNG files.
#'
#' @importFrom ggplot2 ggplot aes geom_tile xlab ylab theme_bw element_text margin scale_fill_gradient guides guide_colorbar geom_segment geom_sf geom_point geom_text scale_size_continuous theme_void
#' @importFrom reshape2 melt
#' @importFrom sf st_read st_coordinates st_centroid
#' @importFrom dplyr left_join rename
#' @importFrom glue glue
#' @importFrom cowplot plot_grid
#' @importFrom utils read.csv write.csv
#' @export

est_mobility <- function(PATHS) {

     # Check for optional mobility package
     if (!requireNamespace("mobility", quietly = TRUE)) {
          stop(
               "The 'mobility' package is required but not installed.\n",
               "Install with: remotes::install_github('COVID-19-Mobility-Data-Network/mobility')\n\n",
               "Note: The mobility package requires JAGS (>= 4.3.0) to be installed.\n",
               "Most users do not need to regenerate mobility data, as pre-computed files\n",
               "are included in model/input/.",
               call. = FALSE
          )
     }

     requireNamespace('ggplot2')
     requireNamespace('reshape2')
     requireNamespace('sf')
     requireNamespace('dplyr')
     requireNamespace('tidyr')
     requireNamespace('glue')


     #--------------------------------------------------------------------------
     # Load flight data and build mobility matrix (M)
     #--------------------------------------------------------------------------

     message("Getting mean DAILY OAG flight data from 2017")
     data_flights <- utils::read.csv(file.path(PATHS$DATA_OAG, "oag_africa_2017_mean_daily.csv"), stringsAsFactors = FALSE)
     data_flights <- data_flights[data_flights$origin_iso3 %in% MOSAIC::iso_codes_mosaic,]
     data_flights <- data_flights[data_flights$destination_iso3 %in% MOSAIC::iso_codes_mosaic,]

     M <- mobility::get_mob_matrix(orig=data_flights$origin_iso3,
                                   dest=data_flights$destination_iso3,
                                   value=data_flights$count)



     #--------------------------------------------------------------------------
     # Get distance matrix (D)
     #--------------------------------------------------------------------------

     message("Making distance matrix")
     shapefiles <- list.files(PATHS$DATA_SHAPEFILES, pattern = "\\.shp$", full.names = TRUE)
     data_centroids <- do.call(rbind, lapply(shapefiles, MOSAIC::get_centroid))

     if (!(all(data_flights$origin_iso3 %in% data_centroids$iso3))) stop("Some iso3 codes are missing in data_centriods")
     data_centroids <- data_centroids[data_centroids$iso3 %in% MOSAIC::iso_codes_mosaic,]
     row.names(data_centroids) <- NULL
     head(data_centroids)

     D <- get_distance_matrix(x=data_centroids$lon,
                              y=data_centroids$lat,
                              id=data_centroids$iso3)
     D <- D*111.35  # Convert decimal degrees to kilometers


     #--------------------------------------------------------------------------
     # Get Population size vector (N)
     #--------------------------------------------------------------------------

     message("Getting population sizes (2017 to match OAG data)")
     data_demographics <- utils::read.csv(file.path(PATHS$DATA_DEMOGRAPHICS, "demographics_africa_2000_2023.csv"), stringsAsFactors = FALSE)
     data_demographics <- data_demographics[data_demographics$year == 2017 & data_demographics$iso_code %in% MOSAIC::iso_codes_mosaic,]
     data_demographics <- data_demographics[order(data_demographics$iso_code),]
     N <- as.integer(data_demographics$population)
     names(N) <- data_demographics$iso_code


     #--------------------------------------------------------------------------
     # Check that dimensions match
     #--------------------------------------------------------------------------

     check <- c(
          dim(M)[1] == dim(M)[2],
          dim(M)[1] == length(N),
          dim(M)[2] == length(N),
          dimnames(M)$origin == names(N),
          dimnames(M)$destination == names(N),
          dim(M)[1] == dim(D)[1],
          dim(M)[2] == dim(D)[2],
          dimnames(M)$origin == dimnames(D)$origin,
          dimnames(M)$destination == dimnames(D)$destination
     )

     if (!all(check)) {
          stop("Dimension mismatch in M, D, or N.")
     } else {
          message("Mobility matrices dimensions match")
     }

     #--------------------------------------------------------------------------
     # Fit probability of travel, departure (tau_i)
     #--------------------------------------------------------------------------

     message("Fitting departure process: travel probability (tau_j)")
     diagonal <- diag(M)
     diagonal[is.na(diagonal)] <- 0

     trips_total <- apply(M, 1, function(x) sum(x, na.rm = TRUE))
     y <- as.integer(trips_total - diagonal)
     names(y) <- names(diag(M))

     y <- y[match(names(N), names(y))]

     mod_travel_prob <- mobility::fit_prob_travel(travel = y,
                                                  total = N,
                                                  n_chain = 5,
                                                  n_burn = 1000,
                                                  n_samp = 1000,
                                                  n_thin = 5)

     mod_travel_prob_summary <- mobility::summary(mod_travel_prob)
     mod_travel_prob_summary <- data.frame(iso3 = names(N), mod_travel_prob_summary)

     beta_params <- propvacc::get_beta_params(mu = mod_travel_prob_summary$mean, mod_travel_prob_summary$sd^2)

     df_travel_prob <- data.frame(
          country = convert_iso_to_country(names(y)),
          iso_code = names(y),
          mean = mod_travel_prob_summary$mean,
          sd = mod_travel_prob_summary$sd,
          ci_lo = mod_travel_prob_summary$Q2.5,
          ci_hi = mod_travel_prob_summary$Q97.5,
          shape1 = beta_params$shape1,
          shape2 = beta_params$shape2
     )

     df_travel_prob <- merge(df_travel_prob, data.frame(iso_code = names(N), population = N), by='iso_code')

     tau_vec <- as.vector(df_travel_prob$mean)
     names(tau_vec) <- df_travel_prob$iso_code


     #--------------------------------------------------------------------------
     # Fit probability of travel from origin to destination, diffusion (pi_i)
     #--------------------------------------------------------------------------

     message("Fitting diffusion process: gravity power model for pi_ij")
     mobility_matrices <- list(M=M, D=D, N=N)
     mod_mobility <- mobility::mobility(data=mobility_matrices,
                                        model='departure-diffusion',
                                        type='power',
                                        hierarchical = F,
                                        n_chain = 5,
                                        n_burn = 1000,
                                        n_samp = 1000,
                                        n_thin = 5)
     mod_mobility_summary <- mobility::summary(mod_mobility, probs=c(0.025, 0.975), ac_lags=10)
     mod_mobility_summary <- data.frame(parameter = row.names(mod_mobility_summary), mod_mobility_summary)
     mobility::check(mod_mobility)

     pi_mat <- MOSAIC::calc_diffusion_matrix_pi(D = D,
                                                N = N,
                                                gamma = mod_mobility_summary['gamma', 'mean'],
                                                omega = mod_mobility_summary['omega', 'mean'])


     #--------------------------------------------------------------------------
     # Save matrices and parameters to file
     #--------------------------------------------------------------------------

     message("Writing mobility model matrices to file: M, D, N, tau, pi")
     utils::write.csv(data_centroids, file.path(PATHS$MODEL_INPUT, "mobility_lon_lat.csv"), row.names = FALSE)
     utils::write.csv(M, file.path(PATHS$MODEL_INPUT, "mobility_M.csv"), row.names = TRUE)
     utils::write.csv(D, file.path(PATHS$MODEL_INPUT, "mobility_D.csv"), row.names = TRUE)
     utils::write.csv(N, file.path(PATHS$MODEL_INPUT, "mobility_N.csv"), row.names = TRUE)
     utils::write.csv(mod_travel_prob_summary, file.path(PATHS$MODEL_INPUT, "mobility_travel_prob_params.csv"), row.names = TRUE)
     utils::write.csv(mod_mobility_summary, file.path(PATHS$MODEL_INPUT, "mobility_gravity_params.csv"), row.names = TRUE)
     utils::write.csv(tau_vec, file.path(PATHS$MODEL_INPUT, "mobility_tau.csv"), row.names = TRUE)
     utils::write.csv(pi_mat, file.path(PATHS$MODEL_INPUT, "mobility_pi.csv"), row.names = TRUE)


     message("Writing standard format parameter data frames")
     param_df_point <- make_param_df(
          variable_name = "tau",
          variable_description = "Country-level travel probabilities",
          parameter_distribution = "point",
          i = df_travel_prob$iso_code,
          parameter_name = "mean",
          parameter_value = df_travel_prob$mean
     )

     param_df_stoch <- make_param_df(
          variable_name = "tau",  # Assuming 'tau' represents travel probabilities
          variable_description = "Country-level travel probabilities",
          parameter_distribution = "beta",
          i = df_travel_prob$iso_code,
          parameter_name = c(rep("shape1", nrow(df_travel_prob)), rep("shape2", nrow(df_travel_prob))),
          parameter_value = c(df_travel_prob$shape1, df_travel_prob$shape2)
     )

     param_df <- rbind(param_df_point, param_df_stoch)
     param_df <- param_df[order(param_df$i),]

     utils::write.csv(param_df, file.path(PATHS$MODEL_INPUT, "param_tau_departure.csv"), row.names = FALSE)

     tmp <- melt(pi_mat)

     param_df <- make_param_df(
          variable_name = "pi",  # Assuming 'tau' represents travel probabilities
          variable_description = "Probability of travel from i to j",
          parameter_distribution = "point",
          i = tmp$origin,
          j = tmp$destination,
          parameter_name = 'mean',
          parameter_value = tmp$value
     )

     utils::write.csv(param_df, file.path(PATHS$MODEL_INPUT, "param_pi_diffusion.csv"), row.names = FALSE)


     param_df <- rbind(
          make_param_df(
               variable_name = "mobility_gamma",
               variable_description = "Distance parameter in mobility model",
               parameter_distribution = "point",
               parameter_name = 'mean',
               parameter_value = mod_mobility_summary['gamma', 'mean']
          ),
          make_param_df(
               variable_name = "mobility_omega",
               variable_description = "Population parameter in mobility model",
               parameter_distribution = "point",
               parameter_name = 'mean',
               parameter_value = mod_mobility_summary['omega', 'mean']
          )
     )

     utils::write.csv(param_df, file.path(PATHS$MODEL_INPUT, "param_gravity_model.csv"), row.names = FALSE)

     message("Matrices and parameter estimates saved here:")
     message(PATHS$MODEL_INPUT)

}
