#' Get Median Elevation Data for Multiple Countries Using Shapefiles
#'
#' This function retrieves elevation data for a specified number of points within the boundary of each country's shapefile from the `iso_codes_mosaic` list using the Open-Meteo API. It returns the median elevation for each country.
#'
#' @param PATHS A list containing the paths to where the elevation data should be saved. Typically generated by the `get_paths()` function and should include:
#' \itemize{
#'   \item \strong{DATA_SHAPEFILES}: Path to the directory containing country shapefiles.
#'   \item \strong{DATA_ELEVATION}: Path to the directory where the elevation data will be saved.
#' }
#' @param n_points An integer specifying the number of points to generate within each country's boundary.
#' @param api_key A character string representing the API key for the Open-Meteo API.
#'
#' @return A data frame with the median elevation for each country in `iso_codes_mosaic`.
#'
#' @details The function loads the shapefiles for all countries in `iso_codes_mosaic` from the specified directory, generates `n_points` random points within each country's boundary, and queries the Open-Meteo API for the elevation data at each point. It returns the median elevation for each country and saves the data as a CSV file.
#'
#' @examples
#' \dontrun{
#' # Example usage to get median elevation data for all countries in iso_codes_mosaic
#' n_points <- 10
#' api_key <- "your_api_key_here"
#' PATHS <- get_paths()
#' median_elevations <- get_elevation(n_points, api_key, PATHS)
#' print(median_elevations)
#'}
#' @importFrom httr GET content status_code
#' @importFrom jsonlite fromJSON
#' @importFrom utils download.file write.csv txtProgressBar setTxtProgressBar
#' @importFrom sf st_read st_sample st_coordinates
#' @export

get_elevation <- function(PATHS, n_points, api_key = NULL) {

     requireNamespace('sf')
     requireNamespace('utils')

     # Load the list of ISO3 country codes for the MOSAIC model
     iso_codes <- MOSAIC::iso_codes_africa

     # Ensure the elevation directory exists
     if (!dir.exists(PATHS$DATA_ELEVATION)) dir.create(PATHS$DATA_ELEVATION, recursive = TRUE)

     results_list <- list()

     pb <- utils::txtProgressBar(min = 0, max = length(iso_codes), style = 3)

     for (i in seq_along(iso_codes)) {

          country_results_list <- list()

          # Construct the path to the shapefile for each country
          shapefile_path <- file.path(PATHS$DATA_SHAPEFILES, paste0(iso_codes[i], "_ADM0.shp"))

          # Check if the shapefile exists
          if (!file.exists(shapefile_path)) {
               message(paste("Shapefile for", iso_codes[i], "not found. Skipping."))
               next
          }

          # Load the country shapefile
          country_shapefile <- sf::st_read(shapefile_path, quiet = TRUE)

          # Generate n_points random points within the country's shapefile boundary
          pts <- MOSAIC::generate_country_grid_n(country_shapefile, n_points)
          coords <- sf::st_coordinates(pts)
          rm(pts)
          rm(country_shapefile)

          for (j in 1:nrow(coords)) {

               lat <- coords[j, "Y"]
               lon <- coords[j, "X"]

               url <- paste0(
                    "https://customer-api.open-meteo.com/v1/elevation?",
                    "latitude=", lat,
                    "&longitude=", lon,
                    "&apikey=", api_key
               )

               temp_file <- tempfile(fileext = ".json")
               utils::download.file(url, temp_file, mode = "wb", quiet = TRUE)
               data <- jsonlite::fromJSON(temp_file)

               country_df <- data.frame(country = iso_codes[i],
                                        latitude = lat,
                                        longitude = lon,
                                        elevation = data$elevation)

               country_results_list <- c(country_results_list, list(country_df))

          }

          result_country <- do.call(rbind, country_results_list)
          result_country <- aggregate(elevation ~ country, data = result_country, FUN = median, na.rm = TRUE)
          results_list <- c(results_list, list(result_country))

          utils::setTxtProgressBar(pb, i)

     }

     close(pb)

     out <- do.call(rbind, results_list)

     file_path <- file.path(PATHS$DATA_ELEVATION, "median_elevation_data.csv")
     utils::write.csv(out, file = file_path, row.names = FALSE)
     message(paste("Elevation data saved to:", file_path))

}
