#' Estimate the Generation Time Distribution for Days and Weeks
#'
#' This function generates the probability distribution of the generation time for cholera based on a gamma distribution. It allows the specification of the mean generation time, which adjusts the shape and rate parameters. The day-wise and week-wise probabilities are saved as CSV files.
#'
#' @param PATHS A list containing the paths where the output tables will be saved. Typically generated by the `get_paths()` function and should include:
#' \itemize{
#'   \item \strong{MODEL_INPUT}: Path to the directory where model input data will be saved.
#'   \item \strong{DOCS_TABLES}: Path to the directory where day-wise and week-wise generation time tables will be saved.
#' }
#' @param mean_generation_time A numeric value representing the desired mean generation time (in days). This value is used to adjust the shape and rate parameters of the gamma distribution.
#'
#' @importFrom utils write.csv
#' @export

get_generation_time_distribution <- function(PATHS, mean_generation_time) {


     param_df_point <- make_param_df(variable_name = 'g',
                               variable_description = 'The generation time',
                               parameter_distribution = 'point',
                               parameter_name = 'mean',
                               parameter_value = mean_generation_time)

     # Adjust the shape and rate parameters based on the mean_generation_time
     shape <- mean_generation_time / 10  # Shape parameter (k) adjusted based on mean generation time
     rate <- 1 / 10  # Rate parameter (1/scale) is set constant

     # Create the parameter data frame
     param_df_stoch <- make_param_df(variable_name = 'g',
                               variable_description = 'The generation time',
                               parameter_distribution = 'gamma',
                               parameter_name = c('shape', 'rate'),
                               parameter_value = c(shape, rate))

     param_df <- rbind(param_df_point, param_df_stoch)

     # Save the parameter data frame
     param_path <- file.path(PATHS$MODEL_INPUT, "param_g_generation_time.csv")
     utils::write.csv(param_df, param_path, row.names = FALSE)
     message(paste("Parameter data frame for the generation time distribution g() saved to:", param_path))

     # Generate the gamma distribution for x = 1 to 56 days (8 weeks)
     x <- 1:(7*8)
     y <- dgamma(x, shape = shape, rate = rate)

     # Create a data frame for day-wise generation time
     df <- data.frame(x = x, y = y)

     # Aggregate days into 7-day weeks
     week_bins <- cut(x, breaks = seq(0, max(x), by = 7), include.lowest = TRUE)
     week_aggregated <- aggregate(y, by = list(week_bins), FUN = sum)

     # Rename columns and normalize probabilities for week-wise generation time
     colnames(week_aggregated) <- c("Interval", "Total_Probability")
     week_aggregated$Week <- 1:nrow(week_aggregated)
     total_sum <- sum(week_aggregated$Total_Probability)
     week_aggregated$Probability <- week_aggregated$Total_Probability / total_sum
     week_aggregated <- week_aggregated[,-which(colnames(week_aggregated) == 'Total_Probability')]

     # Save the day-wise and week-wise generation time data
     day_file <- file.path(PATHS$MODEL_INPUT, "pred_generation_time_days.csv")
     week_file <- file.path(PATHS$MODEL_INPUT, "pred_generation_time_weeks.csv")
     utils::write.csv(df, day_file, row.names = FALSE)
     utils::write.csv(week_aggregated, week_file, row.names = FALSE)
     message("Generation time distribution saved to:", PATHS$MODEL_INPUT)

     # Also save the data to DOCS_TABLES
     utils::write.csv(df, file = file.path(PATHS$DOCS_TABLES, "generation_time_days.csv"), row.names = FALSE)
     utils::write.csv(week_aggregated, file = file.path(PATHS$DOCS_TABLES, "generation_time_weeks.csv"), row.names = FALSE)
     message("Generation time distribution also saved to:", PATHS$DOCS_TABLES)

}
