#' Get Immune Decay Data
#'
#' This function retrieves immune durability data based on known values from various studies.
#' The data includes time (in days), effectiveness, and confidence intervals from studies.
#'
#' @param PATHS A list containing the paths where data and figures are saved. Typically generated by the `get_paths()` function and should include:
#' \itemize{
#'   \item \strong{DATA_IMMUNE_DURABILITY}: Path to the directory where the immune durability data will be saved.
#' }
#'
#' @return A data frame with columns: day, effectiveness, effectiveness_hi, effectiveness_lo, and source.
#' @examples
#' \dontrun{
#' # Assuming PATHS is generated from get_paths()
#' PATHS <- get_paths()
#' immune_data <- get_immune_decay_data(PATHS)
#' print(immune_data)
#' }
#' @export

get_immune_decay_data <- function(PATHS) {

     if (!dir.exists(PATHS$DATA_IMMUNITY)) dir.create(PATHS$DATA_IMMUNITY, recursive = TRUE)

     # Immune durability data from lit review
     df <- data.frame(
          day = c(90, 30*36, 30*42),  # Days from study points
          effectiveness = c(0.95, 0.65, 0.61),  # Effectiveness at these points
          effectiveness_hi = c(0.95, 0.81, 0.81),  # Upper CI for effectiveness
          effectiveness_lo = c(0.95, 0.37, 0.21),  # Lower CI for effectiveness
          source = c("Assumption", "Ali et al (2011)", "Clemens et al (1991)")
     )

     df$source <- factor(df$source, levels = c("Ali et al (2011)", "Clemens et al (1991)", "Assumption"))

     output_file <- file.path(PATHS$DATA_IMMUNITY, "immune_decay_data.csv")
     utils::write.csv(df, output_file, row.names = FALSE)
     message(paste("Immune durability data saved to:", output_file))

}
