#' Get Proportion of Suspected Cholera Cases and Save Parameter Data Frame
#'
#' This function generates the parameters for the proportion of suspected cholera cases (rho) and saves it as a parameter data frame.
#'
#' @param PATHS A list containing paths where the parameter data will be saved. Typically generated by the `get_paths()` function and should include:
#' \itemize{
#'   \item \strong{MODEL_INPUT}: Path to the directory where the parameter data frame will be saved.
#' }
#' @return A data frame containing the parameter values for the proportion of suspected cholera cases (rho).
#' @export

get_suspected_cases <- function(PATHS) {

     # Estimates manually extracted from Weins et al 2023: https://journals.plos.org/plosmedicine/article?id=10.1371/journal.pmed.1004286

     # Low estimate (all settings) - parameter distribution for rho
     probs_all <- c(0.24, 0.52, 0.8)
     prm_all <- propvacc::get_beta_params(quantiles = c(0.0275, 0.5, 0.975),
                                          probs = probs_all)

     # High estimate (during outbreaks) - parameter distribution for rho
     probs_outbreak <- c(0.40, 0.78, 0.99)
     prm_outbreak <- propvacc::get_beta_params(quantiles = c(0.0275, 0.5, 0.975),
                                               probs = probs_outbreak)

     # Create a parameter data frame with the distribution parameters

     param_df_point <-
          make_param_df(
          variable_name = "rho",
          variable_description = c("Proportion of suspected cases that are true infections: Point estimate low (all settings)",
                                   "Proportion of suspected cases that are true infections: Point estimate high (during outbreaks)"),
          parameter_distribution = "beta",
          parameter_name = c("mean", "mean"),
          parameter_value = c(probs_all[2], probs_outbreak[2])
     )

     param_df_stoch <-
          make_param_df(
          variable_name = "rho",
          variable_description = c("Proportion of suspected cases that are true infections: Low estimate (all settings)",
                                   "Proportion of suspected cases that are true infections: Low estimate (all settings)",
                                   "Proportion of suspected cases that are true infections: High estimate (during outbreaks)",
                                   "Proportion of suspected cases that are true infections: High estimate (during outbreaks)"),
          parameter_distribution = "beta",
          parameter_name = c("shape1", "shape2", "shape1", "shape2"),
          parameter_value = c(prm_all$shape1, prm_all$shape2, prm_outbreak$shape1, prm_outbreak$shape2)
     )


     param_df <- rbind(param_df_point, param_df_stoch)

     # Save the parameter data frame
     param_path <- file.path(PATHS$MODEL_INPUT, "param_rho_suspected_cases.csv")
     utils::write.csv(param_df, param_path, row.names = FALSE)
     message(paste("Parameter data frame for suspected cases saved to:", param_path))

}
