#' Estimate the Generation Time Distribution for Days and Weeks
#'
#' This function generates the probability distribution of the generation time for cholera based on a gamma distribution. It allows the specification of the mean generation time, which adjusts the shape and rate parameters. The day-wise and week-wise probabilities are saved as CSV files.
#'
#' @param PATHS A list containing the paths where the output tables will be saved. Typically generated by the `get_paths()` function and should include:
#' \itemize{
#'   \item \strong{MODEL_INPUT}: Path to the directory where model input data will be saved.
#'   \item \strong{DOCS_TABLES}: Path to the directory where day-wise and week-wise generation time tables will be saved.
#' }
#' @param mean_generation_time A numeric value representing the desired mean generation time (in days). This value is used to adjust the shape and rate parameters of the gamma distribution.
#'
#' @importFrom utils write.csv
#' @export

get_generation_time_distribution <- function(PATHS, mean_generation_time) {


     param_df_point <- make_param_df(variable_name = 'g',
                               variable_description = 'The generation time',
                               parameter_distribution = 'point',
                               parameter_name = 'mean',
                               parameter_value = mean_generation_time)

     # Adjust the shape and rate parameters based on the mean_generation_time
     shape <- mean_generation_time / 10  # Shape parameter (k) adjusted based on mean generation time
     rate <- 1 / 10  # Rate parameter (1/scale) is set constant

     # Create the parameter data frame
     param_df_stoch <- make_param_df(variable_name = 'g',
                               variable_description = 'The generation time',
                               parameter_distribution = 'gamma',
                               parameter_name = c('shape', 'rate'),
                               parameter_value = c(shape, rate))

     param_df <- rbind(param_df_point, param_df_stoch)

     # Save the parameter data frame
     param_path <- file.path(PATHS$MODEL_INPUT, "param_g_generation_time.csv")
     utils::write.csv(param_df, param_path, row.names = FALSE)
     message(paste("Parameter data frame for the generation time distribution g() saved to:", param_path))

     # Generate the gamma distribution for x = 1 to 56 days (8 weeks)
     x <- 1:(7*8)
     y <- dgamma(x, shape = shape, rate = rate)

     # Create a data frame for day-wise generation time
     df <- data.frame(x = x, y = y)

     # Aggregate days into 7-day weeks
     week_bins <- cut(x, breaks = seq(0, max(x), by = 7), include.lowest = TRUE)
     week_aggregated <- aggregate(y, by = list(week_bins), FUN = sum)

     # Rename columns and normalize probabilities for week-wise generation time
     colnames(week_aggregated) <- c("Interval", "Total_Probability")
     week_aggregated$Week <- 1:nrow(week_aggregated)
     total_sum <- sum(week_aggregated$Total_Probability)
     week_aggregated$Probability <- week_aggregated$Total_Probability / total_sum
     week_aggregated <- week_aggregated[,-which(colnames(week_aggregated) == 'Total_Probability')]

     # Save the day-wise and week-wise generation time data
     day_file <- file.path(PATHS$MODEL_INPUT, "pred_generation_time_days.csv")
     week_file <- file.path(PATHS$MODEL_INPUT, "pred_generation_time_weeks.csv")
     utils::write.csv(df, day_file, row.names = FALSE)
     utils::write.csv(week_aggregated, week_file, row.names = FALSE)
     message("Generation time distribution saved to:", PATHS$MODEL_INPUT)

     # Also save the data to DOCS_TABLES
     utils::write.csv(df, file = file.path(PATHS$DOCS_TABLES, "generation_time_days.csv"), row.names = FALSE)
     utils::write.csv(week_aggregated, file = file.path(PATHS$DOCS_TABLES, "generation_time_weeks.csv"), row.names = FALSE)
     message("Generation time distribution also saved to:", PATHS$DOCS_TABLES)

}


#' Two-clock moment-matched generation-interval pmf (in memory)
#'
#' Internal helper returning the daily generation-INTERVAL probability mass
#' function as a normalized numeric vector. The interval is the
#' infection-to-infection generation time \eqn{\mathcal{G} = \text{latent} +
#' \text{infectious}}, approximated by a moment-matched \eqn{\mathrm{Gamma}(s, r)}
#' whose first two moments are derived from the engine timing parameters
#' \code{iota}, \code{gamma_1}, \code{gamma_2}, \code{sigma} (canonical theory:
#' \code{MOSAIC-docs/04-model-description.Rmd}, eqs. gamma-eff /
#' generation-time-moments / infectious-period-variance / gamma-shape-rate).
#'
#' Moments (two clocks: latent + infectious):
#' \itemize{
#'   \item \eqn{\gamma_{\mathrm{eff}} = [\sigma/\gamma_1 + (1-\sigma)/\gamma_2]^{-1}}
#'         (reciprocal of the \eqn{\sigma}-weighted mean infectious *duration*).
#'   \item \eqn{E[\mathcal{G}] = 1/\iota + 1/\gamma_{\mathrm{eff}}}.
#'   \item \eqn{V_{\mathrm{inf}} = \sigma/\gamma_1^2 + (1-\sigma)/\gamma_2^2 +
#'         \sigma(1-\sigma)(1/\gamma_1 - 1/\gamma_2)^2} (the over-dispersed
#'         \eqn{\sigma}-mixture variance; NOT \eqn{1/\gamma_{\mathrm{eff}}^2}).
#'   \item \eqn{V[\mathcal{G}] = 1/\iota^2 + V_{\mathrm{inf}}}.
#'   \item shape \eqn{s = E^2/V}, rate \eqn{r = E/V}.
#' }
#'
#' The continuous \eqn{\mathrm{Gamma}(s, r)} is discretized onto daily bins with
#' the canonical \strong{mean-preserving} (Cori et al. 2013 / Cauchemez)
#' discretization used by EpiEstim's \code{discr_si}, NOT a naive Gamma-CDF
#' difference. A plain CDF difference \eqn{F(d) - F(d-1)} over \eqn{[d-1, d]}
#' assigns each unit interval's mass to its right endpoint \eqn{d}, which shifts
#' the discretized mean to \eqn{\approx \mathbb{E}[\mathcal{G}] + 0.5} and inflates
#' the renewal \eqn{R} in the growth phase (a ~3-10\% upward bias, worsening for
#' low-shape / heavily right-skewed kernels). The mean-preserving form instead
#' places mass so that \eqn{\sum_d d\,g(d) = \mathbb{E}[\mathcal{G}]} (the target
#' mean, not \eqn{+0.5}), with \eqn{g} at lag 0 forced to 0 (Cori convention).
#' Concretely, on integer support \eqn{d = 0, 1, \ldots} (using
#' \eqn{a = ((\mu-1)/\varsigma)^2}, \eqn{b = \varsigma^2/(\mu-1)},
#' \eqn{\mu = \mathbb{E}[\mathcal{G}]}, \eqn{\varsigma = \sqrt{\mathbb{V}[\mathcal{G}]}},
#' \eqn{F_a = } CDF of \eqn{\mathrm{Gamma}(a, \mathrm{scale}=b)}):
#' \deqn{w(d) = d\,F_a(d) + (d-2)\,F_a(d-2) - 2(d-1)\,F_a(d-1)
#'   + ab\,[\,2 F_{a+1}(d-1) - F_{a+1}(d-2) - F_{a+1}(d)\,].}
#' The mass is then truncated to \eqn{d = 1 \ldots \texttt{max\_days}} and
#' renormalized so it sums to 1. This is the kernel \eqn{g(\Delta t)} consumed by
#' the Cori renewal estimator in \code{\link{calc_Reff}}. It is deliberately
#' separate from the legacy fixed \eqn{\mathrm{Gamma}(0.5, 0.1)} CSV path of
#' \code{get_generation_time_distribution()} (left fully intact).
#'
#' @param iota Numeric scalar > 0. Latent-period rate (\eqn{1/\iota} = mean latent days).
#' @param gamma_1 Numeric scalar > 0. Symptomatic recovery rate.
#' @param gamma_2 Numeric scalar > 0. Asymptomatic recovery rate.
#' @param sigma Numeric scalar in the unit interval. Symptomatic proportion of new infections.
#' @param max_days Integer. Daily truncation horizon (kernel length). Default 56.
#'
#' @return A numeric vector of length \code{max_days} that sums to 1; element
#'   \code{g[d]} is the probability the generation interval falls in day \code{d}.
#'   Carries attributes \code{shape}, \code{rate}, \code{mean} (\eqn{E[\mathcal{G}]}),
#'   and \code{var} (\eqn{V[\mathcal{G}]}) for provenance/testing.
#'
#' @keywords internal
#' @noRd
.mosaic_generation_time_pmf <- function(iota, gamma_1, gamma_2, sigma,
                                        max_days = 56L) {
  stopifnot(
    is.numeric(iota), length(iota) == 1L, is.finite(iota), iota > 0,
    is.numeric(gamma_1), length(gamma_1) == 1L, is.finite(gamma_1), gamma_1 > 0,
    is.numeric(gamma_2), length(gamma_2) == 1L, is.finite(gamma_2), gamma_2 > 0,
    is.numeric(sigma), length(sigma) == 1L, is.finite(sigma),
    sigma >= 0, sigma <= 1
  )
  max_days <- as.integer(max_days)
  if (length(max_days) != 1L || is.na(max_days) || max_days < 1L)
    stop(".mosaic_generation_time_pmf: max_days must be a positive integer scalar")

  # Effective removal rate = reciprocal of the sigma-weighted mean DURATION
  # (NOT a harmonic mean of the rates). doc eq:gamma-eff.
  mean_inf_dur <- sigma / gamma_1 + (1 - sigma) / gamma_2
  gamma_eff    <- 1 / mean_inf_dur

  # First two moments of G = latent + infectious (two independent clocks).
  E_G <- 1 / iota + 1 / gamma_eff

  # Over-dispersed sigma-mixture infectious-period variance. doc
  # eq:infectious-period-variance -- the third (between-class) term is what
  # 1/gamma_eff^2 omits.
  V_inf <- sigma / gamma_1^2 + (1 - sigma) / gamma_2^2 +
    sigma * (1 - sigma) * (1 / gamma_1 - 1 / gamma_2)^2
  V_G   <- 1 / iota^2 + V_inf

  # Moment-matched Gamma(shape s, rate r) of the TARGET generation interval.
  # doc eq:gamma-shape-rate. Kept as provenance attributes below.
  s <- E_G^2 / V_G
  r <- E_G / V_G

  # Mean-preserving daily discretization (Cori et al. 2013 / Cauchemez; the form
  # used by EpiEstim::discr_si), NOT a naive CDF difference. A plain F(d)-F(d-1)
  # over [d-1, d] shifts the discretized mean to ~E[G]+0.5 day and inflates the
  # renewal R in growth; this form places mass so the discretized mean equals
  # E[G] exactly, with g at lag 0 forced to 0 (Cori convention).
  #
  # Requires mu = E[G] > 1; cholera generation intervals (~5 days) satisfy this,
  # but guard explicitly so a degenerate parameter set fails loudly.
  sd_G <- sqrt(V_G)
  if (!is.finite(E_G) || E_G <= 1 || !is.finite(sd_G) || sd_G <= 0)
    stop(".mosaic_generation_time_pmf: mean-preserving discretization requires ",
         "E[G] > 1 and SD[G] > 0 (got E[G]=", signif(E_G, 4), ", SD[G]=",
         signif(sd_G, 4), "); check iota/gamma_1/gamma_2/sigma")

  a <- ((E_G - 1) / sd_G)^2
  b <- sd_G^2 / (E_G - 1)
  cdf <- function(k, shape) stats::pgamma(k, shape = shape, scale = b)

  # Evaluate the discretization over integer support d = 0 .. max_days; w(0) = 0
  # by construction, and d = 1..max_days are the daily masses.
  d   <- 0:max_days
  w   <- d * cdf(d, a) + (d - 2) * cdf(d - 2, a) - 2 * (d - 1) * cdf(d - 1, a) +
    a * b * (2 * cdf(d - 1, a + 1) - cdf(d - 2, a + 1) - cdf(d, a + 1))
  w   <- pmax(0, w)
  # Drop lag 0 (forced to 0) and keep d = 1..max_days.
  pmf <- w[-1L]

  total <- sum(pmf)
  if (!is.finite(total) || total <= 0)
    stop(".mosaic_generation_time_pmf: degenerate kernel (mass <= 0); check ",
         "iota/gamma_1/gamma_2/sigma")
  g <- pmf / total

  attr(g, "shape") <- s
  attr(g, "rate")  <- r
  attr(g, "mean")  <- E_G
  attr(g, "var")   <- V_G
  g
}
