#' Get Mean Elevation Data for Multiple Countries Using Shapefiles
#'
#' This function retrieves elevation data for a specified number of points within the boundary of each country's shapefile from the `iso_codes_mosaic` list using the Open-Meteo API. It returns the mean elevation for each country.
#'
#' @param PATHS A list containing the paths to where the elevation data should be saved. Typically generated by the `get_paths()` function and should include:
#' \itemize{
#'   \item \strong{DATA_SHAPEFILES}: Path to the directory containing country shapefiles.
#'   \item \strong{DATA_ELEVATION}: Path to the directory where the elevation data will be saved.
#' }
#' @param n_points An integer specifying the number of points to generate within each country's boundary.
#' @param api_key A character string representing the API key for the Open-Meteo API.

#'
#' @return A data frame with the mean elevation for each country in `iso_codes_mosaic`.
#'
#' @details The function loads the shapefiles for all countries in `iso_codes_mosaic` from the specified directory, generates `n_points` random points within each country's boundary, and queries the Open-Meteo API for the elevation data at each point. It returns the mean elevation for each country and saves the data as a CSV file.
#'
#' @examples
#' \dontrun{
#' # Example usage to get mean elevation data for all countries in iso_codes_mosaic
#' n_points <- 10
#' api_key <- "your_api_key_here"
#' PATHS <- get_paths()
#' mean_elevations <- get_elevation(n_points, api_key, PATHS)
#' print(mean_elevations)
#'}
#' @importFrom httr GET content status_code
#' @importFrom jsonlite fromJSON
#' @importFrom utils download.file write.csv
#' @importFrom sf st_read st_sample st_coordinates
#' @export

get_elevation <- function(PATHS, n_points, api_key = NULL) {

     requireNamespace('sf')
     requireNamespace('utils')

     # Load the list of ISO3 country codes for the MOSAIC model
     iso_codes <- MOSAIC::iso_codes_mosaic

     # Ensure the elevation directory exists
     if (!dir.exists(PATHS$DATA_ELEVATION)) dir.create(PATHS$DATA_ELEVATION, recursive = TRUE)

     results_list <- list()

     # Initialize a progress bar
     pb <- utils::txtProgressBar(min = 0, max = length(iso_codes), style = 3)

     # Loop through each country's ISO3 code in iso_codes_mosaic
     for (idx in seq_along(iso_codes)) {

          iso_code <- iso_codes[idx]

          # Construct the path to the shapefile for each country
          shapefile_path <- file.path(PATHS$DATA_SHAPEFILES, paste0(iso_code, "_ADM0.shp"))

          # Check if the shapefile exists
          if (!file.exists(shapefile_path)) {
               message(paste("Shapefile for", iso_code, "not found. Skipping."))
               next
          }

          # Load the country shapefile
          country_shapefile <- sf::st_read(shapefile_path, quiet = TRUE)

          # Generate n_points random points within the country's shapefile boundary
          random_points <- sf::st_sample(country_shapefile, size = n_points, type = "random")
          coords <- sf::st_coordinates(random_points)

          # Loop through each generated point to get elevation
          for (i in seq_len(nrow(coords))) {
               lat <- coords[i, "Y"]
               lon <- coords[i, "X"]

               # Construct the API request URL for each location
               url <- paste0(
                    "https://customer-api.open-meteo.com/v1/elevation?",
                    "latitude=", lat,
                    "&longitude=", lon,
                    "&apikey=", api_key
               )

               # Create a temporary file to save the data
               temp_file <- tempfile(fileext = ".json")

               # Download the file using download.file with mode = "wb"
               utils::download.file(url, temp_file, mode = "wb", quiet = TRUE)

               # Load the downloaded JSON file into a data frame
               data <- jsonlite::fromJSON(temp_file)

               # Append the result for this location to the results list
               results_list[[length(results_list) + 1]] <- data.frame(
                    country = iso_code,
                    latitude = lat,
                    longitude = lon,
                    elevation = data$elevation
               )
          }

          # Update progress bar
          utils::setTxtProgressBar(pb, idx)
     }

     # Close the progress bar
     close(pb)

     # Combine all results into a single data frame
     out <- do.call(rbind, results_list)

     # Calculate the mean elevation for each country
     median_elevations <- aggregate(elevation ~ country, data = out, FUN = median, na.rm = TRUE)

     # Define the file path to save the elevation data
     file_path <- file.path(PATHS$DATA_ELEVATION, "mean_elevation_data.csv")

     # Save the data to a CSV file
     utils::write.csv(out, file = file_path, row.names = FALSE)

     message(paste("Elevation data saved to:", file_path))

     # Return the mean elevations as a data frame
     return(median_elevations)

}
