#' Download, Process, and Save WASH Coverage Data
#'
#' This function processes WASH (Water, Sanitation, and Hygiene) coverage data for African countries from Sikder et al. (2023). The data includes indicators of water and sanitation access, including piped water, improved sanitation, unimproved water sources, and open defecation. The processed data is saved as a CSV file in the specified path.
#'
#' @param PATHS A list containing the paths to where WASH data should be saved. Typically generated by the `get_paths()` function and should include:
#' \itemize{
#'   \item \strong{DATA_WASH}: Path to the directory where the processed WASH data will be saved.
#' }
#'
#' @return The function does not return a value but processes the WASH coverage data and saves it to the specified directory as a CSV file.
#'
#' @details
#' The WASH coverage data is based on percentages of the population with access to piped water, other improved water sources, septic or sewer sanitation, and other improved sanitation. The data also includes the proportions of the population using unimproved water sources, surface water, unimproved sanitation, and practicing open defecation.
#'
#' The risk-related variables (unimproved water, surface water, unimproved sanitation, and open defecation) are converted to a complement (1 - value) to reflect protective factors. All data are scaled between 0 and 1.
#'
#' Data Source: Sikder et al. (2023). Water, Sanitation, and Hygiene Coverage and Cholera Incidence in Sub-Saharan Africa. \doi{10.1021/acs.est.3c01317}.
#'
#' @importFrom reshape2 melt
#' @importFrom dplyr mutate
#' @importFrom gtools smartbind
#' @importFrom countrycode countrycode
#'
#' @examples
#' \dontrun{
#' # Define paths for saving WASH data
#' PATHS <- get_paths()
#'
#' # Download, process, and save WASH coverage data
#' get_WASH_data(PATHS)
#' }
#'
#' @export

get_WASH_data <- function(PATHS) {

     requireNamespace('reshape2')
     requireNamespace('dplyr')
     requireNamespace('gtools')
     requireNamespace('countrycode')

     if (!dir.exists(PATHS$DATA_WASH)) dir.create(PATHS$DATA_WASH, recursive = TRUE)

     ################################################################################
     # Make dataframe from Sikder et al 2023 data
     ################################################################################

     chunk1 <- data.frame(
          Country = c("Angola", "Burundi", "Benin", "Burkina Faso", "Central African Republic", "Cote dIvoire",
                      "Cameroon", "Democratic Republic of Congo", "Congo", "Ethiopia", "Gabon", "Ghana", "Guinea",
                      "Gambia", "Guinea-Bissau", "Equatorial Guinea", "Kenya", "Liberia", "Madagascar", "Mali",
                      "Mozambique", "Mauritania", "Malawi", "Namibia", "Niger"),
          Piped_Water = c(32.0, 36.4, 39.1, 18.0, 12.1, 42.6, 35.7, 21.2, 27.1, 37.5, 61.9, 28.3, 23.9,
                          63.0, 23.8, 39.0, 31.5, 2.9, 23.9, 32.6, 39.9, 48.1, 21.3, 73.2, 39.6),
          Other_Improved_Water = c(26.6, 46.4, 33.2, 58.4, 46.4, 35.2, 34.6, 22.3, 34.2, 23.2, 20.7, 54.9, 49.8,
                                   23.4, 34.7, 30.8, 28.5, 69.8, 19.1, 34.4, 12.5, 31.0, 62.1, 8.5, 28.0),
          Septic_or_Sewer_Sanitation = c(32.6, 5.0, 3.6, 1.3, 0.4, 15.8, 9.7, 3.9, 4.8, 1.9, 20.9, 13.3, 9.5,
                                         7.3, 7.0, 8.3, 6.2, 9.8, 3.2, 4.1, 1.3, 7.1, 1.5, 35.9, 4.7),
          Other_Improved_Sanitation = c(9.5, 47.6, 23.9, 29.6, 32.3, 29.2, 44.6, 35.9, 26.2, 17.2, 16.0, 48.3, 32.3,
                                        56.2, 46.0, 33.8, 41.5, 22.8, 8.6, 37.8, 24.2, 38.4, 40.9, 7.6, 18.4),
          Unimproved_Water = c(11.5, 11.4, 21.6, 21.7, 37.6, 14.3, 20.7, 45.3, 21.3, 23.4, 1.8, 4.7, 13.0,
                               13.4, 41.1, 16.3, 13.4, 7.5, 32.7, 29.1, 33.0, 20.4, 12.6, 10.5, 31.4),
          Surface_Water = c(29.9, 5.8, 6.1, 1.9, 4.0, 7.8, 9.0, 11.2, 17.4, 16.0, 15.6, 12.1, 13.3,
                            0.2, 0.4, 13.8, 26.6, 19.8, 24.3, 3.9, 14.6, 0.5, 4.1, 7.7, 1.0),
          Unimproved_Sanitation = c(28.4, 43.1, 7.7, 3.3, 39.1, 17.2, 37.2, 43.9, 50.3, 40.6, 49.3, 7.6, 38.6,
                                    12.3, 20.8, 50.9, 33.4, 12.5, 36.8, 44.1, 35.1, 11.6, 47.7, 3.4, 14.1),
          Open_Defecation = c(29.5, 4.3, 64.8, 65.8, 28.2, 37.7, 8.5, 16.3, 18.8, 40.3, 13.8, 30.9, 19.6,
                              24.1, 26.1, 7.0, 18.9, 54.9, 51.4, 14.0, 39.4, 42.9, 9.9, 53.1, 62.8),
          Incidence_per_1000 = c(0.09904, 0.24680, 0.04665, 0.00358, 0.02886, 0.01891, 0.50913, 0.36399,
                                 0.20317, 0.06755, 0.00033, 0.40156, 0.20086, 0.00612, 0.39827, 0.00100,
                                 0.17645, 0.11201, 0.00895, 0.03260, 0.12538, 0.01136, 0.03755, 0.17558, 0.06494)
     )

     chunk2 <- data.frame(
          Country = c("Nigeria", "Rwanda", "Sudan", "Senegal", "Sierra Leone", "Somalia", "South Sudan",
                      "Swaziland", "Chad", "Togo", "Tanzania", "Uganda", "South Africa", "Zambia", "Zimbabwe"),
          Piped_Water = c(11.1, 33.9, 28.3, 56.8, 16.1, 32.3, 3.2, 54.3, 18.9, 27.6, 38.2, 18.0, 87.6, 28.4, 32.9),
          Other_Improved_Water = c(53.1, 39.8, 44.7, 12.3, 40.3, 52.8, 30.9, 16.9, 36.3, 33.9, 20.4, 57.8, 3.9, 28.9, 42.6),
          Septic_or_Sewer_Sanitation = c(15.8, 0.6, 0.1, 15.8, 4.8, 7.6, 0.7, 16.2, 1.6, 10.4, 4.9, 0.2, 55.4, 3.7, 32.3),
          Other_Improved_Sanitation = c(27.1, 84.1, 20.3, 53.7, 42.7, 27.5, 12.1, 62.3, 13.5, 20.3, 29.1, 78.7, 19.8, 32.2, 29.4),
          Unimproved_Water = c(19.4, 15.1, 21.5, 30.5, 19.4, 5.3, 48.7, 10.1, 37.5, 18.9, 25.0, 13.6, 2.3, 27.4, 14.6),
          Surface_Water = c(16.4, 11.2, 5.6, 0.4, 24.2, 9.6, 17.2, 18.7, 7.2, 19.7, 16.4, 10.6, 6.2, 15.4, 9.9),
          Unimproved_Sanitation = c(22.0, 13.4, 27.0, 6.9, 28.0, 7.8, 18.9, 8.7, 15.4, 9.2, 49.0, 10.2, 20.8, 43.6, 6.9),
          Open_Defecation = c(35.2, 1.9, 52.7, 23.6, 24.5, 57.1, 68.4, 12.8, 69.5, 60.1, 17.0, 10.9, 4.0, 20.6, 31.4),
          Incidence_per_1000 = c(0.10247, 0.01835, 0.00598, 0.00072, 1.89451, 1.27452, 0.61066, 0.00065,
                                 0.86626, 0.01796, 0.18485, 0.03673, 0.00103, 0.11792, 0.03265)
     )

     wash_data <- rbind(chunk1, chunk2)

     wash_data$iso_code <- convert_country_to_iso(wash_data$Country)
     wash_data$Country <- convert_iso_to_country(wash_data$iso_code)

     path <- file.path(PATHS$DATA_WASH, "WASH_data_Sikder_2023.csv")
     write.csv(wash_data, file=path, row.names = FALSE)
     message(paste0("WASH data from Sikder et al 2023 saved here: ", path))

}
