#' Get Mean or Median Elevation from Downloaded DEM Data Using Country Boundaries
#'
#' This function calculates the mean or median elevation for a given set of ISO3 country codes by loading the downloaded DEM files and extracting raster values within the country's boundary.
#'
#' @param iso_codes A character vector of ISO3 country codes for which the elevation data will be calculated.
#' @param PATHS A list containing paths where DEM data is stored. Typically generated by the `get_paths()` function and should include:
#' \itemize{
#'   \item \strong{DATA_DEM}: Path to the directory where DEM rasters are saved (GeoTIFF format).
#'   \item \strong{DATA_SHAPEFILES}: Path to the directory where shapefiles are saved.
#' }
#' @param method A character string specifying the method to use for calculating elevation statistics. Can be `"mean"` or `"median"` (default is `"median"`).
#'
#' @return A data frame with ISO3 codes, country names, and the calculated mean or median elevation for each country.
#'
#' @importFrom exactextractr exact_extract
#' @importFrom raster raster
#' @importFrom sf st_read
#' @importFrom dplyr bind_rows
#' @importFrom utils write.csv
#' @importFrom glue glue
#' @examples
#' \dontrun{
#' # Define the ISO3 country codes
#' iso_codes <- c("ZAF", "KEN", "NGA")
#'
#' # Get paths for data storage
#' PATHS <- get_paths()
#'
#' # Calculate mean elevation for the countries
#' mean_elevations <- get_elevation(iso_codes, PATHS, method = "mean")
#' print(mean_elevations)
#' }
#' @export

get_elevation <- function(PATHS, iso_codes, method = "median") {

     # Ensure the method is either "mean" or "median"
     if (!method %in% c("mean", "median")) {
          stop("Invalid method. Choose 'mean' or 'median'.")
     }

     # Initialize an empty list to store results
     results_list <- list()

     # Loop through each ISO3 country code
     for (i in 1:length(iso_codes)) {

          iso_code <- iso_codes[i]

          message(glue::glue("Calculating {method} elevation for {iso_code}..."))

          # Load the shapefile for the country
          shapefile_path <- file.path(PATHS$DATA_SHAPEFILES, paste0(iso_code, "_ADM0.shp"))

          if (!file.exists(shapefile_path)) {
               message(glue::glue("Shapefile for {iso_code} not found. Skipping."))
               next
          }

          country_shapefile <- sf::st_read(shapefile_path, quiet = TRUE)

          # Load the DEM raster
          dem_filename <- file.path(PATHS$DATA_DEM, glue::glue("{iso_code}_1km_DEM.tif"))

          if (!file.exists(dem_filename)) {
               message(glue::glue("DEM file for {iso_code} not found. Skipping."))
               next
          }

          dem_raster <- raster::raster(dem_filename)

          # Use exactextractr::exact_extract() for faster extraction within the country boundary
          extracted_values <- exactextractr::exact_extract(dem_raster, country_shapefile)[[1]]

          if (method == 'mean') {
               extracted_stat <- mean(extracted_values$value, na.rm=TRUE)
          } else {
               extracted_stat <- median(extracted_values$value, na.rm=TRUE)
          }

          # Check if any values were extracted
          if (is.null(extracted_values) || length(extracted_values) == 0) {
               message(glue::glue("No elevation data available for {iso_code}. Skipping."))
               next
          }

          # Get the country name
          country_name <- convert_iso_to_country(iso_code)

          # Store the result
          result_df <- data.frame(
               country = country_name,
               iso_code = iso_code,
               elevation = extracted_stat
          )

          results_list <- c(results_list, list(result_df))
     }

     # Combine results into a single data frame
     results_df <- dplyr::bind_rows(results_list)

     # Define the output file path
     file_path <- file.path(PATHS$DATA_ELEVATION, glue::glue("country_elevation_{method}.csv"))

     # Save the results as a CSV file
     utils::write.csv(results_df, file = file_path, row.names = FALSE)
     message(glue::glue("Elevation data saved to: {file_path}"))

}
