#' Plot ENSO and DMI Data
#'
#' This function creates a facet plot to visualize ENSO and DMI data over time, with separate panels for each variable (DMI, ENSO3, ENSO34, ENSO4). A horizontal line at zero is included to indicate the neutral value, and a vertical line marks the current date, with the date displayed vertically on the left side of the line.
#'
#' @param compiled_data A data frame containing ENSO and DMI data, with columns for `date`, `variable`, and `value`. This data is typically generated by the `compile_ENSO_data` function.
#'
#' @return A ggplot facet plot showing the time series of DMI, ENSO3, ENSO34, and ENSO4 over time. The plot includes:
#' \itemize{
#'   \item A horizontal solid line at zero to indicate the neutral sea surface temperature anomaly.
#'   \item A vertical dashed line to indicate the current date, with the current date displayed as vertical text.
#'   \item Facets for each variable, allowing for easy comparison of DMI and ENSO regions.
#' }
#'
#' @details This function uses `ggplot2` to create a line plot with facets for each variable (DMI, ENSO3, ENSO34, and ENSO4). It adds a horizontal reference line at zero and a vertical line representing the current date. The current date is displayed as vertical text aligned to the left of the vertical line. The data is expected to be in a `date`, `variable`, and `value` format.
#'
#' @examples
#' \dontrun{
#' # Compile the ENSO and DMI data from the year 2000 onwards
#' compiled_enso_data <- compile_ENSO_data(2010, "daily")
#'
#' # Plot the data
#' plot_ENSO_data(compiled_enso_data)
#'}
#' @export

plot_ENSO_data <- function(compiled_data) {

     requireNamespace('ggplot2')

     # Get the current date for the vertical line
     current_date <- Sys.Date()

     # Create the plot using ggplot2
     plot <- ggplot(compiled_data, aes(x = date, y = value, color = variable)) +
          geom_hline(yintercept = 0, linetype = "solid", color = "black") +  # Horizontal line at y=0
          geom_line(linewidth = 1) +  # Plot lines for each variable
          geom_vline(xintercept = as.numeric(current_date), linetype = "dashed", color = "black") +  # Vertical line for current date
          annotate("text", x = as.Date(current_date), y = Inf, label = as.character(current_date),
                   angle = 90, hjust = 1.2, vjust = -0.5, size = 3, color = "black") +  # Vertical date label aligned to the left
          #facet_wrap(~ variable, scales = "free_y", ncol = 1) +  # Facet by variable
          labs(title = "Time series of ENSO and DMI",
               x = "",
               y = "Value (Sea Surface Temperature Anomaly)") +
          theme_minimal() +  # Use a minimal theme
          theme(legend.position = "right",
                legend.title = element_blank())  # Remove legend since facets are labeled

     # Display the plot
     print(plot)
}
