#' Plot Mobility Data, Mobility Network, and Results
#'
#' This function loads and visualizes the mobility data, including the flight data, travel probabilities, diffusion model estimates, and mobility network.
#'
#' @param PATHS A list containing paths where data, models, and figures are stored. Typically generated by the `get_paths()` function and should include:
#' \itemize{
#'   \item \strong{MODEL_INPUT}: Path to the directory where the mobility matrices and parameter estimates are saved.
#'   \item \strong{DATA_SHAPEFILES}: Path to the directory containing shapefiles for African countries.
#'   \item \strong{DOCS_FIGURES}: Path to the directory where figures will be saved.
#' }
#'
#' @return The function generates and saves mobility-related visualizations as PNG files.
#'
#' @importFrom ggplot2 ggplot aes geom_tile geom_bar geom_errorbar geom_line geom_segment geom_sf geom_point geom_text scale_fill_gradient scale_color_manual xlab ylab theme_bw element_text margin guides guide_colorbar theme scale_fill_viridis_c
#' @importFrom reshape2 melt
#' @importFrom cowplot plot_grid
#' @importFrom sf st_read
#' @importFrom dplyr left_join
#' @export

plot_mobility <- function(PATHS) {

     requireNamespace('ggplot2')
     requireNamespace('reshape2')
     requireNamespace('dplyr')
     requireNamespace('sf')
     requireNamespace('cowplot')

     message("Loading mobility data...")

     data_flights <- utils::read.csv(file.path(PATHS$DATA_OAG, "oag_mosaic_2017_mean_weekly.csv"), stringsAsFactors = FALSE)
     data_flights <- data_flights[data_flights$origin_iso3 %in% MOSAIC::iso_codes_mosaic,]

     # Load the mobility matrices (M, D, N) and parameter estimates
     M <- utils::read.csv(file.path(PATHS$MODEL_INPUT, "data_mobility_matrix_M.csv"))
     D <- utils::read.csv(file.path(PATHS$MODEL_INPUT, "data_mobility_matrix_D.csv"))
     N <- utils::read.csv(file.path(PATHS$MODEL_INPUT, "data_mobility_matrix_N.csv"))
     tau <- utils::read.csv(file.path(PATHS$MODEL_INPUT, "pred_tau_departure.csv"))
     pi <- utils::read.csv(file.path(PATHS$MODEL_INPUT, "pred_pi_diffusion.csv"))



     africa <- sf::st_read(dsn = file.path(PATHS$DATA_SHAPEFILES, "AFRICA_ADM0.shp"), quiet = TRUE)

     centroids <- sf::st_centroid(africa)
     data_centroids <- data.frame(
          iso3 = centroids$iso_a3,
          lon = sf::st_coordinates(centroids)[, 1],
          lat = sf::st_coordinates(centroids)[, 2]
     )

     data_centroids <- data_centroids[data_centroids$iso3 %in% unique(c(M$origin, M$destination)),]

     # Order the countries from south to north based on latitude
     iso3_ordered_south_north <- data_centroids$iso3[order(data_centroids$lat, decreasing = FALSE)]



     #--------------------------------------------------------------------------
     # Plot the mobility matrix (M) - observed flights
     #--------------------------------------------------------------------------

     message("Plotting flight data (mobility matrix M)...")
     p1 <- ggplot2::ggplot(data = reshape2::melt(M)) +
          ggplot2::geom_tile(ggplot2::aes(x = factor(destination, levels = iso3_ordered_south_north),
                                          y = factor(origin, levels = iso3_ordered_south_north),
                                          fill = log(value + 1))) +
          ggplot2::xlab('Destination') +
          ggplot2::ylab("Origin") +
          ggplot2::theme_bw() +
          ggplot2::theme(axis.text.x = ggplot2::element_text(size = 10, angle = 90, vjust = 0.5),
                         axis.text.y = ggplot2::element_text(size = 10),
                         axis.title.x = ggplot2::element_text(size = 12, margin = ggplot2::margin(t = 15)),
                         axis.title.y = ggplot2::element_text(size = 12, margin = ggplot2::margin(r = 15)),
                         legend.position = 'bottom') +
          ggplot2::scale_fill_gradient(low = "black", high = "skyblue",
                                       guide = ggplot2::guide_colorbar(title = 'Observed trips (log-scale)',
                                                                       title.position = 'top',
                                                                       label.theme = ggplot2::element_text(size = 9),
                                                                       barwidth = 20,
                                                                       barheight = 0.5,
                                                                       frame.colour = 'black',
                                                                       ticks = TRUE))

     print(p1)

     png(filename = file.path(PATHS$DOCS_FIGURES, "mobility_flight_data.png"), width = 9, height = 9, units = "in", res = 300)
     print(p1)
     dev.off()






     #--------------------------------------------------------------------------
     # Mobility network plot
     #--------------------------------------------------------------------------
     message("Plotting mobility network...")

     min_trips <- 30

     # Sort data_flights by count in ascending order so that larger edges are plotted last (on top)
     data_flights_sorted <- data_flights[data_flights$count > min_trips, ]
     data_flights_sorted <- data_flights_sorted[order(data_flights_sorted$count), ]

     p2 <-
          ggplot() +
          geom_sf(data = africa, fill = "#E0E0E0", color = "black") +  # Light gray for country map
          geom_segment(data = data_flights_sorted,
                       aes(x = origin_lon,
                           y = origin_lat,
                           xend = destination_lon,
                           yend = destination_lat,
                           color = log(count + 1))) +  # Combine size and color in legend
          scale_color_viridis_c(
               option = "B",   # Viridis color palette option A
               direction = -1, # Reverse the color direction for better contrast
               breaks = c(log(100), log(1000), log(10000), log(100000)),  # Set breaks in log units
               labels = c("100", "1,000", "10,000", "100,000"),  # Non-log labels
               guide = guide_colorbar(
                    title = "Trip Count",    # Legend title
                    title.position = "top",  # Move the title above the color bar
                    barwidth = 20,           # Make the legend longer
                    barheight = 0.6,         # Make the legend narrower
                    ticks = TRUE,            # Show ticks on the legend
                    frame.colour = "black",  # Add a border around the colorbar
                    ticks.colour = "black"
               )
          ) +
          theme_void() +  # Remove axes and background
          theme(
               legend.position = "bottom",               # Move the legend to the bottom
               legend.text = element_text(size = 10),    # Adjust text size for readability
               legend.title = element_text(size = 12),   # Adjust legend title size
               legend.key.width = unit(3, "cm")          # Make the colorbar longer
          )

     # Extract the legend
     legend <- MOSAIC::get_ggplot_legend(p2)

     # Create the final plot with line size mapping included
     p2 <- p2 + geom_segment(data = data_flights_sorted,
                             aes(x = origin_lon,
                                 y = origin_lat,
                                 xend = destination_lon,
                                 yend = destination_lat,
                                 linewidth = log(count + 1),
                                 color = log(count + 1))) +
          geom_point(data = data_centroids, aes(x = lon, y = lat), color = "black", fill = 'white', shape=21, size = 2.5) +
          geom_text_repel(data = data_centroids, aes(x = lon, y = lat, label = iso3), size = 3.25, vjust = -1) +  # Repel the labels
          scale_size_continuous(range = c(0.001, 2.5)) +
          theme(legend.position = 'none')

     # Combine the plot and the extracted legend
     combined_plot <- gridExtra::grid.arrange(
          grobs = list(p2, legend),
          ncol = 1,
          heights = c(0.9, 0.1)  # Relative heights for plot and legend
     )

     print(combined_plot)


     # Save the combined plot as PNG
     png(filename = file.path(PATHS$DOCS_FIGURES, "mobility_network.png"), width = 9, height = 9, units = "in", res = 300)
     grid::grid.draw(combined_plot)
     dev.off()



     #--------------------------------------------------------------------------
     # Plot travel probability (tau_j)
     #--------------------------------------------------------------------------

     message("Plotting travel probability (tau_j)...")

     # Plot travel probability

     main_plot <- ggplot(df_travel_prob, aes(x = mean, y = reorder(country, mean))) +
          geom_vline(xintercept = mean(df_travel_prob$mean), linetype=2, color='red') +
          geom_point(size=2.5, shape=21, fill="black") +  # Black circles for the mean
          geom_errorbarh(aes(xmin = ci_lo, xmax = ci_hi), height = 0, linewidth=0.75) +  # Error bars for CI
          xlab("Mean weekly probability of travel") +
          ylab(NULL) +
          theme_minimal() +
          theme(axis.text.x = element_text(size=10),
                axis.text.y = element_text(size=10),
                axis.title.x = element_text(size=12, margin = margin(t = 15)),
                axis.title.y = element_text(size=12, margin = margin(r = 15)),
                plot.margin = margin(20, 5, 5, 0))  # Remove margin on the right

     # Create the horizontal barplot for mean * population
     bar_plot <- ggplot(df_travel_prob, aes(x = mean * population, y = reorder(country, mean))) +
          geom_bar(stat="identity", fill="dodgerblue") +
          scale_x_sqrt(breaks=c(1000, 10000, 25000)) +
          theme_minimal() +
          xlab("Estimated total\nweekly travelers") +
          theme(axis.title.x = element_text(size=12, margin = margin(t = 15)),
                axis.title.y = element_blank(),
                axis.text.x = element_text(size=10),
                axis.text.y = element_blank(),
                axis.ticks.y = element_blank(),
                panel.grid.minor.x = element_blank(),
                plot.margin = margin(20, 5, 5, 5))  # Remove left margin

     p3 <- plot_grid(main_plot, bar_plot, rel_widths = c(2, 1), align = 'h', axis = 'tb', labels=c("A", "B"))
     print(p3)

     png(filename = file.path(PATHS$DOCS_FIGURES, "mobility_travel_prob_tau.png"), width = 7, height = 9, units = "in", res = 300)
     print(p3)
     dev.off()



     #--------------------------------------------------------------------------
     # Plot diffusion model (pi_ij) - probability of travel between destinations
     #--------------------------------------------------------------------------

     message("Plotting diffusion matrix (pi_ij)...")


     # Plot diffusion

     iso3_ordered_south_north <- data_centroids$iso3[order(data_centroids$lat, decreasing = FALSE)]

     p4 <-
          ggplot(data=melt(pi)) +
          geom_tile(aes(x=factor(destination, levels = iso3_ordered_south_north),
                        y=factor(origin, levels = iso3_ordered_south_north),
                        fill=value)) +
          xlab('Destination') + ylab("Origin") +
          theme_bw() + theme(axis.text.x=element_text(size=10, angle=90, vjust=0.5),
                             axis.text.y=element_text(size=10),
                             axis.title.x=element_text(size=12, margin = margin(t = 15)),
                             axis.title.y=element_text(size=12, margin = margin(r = 15)),
                             legend.position='bottom') +
          viridis::scale_fill_viridis(option="G",
                                      direction=1) +
          guides(fill=guide_colorbar(title='Probability of travel given departure from origin',
                                     title.position='top',
                                     label.theme=element_text(size=9),
                                     barwidth=20,
                                     barheight=0.5,
                                     frame.colour='black',
                                     ticks=TRUE))

     print(p4)

     png(filename = file.path(PATHS$DOCS_FIGURES, "mobility_diffusion_pi.png"), width = 9, height = 9, units = "in", res = 300)
     print(p4)
     dev.off()

     message(glue("Writing plots to: {PATHS$DOCS_FIGURES}"))

}
