#' Plot Vaccine Effectiveness and Beta Distribution
#'
#' This function generates two plots: one showing the vaccine effectiveness decay over time, and another showing the Beta distribution for the initial vaccine effectiveness.
#'
#' @param PATHS A list containing the paths where the figures will be saved. Typically generated by the `get_paths()` function and should include:
#' \itemize{
#'   \item \strong{DOCS_FIGURES}: Path to the directory where the figures will be saved.
#' }
#'
#' @export

plot_vaccine_effectiveness <- function(PATHS) {

     # Load vaccine effectiveness data and parameters
     df <- read.csv(file.path(PATHS$DATA_VACCINE_EFFECTIVENESS, "vaccine_effectiveness_data.csv"))
     param_df <- read.csv(file.path(PATHS$MODEL_INPUT, "param_vaccine_effectiveness.csv"))
     prediction <- read.csv(file.path(PATHS$MODEL_INPUT, "pred_vaccine_effectiveness.csv"))

     p1 <-
          ggplot() +
          geom_ribbon(data = prediction, aes(x = day, ymin = predicted_lo, ymax = predicted_hi), fill = "grey", alpha = 0.3) +  # Shaded ribbon for confidence intervals
          geom_line(data = prediction, aes(x = day, y = predicted), color = "black", size = 1.25) +  # Line for predicted values
          geom_hline(aes(yintercept = fitted_parameters[1]), linetype = "solid", linewidth=0.5, color = "grey30") +  # Horizontal line at mean effectiveness
          geom_hline(aes(yintercept = fitted_parameters_lo[1]), linetype = "dashed", linewidth=0.25, color = "grey40") +  # Horizontal line at mean effectiveness
          geom_hline(aes(yintercept = fitted_parameters_hi[1]), linetype = "dashed", linewidth=0.25, color = "grey40") +  # Horizontal line at mean effectiveness
          geom_point(data = df, aes(x = day, y = effectiveness, color = source), size = 5) +  # Points for original data
          geom_segment(data = df, aes(x = day_min, xend = day_max, y = effectiveness, color = source), size = 1.25) +  # Vertical error bars
          geom_segment(data = df, aes(x = day, y = effectiveness_lo, yend = effectiveness_hi, color = source), size = 1.25) +  # Horizontal error bars
          annotate("text", x = 365 * 8.25, y = 0.45, label = bquote(omega == .(sprintf("%.5f", fitted_parameters['b']))), color = "black", size = 5) +
          labs(x = "Years after vaccination", y = "Effectiveness of One Dose OCV") +
          ggtitle('A') +
          theme_classic(base_size = 18) +
          theme(panel.grid.minor = element_blank(),  # Remove minor gridlines
                panel.grid.major.y = element_blank(),
                axis.title.x = element_text(margin = margin(t = 15)),  # Increase space between x-axis and x-axis label
                axis.title.y = element_text(margin = margin(r = 15)),
                plot.margin = unit(c(0.1, 0.3, 0.1, 0), "inches"),
                legend.position = c(0.99, 0.975),  # Place legend inside the plot (top-right corner)
                legend.justification = c("right", "top"),  # Align the legend to the right-top
                legend.title = element_blank(),  # Remove the legend title
                legend.text = element_text(size = 10),
                legend.background = element_blank()) +  # Make the legend text smaller
          scale_y_continuous(limits = c(0, 1), expand = c(0, 0)) +
          scale_x_continuous(limits = c(0, 10*365), labels = 1:10, breaks = 365 * (1:10), expand = c(0, 0)) +  # Yearly labels and breaks
          scale_color_manual(values = c('Azman et al (2016)' = '#DC143C',
                                        'Qadri et al (2016)' = '#9370DB',
                                        'Qadri et al (2018)' = '#FF8C00',
                                        'Malembaka et al (2024)' = '#32CD32'))  # Manually set colors for each source



     df_samples <- data.frame(x = samps)

     p2 <-
          ggplot(df_samples, aes(x = x)) +
          geom_histogram(aes(y = after_stat(density)), bins = 35, fill = "lightblue", color='white', alpha = 0.7) +
          stat_function(fun = dbeta, args = list(shape1 = prm$shape1, shape2 = prm$shape2), color = "black", size = 0.8) +
          geom_vline(aes(xintercept = fitted_parameters[1]), linetype = "solid", linewidth=0.5, color = "grey30") +  # Horizontal line at mean effectiveness
          geom_vline(aes(xintercept = fitted_parameters_lo[1]), linetype = "dashed", linewidth=0.25, color = "grey40") +  # Horizontal line at mean effectiveness
          geom_vline(aes(xintercept = fitted_parameters_hi[1]), linetype = "dashed", linewidth=0.25, color = "grey40") +  # Horizontal line at mean effectiveness
          labs(x = expression("Initial one dose OCV effectiveness (" * phi * ")"), y = "Density") +
          theme_classic(base_size = 18) +
          ggtitle('B') +
          theme(panel.grid.minor = element_blank(),  # Remove minor gridlines
                panel.grid.major.y = element_blank(),
                #axis.title.y = element_blank(),  # Increase space between x-axis and x-axis label
                axis.title.x = element_text(margin = margin(t = 15)),
                axis.ticks = element_line(),
                #axis.text.y = element_blank(),
                plot.margin = unit(c(0.1, 0, 0.1, 0.1), "inches")) +
          scale_x_continuous(limits = c(0, 1), expand = c(0, 0)) +
          scale_y_continuous(breaks = 0:5, expand = c(0, 0.01)) +
          coord_flip()


     combo <- cowplot::plot_grid(p1, p2, nrow=1, rel_widths = c(3,1.1), align = "vh", axis='tb')
     print(combo)
     # Save plot
     plot_path <- file.path(PATHS$DOCS_FIGURES, "vaccine_effectiveness.png")
     ggplot2::ggsave(plot_path, plot = combo, width = 10, height = 5, dpi = 300)
     message(paste("Plot saved to:", plot_path))

}
