#' Plot Seasonal Transmission Example with Grid Points
#'
#' This function plots the map of a selected country with grid points used for climate data sampling, and visualizes the seasonal transmission dynamics using Fourier series for both precipitation and cholera cases.
#'
#' @param PATHS A list containing paths where processed climate, cholera, and fitted data are stored. Typically generated by the `get_paths()` function and should include:
#' \itemize{
#'   \item \strong{DATA_SHAPEFILES}: Path to the directory containing shapefiles for African countries.
#'   \item \strong{DOCS_TABLES}: Path to load the processed precipitation and fitted values data.
#'   \item \strong{DOCS_FIGURES}: Path to save the output plot.
#' }
#' @param country_iso_code A character string representing the ISO3 code of the country to plot.
#' @param n_points An integer specifying the number of grid points to generate within the country for sampling.
#'
#' @return The function generates and saves a PNG file showing the grid points on the country map and the seasonal transmission dynamics.
#'
#' @importFrom ggplot2 ggplot aes geom_sf geom_point geom_line geom_text labs scale_color_manual scale_x_discrete scale_y_continuous theme_minimal theme element_text element_blank
#' @importFrom cowplot plot_grid get_legend
#' @importFrom dplyr filter
#' @importFrom glue glue
#' @importFrom sf st_read st_coordinates
#' @importFrom utils read.csv
#' @export

plot_seasonal_transmission_example <- function(PATHS, country_iso_code, n_points = 30) {

     # Load the country shapefile
     country_name <- MOSAIC::convert_iso_to_country(country_iso_code)
     country_shp <- sf::st_read(dsn = file.path(PATHS$DATA_SHAPEFILES, paste0(country_iso_code, "_ADM0.shp")), quiet = TRUE)

     # Generate grid points within the country
     grid_points <- MOSAIC::generate_country_grid_n(country_shp, n_points = n_points)
     coords <- sf::st_coordinates(grid_points)
     coords <- as.data.frame(coords)
     colnames(coords) <- c("Longitude", "Latitude")

     # Create the plot for grid points on the country map
     p1 <- ggplot() +
          geom_sf(data = country_shp, fill = "#fef6e1") +
          geom_sf(data = grid_points, color = "black", size = 1.5) +
          labs(title = glue("Grid of sampling points\nin {country_name}"),
               subtitle = "",
               x = NULL, y = NULL) +
          theme_minimal() +
          theme(plot.title = element_text(hjust = 0.5),
                plot.margin = margin(3, 3, 3, 3))

     # Load processed precipitation and fitted values data
     combined_precip_data <- utils::read.csv(file.path(PATHS$DOCS_TABLES, "data_seasonal_precipitation.csv"), stringsAsFactors = FALSE)
     combined_fitted_values <- utils::read.csv(file.path(PATHS$DOCS_TABLES, "pred_seasonal_dynamics.csv"), stringsAsFactors = FALSE)

     # Filter the data for the selected country
     tmp_precip <- combined_precip_data[combined_precip_data$iso_code == country_iso_code,]
     tmp_fit <- combined_fitted_values[combined_fitted_values$iso_code == country_iso_code,]

     # Create the seasonal transmission plot
     p2 <- ggplot(tmp_precip, aes(x = factor(week))) +
          geom_hline(yintercept = 0, color = "black") +
          geom_point(aes(y = precip_scaled, color = "Precipitation (1994-2024)"), size = 3, alpha = 0.05) +
          geom_point(aes(x = week, y = cases_scaled, color = "Cholera Cases (2023-2024)"), size = 2.25) +
          geom_line(data = tmp_fit, aes(x = week, y = fitted_values_fourier_precip, color = "Fourier Series (Precip)"), linewidth = 2.5) +
          geom_line(data = tmp_fit,
                    aes(x = week, y = fitted_values_fourier_cases, color = "Fourier Series (Cases)"), linewidth = 2.5) +
          geom_line(data = tmp_fit,
                    aes(x = week, y = fitted_values_fourier_cases, color = "Fourier Series (Cases)"), linewidth = 2.5) +
          geom_text(data = tmp_fit %>% filter(!is.na(inferred_from_neighbor)),
                    aes(x = 15, y = Inf, label = glue("Inferred from:\n{inferred_from_neighbor}")),
                    vjust = 1.2, hjust = 0.5, size = 2.5, color = "#DC143C") +
          scale_x_discrete(breaks = c(1, 10, 20, 30, 40, 52)) +
          scale_y_continuous(limits = c(min(c(tmp_fit$fitted_values_fourier_precip, tmp_fit$fitted_values_fourier_cases)), 8)) +
          scale_color_manual(values = c(
               "Precipitation (1994-2024)" = "black",
               "Cholera Cases (2023-2024)" = "#FFA500",
               "Fourier Series (Precip)" = "#004CFF",
               "Fourier Series (Cases)" = "#DC143C"
          )) +
          labs(title = "Scaled Precipitation and\nCholera Cases (Z-Score)", x = "Week of Year", y = "Z-Score") +
          theme_minimal() +
          theme(plot.title = element_text(hjust = 0.5),
                axis.title.x = element_text(size = 14, margin = margin(t = 20)),
                axis.title.y = element_text(size = 14, margin = margin(r = 20)),
                axis.text = element_text(size = 12),
                legend.text = element_text(size = 12),
                legend.title = element_blank(),
                legend.position = "right",
                legend.box = "vertical",
                legend.box.just = "left",
                panel.grid.major.x = element_blank(),
                panel.grid.major.y = element_line(color = "grey90", linewidth = 0.25),
                panel.grid.minor = element_blank(),
                plot.margin = margin(3, 3, 3, 3)) +
          guides(color = guide_legend(nrow = 2, byrow = T))

     # Remove the legend from p2 and extract it separately
     p2_no_legend <- p2 + theme(legend.position = "none")
     legend_p2 <- MOSAIC::get_ggplot_legend(p2)

     # Combine the two plots (p1 and p2) in a two-panel layout
     combined_plot <- cowplot::plot_grid(p1, p2_no_legend, ncol = 2, rel_widths = c(1.2, 2), align = 'h', labels = c("A", "B"))

     # Place the legend below the combined plot
     final_plot <- cowplot::plot_grid(combined_plot, legend_p2, ncol = 1, rel_heights = c(1, 0.2))

     print(final_plot)

     # Save the plot as a PNG file
     png_filename <- file.path(PATHS$DOCS_FIGURES, glue::glue("seasonal_transmission_example_{country_iso_code}.png"))
     png(filename = png_filename, width = 8, height = 5.5, units = "in", res = 300)
     print(final_plot)
     dev.off()

     message(glue::glue("Seasonal transmission example plot saved to {png_filename}."))

}
