#' Plot Africa Map with Cholera Outbreak Countries
#'
#' This function creates a map of Africa highlighting countries in Sub-Saharan Africa and those with cholera outbreaks in the past 5 and 10 years. The map is saved as a PNG file in the specified `PATHS$DOCS_FIGURES` directory.
#'
#' @param PATHS A list containing the paths where the figure will be saved. Typically generated by the `get_paths()` function and should include:
#' \itemize{
#'   \item \strong{DOCS_FIGURES}: Path to the directory where the map image will be saved.
#' }
#'
#' @return A ggplot object showing the map.
#'
#' @details The function generates a map of Africa, highlighting Sub-Saharan African countries and those with cholera outbreaks in the past 5 and 10 years. The map is saved as a PNG file.
#'
#' @importFrom ggplot2 ggplot geom_sf aes scale_fill_manual theme_minimal element_text unit
#' @importFrom rnaturalearth ne_countries
#' @importFrom sf st_read
#' @importFrom dplyr filter
#' @importFrom stringr str_wrap
#' @importFrom grDevices png dev.off
#'
#' @examples
#' \dontrun{
#' # Assuming PATHS is generated from get_paths()
#' PATHS <- get_paths()
#' plot_africa_map(PATHS)
#' }
#'
#' @export
plot_africa_map <- function(PATHS) {

     # List of countries with cholera outbreaks in the past 10 years
     cholera_outbreak_countries_10yrs <- c(
          "Nigeria", "Democratic Republic of the Congo", "Somalia", "Kenya",
          "Ethiopia", "Mozambique", "Zambia", "South Sudan", "Malawi",
          "Uganda", "Zimbabwe", "Tanzania", "Cameroon", "Niger", "Burundi",
          "Angola", "Chad", "Ghana", "Sierra Leone", "Sudan", "Madagascar"
     )

     # List of countries with cholera outbreaks in the past 5 years
     cholera_outbreak_countries_5yrs <- c(
          "Nigeria", "Democratic Republic of the Congo", "Somalia", "Kenya",
          "Ethiopia", "Mozambique", "Zambia", "South Sudan", "Malawi",
          "Uganda", "Zimbabwe", "Tanzania", "Cameroon", "Niger", "Burundi"
     )

     # Define color palette
     pal <- c("#fef6e1", "#c5d8b6", "#4f8362")

     # Load African country shapefiles
     africa <- rnaturalearth::ne_countries(scale = "medium", continent = "Africa", returnclass = "sf")

     # Filter for Sub-Saharan Africa and cholera outbreak countries
     SSA <- africa[africa$region_wb == "Sub-Saharan Africa",]
     SSA_outbreak_5yr <- africa[africa$name_long %in% cholera_outbreak_countries_5yrs,]
     SSA_outbreak_10yr <- africa[africa$name_long %in% cholera_outbreak_countries_10yrs,]

     # Create the map plot
     p <- ggplot2::ggplot(data = africa) +
          ggplot2::geom_sf(fill = "white", color = "black") +
          ggplot2::geom_sf(data = SSA, aes(fill = "SSA"), color = "black") +
          ggplot2::geom_sf(data = SSA_outbreak_10yr, aes(fill = "SSA_outbreak_10yr"), color = "black", linetype = "solid", size = 0.8) +
          ggplot2::geom_sf(data = SSA_outbreak_5yr, aes(fill = "SSA_outbreak_5yr"), color = "black", linetype = "solid", size = 0.8) +
          ggplot2::scale_fill_manual(values = pal,
                                     labels = c( "Sub-Saharan Africa",
                                                 stringr::str_wrap("Cholera outbreak in past 10 years", 18),
                                                 stringr::str_wrap("Cholera outbreak in past 5 years", 18))) +
          ggplot2::theme_minimal(base_size = 13) +
          ggplot2::theme(
               panel.grid.major = ggplot2::element_line(size = 0.25),
               legend.position = "right",
               legend.title = ggplot2::element_blank(),
               legend.text = ggplot2::element_text(size = 10.5),
               legend.key.height = ggplot2::unit(1.25, "cm"),
               legend.key.width = ggplot2::unit(0.75, "cm"),
               plot.margin = ggplot2::unit(c(0.25, 0.25, 0.25, 0.25), "inches")
          )

     # Define the output file path for the map
     output_file <- file.path(PATHS$DOCS_FIGURES, "africa_map.png")

     # Save the map as a PNG file
     grDevices::png(filename = output_file, width = 2000, height = 1600, units = "px", res = 300)
     print(p)
     grDevices::dev.off()

     message(paste("Map saved to:", output_file))

     return(p)
}
