#' Plot Vaccine Effectiveness Decay and Prior Distributions
#'
#' This function generates comprehensive plots showing vaccine effectiveness decay over time and
#' prior distributions for both one-dose and two-dose OCV regimens. It creates three sets of figures:
#' one for one-dose OCV, one for two-dose OCV, and a combined figure showing both regimens.
#'
#' @param PATHS A list containing the paths where the figures will be saved. Typically generated by the `get_paths()` function and should include:
#' \itemize{
#'   \item \strong{MODEL_INPUT}: Path to the directory containing the vaccine effectiveness data and parameters
#'   \item \strong{DOCS_FIGURES}: Path to the directory where the figures will be saved
#' }
#'
#' @details The function creates the following plots:
#' \itemize{
#'   \item \strong{One-dose OCV (A-C)}: Decay curve, phi_1 prior distribution, omega_1 prior distribution (blue theme)
#'   \item \strong{Two-dose OCV (D-F)}: Decay curve, phi_2 prior distribution, omega_2 prior distribution (green theme)
#' }
#'
#' Three PDF files are saved:
#' \itemize{
#'   \item \code{vaccine_one_dose_combined.pdf}: One-dose vaccine effectiveness plots
#'   \item \code{vaccine_two_dose_combined.pdf}: Two-dose vaccine effectiveness plots
#'   \item \code{vaccine_all_combined.pdf}: Both regimens combined in a single figure
#' }
#'
#' @export

plot_vaccine_effectiveness <- function(PATHS) {

     # Load vaccine effectiveness data and parameters
     df_data <- read.csv(file.path(PATHS$MODEL_INPUT, "data_vaccine_effectiveness.csv"))
     df_param <- read.csv(file.path(PATHS$MODEL_INPUT, "param_vaccine_effectiveness.csv"))
     df_prediction <- read.csv(file.path(PATHS$MODEL_INPUT, "pred_vaccine_effectiveness.csv"))

     # Define colors
     color_one_dose <- "#0066cc"  # Bright Blue - professional, good contrast
     color_two_dose <- "#00966e"  # Emerald Green - complementary, distinguishable

     # Filter data by dose regimen
     one_dose_data <- df_data[df_data$dose_regimen == "One-dose OCV", ]
     one_dose_pred <- df_prediction[df_prediction$dose_regimen == "One-dose OCV", ]
     two_dose_data <- df_data[df_data$dose_regimen == "Two-dose OCV", ]
     two_dose_pred <- df_prediction[df_prediction$dose_regimen == "Two-dose OCV", ]

     # Helper function for extracting parameters
     get_param <- function(var_name, param_name) {
          df_param[df_param$variable_name == var_name & df_param$parameter_name == param_name, "parameter_value"]
     }

     # Extract one-dose parameters
     phi_1_mean <- get_param("phi_1", "mean")
     phi_1_low <- get_param("phi_1", "low")
     phi_1_high <- get_param("phi_1", "high")
     omega_1_mean <- get_param("omega_1", "mean")
     omega_1_low <- get_param("omega_1", "low")
     omega_1_high <- get_param("omega_1", "high")
     omega_1_shape <- get_param("omega_1", "shape")
     omega_1_rate <- get_param("omega_1", "rate")
     phi_1_shape1 <- get_param("phi_1", "shape1")
     phi_1_shape2 <- get_param("phi_1", "shape2")

     # Extract two-dose parameters
     phi_2_mean <- get_param("phi_2", "mean")
     phi_2_low <- get_param("phi_2", "low")
     phi_2_high <- get_param("phi_2", "high")
     omega_2_mean <- get_param("omega_2", "mean")
     omega_2_low <- get_param("omega_2", "low")
     omega_2_high <- get_param("omega_2", "high")
     omega_2_shape <- get_param("omega_2", "shape")
     omega_2_rate <- get_param("omega_2", "rate")
     phi_2_shape1 <- get_param("phi_2", "shape1")
     phi_2_shape2 <- get_param("phi_2", "shape2")

     # Helper for labels
     as_label <- function(e) paste(deparse(e), collapse = "")

     # ========== ONE-DOSE PLOTS ==========
     # Plot A: One-dose decay curve
     p_decay_1 <- ggplot() +
          geom_ribbon(data = one_dose_pred, aes(x = day, ymin = predicted_lo, ymax = predicted_hi),
                      fill = color_one_dose, alpha = 0.1) +
          geom_line(data = one_dose_pred, aes(x = day, y = predicted),
                    color = "black", size = 1.2) +
          geom_line(data = one_dose_pred, aes(x = day, y = predicted_lo),
                    color = color_one_dose, size = 1, linetype = 2) +
          geom_line(data = one_dose_pred, aes(x = day, y = predicted_hi),
                    color = color_one_dose, size = 0.9, linetype = 2) +
          geom_errorbar(data = one_dose_data, aes(x = days, ymin = effectiveness_lo, ymax = effectiveness_hi, color = source),
                        width = 0, alpha = 0.75, size = 0.8, show.legend = FALSE) +
          geom_point(data = one_dose_data, aes(x = days, y = effectiveness, color = source),
                     shape = 21, fill = "black", size = 4.5) +
          scale_color_manual(
               values = c("Xu et al (2024)" = "black"),
               labels = c("Xu et al (2024)" = expression(italic("Xu et al. (2024)")))
          ) +
          guides(color = guide_legend(override.aes = list(shape = 21, fill = "black", size = 4))) +
          annotate("text", x = 365 * 8.05, y = 0.875,
                   label = as_label(bquote(bold(phi[1]) == .(sprintf("%.3f", phi_1_mean)))),
                   parse = TRUE, color = "black", size = 4, hjust = 0) +
          annotate("text", x = 365 * 8.05, y = 0.825,
                   label = as_label(bquote(bold(omega[1]) == .(sprintf("%.5f", omega_1_mean)))),
                   parse = TRUE, color = "black", size = 4, hjust = 0) +
          labs(x = "Years after first-dose OCV", y = "One-dose OCV effectiveness", title = "A") +
          theme_classic(base_size = 12) +
          theme(
               plot.title = element_text(face = "bold", size = 12),
               axis.title = element_text(size = 10),
               axis.title.x = element_text(margin = margin(t = 5)),
               axis.title.y = element_text(margin = margin(r = 10)),
               axis.text = element_text(size = 9),
               plot.margin = margin(5, 5, 5, 5, "pt"),
               legend.position = c(0.8, 0.95),
               legend.justification = c(0, 1),
               legend.title = element_blank(),
               legend.text = element_text(size = 9),
               legend.background = element_blank(),
               legend.key = element_blank(),
               legend.key.size = unit(0.8, "lines"),
               legend.margin = margin(0, 0, 0, 0)) +
          scale_y_continuous(limits = c(0, 1), expand = c(0, 0)) +
          scale_x_continuous(limits = c(0, 365 * 10), labels = 1:10, breaks = 365 * (1:10), expand = c(0, 0))

     # Plot B: Phi_1 prior
     x_vals_phi_1 <- seq(0.70, 0.85, length.out = 1000)
     dens_raw_phi_1 <- dbeta(x_vals_phi_1, shape1 = phi_1_shape1, shape2 = phi_1_shape2)
     df_phi_1 <- data.frame(x = x_vals_phi_1, density = dens_raw_phi_1/sum(dens_raw_phi_1))

     p_phi_1 <- ggplot(df_phi_1, aes(x = x, y = density)) +
          geom_area(fill = color_one_dose, alpha = 0.1) +
          geom_line(size = 1.2) +
          geom_vline(xintercept = phi_1_mean, linewidth = 1) +
          geom_vline(xintercept = phi_1_low, color = color_one_dose, linewidth = 0.9, linetype = 2) +
          geom_vline(xintercept = phi_1_high, color = color_one_dose, linewidth = 0.9, linetype = 2) +
          scale_x_continuous(expand = c(0, 0)) +
          scale_y_continuous(expand = c(0, 0)) +
          coord_cartesian(ylim = c(0, max(df_phi_1$density) * 1.05)) +
          theme_classic(base_size = 12) +
          theme(
               plot.title = element_text(face = "bold", size = 12),
               axis.title = element_text(size = 10),
               axis.title.x = element_text(margin = margin(t = 8)),
               axis.text = element_text(size = 8),
               plot.margin = margin(2, 6, 5, 3, "pt")) +
          labs(title = "B", x = expression(phi[1] ~ "(initial effectiveness)"), y = "Density")

     # Plot C: Omega_1 prior
     x_vals_omega_1 <- seq(0, 0.002, length.out = 1000)
     dens_raw_omega_1 <- dgamma(x_vals_omega_1, shape = omega_1_shape, rate = omega_1_rate)
     df_omega_1 <- data.frame(x = x_vals_omega_1, density = dens_raw_omega_1/sum(dens_raw_omega_1))

     p_omega_1 <- ggplot(df_omega_1, aes(x = x, y = density)) +
          geom_area(fill = color_one_dose, alpha = 0.1) +
          geom_line(size = 1.2) +
          geom_vline(xintercept = omega_1_mean, linewidth = 1) +
          geom_vline(xintercept = omega_1_low, color = color_one_dose, linewidth = 0.9, linetype = 2) +
          geom_vline(xintercept = omega_1_high, color = color_one_dose, linewidth = 0.9, linetype = 2) +
          scale_x_continuous(expand = c(0, 0), labels = scales::scientific) +
          scale_y_continuous(expand = c(0, 0)) +
          coord_cartesian(ylim = c(0, max(df_omega_1$density) * 1.05)) +
          theme_classic(base_size = 12) +
          theme(
               plot.title = element_text(face = "bold", size = 12),
               axis.title = element_text(size = 10),
               axis.text = element_text(size = 8),
               axis.text.x = element_text(angle = 45, hjust = 1),
               plot.margin = margin(5, 6, 2, 3, "pt")) +
          labs(title = "C", x = expression(omega[1] ~ "(immune waning per day)"), y = "Density")

     # ========== TWO-DOSE PLOTS ==========
     # Plot D: Two-dose decay curve
     p_decay_2 <- ggplot() +
          geom_ribbon(data = two_dose_pred, aes(x = day, ymin = predicted_lo, ymax = predicted_hi),
                      fill = color_two_dose, alpha = 0.1) +
          geom_line(data = two_dose_pred, aes(x = day, y = predicted),
                    color = "black", size = 1.2) +
          geom_line(data = two_dose_pred, aes(x = day, y = predicted_lo),
                    color = color_two_dose, size = 1, linetype = 2) +
          geom_line(data = two_dose_pred, aes(x = day, y = predicted_hi),
                    color = color_two_dose, size = 0.9, linetype = 2) +
          geom_errorbar(data = two_dose_data, aes(x = days, ymin = effectiveness_lo, ymax = effectiveness_hi, color = source),
                        width = 0, alpha = 0.75, size = 0.8, show.legend = FALSE) +
          geom_point(data = two_dose_data, aes(x = days, y = effectiveness, color = source),
                     shape = 21, fill = "black", size = 4.5) +
          scale_color_manual(
               values = c("Xu et al (2024)" = "black"),
               labels = c("Xu et al (2024)" = expression(italic("Xu et al. (2024)")))
          ) +
          guides(color = guide_legend(override.aes = list(shape = 21, fill = "black", size = 4))) +
          annotate("text", x = 365 * 8.05, y = 0.875,
                   label = as_label(bquote(bold(phi[2]) == .(sprintf("%.3f", phi_2_mean)))),
                   parse = TRUE, color = "black", size = 4, hjust = 0) +
          annotate("text", x = 365 * 8.05, y = 0.825,
                   label = as_label(bquote(bold(omega[2]) == .(sprintf("%.5f", omega_2_mean)))),
                   parse = TRUE, color = "black", size = 4, hjust = 0) +
          labs(x = "Years after two-dose OCV", y = "Two-dose OCV effectiveness", title = "D") +
          theme_classic(base_size = 12) +
          theme(
               plot.title = element_text(face = "bold", size = 12),
               axis.title = element_text(size = 10),
               axis.title.x = element_text(margin = margin(t = 5)),
               axis.title.y = element_text(margin = margin(r = 10)),
               axis.text = element_text(size = 9),
               plot.margin = margin(5, 5, 5, 5, "pt"),
               legend.position = c(0.8, 0.95),
               legend.justification = c(0, 1),
               legend.title = element_blank(),
               legend.text = element_text(size = 9),
               legend.background = element_blank(),
               legend.key = element_blank(),
               legend.key.size = unit(0.8, "lines"),
               legend.margin = margin(0, 0, 0, 0)) +
          scale_y_continuous(limits = c(0, 1), expand = c(0, 0)) +
          scale_x_continuous(limits = c(0, 365 * 10), labels = 1:10, breaks = 365 * (1:10), expand = c(0, 0))

     # Plot E: Phi_2 prior
     x_vals_phi_2 <- seq(0.60, 0.80, length.out = 1000)
     dens_raw_phi_2 <- dbeta(x_vals_phi_2, shape1 = phi_2_shape1, shape2 = phi_2_shape2)
     df_phi_2 <- data.frame(x = x_vals_phi_2, density = dens_raw_phi_2/sum(dens_raw_phi_2))

     p_phi_2 <- ggplot(df_phi_2, aes(x = x, y = density)) +
          geom_area(fill = color_two_dose, alpha = 0.1) +
          geom_line(size = 1.2) +
          geom_vline(xintercept = phi_2_mean, linewidth = 1) +
          geom_vline(xintercept = phi_2_low, color = color_two_dose, linewidth = 0.9, linetype = 2) +
          geom_vline(xintercept = phi_2_high, color = color_two_dose, linewidth = 0.9, linetype = 2) +
          scale_x_continuous(expand = c(0, 0)) +
          scale_y_continuous(expand = c(0, 0)) +
          coord_cartesian(ylim = c(0, max(df_phi_2$density) * 1.05)) +
          theme_classic(base_size = 12) +
          theme(
               plot.title = element_text(face = "bold", size = 12),
               axis.title = element_text(size = 10),
               axis.title.x = element_text(margin = margin(t = 8)),
               axis.text = element_text(size = 8),
               plot.margin = margin(2, 6, 5, 3, "pt")) +
          labs(title = "E", x = expression(phi[2] ~ "(initial effectiveness)"), y = "Density")

     # Plot F: Omega_2 prior
     x_vals_omega_2 <- seq(0, 0.002, length.out = 1000)
     dens_raw_omega_2 <- dgamma(x_vals_omega_2, shape = omega_2_shape, rate = omega_2_rate)
     df_omega_2 <- data.frame(x = x_vals_omega_2, density = dens_raw_omega_2/sum(dens_raw_omega_2))

     p_omega_2 <- ggplot(df_omega_2, aes(x = x, y = density)) +
          geom_area(fill = color_two_dose, alpha = 0.1) +
          geom_line(size = 1.2) +
          geom_vline(xintercept = omega_2_mean, linewidth = 1) +
          geom_vline(xintercept = omega_2_low, color = color_two_dose, linewidth = 0.9, linetype = 2) +
          geom_vline(xintercept = omega_2_high, color = color_two_dose, linewidth = 0.9, linetype = 2) +
          scale_x_continuous(expand = c(0, 0), labels = scales::scientific) +
          scale_y_continuous(expand = c(0, 0)) +
          coord_cartesian(ylim = c(0, max(df_omega_2$density) * 1.05)) +
          theme_classic(base_size = 12) +
          theme(
               plot.title = element_text(face = "bold", size = 12),
               axis.title = element_text(size = 10),
               axis.text = element_text(size = 8),
               axis.text.x = element_text(angle = 45, hjust = 1),
               plot.margin = margin(5, 6, 2, 3, "pt")) +
          labs(title = "F", x = expression(omega[2] ~ "(immune waning per day)"), y = "Density")

     # ========== COMBINE PLOTS ==========
     if (requireNamespace("patchwork", quietly = TRUE)) {
          # One-dose plot
          combined_plot_1 <- p_decay_1 + (p_phi_1 / p_omega_1) + plot_layout(widths = c(3, 2))
          # Two-dose plot
          combined_plot_2 <- p_decay_2 + (p_phi_2 / p_omega_2) + plot_layout(widths = c(3, 2))
          # Combined both
          combined_plot_all <- combined_plot_1 / combined_plot_2
     } else {
          # One-dose plots
          p_priors_1 <- cowplot::plot_grid(p_phi_1, p_omega_1, ncol = 1, align = "v")
          combined_plot_1 <- cowplot::plot_grid(p_decay_1, p_priors_1, ncol = 2, rel_widths = c(3, 2), align = "h")
          # Two-dose plots
          p_priors_2 <- cowplot::plot_grid(p_phi_2, p_omega_2, ncol = 1, align = "v")
          combined_plot_2 <- cowplot::plot_grid(p_decay_2, p_priors_2, ncol = 2, rel_widths = c(3, 2), align = "h")
          # Combined both
          combined_plot_all <- cowplot::plot_grid(combined_plot_1, combined_plot_2, ncol = 1, align = "v")
     }

     # Save figures
     path_one_dose <- file.path(PATHS$DOCS_FIGURES, "vaccine_one_dose_combined.pdf")
     ggsave(path_one_dose, combined_plot_1, width = 12, height = 6, dpi = 300)
     message(paste("One-dose vaccine figure (A, B, C) saved to:", path_one_dose))

     path_two_dose <- file.path(PATHS$DOCS_FIGURES, "vaccine_two_dose_combined.pdf")
     ggsave(path_two_dose, combined_plot_2, width = 12, height = 6, dpi = 300)
     message(paste("Two-dose vaccine figure (D, E, F) saved to:", path_two_dose))

     path_all <- file.path(PATHS$DOCS_FIGURES, "vaccine_all_combined.pdf")
     ggsave(path_all, combined_plot_all, width = 12, height = 9, dpi = 300)
     message(paste("Combined vaccine figure (all panels) saved to:", path_all))
}
