#' Plot Case Fatality Ratios, Total Cases, and Beta Distributions by Country
#'
#' This function creates two separate plots: one for case fatality ratios (CFR) with confidence intervals and total cases by country, and another for Beta distributions for selected countries. The plots are generated based on cholera data stored in the `PATHS$DATA_WHO_ANNUAL` directory.
#'
#' @param PATHS A list containing the paths where the cholera data and figures will be saved. Typically generated by the `get_paths()` function and should include:
#' \itemize{
#'   \item \strong{DATA_WHO_ANNUAL}: Path to the directory where processed WHO annual cholera data is located.
#'   \item \strong{DOCS_FIGURES}: Path to the directory where the plots will be saved.
#' }
#'
#' @details The Beta densities (AFRO Region and the countries with the lowest and
#' highest CFR) are evaluated on an adaptive grid: a uniform grid of 1,000 points
#' over the plotted range plus 500 points across each density's central
#' 99.98% interval, so a very narrow density is resolved (the AFRO Region Beta,
#' built from more than a million cases, has an SD of about 1e-4, ten times
#' narrower than the spacing of a uniform 1,000-point grid from 0 to 1). The x axis
#' runs from 0 to 1.1 times the largest 99.99% quantile of the plotted densities,
#' and the y axis is on a square-root scale so the tall AFRO density and the much
#' wider country densities are visible together. A density with
#' \code{shape1 < 1} (a country with no recorded deaths) is unbounded at 0 and is
#' drawn from the first grid point above 0.
#'
#' @return Invisibly, a list of the two ggplot objects: \code{cfr_and_cases}
#'   (CFR and total cases) and \code{beta_distributions} (Beta densities;
#'   \code{NULL} when no density could be drawn). Each figure drawn is also
#'   saved to \code{PATHS$DOCS_FIGURES}.
#'
#' @importFrom ggplot2 ggplot aes geom_point geom_errorbar geom_bar scale_fill_manual scale_color_manual coord_flip labs theme_minimal scale_y_sqrt element_text margin theme geom_line scale_x_continuous scale_y_continuous
#' @importFrom cowplot plot_grid
#' @importFrom utils read.csv
#' @importFrom dplyr filter group_by do arrange
#' @examples
#' \dontrun{
#' PATHS <- get_paths()
#' plot_CFR_by_country(PATHS)
#' }
#' @export

plot_CFR_by_country <- function(PATHS) {
     # Resolve the CFR artifact by end-year, never by a hardcoded name.
     # process_CFR_data() writes sprintf("case_fatality_ratio_2014_%d.csv", max_year)
     # (R/process_CFR_data.R:120), so the filename moves every time surveillance
     # coverage extends. This function used to read a hardcoded
     # "case_fatality_ratio_2014_2024.csv" while the processor had moved on to
     # ..._2014_2026.csv; both sat on disk and the figure silently rendered the
     # stale one (they differ by up to 4.4 CFR percentage points). Select the
     # highest end-year rather than the newest mtime: the end-year is the
     # artifact's own statement of coverage and does not change if an old file is
     # touched or re-copied.
     cfr_files <- list.files(PATHS$DATA_WHO_ANNUAL,
                             pattern = "^case_fatality_ratio_2014_[0-9]{4}\\.csv$",
                             full.names = TRUE)
     if (!length(cfr_files)) {
          stop("plot_CFR_by_country: no case_fatality_ratio_2014_<year>.csv found in ",
               PATHS$DATA_WHO_ANNUAL, " - run process_CFR_data() first.")
     }
     end_years <- as.integer(sub("^case_fatality_ratio_2014_([0-9]{4})\\.csv$", "\\1",
                                 basename(cfr_files)))
     cfr_file <- cfr_files[which.max(end_years)]
     message("plot_CFR_by_country: reading ", basename(cfr_file))

     # Load cholera data
     cholera_data <- utils::read.csv(cfr_file, stringsAsFactors = FALSE)

     # Ensure AFRO Region is at the top, followed by other countries in alphabetical order
     cholera_data <- cholera_data %>%
          dplyr::arrange(dplyr::desc(country == "AFRO Region"), country)
     cholera_data$country <- factor(cholera_data$country, levels = c("AFRO Region", sort(unique(cholera_data$country[cholera_data$country != "AFRO Region"]))))

     # Get the number of unique countries in the data
     num_countries <- length(unique(cholera_data$country))

     # Define a color palette that can handle an arbitrary number of countries
     pal <- rev(colorRampPalette(RColorBrewer::brewer.pal(9, "Set1"))(num_countries))
     names(pal) <- levels(cholera_data$country)
     pal["AFRO Region"] <- "black"  # Set AFRO Region to black

     # Plot CFR with CIs
     p1 <- ggplot2::ggplot(cholera_data, ggplot2::aes(x = country, y = cfr, color = country)) +
          ggplot2::geom_hline(yintercept = cholera_data$cfr[cholera_data$country == "AFRO Region"], linetype = "solid", color = "black", linewidth = 0.25) +
          ggplot2::geom_point(size = 3.5) +
          ggplot2::geom_errorbar(ggplot2::aes(ymin = cfr_lo, ymax = cfr_hi), width = 0, linewidth = 1) +
          ggplot2::scale_color_manual(values = pal) +  # Use the dynamically generated color palette
          ggplot2::scale_x_discrete(limits=rev) +
          ggplot2::coord_flip() +
          ggplot2::labs(title = "A", y = "Case Fatality Ratio (CFR)") +
          ggplot2::theme_minimal() +
          ggplot2::theme(axis.text.x = ggplot2::element_text(size = 10),
                         axis.title.x = ggplot2::element_text(margin = ggplot2::margin(t = 20)),
                         legend.position = 'none')

     # Plot total cases
     p2 <- ggplot2::ggplot(cholera_data, ggplot2::aes(x = country, y = cases_total, fill = country)) +
          ggplot2::geom_bar(stat = "identity") +
          ggplot2::scale_fill_manual(values = pal) +  # Use the dynamically generated color palette
          ggplot2::scale_y_sqrt() +
          ggplot2::scale_x_discrete(limits=rev) +
          ggplot2::coord_flip() +
          ggplot2::labs(title = "B", y = "Total Cases") +
          ggplot2::theme_minimal() +
          ggplot2::theme(axis.text.x = ggplot2::element_text(size = 10, angle = 45, hjust = 1),
                         legend.position = 'none')

     # Combine the two plots for CFR and total cases
     combined_plot <- cowplot::plot_grid(p1, p2, ncol = 2, align = "h", rel_widths = c(2, 1))

     print(combined_plot)

     # Save the combined CFR and total cases plot
     file_out_combined <- file.path(PATHS$DOCS_FIGURES, "case_fatality_ratio_and_cases_total_by_country.png")
     ggplot2::ggsave(file_out_combined, plot = combined_plot, width = 10, height = 7, dpi = 300)
     message(paste("CFR and total cases plot saved to:", file_out_combined))


     filtered_data <- cholera_data %>%
          dplyr::filter(!is.na(shape1), !is.na(shape2), shape1 > 0, shape2 > 0, country != "AFRO Region")

     # Find the country with the minimum CFR
     cfr_country_min <- as.character(filtered_data$country[which.min(filtered_data$cfr)])

     # Find the country with the maximum CFR
     cfr_country_max <- as.character(filtered_data$country[which.max(filtered_data$cfr)])

     selected_countries <- c("AFRO Region", cfr_country_min, cfr_country_max)  # Customize this list as needed

     # Filter out rows with missing or invalid shape1 and shape2 parameters, then
     # evaluate each density on an adaptive grid (see @details)
     beta_params <- cholera_data %>%
          dplyr::filter(country %in% selected_countries, !is.na(shape1), !is.na(shape2), shape1 > 0, shape2 > 0)
     beta_density <- .cfr_beta_density_grid(beta_params)

     p3 <- NULL
     if (nrow(beta_density) > 0) {
          p3 <- ggplot2::ggplot(beta_density, ggplot2::aes(x = x, y = density, color = country)) +
               ggplot2::geom_line(linewidth = 1.25) +
               ggplot2::geom_line(data=beta_density[beta_density$country == "AFRO Region",], linewidth = 1.25) +
               ggplot2::scale_color_manual(values = pal[selected_countries]) +
               ggplot2::scale_x_continuous(expand = c(0.005, 0.005)) +
               ggplot2::scale_y_sqrt(expand = c(0.005, 0.005)) +
               ggplot2::labs(x = "Case Fatality Ratio (CFR)", y = "Density (square-root scale)") +
               ggplot2::theme_minimal() +
               ggplot2::theme(legend.position = "right", legend.title = ggplot2::element_blank())

          print(p3)

          # Save the Beta distributions plot
          file_out_beta <- file.path(PATHS$DOCS_FIGURES, "case_fatality_ratio_beta_distributions.png")
          ggplot2::ggsave(file_out_beta, plot = p3, width = 10, height = 7, dpi = 300)
          message(paste("Beta distributions plot saved to:", file_out_beta))
     } else {
          message("Beta distributions could not be generated: insufficient data for min and max CFR countries.")
     }

     invisible(list(cfr_and_cases = combined_plot, beta_distributions = p3))
}


# Beta densities for plot_CFR_by_country() on an adaptive grid. `params` has one
# row per curve with columns country, shape1, shape2. Each curve is evaluated on
# a uniform grid of n_base points over [0, x_max], where x_max is 1.1 times the
# largest (1 - tail_p) quantile (capped at 1), plus n_dense points spanning its
# own [tail_p, 1 - tail_p] quantile interval. Dense points that fall outside the
# uniform grid's interior are dropped, so a J-shaped density (shape1 < 1 or
# shape2 < 1, unbounded at an end) starts at the first grid point inside (0, 1)
# instead of climbing towards infinity; non-finite densities are removed.
# Returns a data frame with columns country, x, density.
.cfr_beta_density_grid <- function(params, n_base = 1000L, n_dense = 500L, tail_p = 1e-4) {
     empty <- data.frame(country = character(0), x = numeric(0), density = numeric(0))
     if (is.null(params) || !nrow(params)) return(empty)
     x_max <- min(1, 1.1 * max(stats::qbeta(1 - tail_p, params$shape1, params$shape2)))
     base <- seq(0, x_max, length.out = n_base)
     inner <- base[base > 0 & base < 1]
     out <- lapply(seq_len(nrow(params)), function(i) {
          a <- params$shape1[i]
          b <- params$shape2[i]
          dense <- seq(stats::qbeta(tail_p, a, b), stats::qbeta(1 - tail_p, a, b), length.out = n_dense)
          dense <- dense[dense >= min(inner) & dense <= max(inner)]
          x <- sort(unique(c(base, dense)))
          dens <- stats::dbeta(x, a, b)
          keep <- is.finite(dens)
          data.frame(country = rep(params$country[i], sum(keep)), x = x[keep], density = dens[keep],
                     stringsAsFactors = FALSE)
     })
     do.call(rbind, out)
}
