#' Plot Precipitation and Cholera Case Data with Fourier Series Fits
#'
#' This function visualizes the seasonal precipitation and cholera cases data, fitted with a double Fourier series model. It generates a plot of the Z-scored data for each country, indicating inferred countries where cholera cases data was imputed from neighbors.
#'
#' @param PATHS A list containing paths where processed climate, cholera, and fitted data are stored. Typically generated by the `get_paths()` function and should include:
#' \itemize{
#'   \item \strong{DOCS_FIGURES}: Path to save the output plot.
#' }
#'
#' @return The function generates and saves a PNG file showing the seasonal dynamics of precipitation and cholera cases across multiple countries.
#'
#' @importFrom ggplot2 ggplot aes geom_point geom_line geom_text scale_x_continuous scale_color_manual labs theme_minimal theme element_text element_blank
#' @importFrom dplyr filter
#' @importFrom glue glue
#' @importFrom cowplot get_legend
#' @export

plot_seasonal_transmission <- function(PATHS) {

     # Load the combined precipitation data, fitted values, and clustering results from DOCS_TABLES
     combined_precip_data <- utils::read.csv(file.path(PATHS$DOCS_TABLES, "data_seasonal_precipitation.csv"))
     combined_fitted_values <- utils::read.csv(file.path(PATHS$DOCS_TABLES, "pred_seasonal_dynamics.csv"))

     # Updated plot to include annotation for countries with inferred data and Z-score scaling for precipitation and cases
     p_facet <- ggplot(combined_precip_data, aes(x = factor(week))) +
          geom_hline(yintercept = 0, color = "black") +

          # Plot cholera cases (Z-score)
          geom_point(aes(x = week, y = cases_scaled, color = "Cholera Cases (2023-2024)"), size = 1.5) +

          # Plot fitted values for precipitation and cholera cases
          geom_line(data = combined_fitted_values, aes(x = week, y = fitted_values_fourier_precip, color = "Fourier Series (Precip)"), linewidth = 2) +
          geom_line(data = combined_fitted_values[combined_fitted_values$iso_code %in% iso_codes_with_data, ],
                    aes(x = week, y = fitted_values_fourier_cases, color = "Fourier Series (Cases)"), linewidth = 2) +
          geom_line(data = combined_fitted_values[combined_fitted_values$iso_code %in% iso_codes_no_data, ],
                    aes(x = week, y = fitted_values_fourier_cases, color = "Fourier Series (Cases)"), linewidth = 2) +

          # Annotate inferred countries
          geom_text(data = combined_fitted_values %>% filter(!is.na(inferred_from_neighbor)),
                    aes(x = 15, y = Inf, label = glue("Inferred from:\n{inferred_from_neighbor}")),
                    vjust = 1.2, hjust = 0.5, size = 2.5, color = "#DC143C") +

          scale_x_continuous(breaks = c(1, 10, 20, 30, 40, 52)) +

          # Set color scheme
          scale_color_manual(
               values = c(
                    "Precipitation (1994-2024)" = "black",
                    "Cholera Cases (2023-2024)" = "#FFA500",
                    "Fourier Series (Precip)" = "#004CFF",
                    "Fourier Series (Cases)" = "#DC143C"
               ),
               breaks = c(
                    "Precipitation (1994-2024)",
                    "Cholera Cases (2023-2024)",
                    "Fourier Series (Precip)",
                    "Fourier Series (Cases)"
               )
          ) +

          labs(x = "Week of Year",
               y = "Scaled Precipitation and Cholera Cases (Z-Score)") +

          theme_minimal() +
          theme(
               plot.title = element_text(hjust = 0.5, size = 16, face = "bold"),
               axis.title.x = element_text(size = 14, margin = margin(t = 20)),
               axis.title.y = element_text(size = 14, margin = margin(r = 20)),
               axis.text = element_text(size = 12),
               legend.text = element_text(size = 12),
               legend.title = element_blank(),
               legend.position = "bottom",  # Position the legend at the bottom
               legend.box = "vertical",  # Arrange the legends vertically
               legend.box.just = "left",
               panel.grid.major.x = element_blank(),
               panel.grid.major.y = element_line(color = "grey90", size = 0.25),
               panel.grid.minor = element_blank(),
               strip.text = element_text(size = 11)
          ) +

          # Arrange legends in two columns
          guides(color = guide_legend(nrow = 1, byrow = TRUE)) +

          facet_wrap(~ Country, scales = "free_y", ncol = 4)

     print(p_facet)

     # Save the plot to the figures directory
     png_filename <- file.path(PATHS$DOCS_FIGURES, "seasonal_transmission_all.png")
     png(filename = png_filename, width = 10.5, height = 16, units = "in", res = 300)
     print(p_facet)
     dev.off()

     message(glue::glue("Seasonal transmission plot saved to {png_filename}."))
}
