#' Plot Generation Time as Gamma Distribution for Days and Weeks
#'
#' This function generates a combined plot for the generation time probability distribution over days (based on a gamma distribution) and aggregated over weeks. The resulting plot is saved as a PNG file.
#'
#' @param PATHS A list containing the paths where the plot will be saved. Typically generated by the `get_paths()` function and should include:
#' \itemize{
#'   \item \strong{DOCS_FIGURES}: Path to the directory where the generation time plot will be saved.
#' }
#'
#' @importFrom ggplot2 ggplot aes geom_bar geom_line geom_vline labs theme_minimal element_text margin scale_y_continuous scale_x_continuous
#' @importFrom cowplot plot_grid
#' @importFrom utils read.csv
#' @importFrom grDevices png dev.off
#' @export

plot_generation_time <- function(PATHS) {

     # Load the day-wise and week-wise generation time data
     day_data <- utils::read.csv(file.path(PATHS$DOCS_TABLES, "generation_time_days.csv"), stringsAsFactors = FALSE)
     week_data <- utils::read.csv(file.path(PATHS$DOCS_TABLES, "generation_time_weeks.csv"), stringsAsFactors = FALSE)

     # Set parameters for the gamma distribution (for plotting purposes)
     shape <- 0.5  # Shape parameter (k)
     rate <- 0.1   # Rate parameter (1/scale)
     mean_val <- shape / rate
     lower_bound <- qgamma(0.025, shape = shape, rate = rate)
     upper_bound <- qgamma(0.975, shape = shape, rate = rate)

     # Create the base plot for day-wise gamma distribution
     base_plot <- ggplot2::ggplot(day_data, aes(x = x, y = y)) +
          geom_bar(stat = "identity", aes(y = y), fill = "dodgerblue", color = "white", width = 0.99) +  # Per-day probabilities as bars
          geom_line(color = 'black', size = 1.5) +  # Gamma distribution line
          geom_vline(xintercept = mean_val, linetype = "solid", color = "#E41A1C", size = 1.25) +  # Mean line
          geom_vline(xintercept = upper_bound, linetype = "dashed", color = "#E41A1C", size = 0.75) +  # Upper CI line
          geom_vline(xintercept = lower_bound, linetype = "dashed", color = "#E41A1C", size = 0.75) +  # Lower CI line
          labs(title = 'A', x = 'Day', y = 'Probability') +
          theme_minimal(base_size = 16) +
          theme(axis.title.x = element_text(margin = margin(t = 10)),
                axis.title.y = element_text(margin = margin(r = 10)),
                panel.grid.minor = element_blank(),  # Remove minor gridlines
                panel.grid.major = element_line(color = "grey70", size = 0.1)) +
          scale_y_continuous(expand = c(0.001, 0.001)) +
          scale_x_continuous(breaks = seq(0, max(day_data$x), by = 7), limits = c(0, max(day_data$x)), expand = c(0.001, 0.001))  # Align gridlines with weeks

     # Create a bar plot for the week-wise generation time probabilities
     bar_plot <- ggplot2::ggplot(week_data, aes(x = Week - 0.5, y = Probability)) +
          geom_bar(stat = "identity", fill = "dodgerblue", color = "white", width = 0.95) +
          labs(title = "B", x = 'Week', y = 'Probability') +
          theme_minimal(base_size = 16) +
          theme(axis.title.x = element_text(margin = margin(t = 10)),
                axis.title.y = element_text(margin = margin(r = 10)),
                panel.grid.minor = element_blank(),  # Remove minor gridlines
                panel.grid.major = element_line(color = "grey70", size = 0.1)) +
          scale_y_continuous(expand = c(0.001, 0.001)) +
          scale_x_continuous(breaks = seq(1, max(day_data$x)/7, by = 1), limits = c(0, max(day_data$x)/7), expand = c(0.001, 0.001))  # Adjust breaks to match shifted bars

     # Combine the two plots using cowplot
     combo <- cowplot::plot_grid(base_plot, bar_plot, ncol = 1, align = "v")

     # Save the combined plot as a PNG file
     output_file <- file.path(PATHS$DOCS_FIGURES, "generation_time.png")
     grDevices::png(filename = output_file, width = 2500, height = 2000, units = "px", res = 300)
     print(combo)
     grDevices::dev.off()

     message("Generation time plot saved to:", output_file)
}
