#' Plot Mobility Data, Mobility Network, and Results
#'
#' This function loads and visualizes the mobility data, including the flight data, travel probabilities, diffusion model estimates, and mobility network.
#'
#' @param PATHS A list containing paths where data, models, and figures are stored. Typically generated by the `get_paths()` function and should include:
#' \itemize{
#'   \item \strong{MODEL_INPUT}: Path to the directory where the mobility matrices and parameter estimates are saved.
#'   \item \strong{DATA_SHAPEFILES}: Path to the directory containing shapefiles for African countries.
#'   \item \strong{DOCS_FIGURES}: Path to the directory where figures will be saved.
#' }
#'
#' @return The function generates and saves mobility-related visualizations as PNG files.
#'
#' @importFrom ggplot2 ggplot aes geom_tile geom_bar geom_errorbar geom_line geom_segment geom_sf geom_point geom_text scale_fill_gradient scale_color_manual xlab ylab theme_bw element_text margin guides guide_colorbar theme scale_fill_viridis_c
#' @importFrom reshape2 melt
#' @importFrom cowplot plot_grid
#' @importFrom sf st_read
#' @importFrom dplyr left_join
#' @export

plot_mobility <- function(PATHS) {

     requireNamespace('ggplot2')
     requireNamespace('reshape2')
     requireNamespace('dplyr')
     requireNamespace('sf')
     requireNamespace('cowplot')

     message("Loading mobility data...")

     data_flights <- utils::read.csv(file.path(PATHS$DATA_OAG, "oag_africa_2017_mean_daily.csv"), stringsAsFactors = FALSE)
     data_flights <- data_flights[data_flights$origin_iso3 %in% MOSAIC::iso_codes_mosaic,]
     data_flights <- data_flights[data_flights$destination_iso3 %in% MOSAIC::iso_codes_mosaic,]

     message("Loading the mobility model quantities (M, D, N) and parameter estimates...")
     lonlat <- utils::read.csv(file.path(PATHS$MODEL_INPUT, "mobility_lon_lat.csv"))
     M <- as.matrix(read.csv(file.path(PATHS$MODEL_INPUT, "mobility_M.csv"), header = TRUE, row.names = 1, stringsAsFactors = FALSE))
     D <- as.matrix(read.csv(file.path(PATHS$MODEL_INPUT, "mobility_D.csv"), header = TRUE, row.names = 1, stringsAsFactors = FALSE))
     pi <- as.matrix(read.csv(file.path(PATHS$MODEL_INPUT, "mobility_pi.csv"), header = TRUE, row.names = 1, stringsAsFactors = FALSE))

     N <- utils::read.csv(file.path(PATHS$MODEL_INPUT, "mobility_N.csv"), header = TRUE, row.names = 1, stringsAsFactors = FALSE)
     tmp <- as.vector(N[,1])
     names(tmp) <- row.names(N)
     N <- tmp

     tau <- utils::read.csv(file.path(PATHS$MODEL_INPUT, "mobility_tau.csv"))
     tmp <- as.vector(tau[,1])
     names(tmp) <- row.names(tau)
     tau <- tmp

     tau_df <- read.csv(file.path(PATHS$MODEL_INPUT, "mobility_travel_prob_params.csv"), header = TRUE, row.names = 1, stringsAsFactors = FALSE)
     tau_df <- merge(tau_df, data.frame(iso3 = names(N), population = N), by='iso3')


     # Order the countries from south to north based on latitude
     iso3_ordered <- lonlat$iso3[order(lonlat$lat, lonlat$lat)]


     #--------------------------------------------------------------------------
     # Plot the mobility matrix (M) - observed flights
     #--------------------------------------------------------------------------

     message("Plotting flight data (mobility matrix M)...")

     p1 <- ggplot2::ggplot(
          data = reshape2::melt(M, varnames = c("origin", "destination"), value.name = "value")
     ) +
          ggplot2::geom_tile(
               ggplot2::aes(
                    x = factor(destination, levels = iso3_ordered),
                    y = factor(origin, levels = iso3_ordered),
                    fill = log(value + 1)
               )
          ) +
          ggplot2::xlab('Destination') +
          ggplot2::ylab("Origin") +
          ggplot2::theme_bw() +
          ggplot2::theme(
               axis.text.x = ggplot2::element_text(size = 10, angle = 90, vjust = 0.5),
               axis.text.y = ggplot2::element_text(size = 10),
               axis.title.x = ggplot2::element_text(size = 12, margin = ggplot2::margin(t = 15)),
               axis.title.y = ggplot2::element_text(size = 12, margin = ggplot2::margin(r = 15)),
               legend.position = 'bottom'
          ) +
          ggplot2::scale_fill_gradient(
               low = "black",
               high = "skyblue",
               # Here we set the breaks to the log-transformed values.
               breaks = log(c(0, 10, 100, 1000, 10000) + 1),
               # And we set the labels to the original (non-log) values.
               labels = c("0", "10", "100", "1,000", "10,000"),
               guide = ggplot2::guide_colorbar(
                    title = 'Observed mean daily trips',
                    title.position = 'top',
                    label.theme = ggplot2::element_text(size = 9),
                    barwidth = 20,
                    barheight = 0.5,
                    frame.colour = 'black',
                    ticks = TRUE
               )
          )

     print(p1)

     png(filename = file.path(PATHS$DOCS_FIGURES, "mobility_flight_data.png"), width = 9, height = 9, units = "in", res = 300)
     print(p1)
     dev.off()






     #--------------------------------------------------------------------------
     # Mobility network plot
     #--------------------------------------------------------------------------
     message("Plotting mobility network...")


     # Set a minimum threshold for trips
     min_trips <- 1

     # Melt the M matrix (which has row names for origins and column names for destinations)
     melt_M <- reshape2::melt(M, varnames = c("origin", "destination"), value.name = "count")
     # Filter out flows with counts <= min_trips and sort in ascending order
     melt_M <- melt_M[melt_M$count > min_trips, ]
     melt_M <- melt_M[order(melt_M$count), ]

     # Join the melted M data with the centroids to get geographic coordinates.
     # For origins:
     melt_M <- dplyr::left_join(melt_M, data_centroids, by = c("origin" = "iso3"))
     # Rename the joined lon/lat columns to origin_lon and origin_lat:
     melt_M <- melt_M %>% dplyr::rename(origin_lon = lon, origin_lat = lat)
     # For destinations:
     melt_M <- dplyr::left_join(melt_M, data_centroids, by = c("destination" = "iso3"))
     # Rename the joined lon/lat columns to destination_lon and destination_lat:
     melt_M <- melt_M %>% dplyr::rename(destination_lon = lon, destination_lat = lat)

     # Now build the network plot using the M matrix flows
     p2 <- ggplot2::ggplot() +
          # Base map of Africa
          ggplot2::geom_sf(data = africa, fill = "#E0E0E0", color = "black") +
          # Plot segments based on flows from M; map color to log(count+1)
          ggplot2::geom_segment(data = melt_M,
                                ggplot2::aes(x = origin_lon,
                                             y = origin_lat,
                                             xend = destination_lon,
                                             yend = destination_lat,
                                             color = log(count + 1)),
                                size = 0.8) +
          # Use viridis color palette on the log-transformed counts
          ggplot2::scale_color_viridis_c(
               option = "B",    # Viridis option
               direction = -1,  # Reverse the color direction
               breaks = log(c(0, 10, 100, 1000, 10000) + 1),
               labels = c("0", "10", "100", "1,000", "10,000"),
               guide = ggplot2::guide_colorbar(
                    title = "Observed mean daily trips",
                    title.position = "top",
                    barwidth = 20,
                    barheight = 0.6,
                    ticks = TRUE,
                    frame.colour = "black",
                    ticks.colour = "black"
               )
          ) +
          ggplot2::theme_void() +  # Remove axes and background
          ggplot2::theme(
               legend.position = "bottom",
               legend.text = ggplot2::element_text(size = 10),
               legend.title = ggplot2::element_text(size = 12),
               legend.key.width = grid::unit(3, "cm")
          )

     # Extract legend (using the MOSAIC package function)
     legend <- MOSAIC::get_ggplot_legend(p2)

     # Now add the segments again with line size mapping, and include centroids & country labels.
     p2 <- p2 +
          ggplot2::geom_segment(data = melt_M,
                                ggplot2::aes(x = origin_lon,
                                             y = origin_lat,
                                             xend = destination_lon,
                                             yend = destination_lat,
                                             linewidth = log(count + 1),
                                             color = log(count + 1))) +
          ggplot2::geom_point(data = data_centroids,
                              ggplot2::aes(x = lon, y = lat),
                              color = "black", fill = 'white',
                              shape = 21, size = 2.5) +
          ggrepel::geom_text_repel(data = data_centroids,
                                   ggplot2::aes(x = lon, y = lat, label = iso3),
                                   size = 3.25, vjust = -1) +
          ggplot2::scale_size_continuous(range = c(0.001, 2.5)) +
          ggplot2::theme(legend.position = 'none')

     # Combine the final plot with the extracted legend
     combined_plot <- gridExtra::grid.arrange(
          grobs = list(p2, legend),
          ncol = 1,
          heights = c(0.9, 0.1)  # Adjust relative heights for plot and legend
     )

     print(combined_plot)


     # Save the combined plot as PNG
     png(filename = file.path(PATHS$DOCS_FIGURES, "mobility_network.png"), width = 9, height = 9, units = "in", res = 300)
     grid::grid.draw(combined_plot)
     dev.off()



     #--------------------------------------------------------------------------
     # Plot travel probability (tau_j)
     #--------------------------------------------------------------------------

     message("Plotting travel probability (tau_j)...")

     main_plot <-
          ggplot(tau_df, aes(x = mean, y = reorder(iso3, mean))) +
          geom_vline(xintercept = mean(tau_df$mean), linetype=2, color='red') +
          geom_point(size=2.5, shape=21, fill="black") +  # Black circles for the mean
          geom_errorbarh(aes(xmin = Q2.5, xmax = Q97.5), height = 0, linewidth=0.75) +  # Error bars for CI
          xlab("Mean daily probability of travel") +
          ylab(NULL) +
          theme_minimal() +
          theme(axis.text.x = element_text(size=10),
                axis.text.y = element_text(size=10),
                axis.title.x = element_text(size=12, margin = margin(t = 15)),
                axis.title.y = element_text(size=12, margin = margin(r = 15)),
                plot.margin = margin(20, 5, 5, 0))  # Remove margin on the right

     # Create the horizontal barplot for mean * population
     bar_plot <- ggplot(tau_df, aes(x = mean * population, y = reorder(iso3, mean))) +
          geom_bar(stat="identity", fill="dodgerblue") +
          scale_x_sqrt(breaks = c(0, 500, 2000, 5000),
                       label = c("0", "500", "2,000", "5,000")) +
          theme_minimal() +
          xlab("Estimated total\ndaily travelers") +
          theme(axis.title.x = element_text(size=12, margin = margin(t = 15)),
                axis.title.y = element_blank(),
                axis.text.x = element_text(size=10),
                axis.text.y = element_blank(),
                axis.ticks.y = element_blank(),
                panel.grid.minor.x = element_blank(),
                plot.margin = margin(20, 5, 5, 5))  # Remove left margin

     p3 <- plot_grid(main_plot, bar_plot, rel_widths = c(2, 1), align = 'h', axis = 'tb', labels=c("A", "B"))
     print(p3)

     png(filename = file.path(PATHS$DOCS_FIGURES, "mobility_travel_prob_tau.png"), width = 7, height = 9, units = "in", res = 300)
     print(p3)
     dev.off()



     #--------------------------------------------------------------------------
     # Plot diffusion model (pi_ij) - probability of travel between destinations
     #--------------------------------------------------------------------------

     message("Plotting diffusion matrix (pi_ij)...")

     p4 <-
          ggplot(data=melt(pi, varnames = c("origin", "destination"), value.name = "value")) +
          geom_tile(aes(x=factor(destination, levels = iso3_ordered),
                        y=factor(origin, levels = iso3_ordered),
                        fill=value)) +
          xlab('Destination') + ylab("Origin") +
          theme_bw() + theme(axis.text.x=element_text(size=10, angle=90, vjust=0.5),
                             axis.text.y=element_text(size=10),
                             axis.title.x=element_text(size=12, margin = margin(t = 15)),
                             axis.title.y=element_text(size=12, margin = margin(r = 15)),
                             legend.position='bottom') +
          viridis::scale_fill_viridis(option="G",
                                      direction=1) +
          guides(fill=guide_colorbar(title='Probability of daily travel given departure from origin',
                                     title.position='top',
                                     label.theme=element_text(size=9),
                                     barwidth=20,
                                     barheight=0.5,
                                     frame.colour='black',
                                     ticks=TRUE))

     print(p4)

     png(filename = file.path(PATHS$DOCS_FIGURES, "mobility_diffusion_pi.png"), width = 9, height = 9, units = "in", res = 300)
     print(p4)
     dev.off()

     message(glue("Writing plots to: {PATHS$DOCS_FIGURES}"))

}
