#' Plot ENSO and DMI Data
#'
#' This function creates a facet plot to visualize ENSO and DMI data over time, with separate panels for each variable (DMI, ENSO3, ENSO34, ENSO4). A horizontal line at zero is included to indicate the neutral value, and a vertical line marks the current date, with the date displayed vertically on the left side of the line.
#'
#' @param PATHS A list containing paths where ENSO and DMI data are stored and where output figures should be saved. Typically generated by the `get_paths()` function and should include:
#' \itemize{
#'   \item \strong{DATA_ENSO}: Path to the directory containing the compiled ENSO and DMI data.
#'   \item \strong{DOCS_FIGURES}: Path to the directory where the output figure will be saved.
#' }
#'
#' @return A ggplot facet plot showing the time series of DMI, ENSO3, ENSO34, and ENSO4 over time. The plot includes:
#' \itemize{
#'   \item A horizontal solid line at zero to indicate the neutral sea surface temperature anomaly.
#'   \item A vertical dashed line to indicate the current date, with the current date displayed as vertical text.
#'   \item Facets for each variable, allowing for easy comparison of DMI and ENSO regions.
#' }
#'
#' @details This function uses `ggplot2` to create a line plot with facets for each variable (DMI, ENSO3, ENSO34, and ENSO4). It adds a horizontal reference line at zero and a vertical line representing the current date. The current date is displayed as vertical text aligned to the left of the vertical line. The data is expected to be in a `date`, `variable`, and `value` format.
#'
#' @examples
#' \dontrun{
#' # Load the ENSO and DMI data and plot it
#' PATHS <- get_paths()
#' plot_ENSO_data(PATHS)
#'}
#' @importFrom ggplot2 ggplot geom_hline geom_line geom_vline annotate labs theme_minimal theme element_blank
#' @importFrom arrow read_parquet
#' @importFrom glue glue
#' @export

plot_ENSO_data <- function(PATHS, frequency) {

     requireNamespace('ggplot2')
     requireNamespace('arrow')
     requireNamespace('glue')

     # Check that frequency is valid
     if (!frequency %in% c("daily", "weekly", "monthly")) {
          stop("Invalid frequency. Choose 'daily', 'weekly', or 'monthly'.")
     }
     # Define the path to the compiled ENSO and DMI data
     enso_data_file <- file.path(PATHS$DATA_ENSO, glue::glue("compiled_ENSO_1970_2025_{frequency}.csv"))

     # Check if the ENSO data file exists
     if (!file.exists(enso_data_file)) {
          stop(glue::glue("ENSO data file not found: {enso_data_file}"))
     }

     # Load the ENSO and DMI data
     message(glue::glue("Loading ENSO and DMI data from {enso_data_file}..."))
     compiled_data <- arrow::read_csv_arrow(enso_data_file)

     # Get the current date for the vertical line
     date_plot_start <- as.Date("2015-01-01")  # Start date for the plot
     date_plot_stop <- max(compiled_data$date_start, na.rm = TRUE)  # End date for the plot
     date_present <- lubridate::today()  # Current date for the vertical line

     plot_data <- compiled_data[compiled_data$date_start >= date_plot_start,]


     # Updated color palette
     darker_palette <- c("#1b9e77", "#d95f02", "#7570b3", "#e7298a")


     # Combine the panels into one plot with a new color palette for the climate variables
     p <-
          ggplot2::ggplot(plot_data, ggplot2::aes(x = date_start, y = value, color = variable)) +
          ggplot2::geom_hline(yintercept = 0, linetype = "solid", color = "black") +  # Horizontal line at y=0

          # Plot solid lines before the present date
          ggplot2::geom_line(data = plot_data, linewidth = 1) +

          # Add a solid vertical line for present day
          ggplot2::geom_vline(xintercept = as.numeric(date_present), linetype = "solid", color = "black") +

          ggplot2::annotate("text", x = as.Date(date_present), y = Inf, label = as.character(date_present),
                            angle = 90, hjust = 1.2, vjust = -0.5, size = 3, color = "black") +

          ggplot2::labs(
               title = "Time series of ENSO and DMI",
               x = "",
               y = "Sea Surface Temperature Anomaly"
          ) +

          ggplot2::scale_color_manual(values = darker_palette) +  # Apply the updated darker palette
          ggplot2::theme_minimal() +  # Use a minimal theme
          ggplot2::theme(
               legend.position = "bottom",
               legend.title = ggplot2::element_blank(),  # Remove legend title
               plot.title = ggplot2::element_text(size = 14, face = "bold", hjust = 0.5),  # Center the plot title
               axis.text.x = ggplot2::element_text(size = 10, angle = 45, hjust = 1),  # Rotate x-axis labels for better visibility
               axis.text.y = ggplot2::element_text(size = 10),
               axis.title.y = ggplot2::element_text(size = 12)
          ) +
          ggplot2::scale_x_date(date_labels = "%Y-%m", date_breaks = "6 months")  # Customize the x-axis labels and breaks



     # Save the plot to a PNG file
     output_file <- file.path(PATHS$DOCS_FIGURES, glue::glue("climate_data_ENSO_{frequency}.png"))
     ggplot2::ggsave(output_file, plot = p, width = 9, height = 6, dpi = 300)
     message(glue::glue("ENSO and DMI plot saved to {output_file}"))

     # Display the plot
     print(p)


}
