#' Plot Weekly Climate Data for a Given Country and Save to File
#'
#' This function loads weekly climate data from a Parquet file for a specified country ISO code and plots a faceted plot showing all available climate variables over time. A vertical line indicates the present day, and the plot is saved to the `DOCS_FIGURES` directory.
#'
#' @param PATHS A list containing paths where climate data is stored. Typically generated by the `get_paths()` function and should include:
#' \itemize{
#'   \item \strong{DATA_CLIMATE}: Path to the directory where the processed climate data is stored.
#'   \item \strong{DOCS_FIGURES}: Path to the directory where the output figures will be saved.
#' }
#' @param country_iso_code A character string representing the ISO3 code of the country for which to plot the climate data.
#'
#' @return The function does not return a value but generates and saves a faceted plot of the weekly climate data for the specified country.
#'
#' @importFrom ggplot2 ggplot geom_line geom_vline facet_wrap labs theme_minimal theme element_text scale_x_date
#' @importFrom lubridate today
#' @importFrom glue glue
#' @importFrom arrow read_parquet
#' @importFrom dplyr mutate
#' @export

plot_climate_data <- function(PATHS, country_iso_code) {

     require(ggplot2)

     # Define the path to the weekly climate data file for the given country
     climate_file <- file.path(PATHS$DATA_CLIMATE, glue::glue("climate_data_{country_iso_code}_weekly.parquet"))

     # Check if the climate file exists
     if (!file.exists(climate_file)) {
          stop(glue::glue("Climate data file for {country_iso_code} not found: {climate_file}"))
     }

     # Load the weekly climate data
     message(glue::glue("Loading weekly climate data for {country_iso_code} from {climate_file}..."))
     climate_data <- arrow::read_parquet(climate_file)
     climate_data <- climate_data[!(climate_data$variable_name == "rain_sum"),]

     # Check if the data contains the expected columns
     if (!all(c("variable_name", "date_start", "value") %in% colnames(climate_data))) {
          stop("Climate data does not contain the required columns: 'variable_name', 'date_start', 'value'")
     }

     # Convert the 'date_start' column to Date type if necessary
     if (!inherits(climate_data$date_start, "Date")) climate_data$date_start <- as.Date(climate_data$date_start)

     # Define date ranges and present day
     date_plot_start <- as.Date("2015-01-01")  # Start date for the plot
     date_plot_stop <- max(climate_data$date_start, na.rm = TRUE)  # End date for the plot
     date_present <- lubridate::today()  # Current date for the vertical line

     # Create the faceted plot of climate variables over time
     p <-
          ggplot2::ggplot(climate_data, ggplot2::aes(x = date_start, y = value)) +

          # Plot the part of the line before the present date
          ggplot2::geom_line(data = subset(climate_data, date_start <= date_present),
                             color = "black", linewidth = 0.6) +

          # Plot the part of the line after the present date in a different color (e.g., blue)
          ggplot2::geom_line(data = subset(climate_data, date_start > date_present),
                             color = "#2980b9", linewidth = 0.6) +

          # Add a solid vertical line for present day using a better green
          ggplot2::geom_vline(xintercept = as.numeric(date_present),
                              linetype = "solid", color = "#006400", linewidth = 0.75) +

          # Facet by climate variable
          ggplot2::facet_wrap(~ variable_name, scales = "free_y", ncol = 2) +

          # Add labels for the plot
          ggplot2::labs(
               title = glue::glue("Weekly Climate Data for {MOSAIC::convert_iso_to_country(country_iso_code)} ({country_iso_code})"),
               x = NULL,
               y = NULL
          ) +

          # Apply minimal theme
          ggplot2::theme_minimal() +

          # Adjust the title, axis labels, strip text, and rotate x-axis labels
          ggplot2::theme(
               plot.title = ggplot2::element_text(size = 14, hjust=0.5),
               axis.title.x = ggplot2::element_text(size = 12),
               axis.title.y = ggplot2::element_text(size = 12),
               strip.text = ggplot2::element_text(size = 10),
               axis.text = ggplot2::element_text(size = 10),
               axis.text.x = ggplot2::element_text(size = 9.5, angle = 90, vjust=0.5),
               axis.text.y = ggplot2::element_text(size = 9.5)
          ) +

          # Set the x-axis limits and breaks
          ggplot2::scale_x_date(
               limits = c(as.Date(date_plot_start), as.Date(date_plot_stop)),
               date_labels = "%Y",
               date_breaks = "12 months"
          )

     # Save the plot to a PNG file
     output_file <- file.path(PATHS$DOCS_FIGURES, glue::glue("climate_data_{country_iso_code}_weekly.png"))
     ggsave(output_file, plot = p, width = 8, height = 9, dpi = 300)
     message(glue::glue("Climate plot saved to {output_file}"))

     # Display the plot
     print(p)
}
