#' Process Weekly Cholera Data: Convert Country Names to ISO3 and Filter by WHO AFRO Region
#'
#' This function processes weekly cholera data by converting country names to ISO3 codes,
#' filtering the data for countries in the WHO AFRO region, and organizing the data by
#' year and week. It also generates start and stop dates for each WHO epidemiological week.
#'
#' @param PATHS A list containing paths to the raw and processed data directories. Typically generated by the `get_paths()` function and should include:
#' \itemize{
#'   \item \strong{DATA_SCRAPE_WHO_WEEKLY}: Path to the raw cholera data file (e.g., `cholera_country_weekly.csv`).
#'   \item \strong{DATA_WHO_WEEKLY}: Path to save the processed cholera data (e.g., `cholera_country_weekly_processed.csv`).
#' }
#'
#' @return Invisibly returns \code{NULL}. Side effects:
#' \itemize{
#'   \item Reads raw data with \code{read.csv()}.
#'   \item Writes processed data to \code{PATHS$DATA_WHO_WEEKLY/cholera_country_weekly_processed.csv} via \code{write.csv()}.
#' }
#'
#' @details
#' This function performs the following tasks:
#' \itemize{
#'   \item Reads raw cholera data from a CSV file.
#'   \item Converts country names to ISO3 codes using the \code{MOSAIC::convert_country_to_iso} and \code{MOSAIC::convert_iso_to_country} functions.
#'   \item Filters the dataset to include only countries in the WHO AFRO region (based on \code{MOSAIC::iso_codes_who_afro}).
#'   \item Orders the data by year, week, and country.
#'   \item Renames columns for consistency: \code{cases_by_week} to \code{cases} and \code{deaths_by_week} to \code{deaths}.
#'   \item Adds \code{date_start} (Monday) and \code{date_stop} (Sunday) for each WHO
#'     epidemiological week (see below).
#'   \item Computes the \code{month} from \code{date_start}.
#'   \item Drops countries with ten or fewer observations.
#' }
#'
#' \strong{Week convention.} The \code{year}/\code{week} columns are WHO's own
#' \code{epiyr}/\code{epiwk} labels, which are NOT ISO-8601 weeks. WHO numbers weeks on
#' the MMWR (US CDC) calendar -- Sunday-start weeks, week 1 being the week that
#' contains 4 January -- and stamps each week with the following Monday
#' (\code{date_wk} in the WHO AWD feature service). This coincides with ISO-8601
#' except in years whose 4 January falls on a Sunday: e.g. WHO has a genuine
#' 2025-W53 starting Monday 2025-12-29 (ISO 2025 has only 52 weeks), and WHO
#' 2026-W01 starts 2026-01-05 (ISO 2026-W01 starts 2025-12-29). Each row is therefore
#' dated from WHO's calendar, never merged into a neighbouring week. Downstream
#' consumers key on \code{date_start}, not on \code{(year, week)}.
#'
#' Missing \code{cases} or \code{deaths} stay \code{NA}; no row is dropped for having
#' one field missing.
#'
#' @importFrom utils read.csv write.csv
#' @importFrom lubridate month
#' @examples
#' \dontrun{
#' PATHS <- get_paths()
#' process_WHO_weekly_data(PATHS)
#' }
#' @export

process_WHO_weekly_data <- function(PATHS) {

     if (!dir.exists(PATHS$DATA_WHO_WEEKLY)) {
          dir.create(PATHS$DATA_WHO_WEEKLY, recursive = TRUE)
     }

     raw_data_path <- file.path(PATHS$DATA_SCRAPE_WHO_WEEKLY, "cholera_country_weekly.csv")
     message("Loading raw data from: ", raw_data_path)

     d <- utils::read.csv(raw_data_path, stringsAsFactors = FALSE)

     # Convert country names to ISO3 codes and back
     d$iso_code <- MOSAIC::convert_country_to_iso(d$country)
     d$country  <- MOSAIC::convert_iso_to_country(d$iso_code)

     # Filter the data to include only AFRO countries
     d <- d[d$iso_code %in% MOSAIC::iso_codes_who_afro, ]

     # Order the data by year, week, and country
     d <- d[order(d$year, d$week, d$country), ]

     # Rename columns for consistency
     colnames(d)[colnames(d) == "cases_by_week"]  <- "cases"
     colnames(d)[colnames(d) == "deaths_by_week"] <- "deaths"

     # One row per country-week is the scrape's contract. Fail loudly rather than
     # silently summing or dropping if two raw names ever map to the same ISO code.
     dup <- duplicated(d[, c("iso_code", "year", "week")])
     if (any(dup)) {
          stop(sprintf("Raw WHO weekly data has %d duplicated (iso_code, year, week) rows, e.g. %s",
                       sum(dup),
                       paste(utils::head(paste(d$iso_code[dup], d$year[dup], d$week[dup], sep = "-"), 5),
                             collapse = ", ")))
     }

     # Week start/stop dates on WHO's own epi-week calendar (see @details)
     d$date_start <- .who_epiweek_start(d$year, d$week)
     d$date_stop  <- d$date_start + 6L

     # Month of week-start
     d$month <- lubridate::month(d$date_start)

     # Drop countries with ten or fewer observations
     tmp  <- table(d$iso_code)
     keep <- names(tmp[tmp > 10])
     d    <- d[d$iso_code %in% keep, ]
     rownames(d) <- NULL

     message("Latest observation: ", max(d$date_stop, na.rm = TRUE))

     # Save the processed data to the processed data directory
     processed_data_path <- file.path(PATHS$DATA_WHO_WEEKLY, "cholera_country_weekly_processed.csv")
     utils::write.csv(d, file = processed_data_path, row.names = FALSE)

     message("Processed weekly cholera data saved to: ", processed_data_path)
     invisible(NULL)
}


#' Monday start date of a WHO epidemiological week
#'
#' WHO's cholera AWD feature service labels weeks with MMWR (Sunday-start) epi
#' weeks -- week 1 is the Sunday-Saturday week containing 4 January -- and stamps
#' each with the Monday after the MMWR Sunday (field \code{date_wk}). Verified
#' against the service on 2026-09-29: 2025-W01 = 2024-12-30, 2025-W53 = 2025-12-29,
#' 2026-W01 = 2026-01-05.
#'
#' @param year Integer WHO epi year (\code{epiyr}).
#' @param week Integer WHO epi week (\code{epiwk}), 1-53.
#' @param invalid \code{"error"} (default) stops on a week outside 1..53 or a
#'   week 53 that does not exist in that epi year; \code{"na"} returns NA for it.
#' @return A \code{Date} vector of week-start Mondays; NA where year or week is NA.
#' @noRd
.who_epiweek_start <- function(year, week, invalid = c("error", "na")) {
     invalid <- match.arg(invalid)
     year <- as.integer(year)
     week <- as.integer(week)
     n <- max(length(year), length(week))
     year <- rep_len(year, n); week <- rep_len(week, n)
     out_of_range <- !is.na(week) & (week < 1L | week > 53L)
     if (any(out_of_range) && invalid == "error") stop("WHO epi week must be in 1..53")
     week[out_of_range] <- NA_integer_

     start <- rep(as.Date(NA), n)
     have <- !is.na(year) & !is.na(week)
     if (any(have)) {
          y <- year[have]
          jan4 <- as.Date(sprintf("%04d-01-04", y))
          # Sunday that starts MMWR week 1 (as.POSIXlt()$wday: 0 = Sunday)
          wk1_sunday <- jan4 - as.POSIXlt(jan4)$wday
          start[have] <- wk1_sunday + 1L + 7L * (week[have] - 1L)
          # A week 53 is only valid if it still belongs to that epi year, i.e. its
          # Sunday precedes the next year's week-1 Sunday.
          next_jan4 <- as.Date(sprintf("%04d-01-04", y + 1L))
          next_wk1_sunday <- next_jan4 - as.POSIXlt(next_jan4)$wday
          bad <- rep(FALSE, n)
          bad[have] <- (start[have] - 1L) >= next_wk1_sunday
          if (any(bad)) {
               if (invalid == "error") {
                    stop(sprintf("WHO epi week does not exist: %s",
                                 paste(unique(paste0(year[bad], "-W", week[bad])), collapse = ", ")))
               }
               start[bad] <- as.Date(NA)
          }
     }
     start
}
