#' Process Open-Meteo Climate Data from open-meteo-pipeline Repository
#'
#' Reads raw ERA5 historical and climate model projection parquets from the
#' open-meteo-pipeline repository, performs spatial averaging across grid points,
#' splices ERA5 observations with model projections for future dates, and writes
#' daily and weekly aggregated parquets to the MOSAIC-data processed directory.
#'
#' @param PATHS A list of paths generated by \code{get_paths()}, must include:
#' \itemize{
#'   \item \strong{OPEN_METEO_REPO}: Path to the open-meteo-pipeline repository.
#'   \item \strong{DATA_CLIMATE}: Path to weekly climate output directory.
#'   \item \strong{DATA_CLIMATE_DAILY}: Path to daily climate output directory.
#' }
#' @param climate_model Character string specifying the climate model for future
#'   projections. Default \code{"MRI_AGCM3_2_S"}.
#' @param force Logical. If \code{TRUE}, re-process all countries even if output
#'   files already exist and are up to date. Default \code{FALSE}.
#'
#' @return Invisibly returns the weekly output directory path. Writes one parquet
#'   per country to both \code{PATHS$DATA_CLIMATE_DAILY} and \code{PATHS$DATA_CLIMATE}.
#'
#' @details
#' For each of the 40 MOSAIC countries, the function:
#' \enumerate{
#'   \item Reads all ERA5 monthly parquets (wide format, per-grid-point, daily)
#'   \item Reads all climate model annual parquets (same schema)
#'   \item Converts timestamps to Date
#'   \item Splices ERA5 as primary source (real observations) with climate model
#'         projections for future dates only (clean cutover at ERA5's last date)
#'   \item Pivots from wide to long format (17 climate variables)
#'   \item Computes spatial mean across grid points per day per variable
#'   \item Writes daily output
#'   \item Aggregates to weekly: mean for most variables, sum for
#'         \code{precipitation_sum} and \code{et0_fao_evapotranspiration_sum}
#'   \item Writes weekly output
#' }
#'
#' @export
process_open_meteo_data <- function(PATHS, climate_model = "MRI_AGCM3_2_S", force = FALSE) {

     requireNamespace("arrow")
     requireNamespace("dplyr")
     requireNamespace("tidyr")

     hist_dir <- file.path(PATHS$OPEN_METEO_REPO, "data", "historical")
     clim_dir <- file.path(PATHS$OPEN_METEO_REPO, "data", "climate", climate_model)

     if (!dir.exists(hist_dir)) stop("Historical data directory not found: ", hist_dir)
     if (!dir.exists(clim_dir)) stop("Climate model directory not found: ", clim_dir)

     # Climate variable columns (wide format) — everything except metadata
     meta_cols <- c("country_name", "iso_code", "climate_model",
                    "year", "month", "week", "doy", "date",
                    "latitude", "longitude")

     # Variables that should be summed (not averaged) in weekly aggregation
     sum_vars <- c("precipitation_sum", "et0_fao_evapotranspiration_sum")

     # Ensure output directories exist
     dir.create(PATHS$DATA_CLIMATE, recursive = TRUE, showWarnings = FALSE)
     dir.create(PATHS$DATA_CLIMATE_DAILY, recursive = TRUE, showWarnings = FALSE)

     # Discover countries from historical directory
     iso_codes <- sort(basename(list.dirs(hist_dir, recursive = FALSE)))
     message(sprintf("Processing climate data for %d countries...", length(iso_codes)))

     for (iso in iso_codes) {

          daily_out <- file.path(PATHS$DATA_CLIMATE_DAILY, paste0(iso, ".parquet"))
          weekly_out <- file.path(PATHS$DATA_CLIMATE, paste0(iso, ".parquet"))

          # Caching: skip if output is newer than newest source file
          if (!force && file.exists(daily_out) && file.exists(weekly_out)) {
               hist_files <- list.files(file.path(hist_dir, iso), pattern = "\\.parquet$",
                                        full.names = TRUE)
               clim_files <- list.files(file.path(clim_dir, iso), pattern = "\\.parquet$",
                                        full.names = TRUE)
               newest_source <- max(file.mtime(c(hist_files, clim_files)))
               oldest_output <- min(file.mtime(c(daily_out, weekly_out)))
               if (oldest_output > newest_source) {
                    message(sprintf("  %s: up to date, skipping", iso))
                    next
               }
          }

          message(sprintf("  %s: processing...", iso))

          # --- Read ERA5 historical ---
          hist_files <- list.files(file.path(hist_dir, iso), pattern = "\\.parquet$",
                                   full.names = TRUE)
          if (length(hist_files) == 0) {
               warning(sprintf("No historical parquet files for %s, skipping", iso))
               next
          }
          hist_data <- arrow::open_dataset(hist_files) |> dplyr::collect()
          hist_data$date <- as.Date(hist_data$date)

          # ERA5 Historical API only serves 0-7cm soil moisture; upstream raw
          # parquets carry the native name. Rename to match the 0-10cm column
          # used by the climate-model parquets and all downstream consumers.
          sm_idx <- which(names(hist_data) == "soil_moisture_0_to_7cm_mean")
          if (length(sm_idx) == 1L) {
               names(hist_data)[sm_idx] <- "soil_moisture_0_to_10cm_mean"
          }

          # --- Read climate model projections ---
          clim_files <- list.files(file.path(clim_dir, iso), pattern = "\\.parquet$",
                                   full.names = TRUE)
          if (length(clim_files) == 0) {
               warning(sprintf("No climate model parquet files for %s, skipping", iso))
               next
          }
          clim_data <- arrow::open_dataset(clim_files) |> dplyr::collect()
          clim_data$date <- as.Date(clim_data$date)

          # --- Splice: ERA5 primary, climate model for future dates only ---
          era5_max_date <- max(hist_data$date, na.rm = TRUE)
          clim_future <- clim_data[clim_data$date > era5_max_date, ]
          combined <- rbind(hist_data, clim_future)

          # --- ISO-8601 week labelling (DA-01) ---------------------------------
          # The raw open-meteo parquets pair CALENDAR year (%Y) with ISO week (%V).
          # That pairing is invalid: a Monday in late December belongs to ISO week 1
          # of the NEXT ISO year, so grouping by (calendar year, ISO week) merges it
          # with the FOLLOWING January. Measured on the shipped MOZ panel before this
          # fix: 19 (year, week) cells per country spanned 365-366 days -- e.g.
          # (2018, week 1) covered 2018-01-01..2018-12-31, so that cell's weekly value
          # was the mean of January AND December. This biased every W01/W52 anomaly
          # climatology and `wind_speed_10m_max`, the cyclone GAM's lead predictor.
          # `%G` is the ISO week-based year and is the only valid partner for `%V`
          # (verified identical to the Thursday-shift idiom used in
          # process_EMDAT_data / process_IDMC_data). Re-derive here so the R side is
          # correct regardless of what the upstream pipeline emits.
          # `month` and `doy` are left CALENDAR-derived on purpose and are therefore
          # NOT consistent with the ISO `year` on the ~48 boundary dates per country
          # (e.g. 2001-12-31 -> year=2002, month=12, doy=365). Join on `date`, never
          # on year+month or year+doy.
          combined$year <- as.integer(format(combined$date, "%G"))
          combined$week <- as.integer(format(combined$date, "%V"))

          # Identify climate variable columns
          var_cols <- setdiff(names(combined), meta_cols)

          # --- Pivot wide to long ---
          daily_long <- tidyr::pivot_longer(
               combined,
               cols = dplyr::all_of(var_cols),
               names_to = "variable_name",
               values_to = "value"
          )

          # --- Spatial average across grid points ---
          daily_avg <- daily_long |>
               dplyr::group_by(iso_code, variable_name, date, year, month, week, doy) |>
               dplyr::summarise(value = mean(value, na.rm = TRUE), .groups = "drop")

          # --- Write daily output ---
          arrow::write_parquet(daily_avg, daily_out)

          # --- Weekly aggregation ---
          weekly_avg <- daily_avg |>
               dplyr::group_by(iso_code, variable_name, year, week) |>
               dplyr::summarise(
                    value = ifelse(
                         variable_name[1] %in% sum_vars,
                         sum(value, na.rm = TRUE),
                         mean(value, na.rm = TRUE)
                    ),
                    date_start = min(date),
                    date_stop = max(date),
                    .groups = "drop"
               )

          # DA-01 guard for the CLIMATE-side failure mode. Mislabelled weeks do
          # not duplicate keys here -- group_by() merges January and December into
          # one cell, so the value is silently wrong. The observable signature is a
          # cell whose member days span more than a week. Measured on MOZ under the
          # old labelling: 19 cells with span > 7 days, max 366; under %G + %V: 0,
          # max 7. This assertion is the only thing that discriminates the two.
          span_bad <- sum((as.numeric(weekly_avg$date_stop - weekly_avg$date_start) + 1) > 7)
          if (span_bad > 0L) {
               stop(sprintf(paste0("process_open_meteo_data(%s): %d weekly cell(s) span more than 7 days. ",
                                   "This means week labelling paired a CALENDAR year with an ISO week ",
                                   "(use %%G with %%V, never %%Y), collapsing the year-boundary week into ",
                                   "the following January."), iso, span_bad), call. = FALSE)
          }

          # --- Write weekly output ---
          arrow::write_parquet(weekly_avg, weekly_out)
     }

     message("Climate data processing complete.")
     invisible(PATHS$DATA_CLIMATE)
}
