#' Process Weekly Cholera Data: Convert Country Names to ISO3 and Filter by AFRO Countries
#'
#' This function processes cholera data by converting country names to ISO3 codes, filtering for AFRO region countries, and cleaning and organizing the data for further analysis.
#'
#' @param PATHS A list containing paths to the raw and processed data directories. Typically generated by the `get_paths()` function and should include:
#' \itemize{
#'   \item \strong{DATA_RAW}: Path to the raw cholera data file (e.g., `cholera_country_weekly.csv`).
#'   \item \strong{DATA_PROCESSED}: Path to save the processed cholera data (e.g., `cholera_country_weekly_processed.csv`).
#' }
#'
#' @return The function does not return a value but processes the cholera data and saves it to a specified file as a CSV.
#'
#' @details
#' The function reads in cholera data, converts country names to ISO3 codes (and vice versa), filters for countries in the AFRO region, and ensures the data is cleaned and organized by year and week. It also handles special cases such as renaming the Democratic Republic of Congo and Congo (Republic) and modifies column names for consistency.
#'
#' @importFrom countrycode countrycode
#' @importFrom utils read.csv write.csv
#'
#' @examples
#' \dontrun{
#' # Assuming PATHS is generated from get_paths()
#' PATHS <- get_paths()
#'
#' # Process cholera data
#' process_WHO_weekly_data(PATHS)
#' }
#'
#' @export

process_WHO_weekly_data <- function(PATHS) {

     requireNamespace('countrycode')
     requireNamespace('utils')

     if (!dir.exists(PATHS$DATA_WHO_WEEKLY)) dir.create(PATHS$DATA_WHO_WEEKLY, recursive = TRUE)

     # Read the cholera data from the raw data directory
     raw_data_path <- file.path(PATHS$DATA_RAW, "WHO/weekly/cholera_country_weekly.csv")
     d <- utils::read.csv(raw_data_path, stringsAsFactors = FALSE)

     # Convert country names to ISO3 codes and back
     d$iso_code <- MOSAIC::convert_country_to_iso(d$country)
     d$country <- MOSAIC::convert_iso_to_country(d$iso_code)

     # Filter the data to include only AFRO countries
     d <- d[d$iso_code %in% MOSAIC::iso_codes_who_afro, ]

     # Order the data by year, week, and country
     d <- d[order(d$year, d$week, d$country), ]

     # Rename columns for consistency
     colnames(d)[colnames(d) == "cases_by_week"] <- "cases"
     colnames(d)[colnames(d) == "deaths_by_week"] <- "deaths"

     # Reorganize the columns for clarity
     d <- d[, c("country", "iso_code", "week", "cases", "deaths")]

     # Print the first few rows for verification
     head(d)

     # Save the processed data to the processed data directory
     processed_data_path <- file.path(PATHS$DATA_WHO_WEEKLY, "cholera_country_weekly_processed.csv")
     utils::write.csv(d, file = processed_data_path, row.names = FALSE)

     message("Processed cholera data saved to: ", processed_data_path)
}
