#' Process Weekly Cholera Data: Convert Country Names to ISO3 and Filter by WHO AFRO Region
#'
#' This function processes weekly cholera data by converting country names to ISO3 codes, filtering the data for countries in the WHO AFRO region, and organizing the data by year and week. It also adds start and stop dates for each ISO week.
#'
#' @param PATHS A list containing paths to the raw and processed data directories. Typically generated by the `get_paths()` function and should include:
#' \itemize{
#'   \item \strong{DATA_SCRAPE_WHO_WEEKLY}: Path to the raw cholera data file (e.g., `cholera_country_weekly.csv`).
#'   \item \strong{DATA_WHO_WEEKLY}: Path to save the processed cholera data (e.g., `cholera_country_weekly_processed.csv`).
#' }
#'
#' @return The function does not return a value but processes the cholera data and saves it as a CSV file.
#'
#' @details
#' This function performs the following tasks:
#' \itemize{
#'   \item Reads raw cholera data from a CSV file.
#'   \item Converts country names to ISO3 codes using the `MOSAIC::convert_country_to_iso` and `MOSAIC::convert_iso_to_country` functions.
#'   \item Filters the dataset to include only countries in the WHO AFRO region (based on `MOSAIC::iso_codes_who_afro`).
#'   \item Orders the data by year, week, and country.
#'   \item Renames columns for consistency: `cases_by_week` to `cases` and `deaths_by_week` to `deaths`.
#'   \item Adds `date_start` and `date_stop` columns based on ISO week, using the `ISOweek::ISOweek2date` function.
#'   \item Reorganizes the columns for clarity and saves the processed data to the specified path.
#' }
#'
#' @importFrom MOSAIC convert_country_to_iso convert_iso_to_country iso_codes_who_afro
#' @importFrom utils read.csv write.csv
#' @importFrom ISOweek ISOweek2date
#' @examples
#' \dontrun{
#' # Define paths for raw and processed cholera data
#' PATHS <- get_paths()
#'
#' # Process the weekly cholera data
#' process_WHO_weekly_data(PATHS)
#' }
#' @export

process_WHO_weekly_data <- function(PATHS) {

     if (!dir.exists(PATHS$DATA_WHO_WEEKLY)) dir.create(PATHS$DATA_WHO_WEEKLY, recursive = TRUE)

     # Read the cholera data from the raw data directory
     raw_data_path <- file.path(PATHS$DATA_SCRAPE_WHO_WEEKLY, "cholera_country_weekly.csv")
     message("Loading raw data from: ", raw_data_path)

     d <- utils::read.csv(raw_data_path, stringsAsFactors = FALSE)

     # Convert country names to ISO3 codes and back
     d$iso_code <- MOSAIC::convert_country_to_iso(d$country)
     d$country <- MOSAIC::convert_iso_to_country(d$iso_code)

     # Filter the data to include only AFRO countries
     d <- d[d$iso_code %in% MOSAIC::iso_codes_who_afro, ]

     # Order the data by year, week, and country
     d <- d[order(d$year, d$week, d$country), ]

     # Rename columns for consistency
     colnames(d)[colnames(d) == "cases_by_week"] <- "cases"
     colnames(d)[colnames(d) == "deaths_by_week"] <- "deaths"

     d$iso_week <- paste0(d$year, "-W", sprintf("%02d", d$week))
     d$date_start <- ISOweek::ISOweek2date(paste0(d$iso_week, "-1"))
     d$date_stop <- ISOweek::ISOweek2date(paste0(d$iso_week, "-7"))
     d$iso_week <- NULL

     # Reorganize the columns for clarity
     d <- d[, c("country", "iso_code", "year", "week", "date_start", "date_stop", "cases", "deaths")]

     # Print the first few rows for verification
     head(d)

     message("Latest observation: ", max(d$date_stop, na.rm=TRUE))

     # Save the processed data to the processed data directory
     processed_data_path <- file.path(PATHS$DATA_WHO_WEEKLY, "cholera_country_weekly_processed.csv")
     utils::write.csv(d, file = processed_data_path, row.names = FALSE)

     message("Processed cholera data saved to: ", processed_data_path)
}
