#' Process IDMC Internal Displacement Events Into Country-Week Panels
#'
#' Reads IDMC Internal Displacement Updates (IDU) event records and expands
#' them into complete country-week panels of displacement-occurrence
#' covariates, mirroring \code{\link{process_EMDAT_data}} so the two hazard
#' families can be joined onto the same ISO-week grid in
#' \code{compile_suitability_data()}.
#'
#' Two panels are written to \code{PATHS$DATA_IDMC}:
#' \code{displacement_conflict_country_weekly.csv} and
#' \code{displacement_disaster_country_weekly.csv}. The split follows IDU's
#' own \code{displacement_type} field (\code{"Conflict"} /
#' \code{"Disaster"}) and is deliberate: the two have different causal
#' relationships to cholera. Disaster-driven displacement is largely
#' flood/storm-mediated and therefore partly collinear with the EM-DAT
#' hazard covariates, whereas conflict-driven displacement is an
#' independent signal (WASH collapse, camp formation, care-seeking
#' disruption) with no EM-DAT analogue.
#'
#' @section Data source and access:
#' IDU are \emph{preliminary} estimates of new displacements, updated daily;
#' the curated annual counterpart is the Global Internal Displacement
#' Database (GIDD), which is too coarse for event-timing work. Two
#' acquisition routes are supported by \code{source_dir}:
#' \itemize{
#'   \item \strong{API} (preferred, full history): the IDMC IDU API, most
#'     easily via the CRAN \pkg{idmc} package
#'     (\code{idmc::idmc_get_data()}), which reads an endpoint URL from the
#'     \code{IDMC_API} environment variable. The URL embeds a client id
#'     issued by IDMC on request. Save the returned frame as a CSV in
#'     \code{PATHS$DATA_IDMC_RAW}.
#'   \item \strong{HDX per-country mirrors} (open, no credentials, but only
#'     ~2025 onward): \code{<iso>-idmc-idu-events} datasets on the
#'     Humanitarian Data Exchange. 26 of the 27 MOSAIC national countries
#'     have one. Useful for standing the pipeline up before a key arrives.
#' }
#' Note the URL advertised on the HDX resource page
#' (\code{backend.idmcdb.org}) no longer resolves; the live API host is
#' \code{helix-tools-api.idmcdb.org}.
#'
#' @param PATHS A list of paths generated by \code{get_paths()}. Must include:
#' \itemize{
#'   \item \strong{DATA_IDMC_RAW}: Path to \code{MOSAIC-data/raw/IDMC}.
#'   \item \strong{DATA_IDMC}: Path to \code{MOSAIC-data/processed/IDMC/weekly}.
#' }
#' @param source_dir Optional directory of IDU event CSVs to read instead of
#'   \code{PATHS$DATA_IDMC_RAW} (e.g. a scratch directory of HDX downloads).
#'   All \code{*.csv} files in the directory are read and row-bound; duplicate
#'   event \code{id}s are dropped, so per-country mirrors and a global export
#'   can be mixed safely.
#' @param panel_start First Monday of the panel grid. Defaults to
#'   \code{"2000-01-03"} to match the EM-DAT panels exactly. Cells before the
#'   first IDU event are structural zeros, NOT observed absences -- see Details.
#'
#' @return Invisibly, a named character vector of the two written CSV paths
#'   (\code{conflict}, \code{disaster}). Each CSV has one row per
#'   (iso_code, year, week):
#' \describe{
#'   \item{iso_code}{ISO3 country code.}
#'   \item{year, week}{ISO-8601 year and week (1-53).}
#'   \item{date_start, date_stop}{Monday and Sunday of the ISO-week.}
#'   \item{\code{idmc_<kind>_active}}{1 if any event of that kind overlaps the week.}
#'   \item{\code{idmc_<kind>_new}}{Number of events of that kind starting in the week.}
#'   \item{\code{idmc_<kind>_displaced}}{\code{log1p} of summed \code{figure} (persons
#'     displaced) across overlapping events; NAs treated as 0.}
#' }
#'
#' @details
#' Each event is expanded across the ISO-weeks its
#' \code{displacement_start_date}:\code{displacement_end_date} range touches.
#' Records missing a start date are dropped; a missing or earlier end date is
#' set to the start date (single-day event).
#'
#' \strong{Coverage caveat -- read before modelling.} IDU is a rolling
#' near-real-time product and the accessible history depends on the route
#' used: the HDX per-country mirrors begin ~2025, the API carries more. Zero
#' cells before a country's first observed event therefore mean "not
#' reported by this extract", not "no displacement occurred". Always check
#' the per-country first-event dates printed by this function (and stored in
#' the \code{coverage} attribute) before using the panel as a covariate or as
#' a trigger denominator. This is a materially weaker coverage guarantee than
#' EM-DAT's, which runs from 2000.
#'
#' \strong{Collinearity caveat.} \code{idmc_disaster_*} is largely
#' flood/storm-driven and will correlate with \code{emdat_flood_*}; do not
#' enter both into a feature set without checking. \code{idmc_conflict_*} is
#' the genuinely additional signal.
#'
#' @seealso \code{\link{process_EMDAT_data}} for the sibling hazard panels.
#'
#' @importFrom utils read.csv write.csv
#' @importFrom glue glue
#' @importFrom lubridate floor_date
#' @export
process_IDMC_data <- function(PATHS, source_dir = NULL, panel_start = "2000-01-03") {

     message("Processing IDMC internal-displacement events into country-week panels...")

     if (is.null(PATHS$DATA_IDMC_RAW) || is.null(PATHS$DATA_IDMC)) {
          stop("PATHS must include DATA_IDMC_RAW and DATA_IDMC (regenerate via get_paths()).")
     }
     src <- if (!is.null(source_dir)) source_dir else PATHS$DATA_IDMC_RAW
     if (!dir.exists(src)) {
          stop("IDMC source directory not found: ", src,
               "\n  Populate it from the IDU API (see ?process_IDMC_data) or the HDX mirrors.")
     }

     files <- list.files(src, pattern = "\\.csv$", full.names = TRUE, ignore.case = TRUE)
     if (length(files) == 0) stop("No IDU event CSVs found in: ", src)
     message(glue::glue("  Reading {length(files)} file(s) from {src}"))

     req <- c("iso3", "displacement_type", "figure", "displacement_start_date")
     d <- do.call(rbind, lapply(files, function(f) {
          x <- utils::read.csv(f, stringsAsFactors = FALSE)
          miss <- setdiff(req, names(x))
          if (length(miss)) {
               warning("Skipping ", basename(f), " (missing: ", paste(miss, collapse = ", "), ")")
               return(NULL)
          }
          keep <- c(req, "displacement_end_date", "id", "event_name", "type", "subtype")
          x <- x[, intersect(keep, names(x)), drop = FALSE]
          for (cc in setdiff(keep, names(x))) x[[cc]] <- NA
          x[, keep, drop = FALSE]
     }))
     if (is.null(d) || nrow(d) == 0) stop("No usable IDU records after reading ", src)

     # Per-country mirrors and a global export can overlap -> de-duplicate on event id
     if ("id" %in% names(d)) {
          n0 <- nrow(d); d <- d[!duplicated(d$id) | is.na(d$id), , drop = FALSE]
          if (nrow(d) < n0) message(glue::glue("  Dropped {n0 - nrow(d)} duplicate event id(s)"))
     }
     message(glue::glue("  {nrow(d)} unique IDU events read"))

     iso_keep <- get("iso_codes_mosaic", envir = asNamespace("MOSAIC"))
     d <- d[!is.na(d$iso3) & d$iso3 %in% iso_keep, , drop = FALSE]

     d$start_date <- as.Date(d$displacement_start_date)
     d$end_date   <- as.Date(d$displacement_end_date)
     d <- d[!is.na(d$start_date), , drop = FALSE]
     d$end_date[is.na(d$end_date) | d$end_date < d$start_date] <-
          d$start_date[is.na(d$end_date) | d$end_date < d$start_date]
     d$figure <- suppressWarnings(as.numeric(d$figure)); d$figure[is.na(d$figure)] <- 0

     if (nrow(d) == 0) stop("No IDU events remain after filtering to MOSAIC AFRO countries.")
     message(glue::glue("  {nrow(d)} events in {length(unique(d$iso3))} MOSAIC AFRO countries ",
                        "({format(min(d$start_date))} to {format(max(d$end_date))})"))

     # Coverage table -- the honest denominator for any downstream trigger work
     cov <- do.call(rbind, lapply(split(d, d$iso3), function(z) data.frame(
          iso_code = z$iso3[1], n_events = nrow(z),
          first_event = min(z$start_date), last_event = max(z$end_date),
          n_conflict = sum(z$displacement_type == "Conflict", na.rm = TRUE),
          n_disaster = sum(z$displacement_type == "Disaster", na.rm = TRUE),
          stringsAsFactors = FALSE)))
     cov <- cov[order(-cov$n_events), ]

     dir.create(PATHS$DATA_IDMC, recursive = TRUE, showWarnings = FALSE)
     panel_end <- max(d$end_date)
     out <- character(0)

     for (kind in c("Conflict", "Disaster")) {
          ev <- d[!is.na(d$displacement_type) & d$displacement_type == kind, , drop = FALSE]
          prefix <- paste0("idmc_", tolower(kind))
          p <- .idmc_build_panel(ev, iso_keep, as.Date(panel_start), panel_end, prefix)
          f <- file.path(PATHS$DATA_IDMC,
                         sprintf("displacement_%s_country_weekly.csv", tolower(kind)))
          utils::write.csv(p, f, row.names = FALSE)
          out[tolower(kind)] <- f
          act <- p[[paste0(prefix, "_active")]]
          message(glue::glue(
               "  Wrote {basename(f)} ({nrow(p)} rows, {length(unique(p$iso_code))} countries, ",
               "{nrow(ev)} events) -- active weeks: {sum(act)} ",
               "({round(100 * mean(act), 3)}% of cells)"))
     }

     message("  Coverage by country (first observed event -- zeros before this are NOT observed absences):")
     print(utils::head(cov, 10), row.names = FALSE)
     attr(out, "coverage") <- cov
     invisible(out)
}


# Internal: expand IDU events onto a complete ISO-week x country grid.
# Mirrors .emdat_build_hazard_panel() so the panels align exactly.
.idmc_build_panel <- function(events, iso_keep, panel_start, panel_end, prefix) {

     panel_end_monday <- lubridate::floor_date(panel_end, "week", week_start = 1)
     mondays <- seq(lubridate::floor_date(panel_start, "week", week_start = 1),
                    panel_end_monday, by = "week")

     iso_weeks <- data.frame(
          date_start = mondays,
          date_stop  = mondays + 6L,
          year       = as.integer(format(mondays + 3L, "%G")),
          week       = as.integer(format(mondays + 3L, "%V")),
          stringsAsFactors = FALSE
     )
     panel <- expand.grid(iso_code = sort(iso_keep), row_id = seq_len(nrow(iso_weeks)),
                          KEEP.OUT.ATTRS = FALSE, stringsAsFactors = FALSE)
     panel$year       <- iso_weeks$year[panel$row_id]
     panel$week       <- iso_weeks$week[panel$row_id]
     panel$date_start <- iso_weeks$date_start[panel$row_id]
     panel$date_stop  <- iso_weeks$date_stop[panel$row_id]
     panel$row_id     <- NULL

     col_active <- paste0(prefix, "_active")
     col_new    <- paste0(prefix, "_new")
     col_disp   <- paste0(prefix, "_displaced")
     panel[[col_active]] <- 0L
     panel[[col_new]]    <- 0L
     panel[[col_disp]]   <- 0

     if (nrow(events) > 0) {
          long <- do.call(rbind, lapply(seq_len(nrow(events)), function(i) {
               days <- seq(events$start_date[i], events$end_date[i], by = "day")
               yw <- unique(data.frame(
                    iso_code = events$iso3[i],
                    year = as.integer(format(days, "%G")),
                    week = as.integer(format(days, "%V")),
                    stringsAsFactors = FALSE))
               yw$is_start <- as.integer(
                    yw$year == as.integer(format(events$start_date[i], "%G")) &
                    yw$week == as.integer(format(events$start_date[i], "%V")))
               yw$figure <- events$figure[i]
               yw
          }))
          key  <- paste(long$iso_code, long$year, long$week, sep = "|")
          pkey <- paste(panel$iso_code, panel$year, panel$week, sep = "|")

          agg_new  <- tapply(long$is_start, key, sum)
          agg_disp <- tapply(long$figure,   key, sum)
          m <- match(pkey, names(agg_new))
          hit <- !is.na(m)
          panel[[col_active]][hit] <- 1L
          panel[[col_new]][hit]    <- as.integer(agg_new[m[hit]])
          panel[[col_disp]][hit]   <- log1p(as.numeric(agg_disp[m[hit]]))
     }

     panel[order(panel$iso_code, panel$date_start), ]
}
