#' Process EM-DAT Flood Events Into a Country-Week Panel
#'
#' Reads the most recent EM-DAT public-extract xlsx file in
#' \code{PATHS$DATA_EMDAT_RAW}, filters to flood events in MOSAIC AFRO
#' countries, expands each event across the ISO-8601 weeks it spans, and
#' writes a complete country-week panel of flood-occurrence covariates to
#' \code{PATHS$DATA_EMDAT/floods_country_weekly.csv}.
#'
#' @param PATHS A list of paths generated by \code{get_paths()}. Must include:
#' \itemize{
#'   \item \strong{DATA_EMDAT_RAW}: Path to \code{MOSAIC-data/raw/EMDAT}.
#'   \item \strong{DATA_EMDAT}: Path to the processed output directory
#'     (\code{MOSAIC-data/processed/EMDAT/weekly}).
#' }
#'
#' @return Invisibly returns the path to the written CSV. The CSV contains
#'   one row per (iso_code, year, week) for every ISO-week between
#'   \code{date_start} (default 2000-01-03) and the latest week covered by
#'   any flood event in the raw extract, restricted to
#'   \code{iso_codes_mosaic}. Columns:
#' \describe{
#'   \item{iso_code}{ISO3 country code.}
#'   \item{year}{ISO-8601 year of the week.}
#'   \item{week}{ISO-8601 week number (1-53).}
#'   \item{date_start}{Monday of the ISO-week.}
#'   \item{date_stop}{Sunday of the ISO-week.}
#'   \item{emdat_flood_active}{1 if any flood event overlaps the week, else 0.}
#'   \item{emdat_flood_new}{Number of flood events that start in this week.}
#'   \item{emdat_flood_affected}{\code{log1p} of summed \code{Total Affected}
#'     across overlapping events (NAs treated as 0).}
#'   \item{emdat_flood_deaths}{\code{log1p} of summed \code{Total Deaths}
#'     across overlapping events (NAs treated as 0).}
#' }
#'
#' @details
#' EM-DAT records carry frequent missing day-of-month and occasional missing
#' end-month values. Imputation rules:
#' \itemize{
#'   \item Missing \code{Start Day} or \code{End Day} -> 15.
#'   \item Missing \code{End Month} -> \code{Start Month}.
#'   \item Missing \code{End Year} -> \code{Start Year}.
#'   \item If the resulting \code{end_date} is earlier than \code{start_date}
#'     (data-entry artifact), it is reset to \code{start_date}.
#' }
#'
#' Each event is expanded to the unique set of ISO-8601 (year, week) pairs
#' touched by the daily date range \code{start_date:end_date}. The panel
#' grid is the full Cartesian product of \code{iso_codes_mosaic} and all
#' ISO-weeks from \code{date_start} through the latest event end-week; cells
#' with no flood activity carry zeros, so a downstream left-join against
#' the suitability table does not need to impute missingness.
#'
#' EM-DAT only records events meeting CRED's inclusion thresholds (>=10
#' deaths, >=100 affected, or formal emergency declaration), so this
#' covariate captures major flood occurrences rather than continuous flood
#' intensity. The richer continuous signal lives in the OpenMeteo
#' precipitation/anomaly covariates.
#'
#' @importFrom readxl read_excel
#' @importFrom utils write.csv
#' @importFrom glue glue
#' @importFrom lubridate floor_date ceiling_date
#' @export
process_EMDAT_data <- function(PATHS) {

     message("Processing EM-DAT flood events into a country-week panel...")

     if (is.null(PATHS$DATA_EMDAT_RAW) || is.null(PATHS$DATA_EMDAT)) {
          stop("PATHS must include DATA_EMDAT_RAW and DATA_EMDAT (regenerate via get_paths()).")
     }
     if (!dir.exists(PATHS$DATA_EMDAT_RAW)) {
          stop("Raw EM-DAT directory not found: ", PATHS$DATA_EMDAT_RAW)
     }

     # Locate the newest public extract
     candidates <- list.files(
          PATHS$DATA_EMDAT_RAW,
          pattern = "^public_emdat_.*\\.xlsx$",
          full.names = TRUE,
          recursive = FALSE,
          ignore.case = TRUE
     )
     if (length(candidates) == 0) {
          stop("No 'public_emdat_*.xlsx' files found in: ", PATHS$DATA_EMDAT_RAW)
     }
     # Prefer the filename-encoded request date; fall back to mtime
     fname_dates <- regmatches(
          candidates,
          regexpr("[0-9]{4}-[0-9]{2}-[0-9]{2}", candidates)
     )
     have_date <- nchar(fname_dates) == 10
     order_keys <- ifelse(have_date,
                          as.character(fname_dates),
                          format(file.info(candidates)$mtime, "%Y-%m-%d"))
     src_file <- candidates[order(order_keys, decreasing = TRUE)][1]
     message("  Reading: ", basename(src_file))

     d <- readxl::read_excel(src_file, sheet = "EM-DAT Data")
     message(glue::glue("  {nrow(d)} events in extract"))

     # MOSAIC AFRO country filter (package data)
     iso_keep <- get("iso_codes_mosaic", envir = asNamespace("MOSAIC"))

     # Filter: floods only, AFRO ISOs, with a valid start year
     d <- d[!is.na(d$`Disaster Type`) & d$`Disaster Type` == "Flood", , drop = FALSE]
     d <- d[!is.na(d$ISO) & d$ISO %in% iso_keep, , drop = FALSE]
     d <- d[!is.na(d$`Start Year`), , drop = FALSE]
     message(glue::glue("  {nrow(d)} flood events in MOSAIC AFRO countries"))

     if (nrow(d) == 0) {
          stop("No flood events remain after filtering to MOSAIC AFRO countries.")
     }

     # ----- Date construction with imputation -----
     start_month <- ifelse(is.na(d$`Start Month`), 1L, as.integer(d$`Start Month`))
     start_day   <- ifelse(is.na(d$`Start Day`),  15L, as.integer(d$`Start Day`))
     end_year    <- ifelse(is.na(d$`End Year`),  as.integer(d$`Start Year`),
                                                  as.integer(d$`End Year`))
     end_month   <- ifelse(is.na(d$`End Month`), start_month, as.integer(d$`End Month`))
     end_day     <- ifelse(is.na(d$`End Day`),   15L, as.integer(d$`End Day`))

     start_date <- as.Date(sprintf("%04d-%02d-%02d",
                                    as.integer(d$`Start Year`), start_month, start_day))
     end_date   <- as.Date(sprintf("%04d-%02d-%02d",
                                    end_year, end_month, end_day))

     # Some imputed days may exceed the month length (e.g., 31 in April);
     # as.Date() returns NA. Fall back to the last day of that month.
     bad_end <- is.na(end_date)
     if (any(bad_end)) {
          first <- as.Date(sprintf("%04d-%02d-01",
                                    end_year[bad_end], end_month[bad_end]))
          end_date[bad_end] <- lubridate::ceiling_date(first, "month") - 1L
     }
     bad_start <- is.na(start_date)
     if (any(bad_start)) {
          first <- as.Date(sprintf("%04d-%02d-01",
                                    as.integer(d$`Start Year`)[bad_start],
                                    start_month[bad_start]))
          start_date[bad_start] <- lubridate::ceiling_date(first, "month") - 1L
     }

     # Reset reversed ranges (data-entry artifacts)
     end_date <- pmax(end_date, start_date)

     events <- data.frame(
          iso_code   = d$ISO,
          start_date = start_date,
          end_date   = end_date,
          affected   = ifelse(is.na(d$`Total Affected`), 0, as.numeric(d$`Total Affected`)),
          deaths     = ifelse(is.na(d$`Total Deaths`),   0, as.numeric(d$`Total Deaths`)),
          stringsAsFactors = FALSE
     )

     # ----- Build the ISO-week panel grid -----
     panel_start <- as.Date("2000-01-03")  # Monday of ISO week 2000-W01
     panel_end   <- max(events$end_date)
     panel_end_monday <- lubridate::floor_date(panel_end, "week", week_start = 1)
     mondays <- seq(panel_start, panel_end_monday, by = "week")

     iso_weeks <- data.frame(
          date_start = mondays,
          date_stop  = mondays + 6L,
          year       = as.integer(format(mondays + 3L, "%G")),
          week       = as.integer(format(mondays + 3L, "%V")),
          stringsAsFactors = FALSE
     )

     panel <- expand.grid(
          iso_code = sort(iso_keep),
          row_id   = seq_len(nrow(iso_weeks)),
          KEEP.OUT.ATTRS = FALSE,
          stringsAsFactors = FALSE
     )
     panel$year       <- iso_weeks$year[panel$row_id]
     panel$week       <- iso_weeks$week[panel$row_id]
     panel$date_start <- iso_weeks$date_start[panel$row_id]
     panel$date_stop  <- iso_weeks$date_stop[panel$row_id]
     panel$row_id     <- NULL

     # ----- Expand each event into the ISO-weeks it touches -----
     expand_event <- function(i) {
          days <- seq(events$start_date[i], events$end_date[i], by = "day")
          # Map each day to its ISO (year, week); collapse to unique pairs
          yw <- unique(data.frame(
               iso_code = events$iso_code[i],
               year     = as.integer(format(days, "%G")),
               week     = as.integer(format(days, "%V")),
               stringsAsFactors = FALSE
          ))
          yw$start_year  <- as.integer(format(events$start_date[i], "%G"))
          yw$start_week  <- as.integer(format(events$start_date[i], "%V"))
          yw$is_start    <- as.integer(yw$year == yw$start_year & yw$week == yw$start_week)
          yw$affected    <- events$affected[i]
          yw$deaths      <- events$deaths[i]
          yw$start_year  <- NULL
          yw$start_week  <- NULL
          yw
     }
     touched <- do.call(rbind, lapply(seq_len(nrow(events)), expand_event))

     # Aggregate per (iso_code, year, week)
     key <- paste(touched$iso_code, touched$year, touched$week, sep = "|")
     agg <- data.frame(
          iso_code = tapply(touched$iso_code, key, function(x) x[1]),
          year     = tapply(touched$year,     key, function(x) x[1]),
          week     = tapply(touched$week,     key, function(x) x[1]),
          emdat_flood_active   = 1L,
          emdat_flood_new      = as.integer(tapply(touched$is_start, key, sum)),
          emdat_flood_affected = log1p(tapply(touched$affected, key, sum)),
          emdat_flood_deaths   = log1p(tapply(touched$deaths,   key, sum)),
          stringsAsFactors = FALSE
     )
     row.names(agg) <- NULL

     # ----- Join aggregates onto panel, fill zeros -----
     out <- merge(panel, agg,
                   by = c("iso_code", "year", "week"),
                   all.x = TRUE, sort = FALSE)
     out$emdat_flood_active   <- ifelse(is.na(out$emdat_flood_active),   0L, out$emdat_flood_active)
     out$emdat_flood_new      <- ifelse(is.na(out$emdat_flood_new),      0L, out$emdat_flood_new)
     out$emdat_flood_affected <- ifelse(is.na(out$emdat_flood_affected), 0,  out$emdat_flood_affected)
     out$emdat_flood_deaths   <- ifelse(is.na(out$emdat_flood_deaths),   0,  out$emdat_flood_deaths)

     out <- out[order(out$iso_code, out$date_start),
                 c("iso_code", "year", "week", "date_start", "date_stop",
                   "emdat_flood_active", "emdat_flood_new",
                   "emdat_flood_affected", "emdat_flood_deaths")]

     dir.create(PATHS$DATA_EMDAT, recursive = TRUE, showWarnings = FALSE)
     out_file <- file.path(PATHS$DATA_EMDAT, "floods_country_weekly.csv")
     utils::write.csv(out, out_file, row.names = FALSE)

     message(glue::glue(
          "  Wrote {basename(out_file)} ({nrow(out)} rows, ",
          "{length(unique(out$iso_code))} countries, ",
          "{format(min(out$date_start))} to {format(max(out$date_stop))})"
     ))
     message(glue::glue(
          "  Active flood-weeks: {sum(out$emdat_flood_active)} ",
          "({round(100 * mean(out$emdat_flood_active), 2)}% of cells)"
     ))

     invisible(out_file)
}
