#' Process EM-DAT Flood and Tropical-Cyclone Events Into Country-Week Panels
#'
#' Reads the most recent EM-DAT public-extract xlsx file in
#' \code{PATHS$DATA_EMDAT_RAW}, filters to (a) flood events and (b)
#' tropical-cyclone / storm-surge events in MOSAIC AFRO countries, expands
#' each event across the ISO-8601 weeks it spans, and writes two complete
#' country-week panels of hazard-occurrence covariates:
#' \code{PATHS$DATA_EMDAT/floods_country_weekly.csv} and
#' \code{PATHS$DATA_EMDAT/cyclones_country_weekly.csv}.
#'
#' The flood label is unchanged (\code{Disaster Type == "Flood"}). The
#' cyclone label is a SEPARATE series built from \code{Disaster Type ==
#' "Storm"} restricted to \code{Disaster Subtype \%in\% c("Tropical
#' cyclone", "Storm surge")} -- the crisply-dated, water-producing storm
#' events (49 events / ~74 active weeks in the 2026-05 extract). Storm
#' (General), Severe weather, Lightning/Thunderstorms, Tornado, Hail, and
#' Blizzard/Winter storm are deliberately EXCLUDED: they are not reliably
#' water-producing and would dilute the cyclone signal. Tropical cyclones
#' were previously silently dropped by the flood-only filter, neutering the
#' downstream flood GAM's wind smooth; the separate cyclone series feeds a
#' dedicated wind/coastal GAM (\code{\link{impute_cyclone_probability}}).
#'
#' @param PATHS A list of paths generated by \code{get_paths()}. Must include:
#' \itemize{
#'   \item \strong{DATA_EMDAT_RAW}: Path to \code{MOSAIC-data/raw/EMDAT}.
#'   \item \strong{DATA_EMDAT}: Path to the processed output directory
#'     (\code{MOSAIC-data/processed/EMDAT/weekly}).
#' }
#'
#' @return Invisibly returns a named character vector with the paths to the
#'   two written CSVs (\code{flood} and \code{cyclone}). Each CSV contains
#'   one row per (iso_code, year, week) for every ISO-week between
#'   \code{date_start} (default 2000-01-03) and the latest week covered by
#'   any event of that hazard in the raw extract, restricted to
#'   \code{iso_codes_mosaic}. Flood columns:
#' \describe{
#'   \item{iso_code}{ISO3 country code.}
#'   \item{year}{ISO-8601 year of the week.}
#'   \item{week}{ISO-8601 week number (1-53).}
#'   \item{date_start}{Monday of the ISO-week.}
#'   \item{date_stop}{Sunday of the ISO-week.}
#'   \item{emdat_flood_active}{1 if any flood event overlaps the week, else 0.}
#'   \item{emdat_flood_new}{Number of flood events that start in this week.}
#'   \item{emdat_flood_affected}{\code{log1p} of summed \code{Total Affected}
#'     across overlapping events (NAs treated as 0).}
#'   \item{emdat_flood_deaths}{\code{log1p} of summed \code{Total Deaths}
#'     across overlapping events (NAs treated as 0).}
#' }
#' The cyclone CSV mirrors this schema with \code{emdat_cyclone_active},
#' \code{emdat_cyclone_new}, \code{emdat_cyclone_affected}, and
#' \code{emdat_cyclone_deaths}.
#'
#' @details
#' EM-DAT records carry frequent missing day-of-month and occasional missing
#' end-month values. Imputation rules:
#' \itemize{
#'   \item Missing \code{Start Day} or \code{End Day} -> 15.
#'   \item Missing \code{End Month} -> \code{Start Month}.
#'   \item Missing \code{End Year} -> \code{Start Year}.
#'   \item If the resulting \code{end_date} is earlier than \code{start_date}
#'     (data-entry artifact), it is reset to \code{start_date}.
#' }
#'
#' Each event is expanded to the unique set of ISO-8601 (year, week) pairs
#' touched by the daily date range \code{start_date:end_date}. The panel
#' grid is the full Cartesian product of \code{iso_codes_mosaic} and all
#' ISO-weeks from \code{date_start} through the latest event end-week; cells
#' with no flood activity carry zeros, so a downstream left-join against
#' the suitability table does not need to impute missingness.
#'
#' EM-DAT only records events meeting CRED's inclusion thresholds (>=10
#' deaths, >=100 affected, or formal emergency declaration), so this
#' covariate captures major flood occurrences rather than continuous flood
#' intensity. The richer continuous signal lives in the OpenMeteo
#' precipitation/anomaly covariates.
#'
#' @importFrom readxl read_excel
#' @importFrom utils write.csv read.csv
#' @importFrom glue glue
#' @importFrom lubridate floor_date ceiling_date
#' @export
process_EMDAT_data <- function(PATHS) {

     message("Processing EM-DAT flood events into a country-week panel...")

     if (is.null(PATHS$DATA_EMDAT_RAW) || is.null(PATHS$DATA_EMDAT)) {
          stop("PATHS must include DATA_EMDAT_RAW and DATA_EMDAT (regenerate via get_paths()).")
     }
     if (!dir.exists(PATHS$DATA_EMDAT_RAW)) {
          stop("Raw EM-DAT directory not found: ", PATHS$DATA_EMDAT_RAW)
     }

     # Locate the newest public extract. Two shapes are accepted and mixed
     # freely in the same directory:
     #   *.xlsx -- a manual portal export (sheet "EM-DAT Data")
     #   *.csv  -- an API pull written by download_EMDAT_data()
     candidates <- list.files(
          PATHS$DATA_EMDAT_RAW,
          pattern = "^public_emdat_.*\\.(xlsx|csv)$",
          full.names = TRUE,
          recursive = FALSE,
          ignore.case = TRUE
     )
     if (length(candidates) == 0) {
          stop("No 'public_emdat_*.xlsx' or 'public_emdat_*.csv' files found in: ",
               PATHS$DATA_EMDAT_RAW,
               "\n  Fetch one with download_EMDAT_data(PATHS) (needs EMDAT_API_KEY),",
               "\n  or download a portal extract manually -- see raw/EMDAT/README.md.")
     }
     # Prefer the filename-encoded request date; fall back to mtime
     # NB regmatches() returns ONLY matching elements, so building the key
     # from it directly yields a vector shorter than `candidates` and the
     # resulting index is a wrong-length permutation -- a dateless file could
     # win. Match on basename (not the full path, which may contain a date)
     # and keep the vector aligned.
     src_file <- .rank_raw_candidates(candidates)[1L]
     message("  Reading: ", basename(src_file))

     d_all <- if (grepl("\\.csv$", src_file, ignore.case = TRUE)) {
          utils::read.csv(src_file, stringsAsFactors = FALSE, check.names = FALSE)
     } else {
          readxl::read_excel(src_file, sheet = "EM-DAT Data")
     }
     message(glue::glue("  {nrow(d_all)} events in extract"))

     # Fail loudly on a schema mismatch rather than silently emitting an empty
     # panel: a renamed or missing column would otherwise sail through the
     # filters below and produce a valid-looking all-zero series.
     .emdat_required <- c("ISO", "Disaster Type", "Disaster Subtype",
                          "Start Year", "Start Month", "Start Day",
                          "End Year", "End Month", "End Day",
                          "Total Affected", "Total Deaths")
     .emdat_missing <- setdiff(.emdat_required, names(d_all))
     if (length(.emdat_missing)) {
          stop("EM-DAT extract is missing required column(s): ",
               paste(.emdat_missing, collapse = ", "),
               "\n  Source: ", basename(src_file),
               "\n  If this came from download_EMDAT_data(), the API field mapping",
               "\n  may need updating -- see ?download_EMDAT_data.", call. = FALSE)
     }

     # MOSAIC AFRO country filter (package data)
     iso_keep <- get("iso_codes_mosaic", envir = asNamespace("MOSAIC"))

     # Restrict to MOSAIC AFRO ISOs with a valid start year once, then split
     # the hazard-specific filters from the shared frame so the flood and
     # cyclone series stay reproducibly aligned on the same panel grid.
     d_afro <- d_all[!is.na(d_all$ISO) & d_all$ISO %in% iso_keep &
                     !is.na(d_all$`Start Year`), , drop = FALSE]

     dir.create(PATHS$DATA_EMDAT, recursive = TRUE, showWarnings = FALSE)

     # ----- Flood series (UNCHANGED label: Disaster Type == "Flood") -----
     flood_events <- d_afro[!is.na(d_afro$`Disaster Type`) &
                            d_afro$`Disaster Type` == "Flood", , drop = FALSE]
     message(glue::glue("  {nrow(flood_events)} flood events in MOSAIC AFRO countries"))
     if (nrow(flood_events) == 0) {
          stop("No flood events remain after filtering to MOSAIC AFRO countries.")
     }

     # ----- Cyclone series (SEPARATE label: Storm + Tropical cyclone/Surge) -----
     cyclone_events <- d_afro[!is.na(d_afro$`Disaster Type`) &
                              d_afro$`Disaster Type` == "Storm" &
                              !is.na(d_afro$`Disaster Subtype`) &
                              d_afro$`Disaster Subtype` %in%
                                   c("Tropical cyclone", "Storm surge"), , drop = FALSE]
     message(glue::glue(
          "  {nrow(cyclone_events)} tropical-cyclone/storm-surge events in MOSAIC AFRO countries ",
          "(Storm-General/Severe/Lightning/Tornado/Hail excluded)"))

     # Shared panel end: the later of the two hazards' latest event, so both
     # panels share an identical ISO-week grid (required for a clean join in
     # compile_suitability_data).
     panel_end <- max(.emdat_event_dates(flood_events)$end_date,
                      .emdat_event_dates(cyclone_events)$end_date)

     out_flood <- .emdat_build_hazard_panel(flood_events, iso_keep, panel_end,
                                            prefix = "emdat_flood")
     flood_file <- file.path(PATHS$DATA_EMDAT, "floods_country_weekly.csv")
     utils::write.csv(out_flood, flood_file, row.names = FALSE)
     message(glue::glue(
          "  Wrote {basename(flood_file)} ({nrow(out_flood)} rows, ",
          "{length(unique(out_flood$iso_code))} countries, ",
          "{format(min(out_flood$date_start))} to {format(max(out_flood$date_stop))})"
     ))
     message(glue::glue(
          "  Active flood-weeks: {sum(out_flood$emdat_flood_active)} ",
          "({round(100 * mean(out_flood$emdat_flood_active), 2)}% of cells)"
     ))

     out_cyclone <- .emdat_build_hazard_panel(cyclone_events, iso_keep, panel_end,
                                              prefix = "emdat_cyclone")
     cyclone_file <- file.path(PATHS$DATA_EMDAT, "cyclones_country_weekly.csv")
     utils::write.csv(out_cyclone, cyclone_file, row.names = FALSE)
     message(glue::glue(
          "  Wrote {basename(cyclone_file)} ({nrow(out_cyclone)} rows, ",
          "{length(unique(out_cyclone$iso_code))} countries, ",
          "{format(min(out_cyclone$date_start))} to {format(max(out_cyclone$date_stop))})"
     ))
     message(glue::glue(
          "  Active cyclone-weeks: {sum(out_cyclone$emdat_cyclone_active)} ",
          "({round(100 * mean(out_cyclone$emdat_cyclone_active), 3)}% of cells)"
     ))

     invisible(c(flood = flood_file, cyclone = cyclone_file))
}


# Internal: construct imputed start/end Date vectors from an EM-DAT event
# frame, applying the same day/month/year imputation rules as the flood
# processor. Returns a data.frame with iso_code, start_date, end_date,
# affected, deaths. Used by both the flood and cyclone panels so the two
# series share identical date-construction semantics.
.emdat_event_dates <- function(d) {
     if (nrow(d) == 0) {
          return(data.frame(iso_code = character(0),
                            start_date = as.Date(character(0)),
                            end_date   = as.Date(character(0)),
                            affected = numeric(0), deaths = numeric(0),
                            stringsAsFactors = FALSE))
     }
     start_month <- ifelse(is.na(d$`Start Month`), 1L, as.integer(d$`Start Month`))
     start_day   <- ifelse(is.na(d$`Start Day`),  15L, as.integer(d$`Start Day`))
     end_year    <- ifelse(is.na(d$`End Year`),  as.integer(d$`Start Year`),
                                                  as.integer(d$`End Year`))
     end_month   <- ifelse(is.na(d$`End Month`), start_month, as.integer(d$`End Month`))
     end_day     <- ifelse(is.na(d$`End Day`),   15L, as.integer(d$`End Day`))

     start_date <- as.Date(sprintf("%04d-%02d-%02d",
                                    as.integer(d$`Start Year`), start_month, start_day))
     end_date   <- as.Date(sprintf("%04d-%02d-%02d",
                                    end_year, end_month, end_day))

     # Imputed days can exceed month length; as.Date() returns NA -> fall back
     # to the last day of that month.
     bad_end <- is.na(end_date)
     if (any(bad_end)) {
          first <- as.Date(sprintf("%04d-%02d-01",
                                    end_year[bad_end], end_month[bad_end]))
          end_date[bad_end] <- lubridate::ceiling_date(first, "month") - 1L
     }
     bad_start <- is.na(start_date)
     if (any(bad_start)) {
          first <- as.Date(sprintf("%04d-%02d-01",
                                    as.integer(d$`Start Year`)[bad_start],
                                    start_month[bad_start]))
          start_date[bad_start] <- lubridate::ceiling_date(first, "month") - 1L
     }

     # Reset reversed ranges (data-entry artifacts)
     end_date <- pmax(end_date, start_date)

     data.frame(
          iso_code   = d$ISO,
          start_date = start_date,
          end_date   = end_date,
          affected   = ifelse(is.na(d$`Total Affected`), 0, as.numeric(d$`Total Affected`)),
          deaths     = ifelse(is.na(d$`Total Deaths`),   0, as.numeric(d$`Total Deaths`)),
          stringsAsFactors = FALSE
     )
}


# Internal: expand a hazard event frame into a complete, zero-filled
# (iso_code, year, week) panel over all MOSAIC ISOs from 2000-W01 through
# `panel_end`. `prefix` names the emitted columns (e.g. "emdat_flood",
# "emdat_cyclone"). Identical expansion/aggregation logic for every hazard
# so the flood and cyclone series cannot drift apart.
.emdat_build_hazard_panel <- function(events, iso_keep, panel_end, prefix) {

     events <- .emdat_event_dates(events)

     # ----- Build the ISO-week panel grid -----
     panel_start <- as.Date("2000-01-03")  # Monday of ISO week 2000-W01
     panel_end_monday <- lubridate::floor_date(panel_end, "week", week_start = 1)
     mondays <- seq(panel_start, panel_end_monday, by = "week")

     iso_weeks <- data.frame(
          date_start = mondays,
          date_stop  = mondays + 6L,
          year       = as.integer(format(mondays + 3L, "%G")),
          week       = as.integer(format(mondays + 3L, "%V")),
          stringsAsFactors = FALSE
     )

     panel <- expand.grid(
          iso_code = sort(iso_keep),
          row_id   = seq_len(nrow(iso_weeks)),
          KEEP.OUT.ATTRS = FALSE,
          stringsAsFactors = FALSE
     )
     panel$year       <- iso_weeks$year[panel$row_id]
     panel$week       <- iso_weeks$week[panel$row_id]
     panel$date_start <- iso_weeks$date_start[panel$row_id]
     panel$date_stop  <- iso_weeks$date_stop[panel$row_id]
     panel$row_id     <- NULL

     col_active   <- paste0(prefix, "_active")
     col_new      <- paste0(prefix, "_new")
     col_affected <- paste0(prefix, "_affected")
     col_deaths   <- paste0(prefix, "_deaths")

     if (nrow(events) > 0) {
          # ----- Expand each event into the ISO-weeks it touches -----
          expand_event <- function(i) {
               days <- seq(events$start_date[i], events$end_date[i], by = "day")
               yw <- unique(data.frame(
                    iso_code = events$iso_code[i],
                    year     = as.integer(format(days, "%G")),
                    week     = as.integer(format(days, "%V")),
                    stringsAsFactors = FALSE
               ))
               yw$start_year  <- as.integer(format(events$start_date[i], "%G"))
               yw$start_week  <- as.integer(format(events$start_date[i], "%V"))
               yw$is_start    <- as.integer(yw$year == yw$start_year & yw$week == yw$start_week)
               yw$affected    <- events$affected[i]
               yw$deaths      <- events$deaths[i]
               yw$start_year  <- NULL
               yw$start_week  <- NULL
               yw
          }
          touched <- do.call(rbind, lapply(seq_len(nrow(events)), expand_event))

          # Aggregate per (iso_code, year, week)
          key <- paste(touched$iso_code, touched$year, touched$week, sep = "|")
          agg <- data.frame(
               iso_code = tapply(touched$iso_code, key, function(x) x[1]),
               year     = tapply(touched$year,     key, function(x) x[1]),
               week     = tapply(touched$week,     key, function(x) x[1]),
               active   = 1L,
               new      = as.integer(tapply(touched$is_start, key, sum)),
               affected = log1p(tapply(touched$affected, key, sum)),
               deaths   = log1p(tapply(touched$deaths,   key, sum)),
               stringsAsFactors = FALSE
          )
          row.names(agg) <- NULL
          names(agg)[names(agg) == "active"]   <- col_active
          names(agg)[names(agg) == "new"]      <- col_new
          names(agg)[names(agg) == "affected"] <- col_affected
          names(agg)[names(agg) == "deaths"]   <- col_deaths

          out <- merge(panel, agg, by = c("iso_code", "year", "week"),
                       all.x = TRUE, sort = FALSE)
     } else {
          out <- panel
          out[[col_active]]   <- NA_integer_
          out[[col_new]]      <- NA_integer_
          out[[col_affected]] <- NA_real_
          out[[col_deaths]]   <- NA_real_
     }

     out[[col_active]]   <- ifelse(is.na(out[[col_active]]),   0L, out[[col_active]])
     out[[col_new]]      <- ifelse(is.na(out[[col_new]]),      0L, out[[col_new]])
     out[[col_affected]] <- ifelse(is.na(out[[col_affected]]), 0,  out[[col_affected]])
     out[[col_deaths]]   <- ifelse(is.na(out[[col_deaths]]),   0,  out[[col_deaths]])

     out[order(out$iso_code, out$date_start),
         c("iso_code", "year", "week", "date_start", "date_stop",
           col_active, col_new, col_affected, col_deaths)]
}
