#' Process Country Similarity Data for African Countries
#'
#' This function processes a global country similarity distance matrix and extracts the subset of African countries, normalizes country names, and matches them to ISO3 codes. The resulting matrix for African countries is saved as a CSV file.
#'
#' @param PATHS A list containing the paths where raw and processed data are stored. Typically generated by the `get_paths()` function, and should include:
#' \itemize{
#'   \item \strong{DATA_RAW}: Path to the directory containing the raw similarity matrix data.
#'   \item \strong{DATA_SIMILARITY_MATRIX}: Path to the directory where the processed African similarity matrix will be saved.
#' }
#'
#' @details
#' This function performs the following steps:
#' \enumerate{
#'   \item Loads a global similarity distance matrix from a CSV file.
#'   \item Normalizes country names to title case and replaces non-standard names like "Ivory Coast" with "Côte d'Ivoire" to match ISO3 country standards.
#'   \item Subsets the matrix to only include African countries, based on ISO3 codes provided by `MOSAIC::iso_codes_africa`.
#'   \item Outputs a CSV file containing the similarity matrix for African countries, with row and column names in ISO3 format.
#' }
#'
#' @return The function saves the processed similarity matrix for African countries in the specified directory.
#'
#' @importFrom stringr str_to_title
#' @importFrom utils read.csv write.csv
#'
#' @examples
#' \dontrun{
#' # Example usage to process the country similarity matrix for African countries
#' PATHS <- get_paths()
#' process_country_similarity_data(PATHS)
#' }
#' @export

process_country_similarity_data <- function(PATHS) {

     # Ensure the directory for processed similarity matrix exists
     if (!dir.exists(PATHS$DATA_SIMILARITY_MATRIX)) dir.create(PATHS$DATA_SIMILARITY_MATRIX, recursive = TRUE)

     # Load the global country similarity matrix
     country_similarity_matrix <- utils::read.csv(file.path(PATHS$DATA_RAW, "similarity_matrix/country-similarity-distance-matrix.csv"), stringsAsFactors = FALSE)

     # Convert to matrix and remove the first column (country names)
     m <- as.matrix(country_similarity_matrix[, -1])
     row.names(m) <- country_similarity_matrix$X

     # Normalize country names to match expected ISO conversion
     country_names_normalized <- stringr::str_to_title(row.names(m))
     country_names_normalized[country_names_normalized == "Cent Afr Rep"] <- "Central African Republic"
     country_names_normalized[country_names_normalized == "Dem Rep Congo"] <- "Democratic Republic of Congo"
     country_names_normalized[country_names_normalized == "Rep Congo"] <- "Congo"
     country_names_normalized[country_names_normalized == "Equat. Guinea"] <- "Equatorial Guinea"
     country_names_normalized[country_names_normalized == "Ivory Coast"] <- "Côte d’Ivoire"
     country_names_normalized[country_names_normalized == "Guinea Bissau"] <- "Guinea-Bissau"

     # Subset the matrix for African countries
     country_names_africa <- MOSAIC::convert_iso_to_country(MOSAIC::iso_codes_africa)

     sel <- country_names_normalized %in% country_names_africa
     m_africa <- m[sel, sel]

     # Convert country names to ISO3 codes
     iso_codes_africa_matrix <- MOSAIC::convert_country_to_iso(country_names_normalized[sel])
     row.names(m_africa) <- iso_codes_africa_matrix
     colnames(m_africa) <- iso_codes_africa_matrix

     # Check for missing African countries in the similarity matrix
     missing <- MOSAIC::iso_codes_africa[!(MOSAIC::iso_codes_africa %in% iso_codes_africa_matrix)]
     if (length(missing) > 0) {
          message("ISO3 codes missing from similarity matrix of African countries:")
          message(paste(missing, collapse = " "))
          message(paste(MOSAIC::convert_iso_to_country(missing), collapse = " "))
     }

     # Sort the matrix by ISO3 codes
     m_africa <- m_africa[order(row.names(m_africa), decreasing = FALSE), order(colnames(m_africa), decreasing = FALSE)]

     # Save the processed similarity matrix for African countries
     path <- file.path(PATHS$DATA_SIMILARITY_MATRIX, "similarity_matrix_africa.csv")
     utils::write.table(m_africa, file = path, row.names = TRUE, col.names = NA)
     message("Similarity matrix for African countries saved here:")
     message(path)

}
