#' Process Cholera Data to Calculate Aggregated Case Fatality Ratios and Fit Beta Distributions
#'
#' This function processes WHO annual cholera data, aggregates cases and deaths for each country from 2014 through the last complete year in the data, calculates the aggregated Case Fatality Ratio (CFR), and fits Beta distributions for each country. Countries with fewer cases than `min_obs` will have their CFR set to the value of the AFRO Region.
#'
#' @details
#' A calendar year still in progress when its dashboard snapshot was taken is dropped before aggregating (its deaths lag its cases), using the same rule as \code{\link{est_CFR_hierarchical}}; the end year of the output (and of its filename) is the last year left after that filter. A country whose only data fall in an in-progress year therefore gets the AFRO Region CFR. Any existing \code{case_fatality_ratio_2014_<year>.csv} with a later end year (one built while that year was still counted) is deleted from both output directories, so \code{\link{plot_CFR_by_country}}, which reads the highest end year, picks up the new file. Country-years with a missing case or death count are left out of both totals, so each CFR is computed over the same years for its numerator and denominator. Rows are aggregated by ISO code, and each country is labelled with its most frequent spelling in the data (the WHO file spells some countries more than one way).
#'
#' @param PATHS A list containing the paths where the cholera data is located. Typically generated by the `get_paths()` function and should include:
#' \itemize{
#'   \item \strong{DATA_WHO_ANNUAL}: Path to the directory containing processed WHO annual cholera data.
#'   \item \strong{DOCS_TABLES}: Path to the directory where processed CFR data will be saved.
#' }
#' @param min_obs An integer specifying the minimum number of cases required for a country to have its own CFR. Countries with fewer cases than this threshold will have their CFR set to the value of the AFRO Region.
#'
#' @return Invisibly, a data frame with aggregated CFR, confidence intervals, and Beta distribution parameters for each country (also written to \code{case_fatality_ratio_2014_<end year>.csv} in \code{DOCS_TABLES} and \code{DATA_WHO_ANNUAL}).
#'
#' @importFrom utils read.csv write.csv
#' @importFrom stats binom.test aggregate optim qbeta qlogis
#' @examples
#' \dontrun{
#' PATHS <- get_paths()
#' cholera_data <- process_CFR_data(PATHS, min_obs = 100)
#' }
#' @export

process_CFR_data <- function(PATHS, min_obs) {
     # Load cholera data
     cholera_data <- utils::read.csv(file.path(PATHS$DATA_WHO_ANNUAL, "who_afro_annual.csv"), stringsAsFactors = FALSE)

     # Drop calendar years still in progress at their dashboard snapshot (deaths
     # lag cases), as est_CFR_hierarchical() does, then keep 2014 onward up to the
     # last remaining year.
     if ("source" %in% names(cholera_data))
          cholera_data <- cholera_data[!.cfr_in_progress(cholera_data), , drop = FALSE]
     max_year <- max(cholera_data$year, na.rm = TRUE)
     cholera_data <- cholera_data[cholera_data$year >= 2014 & cholera_data$year <= max_year, ]
     year_range <- sprintf("2014-%d", max_year)

     # Country-years with both counts reported; a year with cases but no deaths
     # would otherwise bias the CFR low.
     cholera_data <- cholera_data[!is.na(cholera_data$iso_code) & nzchar(cholera_data$iso_code) &
                                  is.finite(cholera_data$cases_total) &
                                  is.finite(cholera_data$deaths_total), ]

     # Aggregate by ISO code only: the WHO file spells some countries more than
     # one way (CIV), which would otherwise split a country across two rows.
     aggregated_data <- stats::aggregate(cbind(cases_total, deaths_total) ~ iso_code,
                                         data = cholera_data, FUN = sum)
     aggregated_data$country <- vapply(aggregated_data$iso_code, function(z) {
          nm <- cholera_data$country[cholera_data$iso_code == z]
          nm <- nm[!is.na(nm) & nzchar(nm)]
          if (!length(nm)) return(z)
          tab <- table(nm)
          sort(names(tab)[tab == max(tab)])[1]
     }, character(1), USE.NAMES = FALSE)
     aggregated_data <- aggregated_data[order(aggregated_data$country),
                                        c("country", "iso_code", "cases_total", "deaths_total")]
     rownames(aggregated_data) <- NULL

     # Initialize a list to track countries receiving the AFRO Region CFR (start with countries absent from the data)
     countries_below_min_obs <- MOSAIC::iso_codes_africa[!(MOSAIC::iso_codes_africa %in% cholera_data$iso_code)]

     # Calculate CFR and confidence intervals
     aggregated_data$cfr <- aggregated_data$deaths_total / aggregated_data$cases_total
     aggregated_data$cfr_lo <- aggregated_data$cfr_hi <- aggregated_data$shape1 <- aggregated_data$shape2 <- NA

     # Beta fitted to the 95% binomial CI (2.5% / 97.5% quantiles) and the point CFR (median)
     beta_quantiles <- c(0.025, 0.5, 0.975)

     # Loop through each country and calculate the confidence intervals and Beta distribution parameters
     for (i in seq_len(nrow(aggregated_data))) {
          if (aggregated_data$cases_total[i] > 0) {
               # Confidence intervals for CFR
               conf_int <- stats::binom.test(x = aggregated_data$deaths_total[i], n = aggregated_data$cases_total[i])$conf.int
               aggregated_data$cfr_lo[i] <- conf_int[1]
               aggregated_data$cfr_hi[i] <- conf_int[2]

               # Beta distribution parameters
               prm <- .cfr_beta_from_ci(deaths = aggregated_data$deaths_total[i],
                                        cases = aggregated_data$cases_total[i],
                                        quantiles = beta_quantiles,
                                        probs = c(aggregated_data$cfr_lo[i], aggregated_data$cfr[i], aggregated_data$cfr_hi[i]))
               aggregated_data$shape1[i] <- prm$shape1
               aggregated_data$shape2[i] <- prm$shape2
          }
     }

     # Get AFRO Region values after calculating CI and CFR
     afro_cfr <- aggregated_data$cfr[aggregated_data$iso_code == "AFRO"]
     afro_lo <- aggregated_data$cfr_lo[aggregated_data$iso_code == "AFRO"]
     afro_hi <- aggregated_data$cfr_hi[aggregated_data$iso_code == "AFRO"]

     # Check if AFRO Region values are missing
     if (length(afro_cfr) != 1L || is.na(afro_cfr) || is.na(afro_lo) || is.na(afro_hi)) {
          stop("AFRO Region values for CFR are missing. Cannot assign AFRO Region values to other countries.")
     }

     # The AFRO Beta, fitted once and used for every country given the AFRO CFR
     afro_i <- which(aggregated_data$iso_code == "AFRO")
     afro_prm <- list(shape1 = aggregated_data$shape1[afro_i], shape2 = aggregated_data$shape2[afro_i])

     # Apply AFRO Region CFR to countries with fewer than min_obs cases
     for (i in seq_len(nrow(aggregated_data))) {
          if (aggregated_data$iso_code[i] != "AFRO" && aggregated_data$cases_total[i] < min_obs) {
               countries_below_min_obs <- c(countries_below_min_obs, aggregated_data$iso_code[i])
          }
     }

     # Ensure all countries in countries_below_min_obs are assigned AFRO CFR (and add a new row if necessary)
     for (iso_code in countries_below_min_obs) {
          idx <- which(aggregated_data$iso_code == iso_code)
          if (length(idx) == 0) {
               # If the ISO code is not already in aggregated_data, add a new row
               new_row <- data.frame(
                    country = convert_iso_to_country(iso_code),
                    iso_code = iso_code,
                    cases_total = NA,
                    deaths_total = NA,
                    cfr = afro_cfr,
                    cfr_lo = afro_lo,
                    cfr_hi = afro_hi,
                    shape2 = afro_prm$shape2,
                    shape1 = afro_prm$shape1,
                    stringsAsFactors = FALSE
               )
               aggregated_data <- rbind(aggregated_data, new_row[, names(aggregated_data)])
          } else {
               # If ISO code exists, set it to AFRO Region values
               aggregated_data$cfr[idx] <- afro_cfr
               aggregated_data$cfr_lo[idx] <- afro_lo
               aggregated_data$cfr_hi[idx] <- afro_hi
               aggregated_data$shape1[idx] <- afro_prm$shape1
               aggregated_data$shape2[idx] <- afro_prm$shape2
          }
     }

     # Save the processed data to both DOCS_TABLES and DATA_WHO_ANNUAL with a
     # year-flexible filename that reflects the actual coverage of the input.
     out_basename <- sprintf("case_fatality_ratio_2014_%d.csv", max_year)
     file_out_tables <- file.path(PATHS$DOCS_TABLES, out_basename)
     file_out_who    <- file.path(PATHS$DATA_WHO_ANNUAL, out_basename)

     utils::write.csv(aggregated_data, file = file_out_tables, row.names = FALSE)
     utils::write.csv(aggregated_data, file = file_out_who, row.names = FALSE)

     message(paste("Processed CFR data saved to:", file_out_tables))
     message(paste("Processed CFR data saved to:", file_out_who))

     # An artifact whose end year is later than max_year was built with an
     # in-progress year included (before that year was dropped). It would shadow
     # this output, because plot_CFR_by_country() reads the highest end year, so
     # it is removed from both output directories.
     for (dir_out in unique(c(PATHS$DOCS_TABLES, PATHS$DATA_WHO_ANNUAL))) {
          old_files <- list.files(dir_out, pattern = "^case_fatality_ratio_2014_[0-9]{4}\\.csv$")
          old_end <- as.integer(sub("^case_fatality_ratio_2014_([0-9]{4})\\.csv$", "\\1", old_files))
          stale <- file.path(dir_out, old_files[old_end > max_year])
          if (length(stale)) {
               file.remove(stale)
               message("Removed superseded CFR artifact(s) that included an in-progress year: ",
                       paste(stale, collapse = ", "))
          }
     }

     # Print a message indicating which countries received the AFRO Region values
     if (length(countries_below_min_obs) > 0) {
          message("The following countries had fewer than ", min_obs, " cases (or had no data from ",
                  year_range, ") and were assigned the AFRO Region CFR (by ISO code):")
          message(paste(countries_below_min_obs, collapse = ", "))
     } else {
          message("All countries had sufficient cases to retain their own CFR.")
     }

     invisible(aggregated_data)
}

# Beta(shape1, shape2) whose `quantiles` match `probs` (the binomial CI bounds and
# the point CFR), fitted by least squares on the logit scale over log-shapes.
# The start is the Jeffreys posterior Beta(d + 1/2, n - d + 1/2), whose 2.5%/97.5%
# quantiles already sit close to the Clopper-Pearson bounds (Brown, Cai &
# DasGupta 2001, Stat Sci 16:101-133), so the optimiser converges from a point
# near the answer. propvacc::get_beta_params() starts from Beta(1, 1) and, for
# the tight CIs of a ~2% CFR over thousands of cases, stops at a degenerate
# Beta(~0.009, ~1.9) with mean ~0.005 whatever quantiles it is given.
# With 0 deaths (or deaths == cases) no Beta has the point CFR as its median,
# so the Jeffreys posterior is returned as is.
.cfr_beta_from_ci <- function(deaths, cases, quantiles, probs) {
     a0 <- deaths + 0.5
     b0 <- cases - deaths + 0.5
     if (deaths <= 0 || deaths >= cases || any(!is.finite(probs)) ||
         any(probs <= 0 | probs >= 1)) {
          return(list(shape1 = a0, shape2 = b0))
     }
     target <- stats::qlogis(probs)
     obj <- function(lp) {
          q <- stats::qbeta(quantiles, exp(lp[1]), exp(lp[2]))
          if (any(q <= 0 | q >= 1)) return(1e10)
          sum((stats::qlogis(q) - target)^2)
     }
     fit <- stats::optim(log(c(a0, b0)), obj, method = "Nelder-Mead",
                         control = list(reltol = 1e-12, maxit = 5000))
     if (fit$convergence != 0L || !is.finite(fit$value)) {
          warning("Beta fit to the CFR interval did not converge (", deaths, " deaths in ",
                  cases, " cases); using the Jeffreys posterior.", call. = FALSE)
          return(list(shape1 = a0, shape2 = b0))
     }
     list(shape1 = exp(fit$par[1]), shape2 = exp(fit$par[2]))
}
