#' Process Cholera Data to Calculate Aggregated Case Fatality Ratios and Fit Beta Distributions (2014-2024)
#'
#' This function processes cholera data, aggregates cases and deaths for each country over the period 2014-2024, calculates the aggregated Case Fatality Ratio (CFR), and fits Beta distributions for each country. Countries with fewer cases than `min_obs` will have their CFR set to the value of the AFRO Region.
#'
#' @param PATHS A list containing the paths where the cholera data is located. Typically generated by the `get_paths()` function and should include:
#' \itemize{
#'   \item \strong{DATA_WHO_ANNUAL}: Path to the directory containing processed WHO annual cholera data.
#'   \item \strong{DOCS_TABLES}: Path to the directory where processed CFR data will be saved.
#' }
#' @param min_obs An integer specifying the minimum number of cases required for a country to have its own CFR. Countries with fewer cases than this threshold will have their CFR set to the value of the AFRO Region.
#'
#' @return A data frame with aggregated CFR, confidence intervals, and Beta distribution parameters for each country.
#'
#' @importFrom utils read.csv write.csv
#' @importFrom stats binom.test
#' @importFrom propvacc get_beta_params
#' @examples
#' \dontrun{
#' PATHS <- get_paths()
#' cholera_data <- process_CFR_data(PATHS, min_obs = 100)
#' }
#' @export

process_CFR_data <- function(PATHS, min_obs) {
     # Load cholera data
     cholera_data <- utils::read.csv(file.path(PATHS$DATA_WHO_ANNUAL, "who_afro_annual_1949_2024.csv"), stringsAsFactors = FALSE)

     # Filter data for the period 2014-2024
     cholera_data <- cholera_data[cholera_data$year >= 2014 & cholera_data$year <= 2024,]

     # Aggregate cases and deaths by country
     aggregated_data <- aggregate(cbind(cases_total, deaths_total) ~ country + iso_code, data = cholera_data, sum, na.rm = TRUE)

     # Initialize a list to track countries receiving the AFRO Region CFR (start with countries not in 2014-2024 data)
     countries_below_min_obs <- MOSAIC::iso_codes_africa[!(MOSAIC::iso_codes_africa %in% cholera_data$iso_code)]
     countries_below_min_obs <- c(countries_below_min_obs, aggregated_data$iso_code[is.na(aggregated_data$cases_total)])

     # Calculate CFR and confidence intervals
     aggregated_data$cfr <- aggregated_data$deaths_total / aggregated_data$cases_total
     aggregated_data$cfr_lo <- aggregated_data$cfr_hi <- aggregated_data$shape1 <- aggregated_data$shape2 <- NA

     # Loop through each country and calculate the confidence intervals and Beta distribution parameters
     for (i in 1:nrow(aggregated_data)) {
          if (!is.na(aggregated_data$cases_total[i]) & !is.na(aggregated_data$deaths_total[i])) {
               if (aggregated_data$cases_total[i] > 0) {
                    # Confidence intervals for CFR
                    conf_int <- stats::binom.test(x = aggregated_data$deaths_total[i], n = aggregated_data$cases_total[i])$conf.int
                    aggregated_data$cfr_lo[i] <- conf_int[1]
                    aggregated_data$cfr_hi[i] <- conf_int[2]

                    # Beta distribution parameters
                    prm <- propvacc::get_beta_params(quantiles = c(0.0275, 0.5, 0.975),
                                                     probs = c(aggregated_data$cfr_lo[i], aggregated_data$cfr[i], aggregated_data$cfr_hi[i]))
                    aggregated_data$shape1[i] <- prm$shape1
                    aggregated_data$shape2[i] <- prm$shape2
               }
          }
     }

     # Get AFRO Region values after calculating CI and CFR
     afro_cfr <- aggregated_data$cfr[aggregated_data$iso_code == "AFRO"]
     afro_lo <- aggregated_data$cfr_lo[aggregated_data$iso_code == "AFRO"]
     afro_hi <- aggregated_data$cfr_hi[aggregated_data$iso_code == "AFRO"]

     # Check if AFRO Region values are missing
     if (is.na(afro_cfr) || is.na(afro_lo) || is.na(afro_hi)) {
          stop("AFRO Region values for CFR are missing. Cannot assign AFRO Region values to other countries.")
     }

     # Apply AFRO Region CFR to countries with fewer than min_obs cases or missing data
     for (i in 1:nrow(aggregated_data)) {
          if (!is.na(aggregated_data$cases_total[i]) && aggregated_data$cases_total[i] < min_obs) {
               # Set to AFRO Region values if cases_total < min_obs
               aggregated_data$cfr[i] <- afro_cfr
               aggregated_data$cfr_lo[i] <- afro_lo
               aggregated_data$cfr_hi[i] <- afro_hi

               # Assign Beta distribution parameters
               prm <- propvacc::get_beta_params(quantiles = c(0.0275, 0.5, 0.975), probs = c(afro_lo, afro_cfr, afro_hi))
               aggregated_data$shape1[i] <- prm$shape1
               aggregated_data$shape2[i] <- prm$shape2

               # Track the country that received the AFRO Region values
               countries_below_min_obs <- c(countries_below_min_obs, aggregated_data$iso_code[i])
          }
     }

     # Ensure all countries in countries_below_min_obs are assigned AFRO CFR (and add a new row if necessary)
     for (iso_code in countries_below_min_obs) {
          idx <- which(aggregated_data$iso_code == iso_code)
          if (length(idx) == 0) {
               # If the ISO code is not already in aggregated_data, add a new row
               new_row <- data.frame(
                    country = convert_iso_to_country(iso_code),
                    iso_code = iso_code,
                    cases_total = NA,
                    deaths_total = NA,
                    cfr = afro_cfr,
                    cfr_lo = afro_lo,
                    cfr_hi = afro_hi,
                    shape1 = prm$shape1,
                    shape2 = prm$shape2,
                    stringsAsFactors = FALSE
               )
               aggregated_data <- rbind(aggregated_data, new_row)
          } else {
               # If ISO code exists, ensure it's set to AFRO Region values
               aggregated_data$cfr[idx] <- afro_cfr
               aggregated_data$cfr_lo[idx] <- afro_lo
               aggregated_data$cfr_hi[idx] <- afro_hi
               aggregated_data$shape1[idx] <- prm$shape1
               aggregated_data$shape2[idx] <- prm$shape2
          }
     }

     # Save the processed data to both DOCS_TABLES and DATA_WHO_ANNUAL
     file_out_tables <- file.path(PATHS$DOCS_TABLES, "case_fatality_ratio_2014_2024.csv")
     file_out_who <- file.path(PATHS$DATA_WHO_ANNUAL, "case_fatality_ratio_2014_2024.csv")

     utils::write.csv(aggregated_data, file = file_out_tables, row.names = FALSE)
     utils::write.csv(aggregated_data, file = file_out_who, row.names = FALSE)

     message(paste("Processed CFR data saved to:", file_out_tables))
     message(paste("Processed CFR data saved to:", file_out_who))

     # Print a message indicating which countries received the AFRO Region values
     if (length(countries_below_min_obs) > 0) {
          message("The following countries had fewer than ", min_obs, " cases (or had no data from 2014-2024) and were assigned the AFRO Region CFR (by ISO code):")
          message(paste(countries_below_min_obs, collapse = ", "))
     } else {
          message("All countries had sufficient cases to retain their own CFR.")
     }

}
