#' Process and Aggregate Climate Data for Each Country
#'
#' This function processes the climate data downloaded using the `download_climate_data` function. It creates three aggregated datasets: daily, weekly, and monthly, for each country and saves them as Parquet files with the country ISO code included in the file name.
#'
#' @param PATHS A list containing paths where climate data is stored and processed. Typically generated by the `get_paths()` function and should include:
#' \itemize{
#'   \item \strong{DATA_RAW}: Path to the directory where the raw climate data is stored.
#'   \item \strong{DATA_CLIMATE}: Path to the directory where the processed climate data will be saved.
#' }
#'
#' @return The function does not return a value. It processes the climate data and saves the daily, weekly, and monthly aggregated datasets for each country in Parquet format.
#'
#' @importFrom dplyr group_by summarize mutate select
#' @importFrom lubridate floor_date ymd week month
#' @importFrom arrow write_parquet read_parquet
#' @importFrom glue glue
#'
#' @export

process_climate_data <- function(PATHS) {

     # Ensure output directory exists
     raw_data_dir <- file.path(PATHS$DATA_RAW, "climate")
     message(paste0("Processing climate data located at: ", raw_data_dir))

     if (!dir.exists(raw_data_dir)) {
          stop(glue::glue("Climate data directory not found: {PATHS$DATA_CLIMATE}"))
     }

     # List all climate data files in the raw data directory
     climate_files <- list.files(raw_data_dir, pattern = "\\.parquet$", full.names = TRUE)

     if (length(climate_files) == 0) {
          stop(glue::glue("No climate data files found in {PATHS$DATA_CLIMATE}."))
     }

     # List of available climate variables
     climate_variables <- c(
          "temperature_2m_mean", "temperature_2m_max", "temperature_2m_min",
          "wind_speed_10m_mean", "wind_speed_10m_max", "cloud_cover_mean",
          "shortwave_radiation_sum", "relative_humidity_2m_mean",
          "relative_humidity_2m_max", "relative_humidity_2m_min",
          "dew_point_2m_mean", "dew_point_2m_min", "dew_point_2m_max",
          "precipitation_sum", "pressure_msl_mean", "soil_moisture_0_to_10cm_mean",
          "et0_fao_evapotranspiration_sum"
     )

     # Extract unique ISO codes from the climate file names (last 3 characters before .parquet)
     iso_codes <- unique(sapply(climate_files, function(x) {
          iso_code <- substr(basename(x), nchar(basename(x)) - 10, nchar(basename(x)) - 8)
          return(iso_code)
     }))

     # Initialize a progress bar
     pb <- txtProgressBar(min = 0, max = length(iso_codes), style = 3)

     # Loop through each ISO3 country code and process its data
     for (i in seq_along(iso_codes)) {

          country_iso_code <- iso_codes[i]

          # Select climate files for the current country
          country_climate_files <- climate_files[grepl(country_iso_code, climate_files)]

          if (length(country_climate_files) == 0) {
               message(glue::glue("No climate data found for {country_iso_code}. Skipping."))
               next
          }

          # Initialize an empty list to store data
          country_climate_data_list <- list()

          # Load and combine all climate files for the current country
          for (climate_file in country_climate_files) {

               # Extract the climate variable name from the filename based on the list
               variable_name <- sapply(climate_variables, function(var) {
                    if (grepl(var, basename(climate_file))) return(var)
               })
               variable_name <- unlist(variable_name)[1]  # Take the first matching variable name

               # Load the climate data
               climate_data <- arrow::read_parquet(climate_file)

               # Ensure the 'date' column is of Date type
               if (!inherits(climate_data$date, "Date")) {
                    climate_data$date <- lubridate::ymd(climate_data$date)
               }

               # Add the variable_name column and drop lat/lon
               climate_data <- climate_data %>%
                    dplyr::mutate(variable_name = variable_name) %>%
                    dplyr::select(-latitude, -longitude)

               # Append to the list of data frames
               country_climate_data_list <- append(country_climate_data_list, list(climate_data))
          }

          # Combine all climate data for the country into one data frame
          combined_climate_data <- do.call(rbind, country_climate_data_list)

          # Ensure required columns exist
          if (!("value" %in% names(combined_climate_data))) stop("Missing 'value' column in climate data")

          # Daily aggregation: Keep original daily data
          daily_aggregated <- combined_climate_data

          # Weekly aggregation: Add week as 1:52 and calculate the weekly average
          weekly_aggregated <- combined_climate_data %>%
               dplyr::mutate(week = lubridate::week(date), month = lubridate::month(date)) %>%
               dplyr::group_by(iso_code, variable_name, year, week) %>%
               dplyr::summarize(value = mean(value, na.rm = TRUE),
                                date_start = min(date),
                                date_stop = max(date), .groups = 'drop')

          # Monthly aggregation: Add month as 1:12 and calculate the monthly average
          monthly_aggregated <- combined_climate_data %>%
               dplyr::mutate(month = lubridate::month(date)) %>%
               dplyr::group_by(iso_code, variable_name, year, month) %>%
               dplyr::summarize(value = mean(value, na.rm = TRUE),
                                date_start = min(date),
                                date_stop = max(date), .groups = 'drop')

          # Define output file paths for daily, weekly, and monthly aggregations
          daily_file <- file.path(PATHS$DATA_CLIMATE, glue::glue("climate_data_{country_iso_code}_daily.parquet"))
          weekly_file <- file.path(PATHS$DATA_CLIMATE, glue::glue("climate_data_{country_iso_code}_weekly.parquet"))
          monthly_file <- file.path(PATHS$DATA_CLIMATE, glue::glue("climate_data_{country_iso_code}_monthly.parquet"))

          # Save the aggregated data as Parquet files
          arrow::write_parquet(daily_aggregated, daily_file)
          arrow::write_parquet(weekly_aggregated, weekly_file)
          arrow::write_parquet(monthly_aggregated, monthly_file)

          # Update the progress bar
          setTxtProgressBar(pb, i)
     }

     # Close the progress bar
     close(pb)

     message(glue::glue("Climate data processing complete. Aggregated data saved to {PATHS$DATA_CLIMATE}."))
}
