#' Run Shiny Application for Visualizing WHO Annual Cholera Data in AFRO Countries
#'
#' This function launches a Shiny app that visualizes cholera cases, deaths, and case fatality rate (CFR) for countries in the AFRO region from 1970 to 2024. Users can select a metric (cases, deaths, or CFR) and filter by specific countries.
#'
#' @param PATHS A list containing paths to the processed cholera data file. Typically generated by the `get_paths()` function and should include:
#' \itemize{
#'   \item \strong{DATA_WHO_ANNUAL}: Path to the directory containing the processed cholera data file (e.g., `who_afro_annual_1949_2024.csv`).
#' }
#'
#' @details This function creates a Shiny app that allows users to explore cholera incidence data across AFRO countries from 1970 to 2024. Users can choose between viewing cases, deaths, or CFR and can select specific countries for visualization. The app generates bar plots for cases and deaths, and point plots with error bars for CFR.
#'
#' @importFrom shiny fluidPage sidebarLayout sidebarPanel mainPanel radioButtons checkboxGroupInput plotOutput uiOutput fluidPage
#' @importFrom ggplot2 ggplot geom_bar geom_hline geom_vline geom_errorbar geom_point theme_minimal labs scale_y_sqrt scale_x_discrete theme element_text
#' @importFrom RColorBrewer brewer.pal
#' @importFrom grDevices adjustcolor
#' @importFrom utils read.csv
#'
#' @examples
#' \dontrun{
#' # Define paths for processed data
#' PATHS <- get_paths()
#'
#' # Run the cholera Shiny app
#' run_WHO_annual_data_app(PATHS)
#' }
#'
#' @export
run_WHO_annual_data_app <- function(PATHS) {

     requireNamespace('shiny')
     requireNamespace('ggplot2')
     requireNamespace('RColorBrewer')
     requireNamespace('grDevices')

     # Load cholera data from the processed directory
     cholera_data <- utils::read.csv(file.path(PATHS$DATA_WHO_ANNUAL, "who_afro_annual_1949_2024.csv"), stringsAsFactors = FALSE)

     # Add case fatality rate (CFR) and confidence intervals to the cholera data
     cholera_data$cfr <- with(cholera_data, ifelse(cases_total > 0, deaths_total / cases_total, NA))
     cholera_data$cfr_lo <- with(cholera_data, ifelse(!is.na(cfr), pmax(cfr - 0.05, 0), NA))  # CI lower bound (dummy values for example)
     cholera_data$cfr_hi <- with(cholera_data, ifelse(!is.na(cfr), pmin(cfr + 0.05, 1), NA))  # CI upper bound (dummy values for example)

     # Define country choices
     country_choices <- c("AFRO Region", sort(unique(cholera_data$country[cholera_data$country != "AFRO Region"])))

     # Define UI
     ui <- shiny::fluidPage(
          shiny::titlePanel("Cholera Cases, Deaths, and CFR in AFRO Countries from 1970 to 2024"),
          shiny::sidebarLayout(
               shiny::sidebarPanel(
                    shiny::radioButtons("metric", "Select Metric:",
                                        choices = c("Cases" = "cases_total", "Deaths" = "deaths_total", "CFR" = "cfr"),
                                        selected = "cases_total"),
                    shiny::checkboxGroupInput("selected_countries", "Select Countries:",
                                              choices = c("All", country_choices),
                                              selected = "AFRO Region"),
                    width = 2
               ),
               shiny::mainPanel(
                    shiny::uiOutput("countryPlots"),
                    width = 10
               )
          )
     )

     # Define server
     server <- function(input, output, session) {

          pal <- grDevices::colorRampPalette(RColorBrewer::brewer.pal(9, "Set1"))(48)
          pal <- grDevices::adjustcolor(pal, 5)

          full_years <- as.character(seq(1970, 2024, by = 1))

          shiny::observe({

               if ("All" %in% input$selected_countries) {
                    selected_countries <- country_choices
                    shiny::updateCheckboxGroupInput(session, "selected_countries", selected = c("All", country_choices))
               } else {
                    selected_countries <- input$selected_countries
                    if (length(selected_countries) != length(country_choices)) {
                         shiny::updateCheckboxGroupInput(session, "selected_countries", selected = selected_countries)
                    }
               }

               y_var <- input$metric
               global_y_max <- if (y_var == "cfr") 1 else max(cholera_data[[y_var]], na.rm = TRUE)

               output$countryPlots <- shiny::renderUI({
                    plot_output_list <- lapply(selected_countries, function(country) {
                         plotname <- paste0("plot_", gsub(" ", "_", country))
                         shiny::plotOutput(plotname, height = "300px", width = "100%")
                    })
                    shiny::tagList(plot_output_list)
               })

               lapply(selected_countries, function(country) {
                    output[[paste0("plot_", gsub(" ", "_", country))]] <- shiny::renderPlot({

                         country_data <- cholera_data[cholera_data$country == country, ]
                         country_data$year <- factor(country_data$year, levels = full_years)
                         decade_starts <- which(levels(factor(full_years)) %in% as.character(seq(1970, 2024, by = 10)))
                         country_index <- which(unique(cholera_data$country) == country)
                         fill_color <- ifelse(country == "AFRO Region", "black", pal[country_index])

                         country_data <- country_data[!is.na(country_data[[y_var]]) & country_data[[y_var]] >= 0, ]

                         if (nrow(country_data) > 0) {

                              if (y_var == "cfr") {

                                   # Plot for CFR with points and error bars for confidence intervals
                                   p <- ggplot2::ggplot(country_data, ggplot2::aes(x = year, y = cfr)) +
                                        ggplot2::geom_vline(xintercept = decade_starts, color = "grey80", linewidth = 0.25) +
                                        ggplot2::geom_point(color = fill_color, size = 3) +
                                        ggplot2::geom_errorbar(ggplot2::aes(ymin = cfr_lo, ymax = cfr_hi), color = fill_color, width = 0.25) +
                                        ggplot2::geom_hline(yintercept = 0, color = "black", linewidth = 0.25) +
                                        ggplot2::theme_minimal(base_size = 13.5) +
                                        ggplot2::labs(x = "Year", y = "Case Fatality Rate (CFR)", title = country) +
                                        ggplot2::scale_y_continuous(labels = scales::percent, limits = c(0, global_y_max), expand = c(0.05, 0)) +
                                        ggplot2::scale_x_discrete(drop = FALSE) +
                                        ggplot2::theme(
                                             plot.title = ggplot2::element_text(size = 14, color = 'black', hjust = 0.5, face = "bold"),
                                             axis.text.x = ggplot2::element_text(size = 11, color = 'black', angle = 90, hjust = 1, vjust = 0.5),
                                             axis.text.y = ggplot2::element_text(size = 12, color = 'black'),
                                             axis.title.x = ggplot2::element_blank(),
                                             axis.title.y = ggplot2::element_blank(),
                                             panel.grid.minor = ggplot2::element_blank(),
                                             panel.grid.major.x = ggplot2::element_blank(),
                                             panel.grid.major.y = ggplot2::element_line(color = "grey80", linewidth = 0.25),
                                             legend.position = 'none'
                                        )

                              } else {

                                   # Plot for Cases and Deaths
                                   p <- ggplot2::ggplot(country_data, ggplot2::aes(x = year, y = get(y_var))) +
                                        ggplot2::geom_vline(xintercept = decade_starts, color = "grey80", linewidth = 0.25) +
                                        ggplot2::geom_bar(stat = "identity", fill = fill_color) +
                                        ggplot2::geom_hline(yintercept = 0, color = "black", linewidth = 0.25) +
                                        ggplot2::theme_minimal(base_size = 13.5) +
                                        ggplot2::labs(x = "Year", y = ifelse(y_var == "cases_total", "Reported Cases",
                                                                             ifelse(y_var == "deaths_total", "Reported Deaths")),
                                                      title = country) +
                                        ggplot2::scale_y_sqrt(labels = scales::comma,
                                                              breaks = pretty(cholera_data[[y_var]]),
                                                              limits = c(0, global_y_max),
                                                              expand = c(0.05, 0)) +
                                        ggplot2::scale_x_discrete(drop = FALSE) +
                                        ggplot2::theme(
                                             plot.title = ggplot2::element_text(size = 14, color = 'black', hjust = 0.5, face = "bold"),
                                             axis.text.x = ggplot2::element_text(size = 11, color = 'black', angle = 90, hjust = 1, vjust = 0.5),
                                             axis.text.y = ggplot2::element_text(size = 12, color = 'black'),
                                             axis.title.x = ggplot2::element_blank(),
                                             axis.title.y = ggplot2::element_blank(),
                                             panel.grid.minor = ggplot2::element_blank(),
                                             panel.grid.major.x = ggplot2::element_blank(),
                                             panel.grid.major.y = ggplot2::element_line(color = "grey80", linewidth = 0.25),
                                             legend.position = 'none'
                                        )
                              }

                              print(p)

                         } else {

                              ggplot2::ggplot() +
                                   ggplot2::theme_void() +
                                   ggplot2::labs(title = country, x = NULL, y = NULL) +
                                   ggplot2::theme(plot.title = ggplot2::element_text(size = 14, color = 'black', hjust = 0.5, face = "bold"))
                         }
                    })
               })
          })
     }

     # Run the shiny app
     shiny::shinyApp(ui = ui, server = server)
}
