#' Read a Tier B replay fixture
#'
#' Fixtures are frozen recordings of the Python laser-cholera oracle: every
#' PRNG call it made, in order, plus the 28 result channels it produced. They
#' are generated once by \code{claude/oracle/dump_fixture.py} and committed, so
#' the replay tests run in pure R with no Python installed. See
#' \code{tests/testthat/fixtures/ORACLE.md} for the oracle provenance.
#'
#' @name sim_fixture
#' @keywords internal
NULL

# Oracle draw sites are recorded as `file:line` in the Python source, which is
# precise and stable but meaningless on the R side. This maps each to the
# engine's own site label so a replay mismatch reads in R's vocabulary.
#
# Maintained against laser-cholera v0.16.1 (commit 06938c1). If the oracle is
# ever regenerated from a different version these line numbers move, which is
# exactly why the fixture records its source SHA-256: a stale map produces an
# unmapped-site error rather than a silent mispairing.
.SIM_ORACLE_SITE_MAP <- c(
     "susceptible.py:135"  = "susceptible/non_disease_deaths",
     "susceptible.py:143"  = "susceptible/births",
     "exposed.py:94"       = "exposed/non_disease_deaths",
     "recovered.py:103"    = "recovered/non_disease_deaths",
     "recovered.py:110"    = "recovered/waning",
     "infectious.py:181"   = "infectious/sym_non_disease_deaths",
     "infectious.py:203"   = "infectious/disease_deaths",
     "infectious.py:210"   = "infectious/reported_deaths",
     "infectious.py:217"   = "infectious/sym_recovery",
     "infectious.py:231"   = "infectious/asym_non_disease_deaths",
     "infectious.py:239"   = "infectious/asym_recovery",
     "infectious.py:249"   = "infectious/progression",
     "infectious.py:267"   = "infectious/reported_cases",
     "vaccinated.py:157"   = "vaccinated/v1_non_disease_deaths",
     "vaccinated.py:163"   = "vaccinated/v2_non_disease_deaths",
     "vaccinated.py:170"   = "vaccinated/v1_waning",
     "vaccinated.py:175"   = "vaccinated/v2_waning",
     "humantohuman.py:165" = "humantohuman/infection",
     "envtohuman.py:133"   = "envtohuman/infection",
     "environmental.py:135"= "environmental/decay",
     "environmental.py:139"= "environmental/shedding_sym",
     "environmental.py:143"= "environmental/shedding_asym"
)

#' @rdname sim_fixture
#' @param path Directory holding \code{replay.rds}, or the \code{.rds} itself.
#' @return A list with \code{calls}, \code{values}, \code{results} and
#'   \code{meta}.
#' @keywords internal
sim_read_fixture <- function(path) {
     file <- if (dir.exists(path)) file.path(path, "replay.rds") else path
     if (!file.exists(file)) {
          stop(sprintf("Replay fixture not found: %s", file), call. = FALSE)
     }
     fixture <- readRDS(file)

     unmapped <- setdiff(unique(fixture$calls$site), .SIM_DRAW_SITES)
     if (length(unmapped)) {
          stop(sprintf(paste0("Fixture contains draw site(s) the engine does not ",
                              "know: %s. Either the fixture predates a rename or ",
                              ".SIM_ORACLE_SITE_MAP is stale."),
                       paste(unmapped, collapse = ", ")), call. = FALSE)
     }
     fixture
}

#' Convert a raw Tier A oracle dump into a committed fixture
#'
#' Tier A covers the four deterministic precomputed matrices (\code{pi_ij},
#' \code{beta_jt_human}, \code{beta_jt_env}, \code{delta_jt}), which have no
#' RNG in them and can therefore be compared exactly with no draw alignment.
#' Generated by \code{claude/oracle/dump_tier_a.py}.
#'
#' @param dump Directory containing the \code{.bin} files and \code{meta.json}.
#' @param out Path of the \code{.rds} to write.
#' @return Invisibly, the fixture list that was written.
#' @keywords internal
sim_convert_tier_a_dump <- function(dump, out) {

     meta <- jsonlite::fromJSON(file.path(dump, "meta.json"), simplifyVector = TRUE)
     if (is.null(meta$config_list)) {
          stop("Tier A dump has no embedded `config_list`.", call. = FALSE)
     }

     matrices <- lapply(meta$layout, function(entry) {
          path <- file.path(dump, entry$file)
          v <- readBin(path, what = entry$what, n = entry$n, size = entry$size,
                       signed = entry$signed, endian = "little")
          shape <- unlist(entry$shape)
          # NumPy is row-major, so a flat read fills [ncol, nrow] and is
          # transposed back.
          if (length(shape) == 2L) v <- t(matrix(v, nrow = shape[2], ncol = shape[1]))
          v
     })

     fixture <- list(matrices = matrices,
                     meta = meta[setdiff(names(meta), "layout")])

     dir.create(dirname(out), recursive = TRUE, showWarnings = FALSE)
     saveRDS(fixture, out, compress = "xz")
     invisible(fixture)
}

#' Convert a raw oracle dump into a committed replay fixture
#'
#' Development-time only: reads the raw-binary dump emitted by
#' \code{claude/oracle/dump_fixture.py} and writes the \code{replay.rds} the
#' tests consume.
#'
#' The dev-time interchange is flat little-endian binary plus a JSON manifest,
#' read here with \code{readBin()}. That needs no package on either side --
#' the oracle env has no \pkg{pyarrow}, and base R has no HDF5 or parquet
#' reader -- so the Python/R boundary carries zero dependencies. The committed
#' artefact is a \code{.rds} so the test suite loads it in one call and needs
#' nothing extra.
#'
#' @param dump Directory containing the \code{.bin} files and
#'   \code{meta.json} from the oracle harness.
#' @param out Path of the \code{replay.rds} to write.
#' @return Invisibly, the fixture list that was written.
#' @keywords internal
sim_convert_oracle_dump <- function(dump, out) {

     meta <- jsonlite::fromJSON(file.path(dump, "meta.json"), simplifyVector = TRUE)

     read_entry <- function(entry) {
          path <- file.path(dump, entry$file)
          if (!file.exists(path)) {
               stop(sprintf("Oracle dump is missing %s (declared in meta.json).",
                            entry$file), call. = FALSE)
          }
          v <- readBin(path, what = entry$what, n = entry$n,
                       size = entry$size, signed = entry$signed,
                       endian = "little")
          if (length(v) != entry$n) {
               stop(sprintf("Short read on %s: got %d values, manifest declares %d.",
                            entry$file, length(v), entry$n), call. = FALSE)
          }
          shape <- unlist(entry$shape)
          if (length(shape) == 2L) {
               # NumPy is row-major and the array is [npatches, nticks], so a
               # flat read fills an R matrix of dim [nticks, npatches] which is
               # then transposed back. Getting this backwards would silently
               # produce a plausible-looking transposed reference.
               v <- t(matrix(v, nrow = shape[2], ncol = shape[1]))
          }
          v
     }

     layout <- meta$layout
     calls_of <- function(key) read_entry(layout[[paste0("calls/", key)]])

     phase_levels <- as.character(meta$codes$phase)
     site_levels  <- as.character(meta$codes$site_id)
     kind_levels  <- as.character(meta$codes$kind)

     site_oracle <- site_levels[calls_of("site") + 1L]
     site_r <- unname(.SIM_ORACLE_SITE_MAP[site_oracle])
     if (anyNA(site_r)) {
          stop(sprintf("No R site label for oracle site(s): %s",
                       paste(unique(site_oracle[is.na(site_r)]), collapse = ", ")),
               call. = FALSE)
     }

     calls <- list(
          tick   = calls_of("tick"),
          phase  = phase_levels[calls_of("phase") + 1L],
          site   = site_r,
          kind   = kind_levels[calls_of("kind") + 1L],
          offset = calls_of("offset"),
          length = calls_of("length")
     )
     values <- list(
          n      = read_entry(layout[["values/n"]]),
          param  = read_entry(layout[["values/param"]]),
          result = read_entry(layout[["values/result"]])
     )
     results <- lapply(meta$results_layout, read_entry)

     fixture <- list(calls = calls, values = values, results = results,
                     meta = meta[setdiff(names(meta),
                                         c("layout", "results_layout"))])

     if (is.null(fixture$meta$config_list)) {
          stop("Oracle dump has no embedded `config_list`; the fixture would ",
               "depend on an external config file that could drift.",
               call. = FALSE)
     }

     dir.create(dirname(out), recursive = TRUE, showWarnings = FALSE)
     saveRDS(fixture, out, compress = "xz")
     invisible(fixture)
}
